### ISSUE TITLE
forked-daapd broken with iTunes 12.1.0.71

### ISSUE THREAD

**Issue by ejurgensen** [ejurgensen/forked-daapd#100]
It seems the newest version of iTunes does not work with forked-daapd. So be warned if you consider upgrading. Hope that it turns out to be fixable.

**Comment by jkiddo** [comment]
Hmmm ... let me know as soon as you know what has changed in the protocol - I'm also hit by it in my Java implementation

**Comment by jmaggard10** [comment]
FWIW, it does appear to still work on the old Firefly / mt-daapd.

**Comment by ejurgensen** [comment]
Thank you for the hint, it was very helpful. It has helped me determine that the problem is related to the groups requests. Old Firefly doesn't support these, and won't announce support for them, so iTunes will not try to make any of these requests, and then everything is fine.

The problem does not seem related to the actual content of the group requests and responses, but more to the fact that they are made at all. iTunes does not actually need to make them, and in fact the previous version of iTunes would not make them to forked-daapd (despite the announcement of support), and iTunes 12.1 will still not make them to other iTunes instances (despite their announcement of support), but will now make them to forked-daapd, which results in the problem. I have yet to determine what is stopping iTunes from making the requests to other iTunes instances. This should be the actual fix to the problem.

Until then, here is a temporary fix for the problem if anyone is in need: https://github.com/ejurgensen/forked-daapd/commit/e1cdbbeb08e576a7e38ddd04f9b0e96360faef8c This fix is telling iTunes (and Remote) that forked-daapd only has support for artist group requests (asgr=1). Apparently, that is enough to fix the problem. Interestingly, announcing support for album group requests (asgr=2) will also fix the problem, but announcing support for both (asgr=3) will trigger the problem.

**Comment by protree** [comment]
I tried your fix, @ejurgensen, but it only allows iTunes to list the music again. iTunes is still unable to play music.

**Comment by ejurgensen** [comment]
True, I'll admit I didn't even test that. Seems there was another change in the streaming request format. Here is a fix for that: https://github.com/ejurgensen/forked-daapd/commit/77f1f79263db2b9ac369083efe8d502e99a4138b

**Comment by protree** [comment]
I tested the iTunes12.1 brach, the music is listed and iTunes is able to play the music. Anyway one of my albums isn't playing, but I am not sure if this is related to forked-daapd. I a going to check this tomorrow, maybe I can provide you more details then. Thank you for your work!!!

**Comment by ejurgensen** [comment]
FYI I've just added another small commit to the branch, so when you test again I suggest including that.

**Comment by protree** [comment]
Thanks. I found my bug, the album wasn't stream-optimized. I am still testing, I will update you as soon as I find a bug but everything looks good so far.

**Comment by ejurgensen** [comment]
The problem should be fixed now in master (though not in the optimal way, so might improve on it later).
