### ISSUE TITLE
[web] redundancy in 'about' and 'admin' pages

### ISSUE THREAD

**Issue by whatdoineed2do** [ejurgensen/forked-daapd#1004]
http://localhost:3689/#/about and http://localhost:3689/admin.html have huge overlap but the latter lives outside of the main Vue app.

Need to drop one (the latter?) since its functionality is in `about` and now `settings`.

**Comment by cdlenfert** [comment]
+1, but also request we integrate a link back to the GitHub repo somewhere if we get rid of admin.

![image](https://user-images.githubusercontent.com/17277745/81948138-a3a44c80-95be-11ea-9090-d99f0c4a1f64.png)

Maybe on the version text on the about page?

![image](https://user-images.githubusercontent.com/17277745/81948285-cc2c4680-95be-11ea-8759-dfba44e2da69.png)

**Comment by chme** [comment]
Yes, the plan is to drop `admin.html` and integrate all functionality in the player web interface Vue app. I started this in #962.
