### ISSUE TITLE
Any way to detect a freeze/crash?

### ISSUE THREAD

**Issue by lancelon** [ejurgensen/forked-daapd#1012]
A couple of times recently my ForkeDaapd instance has stopped responding. The pi hosting it is fine, and a call to systemctl to restart the service soon brings it back, but I wonder if there's a way I can detect this and that way automate restarting the service?

Thanks

**Comment by ejurgensen** [comment]
Is it a crash or a freeze? You can check this with `ps ax` to see if the process is still there.

**Comment by lancelon** [comment]
thanks I'll do this next time it happens.

**Comment by ejurgensen** [comment]
Please reopen when you have something to debug from
