### ISSUE TITLE
Ignoring vorbis "Discnumber" tag? Bug, or should I set something else?

### ISSUE THREAD

**Issue by andy-twosticks** [ejurgensen/forked-daapd#1014]
I use forked-daapd to serve .flac from a central server to other devices on my local network.  It works out of the box and has never let me down for years.  Thank you.

However I've just noticed that for albums with multiple discs, I get all the track 1's, then all the track 2's, etc.   These are .flac files with the vorbis tag "Tracknumber" set.  That seems to the be the correct tag.  On the server I see them as I would expect (in Clementine, for example).  

Obviously if you are expecting some other tag, the easiest solution is for me to set that on the file.  That would not be a problem; I can set any tag I like with exiftool.

Here's what exiftool shows me for an example file:

```
[ExifTool]      ExifTool Version Number         : 9.74
[System]        File Name                       : 01_home_for_christmas.flac
[System]        Directory                       : .
[System]        File Size                       : 7.3 MB
[System]        File Modification Date/Time     : 2020:03:28 16:44:01+00:00
[System]        File Access Date/Time           : 2020:05:19 15:19:01+01:00
[System]        File Inode Change Date/Time     : 2020:05:19 15:18:59+01:00
[System]        File Permissions                : rw-r--r--
[File]          File Type                       : FLAC
[File]          MIME Type                       : audio/flac
[FLAC]          Block Size Min                  : 4096
[FLAC]          Block Size Max                  : 4096
[FLAC]          Frame Size Min                  : 14
[FLAC]          Frame Size Max                  : 9680
[FLAC]          Sample Rate                     : 44100
[FLAC]          Channels                        : 2
[FLAC]          Bits Per Sample                 : 16
[FLAC]          Total Samples                   : 4782204
[Vorbis]        Vendor                          : reference libFLAC 1.3.0 20130526
[Vorbis]        Album                           : Other Sides [Remastered]
[Vorbis]        Artist                          : Kate Bush
[Vorbis]        Compilation                     : 0
[Vorbis]        Date                            : 2018
[Vorbis]        Discnumber                      : 3
[Vorbis]        Title                           : Home For Christmas
[Vorbis]        Track Number                    : 1
[Composite]     Duration                        : 0:01:48
```

**Comment by ejurgensen** [comment]
Always good to hear from a long time user! Could you send your songs3.db file to me at espenjurgensen@gmail.com? Also please write examples of albums with issue.

**Comment by whatdoineed2do** [comment]
I thought we had come across this before and fixed but it looks like this is needed in this case
```
diff --git a/src/db.c b/src/db.c
index 09c1c1be..09683987 100644
--- a/src/db.c
+++ b/src/db.c
@@ -423,7 +423,7 @@ static const char *sort_clause[] =
     "",
     "f.title_sort",
     "f.album_sort, f.disc, f.track, f.title_sort, f.album_artist_sort",
-    "f.album_artist_sort, f.album_sort, f.disc, f.track, f.title_sort",
+    "f.album_artist_sort, f.album_sort, f.track, f.disc, f.title_sort",
     "f.type, f.parent_id, f.special_id, f.title",
     "f.year",
     "f.genre",
```

**Comment by andy-twosticks** [comment]
> I thought we had come across this before and fixed it

Hmm.  I'm running v22.3.  That's the version that comes with Debian Stretch.  (In case you did, in fact, already fix it.)

Do you still need my db?

**Comment by ejurgensen** [comment]
Yes

**Comment by andy-twosticks** [comment]
@ejurgensen done.

**Comment by ejurgensen** [comment]
Ok, I can see the tags have been correctly read, and the sorting is also fine with current forked-daapd (see below). I can't test with 22.3, it is so old that it doesn't build. But Stretch should have 24.2, so I'm not sure why you are on 22.3? Buster has 26.4. I can't say for sure when/if this was fixed.

From the db:

id|artist|album|title|disc|track
---|---|---|----|--|--
5452|Kate Bush|Other Sides [Remastered]|Running Up That Hill (A Deal With God)|1|1
5453|Kate Bush|Other Sides [Remastered]|The Big Sky (meteorological mix)|1|2
5454|Kate Bush|Other Sides [Remastered]|Cloud Busting (orgonon mix)|1|3
5455|Kate Bush|Other Sides [Remastered]|Hounds of Love (alternative mix)|1|4
5456|Kate Bush|Other Sides [Remastered]|Expermiment IV (extended mix)|1|5
5457|Kate Bush|Other Sides [Remastered]|Walk Straight Down The Middle|2|1
5458|Kate Bush|Other Sides [Remastered]|You Want Alchemy|2|2
5459|Kate Bush|Other Sides [Remastered]|Be Kind To My Mistakes|2|3
5460|Kate Bush|Other Sides [Remastered]|Lyra|2|4

![sorting](https://user-images.githubusercontent.com/1156686/82455496-48d58e00-9ab3-11ea-9085-39c45eab71c5.jpg)
