### ISSUE TITLE
forked-daapd crashing when trying to browse with Remote or Retune

### ISSUE THREAD

**Issue by Tom14-** [ejurgensen/forked-daapd#102]
Hi,

I have forked-daapd running on my FreeNAS 9.3 box, but I can't actually manage to browse the library from mobile devices.

forked-daapd is running, the library is visible on the network and I can sometimes browse it with iTunes. 
```
# service forked-daapd status
forked_daapd is running as pid 78992.
```
However trying to browse via either Remote or Retune always makes it crash
```
# service forked-daapd status
forked_daapd is not running.
```
I'm using log level 'debug', here are the last few lines. The line "Trying DAAP query" seems to be at the end of the log every time it crashes.
```
# tail /var/log/forked-daapd.log
[2015-02-15 15:47:08] [DEBUG]       db: Running query 'SELECT COUNT(*) FROM files f WHERE f.disabled = 0 AND f.media_kind = 8;'
[2015-02-15 15:47:08] [DEBUG]       db: End of query results
[2015-02-15 15:47:08] [DEBUG]     daap: Done with playlist list, 4 playlists
[2015-02-15 15:47:08] [DEBUG]     daap: DAAP request handled in 6 milliseconds
[2015-02-15 15:47:08] [DEBUG]    httpd: Found query string
[2015-02-15 15:47:08] [DEBUG]     daap: DAAP request: /databases/1/groups?meta=dmap.itemname,dmap.itemid,dmap.persistentid,daap.songartist,daap.songdatereleased,dmap.itemcount,daap.songtime&type=music&group-type=albums&sort=album&include-sort-headers=1&query=(('com.apple.itunes.mediakind:1','com.apple.itunes.mediakind:32')+'daap.songalbum!:')&session-id=100
[2015-02-15 15:47:08] [DEBUG]     daap: Sorting songlist by album
[2015-02-15 15:47:08] [DEBUG]     daap: Sort headers requested
[2015-02-15 15:47:08] [DEBUG]     daap: DAAP browse query filter: (('com.apple.itunes.mediakind:1','com.apple.itunes.mediakind:32') 'daap.songalbum!:')
[2015-02-15 15:47:08] [DEBUG]     daap: Trying DAAP query -(('com.apple.itunes.mediakind:1','com.apple.itunes.mediakind:32') 'daap.songalbum!:')-
```
Let me know if I can provide any more information.

Thanks,

Tom

**Comment by ejurgensen** [comment]
I have seen this error recently, and the reason was that libantlr3c was not built correctly. How did you configure it when you built it?

**Comment by Tom14-** [comment]
```
./configure --disable-antlrdebug --disable-abiflags --disable-dependency-tracking --enable-shared=no
```
Maybe I should try starting again with your FreeBSD script, not sure how this will go on FreeNAS.

**Comment by ejurgensen** [comment]
The problem is "--disable-abiflags". Yes, try the script, and see how it goes.

**Comment by Tom14-** [comment]
Hmm using the script I can get forked-daapd installed but then I get the error `laudio: Could not open sound device: No such file or directory` and the fix mentioned [here](https://github.com/ejurgensen/forked-daapd/issues/56#issuecomment-59664347) doesn't seem to be working for me any more (it did work in the manual install).

I also tried reinstalling libantlr3c without `--disable-abiflags` but it hasn't helped, would I also need to build and install forked-daapd again?

**Comment by ejurgensen** [comment]
I had a go at installing forked-daapd on FreeNAS 9.3, and it did succeed in the end. I used the script. I had to do the following tweaks:
- Script: Remove '-Ofast' from CFLAGS (changed in master now)
- Script: Uncomment the ZLIB_CFLAGS/LDFLAGS
- Forked-daapd: Disable local audio like you mentioned (will make that change properly soon)

I installed antlr3/libantlr3c with the script and didn't have any problems. I think it may be important that you say yes to compiling for 64 bit, when the script asks you.

**Comment by Tom14-** [comment]
This works! The script ran fine (after installing `sudo` from ports) with
```
        export CC=cc
        export LIBUNISTRING_CFLAGS=-I/usr/include
        export LIBUNISTRING_LIBS=-L/usr/lib
        export ZLIB_CFLAGS=-I/usr/include
        export ZLIB_LIBS=-L/usr/lib
```
Thanks for the efforts, now to see how it goes actually streaming music!

**Comment by Tom14-** [comment]
Hi, sorry to drag this up again, but forked-daapd is the last thing I need to break my iTunes dependency so I'm having another try to get it going. I **think** I'm using the same procedure as before, when the install script was working, but now, it fails at `gmake`:

```
Should the script build forked-daapd? [y/N] y
Cloning into 'forked-daapd'...
remote: Counting objects: 16608, done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 16608 (delta 12), reused 0 (delta 0), pack-reused 16579
Receiving objects: 100% (16608/16608), 12.25 MiB | 266.00 KiB/s, done.
Resolving deltas: 100% (10192/10192), done.
Checking connectivity... done.
gmake: *** No rule to make target 'clean'.  Stop.
```
and then later
```
Should the script install forked-daapd and add service startup scripts? [y/N] y
gmake: *** No rule to make target 'install'.  Stop.
```

**Comment by ejurgensen** [comment]
Just remove 'gmake clean'

**Comment by Tom14-** [comment]
Thanks for the reply. Sorry to be a pain in the neck but it still falls over at `gmake`:
```
forked_daapd-filescanner_smartpl.o: In function `smartpl_parse_file':
/home/forked-daapd/forked-daapd_build/forked-daapd/src/filescanner_smartpl.c:55: undefined reference to `antlr3AsciiFileStreamNew'
Makefile:608: recipe for target 'forked-daapd' failed
gmake[3]: *** [forked-daapd] Error 1
gmake[3]: Leaving directory '/usr/home/forked-daapd/forked-daapd_build/forked-daapd/src'
Makefile:514: recipe for target 'all' failed
gmake[2]: *** [all] Error 2
gmake[2]: Leaving directory '/usr/home/forked-daapd/forked-daapd_build/forked-daapd/src'
Makefile:540: recipe for target 'all-recursive' failed
gmake[1]: *** [all-recursive] Error 1
gmake[1]: Leaving directory '/usr/home/forked-daapd/forked-daapd_build/forked-daapd'
Makefile:408: recipe for target 'all' failed
gmake: *** [all] Error 2
```
Some sort of problem with the antlr install?
```
$ which antlr3
/usr/bin/antlr3
$ cat /usr/bin/antlr3 
#!/bin/sh
export CLASSPATH
CLASSPATH=$CLASSPATH:/usr/share/java/antlr-3.4-complete.jar:/usr/share/java
/usr/local/bin/java org.antlr.Tool $*
$ which java
/usr/local/bin/java
$ antlr3
ANTLR Parser Generator  Version 3.4
$ ls /usr/local/lib | grep libantlr
libantlr3c.a
libantlr3c.la
libantlr3c.so
$ java -version
openjdk version "1.8.0_40"
OpenJDK Runtime Environment (build 1.8.0_40-b25)
OpenJDK 64-Bit Server VM (build 25.40-b25, mixed mode)
```

**Comment by ejurgensen** [comment]
No worries, seems you have encountered a bug in some of the new stuff, which is helpful to know.

To get around it, re-enable "gmake clean", and after that line put "git checkout 22.3", which will make sure you installs the most recent release.

**Comment by Tom14-** [comment]
Yep that's got it installed (with `--enable-itunes` and `--enable-lastfm`), thanks. BTW in the script `install --mode=755` was giving me an error (FreeNAS 9.3) so I used `install -m 755`.

I posted the [script I ended up using](https://gist.github.com/Tom14-/70ca5b94315d9141198b) just in case.

**Comment by ejurgensen** [comment]
The compile error you got should be fixed now with this commit: https://github.com/ejurgensen/forked-daapd/commit/0c3712629dad2fdeb5641815549f23774dbf34e9
