### ISSUE TITLE
web interface in iframe

### ISSUE THREAD

**Issue by Ulrar** [ejurgensen/forked-daapd#1025]
Hi,

I'm trying to run forked-daapd as a hassio (home assistant) addon, and the daemon itself works fine but the web interface does not work in ingress.

Going directly to the 3689 port works, but when using ingress (loading the UI directly within home assistant's UI using an iframe) the href aren't prepended with the correct path :+1: 
```html
<iframe src="/api/hassio_ingress/<addon ID>//">
    ...
    <head>
        <link href="/player/css/app.css" rel="preload" as="style">
    </head>
</iframe>
```

The link for app.css (and all other resources) should here be /api/hassio_ingress/<addon ID>/player/css/app.css instead.
Is there some config I could add, or some change I could make when building the addon to make this behave as expected ?

Thank you

**Comment by chme** [comment]
Hi @Ulrar ,

I hope the change from @mill1000 in #973 (merged changes with #1082) will fix the issue.
If this is not the case, please reopen the issue.

Regards
Christian
