### ISSUE TITLE
Install with Chromecast support libgnutls-dev dependency not available

### ISSUE THREAD

**Issue by cdlenfert** [ejurgensen/forked-daapd#1026]
When running the manual install and adding support for Chromecast via `apt-get install libgnutls-dev`, I get an error about it not being available. I'm trying `libgnutls28-dev` instead and seeing if it builds the same. If so the install readme should be updated. This thread makes me think it's a viable substitute. https://github.com/proycon/LaMachine/issues/16

**Comment by ejurgensen** [comment]
Yes, libgnutls28-dev is fine. Putting libgnutls28-dev directly in the INSTALL has the downside that it will become incorrect at some point, but I see apt-get accepts regular expressions, so I will modify the instructions so that both package names will work.
