### ISSUE TITLE
Radios not showing as such in web UI

### ISSUE THREAD

**Issue by Ulrar** [ejurgensen/forked-daapd#1027]
Hi,

I created a few m3u containing just the link to the http stream of the radio, and I'm getting these in the playlist tab and they do work fine.
However they do not show as internet radios, as I understand they should ? I don't even have radio showing at all in the interface.

None of these streams have any metadata defined unfortunately.
I did try setting radio_playlists to false explicitly, but that didn't change anything, the radio tab never appears.

**Comment by ejurgensen** [comment]
The web UI doesn't have a tab for radios (maybe something to add @chme?). You will only see them listed as radios if you use a Remote-type client.

**Comment by Ulrar** [comment]
Oh, I wasn't aware of that. I haven't tried any remote clients yet, I'll give it a shot, thanks !
