### ISSUE TITLE
Wrong IP published in mdns when running in docker

### ISSUE THREAD

**Issue by Ulrar** [ejurgensen/forked-daapd#1028]
Hi,

I'm not too familiar with mdns, but it seems like when running forked-daapd in docker the mdns record has the internal IP for that container, instead of the public IP for the machine, when running in NAT mode.
I'm assuming this is why remote pairing does not work on my instance, when using Retune I'm able to do the pairing step but after that it times out, I'm assuming because it's trying to connect to the wrong IP.

Is there a way to override the IP it's publishing and tell it explicitly what to use ? I wouldn't mind putting the machine's IP in the config file for this, or in some avahi config file, depending on how that works.

Thanks

**Comment by ejurgensen** [comment]
I don't know too much about Docker and networking, but generally you cannot make a connection from the outside to a device in network that is behind NAT. So overriding the IP wouldn't help.

**Comment by Ulrar** [comment]
The daap port is forwarded, connecting to it with the host's IP does work,
it's just not publishing that one

**Comment by ejurgensen** [comment]
Ok, then you could try making a fake mdns announcement like this:
https://ejurgensen.github.io/forked-daapd/#remote-access

That is for dns-sd, but I imagine avahi can do the same.

**Comment by ejurgensen** [comment]
Come to think of it, you would also need to give another address for the _dacp._tcp service. And maybe also the _touch-able._tcp service.... and even then I'm not sure it would work. Looking the code, you might be able to set an alternate address here: https://github.com/ejurgensen/forked-daapd/blob/master/src/mdns_avahi.c#L872

But maybe if you can use bridging it would be easier?

**Comment by Ulrar** [comment]
Unfortunately I don't have control over that, it's running in hassio so I
can't really touch the config.
I'll try that tomorrow, thanks !

**Comment by Ulrar** [comment]
I'm not sure how to do this. It looks like the IP address is automatically found by avahi, the only parameter to that function is the interface index (an int) but that would mean you need the host's IP on one of the interfaces, which isn't the case here.

Looks like the lib does have a AvahiIPv4Address struct defined too, so there's probably a way to force it, but I'm not sure how. Maybe you have to register your IP as a fake interface somewhere else or something like that.

I believe I found a way to get my container to run on the host's network so I'll try that first, but if that doesn't work I'll try to figure out exactly how that lib works.
Thanks for the link anyway !

**Comment by ejurgensen** [comment]
Sounds good. I know other people have forked-daapd running in a Docker, see https://github.com/linuxserver/docker-daapd. So I guess they must have found a solution, but I don't know what it is, or if it is possible for you to use.

You can pass a host parameter to the function I linked to above, but I'm not sure exactly what effect that would have. The Avahi doc says the following about it:
`host | The host this services is residing on. We recommend to pass NULL here, the daemon will than automatically insert the local host name in that case`

**Comment by Ulrar** [comment]
It's working now, basically the solution is to not have dbus and avahi start in the container. Instead they're running on the host, and dbus just needs to be mapped into the container.
That way forked-daapd just connects to the host's avahi daemon through the mapped dbus to publish the records, and they'll have the correct IP automatically.

**Comment by ejurgensen** [comment]
Great, thanks for the update
