### ISSUE TITLE
Question: forked-daapd, shairport-sync and multiple subnets/vlans setup

### ISSUE THREAD

**Issue by ddppddpp** [ejurgensen/forked-daapd#1033]
My home network is separated in a subnet/vlan in which I have all the housholds' laptops/mobiles/tablets (main) and another one in which I'm keeping various smart devices including a couple of AirPlay-capable outputs/speakers (IoT).
Firewall rules are saying IoT should not see hosts in main.
I'd like to use forked-daapd to manage those speakers all and have another service i.e. shairport-sync output to a pipe and play out to all or just selected speakers.
Ideally, I should be able to stream audio from my iPhone (in main) to the forked-daapd/shairport-sync combo.
In which subnet should I host forked-daapd and shairport-sync?
If I put them in main, discovering them on an i.e. iOS device will be easy, but I'll need to forward all traffic to the speakers accross the firewall.
If I put them in IoT, forked-daapd to speaker traffic will be easy, but I'll have trouble discovering shairport-sync from my iPhone.
I'm aware that I'll probably need a mDNS repeater of some sorts to forward services b/w subnets but any previous experience with a similar setup would help greatly.

**Comment by ejurgensen** [comment]
I don't have experience with this, but perhaps you could have something like an RPi with forked-daapd/shairport-sync that is on both networks - i.e. in a way acting as a bridge?

**Comment by ddppddpp** [comment]
thanks!
I spent a couple of days speculating on this and I think it will be easy to:
- have a i.e. RPi with WiFi in 'local' and ethernet in 'IoT'.
- have shairport-sync somehow bind to wifi (and be discoverable to iPhones)
- have shairport-sync output to a pipe
- forked-daapd 'bind' to i.e. eth0 and thus see all available outputs...
Will give this a try.

**Comment by ddppddpp** [comment]
Reporting a working setup:
- linux host i.e. Rpi/Raspbian Buster with 2 net interfaces, one per subnet/vlan whatever
- forked-daapd with shairport-sync setup so that shairport-sync outputs to a pipe in forked-daapd's library directory
- pipes set to autostart/autoplay
- forked-daapd and shairport sync are 'visible' and can be used from both subnets without special setup
- multiple airplay/shairport-sync outputs in subnet B - available and can be setup as forked-daapd outputs
- client iOS device in subnet A
- client iOS device sees ONLY shairport-sync in subnet A, can stream audio
- forked-daapd web GUI visible from subnet A can be used to enable/disable one/multiple/all outputs in subnet B
Thanks for a great project! (happy)

**Comment by ejurgensen** [comment]
Thanks for sharing, always great to hear about the work being of use! You are welcome to add a page about this multiple-subnet setup to the wiki, perhaps others can then find it more easily.
