### ISSUE TITLE
Play Specific Artist Album via API

### ISSUE THREAD

**Issue by kdvlr** [ejurgensen/forked-daapd#1034]
Is there a way I can play a specific Artist/Album through the JSON API ? I see there is a PUT POST option to start the player, but not sure how to specifically send a Album/Artist information. 

I am specifically looking to manually play a pipe because sometimes the auto start does not work well.

**Comment by ejurgensen** [comment]
Yes, see the [playback parameter when adding items to a queue](https://github.com/ejurgensen/forked-daapd/blob/master/README_JSON_API.md#adding-items-to-the-queue)
