### ISSUE TITLE
Websocker Error in Chrome Browser

### ISSUE THREAD

**Issue by kdvlr** [ejurgensen/forked-daapd#1035]
I am getting the following error when running forked-daapd UI on Chrome. I don't get this error in Safari on MacOS and iOS. I don't get this error on Firefox on Windows as well. 
The WebUI gets stuck on reconnecting.
```
Versions
forked-daapd: 27.1
Details: Compiled with support for ffmpeg, iTunes XML, Chromecast, MPD, Device verification, Websockets, ALSA, Webinterface
Chrome: Version 83.0.4103.106
```
```
Jun 15 15:58:45 nas forked-daapd[1452]: [  LOG]      web: LWS Ran out of header data space
Jun 15 15:58:48 nas forked-daapd[1452]: [  LOG]      web: LWS Ran out of header data space
Jun 15 15:58:52 nas forked-daapd[1452]: [  LOG]      web: LWS Ran out of header data space
Jun 15 15:58:59 nas forked-daapd[1452]: [  LOG]      web: LWS Ran out of header data space
Jun 15 15:59:09 nas forked-daapd[1452]: [  LOG]      web: LWS Ran out of header data space
```

**Comment by chme** [comment]
Looks like chrome send a lot of header data and libwebsocket cannot store these. We should be able to increase it to avoid the error: https://github.com/warmcat/libwebsockets/issues/1270

What version of libwebsockets are you using and on which operating system is forked-daapd running?

**Comment by chme** [comment]
@kdvlr Can you build from git to test the proposed fix in #1041?

**Comment by kdvlr** [comment]
I rebuilt from master and I still see the same error. It doesn't look like the PR has been merged yet.

**Comment by kdvlr** [comment]
@chme - I downloaded websocket.c separately and built it again. Looks like this fix resolves it.

**Comment by chme** [comment]
Thanks for testing, the fix is now merged to master.
