### ISSUE TITLE
[web] Search results do not include audio books

### ISSUE THREAD

**Issue by andrsd** [ejurgensen/forked-daapd#1039]
Steps to reproduce:

1. Go to web player, 
2. Select the search icon
3. type in an author of an audiobook or a name of an audiobook
4. Press Enter

Results do not include any audiobook related info (e.g. when a `media_kind` is `audiobook`).

Expected to see results that include audiobooks.

In larger collections of audiobook, search is a critical feature to find the items quickly. Would improve user experience significantly.

**Comment by ejurgensen** [comment]
@chme I tested this and it seems the request made by the web player includes media_kind=music. Should that be removed?

`/api/search?type=track,artist,album,playlist&media_kind=music&query=xyz&limit=3&offset=0`
