### ISSUE TITLE
Cant get output to Airplay Device Working

### ISSUE THREAD

**Issue by Rohmilchkaese** [ejurgensen/forked-daapd#1048]
Hey,
I setup Forked-Daapd. Everything works fine, except for when I try to output audio to an Airplay Device. 
I can get Forked-Daapd connect to a shairport-sync instance on my network. But it doesn't work to a Sonos speaker.

Debug gives me this: 

`[DEBUG]     raop: startup_options: Sending auth-setup to 'Küche'`
`[DEBUG]     raop: startup_auth_setup: Sending ANNOUNCE to 'Küche'`
`[DEBUG]     raop: Local address: 192.168.100.243 (LL: no) port 50304`
`[ INFO]     raop: Setting up AirPlay session 363985909 (192.168.100.243 -> 192.168.100.150)`
`[DEBUG]     raop: startup_announce: Sending SETUP to 'Küche'`
`[DEBUG]      web: notify callback reason: 11`
`[  LOG]     raop: SETUP request failed in session startup: 500 Internal Server Error`
`[DEBUG]   player: Callback request received, id is 0`
`[DEBUG]   player: Unsubscription request for quality 44100/16/2 (now 0 subscribers)`
`[DEBUG]   player: Making deferred callback to device_activate_cb, id was 0`
`[DEBUG]   player: Callback from AirPlay device Küche to device_activate_cb (status -1)`
`[  LOG]   player: The AirPlay device 'Küche' failed to activate`
`[DEBUG]     main: Command has 0 pending events`
`[DEBUG]   player: Status update - status: 4, events: 12, caller: speaker_generic_bh`
`[DEBUG]      mpd: Asynchronous listener callback called with event type 12.`
`[DEBUG]      mpd: Notify clients waiting for idle results: 12`
`[  LOG]      web: JSON api request failed with error code 500 (/api/outputs/57717330260976)`
`[DEBUG]      web: notify callback reason: 11`
`[DEBUG]      web: notify callback reason: 11`
`[DEBUG]      web: JSON api request: '/api/outputs'`
`[DEBUG]      web: JSON api request: '/api/player'`
`[DEBUG]   player: Player status: playing`
`[DEBUG]      web: JSON api request: '/api/player'`
`[DEBUG]   player: Player status: playing`
`[DEBUG]      web: JSON api request: '/api/outputs'`

So what can I do, to get this solved ? 
The ports for Forked-Daapd and Websockets are opened. But I didn't open any other ports. It seems that, the Sonos Device announces itself on the network every time I restart forked-daapd with a different port.

Any suggestions are welcome. Thank you very much in advance.

**Comment by ejurgensen** [comment]
Since the Sonos is reporting an error after the SETUP request it might be because it cannot make a connection back to forked-daapd (with Airplay, both parties make connections to eachother). So first try to open all ports and see if it works. If it does, you can work on restricting ports afterwards (see https://github.com/ejurgensen/forked-daapd/blob/master/forked-daapd.conf.in#L279). If it doesn't, well then the problem is somewhere else.

**Comment by Rohmilchkaese** [comment]
Thank you for you reply @ejurgensen. You were right. It indeed did work when there were no ports closed. As a starting point I just did allow traffic from the static ip of the Sonos speaker to the raspberry. Thank you !
I really appreciate forked-daadp. This is a really nice addition to my smart home setup.
