### ISSUE TITLE
BUG: [output/alsa] fallback quality (44.1/16/2) not suitable on all output devices (output dev only supports s32)

### ISSUE THREAD

**Issue by whatdoineed2do** [ejurgensen/forked-daapd#1053]
I have an usb DAC that I've configured for the server.  However this usb DAC only supports S32_LE format - this means S16_LE flacs (16bit CD rips to flac) fail to play.

Oddly enough, mp3s (`ffmpeg -i foo.wav foo.mp3`) from the same 16bit CD wav are fine.

To verify this, I used sox to create 16bit and 32bit wavs, at 44.1 and then converted them to mp3 and flac with a simple `ffmpeg -i foo.wav foo.flac` and similar for mp3. 

For example, a Q made up of:
* 44.1k 16bit (converted) mp3
* 44.1k 32bit (converted) mp3
* 44.1k 32bit (converted) flac
* 44.1k 16bit (converted) flac

When the server plays the first 3, it finds a `Subscription request for quality 44100/16/2` but it creates a `player: New session values (q=44100/32/2)`.  This is fine as the DAC supports `S32_LE`.

When it gets to track#4, it again finds a subscription for the same quality but it now tries to create a session for `44100/16/2` and it fails:

```
  [2020-07-12 15:11:24] [DEBUG]   player: New session values (q=44100/16/2, spr=441, bufsize=1764)
  [2020-07-12 15:11:24] [DEBUG]   laudio: Adding playback session (quality 44100/16/2) to ALSA device 'hw:E30'
  [2020-07-12 15:11:24] [  LOG]   laudio: Could not set format (bits per sample 16): Invalid argument
  [2020-07-12 15:11:24] [  LOG]   laudio: Device 'hw:E30' does not support quality (44100/16/2), falling back to default
  [2020-07-12 15:11:24] [  LOG]   laudio: Could not set format (bits per sample 16): Invalid argument
  [2020-07-12 15:11:24] [  LOG]   laudio: ALSA device failed setting fallback quality
```

Is there anything that can be done in the server to probe the output device's support format if the file's bit rate is not supported?

----
Attached log of playing the Q and the audio files inserted into the Q
[audio.tar.gz](https://github.com/ejurgensen/forked-daapd/files/4908844/audio.tar.gz)
[fd.log](https://github.com/ejurgensen/forked-daapd/files/4908845/fd.log)

**Comment by whatdoineed2do** [comment]
Having had a look at this, `alsa_session_make()` calls `outputs_quality_subscribe(alsa_fallback_quality)` - values of this being `44100/16/2`.  However `S16` is not supported on this DAC, only `S32`.

In `playback_session_add()`, it tries to open the device using the values based on the input and then if that fails, it uses the fallback quality.  The fallback quality is not derived from the device's attributes and in this case the input bips (16) is not supported with the fallback have the same value.  It would be deseriable to derive the fallback from device settings then this can be retried with these quality values in the 3rd call to `pcm_open()` 

Is this a fix you'd consider?

The quick fix for me at this moment would be changing the fallback to `44100/32/2`.

**Comment by whatdoineed2do** [comment]
After some (re)reading of the alsa docs I was reminded of the `plughw:` interface that would work here and no changes required in the server code - the `plughw` interface providing automatic format conversions, so in this case an API request for an unsupported S16 succeed and would be silently converted to S32 before hitting the h/w.

**Comment by ejurgensen** [comment]
Yes, your analysis is correct. 44100/16/2 is the fallback because it is used for Airplay anyway (so in most cases no extra resampling requiring), and because I wasn't able to imagine that a device existed that wouldn't support that.

Could other programs playback the file on the device? E.g. if you tried with ffplay? If so, do you know why they where succeeding? I would imagine something like ffplay initialises the device much like forked-daapd, i.e. using native sample format.

If other programs also can't do this, then perhaps the fix is like you say, so configure plughw as default - if that is possible?

**Comment by whatdoineed2do** [comment]
Yes, I was also surprised and it took me a few hours to figure out why a USB DAC "supporting up to 32bit" didn't support 16 or 24.

Playing through `ffplay` - using the raw device (`hw:1`) it does play audio.
```
AUDIODEV="hw:1" ffplay -hide_banner -loglevel verbose -nodisp -autoexit /tmp/sins16_le-441-dual.wav 
[wav @ 0xac5005f0] parser not found for codec pcm_s16le, packets or times may be invalid.
Input #0, wav, from '/tmp/sins16_le-441-dual.wav':
  Duration: 00:00:10.00, bitrate: 1411 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 2 channels, s16, 1411 kb/s
[ffplay_abuffer @ 0xac544460] tb:1/44100 samplefmt:s16 samplerate:44100 chlayout:(null)
[ffplay_abuffer @ 0xa9101d00] tb:1/44100 samplefmt:s16 samplerate:44100 chlayout:(null)
```
although `aplay` and the raw device didn't like it at all:
```
$ aplay -Dhw:1 /tmp/sins16_le-441-dual.wav 
Playing WAVE '/tmp/sins16_le-441-dual.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
aplay: set_params:1339: Sample format non available
Available formats:
- S32_LE
- SPECIAL
- DSD_U32_BE
```
with [`aplay` failing](https://github.com/bear24rw/alsa-utils/blob/2d105e0f18a82783ea69e2dbe9da7aeb7d3c1346/aplay/aplay.c#L1093-L1097) when it tries to `snd_pcm_hw_params_set_format(..)` with S16_LE for this wav file.  `forked-daapd` makes the same call.

Using the `plughw:1` with `aplay` its fine as ALSA is doing the format conversion for us.
```
$ aplay -v --dump-hw-params -Dplughw:1 /tmp/sins16_le-441-dual.wav 
Playing WAVE '/tmp/sins16_le-441-dual.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
HW Params of device "plughw:1":
--------------------
ACCESS:  MMAP_INTERLEAVED MMAP_NONINTERLEAVED MMAP_COMPLEX RW_INTERLEAVED RW_NONINTERLEAVED
FORMAT:  S8 U8 S16_LE S16_BE U16_LE U16_BE S24_LE S24_BE U24_LE U24_BE S32_LE S32_BE U32_LE U32_BE FLOAT_LE FLOAT_BE FLOAT64_LE FLOAT64_BE MU_LAW A_LAW IMA_ADPCM S20_LE S20_BE U20_LE U20_BE SPECIAL S24_3LE S24_3BE U24_3LE U24_3BE S20_3LE S20_3BE U20_3LE U20_3BE S18_3LE S18_3BE U18_3LE U18_3BE DSD_U32_BE
SUBFORMAT:  STD
SAMPLE_BITS: [4 64]
FRAME_BITS: [4 640000]
CHANNELS: [1 10000]
RATE: [4000 4294967295)
PERIOD_TIME: [125 1486078)
PERIOD_SIZE: (0 4294967295)
PERIOD_BYTES: (0 4294967295)
PERIODS: (0 4294967295]
BUFFER_TIME: [1 4294967295]
BUFFER_SIZE: [1 4294967294]
BUFFER_BYTES: [1 4294967295]
TICK_TIME: ALL
--------------------
Plug PCM: Linear conversion PCM (S32_LE)
Its setup is:
  stream       : PLAYBACK
  access       : RW_INTERLEAVED
  format       : S16_LE
  subformat    : STD
  channels     : 2
  rate         : 44100
  exact rate   : 44100 (44100/1)
  msbits       : 16
  buffer_size  : 22050
  period_size  : 5513
  period_time  : 125011
  tstamp_mode  : NONE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 5513
  period_event : 0
  start_threshold  : 22050
  stop_threshold   : 22050
  silence_threshold: 0
  silence_size : 0
  boundary     : 1445068800
Slave: Hardware PCM card 1 'E30' device 0 subdevice 0
Its setup is:
  stream       : PLAYBACK
  access       : MMAP_INTERLEAVED
  format       : S32_LE
  subformat    : STD
  channels     : 2
  rate         : 44100
  exact rate   : 44100 (44100/1)
  msbits       : 32
  buffer_size  : 22050
  period_size  : 5513
  period_time  : 125011
  tstamp_mode  : NONE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 5513
  period_event : 0
  start_threshold  : 22050
  stop_threshold   : 22050
  silence_threshold: 0
  silence_size : 0
  boundary     : 1445068800
  appl_ptr     : 0
  hw_ptr       : 0
```
I can't see how `ffplay` is working but it [`ffplay`](https://github.com/FFmpeg/FFmpeg/blob/master/fftools/ffplay.c#L2501) uses  [`SDL_OpenAudioDevice()`](https://wiki.libsdl.org/SDL_OpenAudioDevice) but I can't see silent format conversion happening.

**Comment by whatdoineed2do** [comment]
> perhaps the fix is like you say, so configure `plughw` as default - if that is possible?

It looks like when we use `default` we can't add prefixes like `plughw`. This means in such cases folks will need to refer to the device itself (like `plughw:1` or `plughw:E30`).  I sent an additional PR to update the README to help with this situation.
