### ISSUE TITLE
Auto-reconnect causes paused streams to resume

### ISSUE THREAD

**Issue by SamuelCook** [ejurgensen/forked-daapd#1057]
When playing an audio stream to a remote Airplay receiver, pausing the audio in the forked-daapd web UI causes the connection to close. The player then automatically attempts to reconnect after 5 seconds, which causes the stream to resume.

Log example:

*pause*
```
[2020-07-15 12:36:22] [  LOG]     raop: Device 'Pallida' closed RTSP connection
[2020-07-15 12:36:22] [  LOG]   player: The AirPlay device 'Pallida' failed - attempting reconnect in 5 sec
```
*music starts playing*

Pausing the audio and then removing the Airplay target from the output selector allows the audio to remain paused.

**Comment by ejurgensen** [comment]
Thanks for the report. Again this device seems somewhat unusual in that it disconnects on pause. I haven't seen that before, and it isn't optimal because it makes un-pausing slow. Still, I agree forked-daapd shouldn't auto-reconnect in this case, so I will try to change that.

**Comment by ejurgensen** [comment]
Should be fixed now, hope it works now.
