### ISSUE TITLE
Cannot extract embedded artworks with ffmpeg 4.3.1

### ISSUE THREAD

**Issue by lldsolitude** [ejurgensen/forked-daapd#1061]
The latest version built from github master cannot extract embedded album covers from any of my files. Log shows
```
[2020-07-18 11:22:32] [  LOG]    xcode: Error occurred while encoding: I/O error
[2020-07-18 11:22:32] [  LOG]  artwork: Source 'embedded' returned an error for '%TITLE%'
```
Playback still works. Before updating I was using the 27.1 release from January and artwork extraction worked fine.
I'm using the Docker image built using the latest LSIO Dockerfile ([linuxserver/docker-daapd](https://github.com/linuxserver/docker-daapd)) but replacing the 27.1 release with the latest code. Access to my music files are provided with Docker volumes, and the user running daapd only has read-only privilege to these files.

**Comment by ejurgensen** [comment]
Thanks for reporting, does the log file actually say %TITLE%", or did you redact that part? And does this happen for all files, or is a particular one?

In any case I need more info to understand what is going on: "Steps to reproduce will greatly improve the chance of getting it fixed. If it is not possible then **set the log level to debug** (in /etc/forked-daapd.conf) and try to get some logging of when the error happens."

Finally, it is possible that the error comes from ffmpeg. So check if that has changed, and what the installed version is.

**Comment by lldsolitude** [comment]
The log doesn't actually say %TITLE%, it just means the title of the track. This happens to all files, not just a particular one. After changing log level to debug, it does seem to show that the problem is with ffmpeg ([forked-daapd.log](https://github.com/ejurgensen/forked-daapd/files/4941352/forked-daapd.log)). The currently installed version is ffmpeg 4.3.1 from Alpine Linux repo, upgraded from 4.2.4 when I rebuilt the Docker image.

**Comment by ejurgensen** [comment]
I can reproduce the error with a snapshot of newest ffmpeg (N-98502-g1998d1d6af). The error doesn't seem to be present in ffmpeg 4.1.6. I didn't test versions in between.

Right now, I don't know what is causing the error, but I will see if it is possible to work-around it on forked-daapd's side. Otherwise the only option might be a report to ffmpeg and hope they will fix it.

**Comment by ejurgensen** [comment]
I believe I found the cause and it should be fixed now. As you can see from the commit above it was as small change. I can't say for sure whether ffmpeg was at fault. Perhaps forked-daapd has just been using ffmpeg incorrectly, even though it worked.
