### ISSUE TITLE
Support for compatible movie files?

### ISSUE THREAD

**Issue by agustincordes** [ejurgensen/forked-daapd#1063]
Hi, this is more of a question, not an issue: are personal movie files supported by the server? I have a bunch of iTunes-compatible M4V files (without any DRM) that I'd like to stream from my QNAP NAS. However, it seems that only music is being supported at the time being. Is this correct?

Thanks in advance!

**Comment by ejurgensen** [comment]
forked-daapd is mostly for audio, but you can in fact stream m4v's movies to iTunes and probably also Apple Music. This is because all forked-daapd does is serve the file (like for audio), and then iTunes plays it.

You cannot stream videos directly to Airplay and Chromecast devices.

**Comment by agustincordes** [comment]
Thanks for the quick reply! However, it's my understanding that home sharing isn't supported, and won't ever be supported, right? Meaning that I can't access these files from the built-in Apple TV apps.

**Comment by ejurgensen** [comment]
Yes, that is correct
