### ISSUE TITLE
Library Management: file renames

### ISSUE THREAD

**Issue by SamuelCook** [ejurgensen/forked-daapd#1064]
Are instructions available for how to go about renaming files without losing metadata?

The main use case I have would be to replace files with a different filetype equivalent. For example I would like to replace `mysong.mp3` with `mysong.flac` and not have the play count reset to zero, not have to re-add the song to playlists, etc.

Is this something I would have to do via direct DB manipulation?

**Comment by ejurgensen** [comment]
You can do it with direct db manipulation, but it might not be necessary. One way to do without (not tested):

1. Stop forked-daapd
2. `mv /source/mysong.flac /forked-daapd_library/mysong.mp3`
3. Start forked-daapd. It will detect that the file has changed and rescan, but should preserve playcounts etc. That the file has an incorrect file ending shouldn't matter.
4. `mv /forked-daapd_library/mysong.mp3 /forked-daapd_library/mysong.flac` (forked-daapd should just update paths, so preserve other stuff)

It might not even be necessary to stop forked-daapd, not sure about that. Note that this assumes you are on a normal Linux platform with a fs that supports inotify (so not a network filesystem).

I'm not sure what you mean with regard to playlists? Obviously, if you have a .m3u that has `mysong.mp3` you will need to change that entry to `mysong.flac`.

**Comment by ejurgensen** [comment]
Should add that if you prefer to go with db manipulation, you need to update these tables/columns:
files->path
files->fname
files->virtual_path
playlistitems->filepath

**Comment by SamuelCook** [comment]
Given my music lives on a network share, I wasn't able to test the recommended steps. In the end I cooked up a simple script that seems to work well. I'll share it here in case it's useful to anyone in the future.

This script covers the following use cases:
- replacing an existing file in the library with a different file extension (e.g. replacing `x.mp3` with `x.flac` or vice-versa)
- changing the file name format (e.g. `x.mp3` to `artist-album-01-x.mp3`)
- replacing a single track with one in an album (e.g. `Unknown Album/x.mp3` to `An Album/09-x.mp3`)

In all cases, the metadata associated with the original track is preserved (play count, etc.).

The script requires that the replacement file exist and be readable, but not the original file. This allows the file to be renamed in place or deleted.

The script is run as ```music-merger <original file> <replacement file>```

If entries for both the original and replacement files exist in the database, the script swaps the file locations. This is because attempting to execute `DELETE FROM files` statements fail with an error `Error: no such collation sequence: DAAP`. To work around this, the file locations are swapped, and then the original file can be deleted from the file system, and a library rescan triggered. This allows forked-daapd to recognise that the file is no longer present and will clear the database record itself.

It's recommended to trigger an index rescan after running the script, to allow forked-daapd to update the database record with info found in the ID3 tag (album name, track number, etc.).


https://gist.github.com/SamuelCook/6c9d7a48ae96d83a2eb3ba05fb5ca932
