### ISSUE TITLE
New Wiki Page - iOS Shortcut to start any Spotify playlist quickly

### ISSUE THREAD

**Issue by cdlenfert** [ejurgensen/forked-daapd#1073]
I've added a new page with an iOS shortcut that may come in handy to some. I'm sure it can be enhanced and improved, but it's working well for me and I wanted to share.

https://github.com/ejurgensen/forked-daapd/wiki/iOS-Shortcut-to-start-any-Spotify-playlist-quickly

Not sure anyone can see when things get added to the Wiki. I Googled around on how to subscribe to it, but didn't find any great answers.

**Comment by ejurgensen** [comment]
Brilliant shortcut, thanks for sharing! I will certainly use this myself next time I get a shared Spotify track.

I don't know if we should keep this issue open? My suggestion would be to close it and then hope Google can find the page if anyone is searching for something like this.

**Comment by cdlenfert** [comment]
Good enough for me. I'll close it and lean on the wiki for future find-ability. Just wanted to give the regulars a heads up.
