### ISSUE TITLE
Song rating from iTunes library xml not getting set in songs3.db

### ISSUE THREAD

**Issue by boblund** [ejurgensen/forked-daapd#1075]
I'm running forked-daapd 27.2.107.git2ca10d9-2 on a raspberry pi 3 with stretch lite Linux pi 4.19.66-v7+ #1253.

My iTunes library consisted of songs with a mixture of artwork: in the song file and in the "Albums Artwork" folder. In this scenario, all of the iTunes song ratings were showing up in songs3.db. I noticed that those songs without artwork in the song file did not display artwork when accessed from forked-daapd via iTunes remote. I started adding artwork to those song files. At some point in this process, after updating songs3.db, I noticed all ratings in songs3.db were 0. This consistently happens now.

Attached is a forked-daapd.log in debug mode. I also attached the file NorthShoreDBEntry which is an extract from forked-daapd.log for a song that has a rating of 100 in iTunes.

[forked-daapd.log](https://github.com/ejurgensen/forked-daapd/files/5057927/forked-daapd.log)

[NorthShoreDBEntry.txt](https://github.com/ejurgensen/forked-daapd/files/5057930/NorthShoreDBEntry.txt)

**Comment by ejurgensen** [comment]
As far as I can tell from the log file, the rating is not being imported from the iTunes XML file. To do that you need to enable itunes_overrides in the configuration file.

Another time please attach a shortened log file.
