### ISSUE TITLE
mpd integration

### ISSUE THREAD

**Issue by snizzleorg** [ejurgensen/forked-daapd#108]
Just trying the mpc integration. I can get the status and play/paus but I suppose the playlist listing is not working yet right?

when I issue 

```
mpc lsplaylists
```

I get nothing in return.

any idea on how I play a particular playlist?

**Comment by chme** [comment]
Yes, this is one of the commands that is not yet implemented (you can find the list of supported commands in the [README](https://github.com/ejurgensen/forked-daapd#mpd-clients ).

You can play a playlist with the load command:
```
mpc load "file:/absolute/path/to/playlist"
```
To identify the path you can use the ls command.
