### ISSUE TITLE
libwebsockets requirements

### ISSUE THREAD

**Issue by karlp** [ejurgensen/forked-daapd#1084]
Hi,  I'm trying to cleanup the packaging of libwebsockets for openwrt, and would like to know which features of libwebsockets you are using, and/or need?

**Comment by ejurgensen** [comment]
I'm not sure what features libwebsocket offers, but have you considered aligning the OpenWrt features with the Debian version of the package? Most applications that use libwebsockets will probably work with that, I imagine.

To answer your question, you can check https://github.com/ejurgensen/forked-daapd/blob/master/src/websocket.c. The author is @chme so maybe he can also help you.

**Comment by karlp** [comment]
I have, but debian is far bigger, so no :)  forked-daapd compiles with the "core" functionality at least, but I didn't try running it.

**Comment by chme** [comment]
@karlp forked-daapd does not use any special feature from libwebsockets.

**Comment by karlp** [comment]
Ok, great thanks for the info!
