### ISSUE TITLE
Autostart forked-daapd

### ISSUE THREAD

**Issue by Ulrichgau** [ejurgensen/forked-daapd#1096]
It would be convenient if forked-daapd started automatically with the same song on the same place where it ended before.

**Comment by ejurgensen** [comment]
I don't think I will add this; I think restarting a song in the middle is a bit brutal towards the song/artist. It makes sense for podcasts and audiobooks, where is already supported.

Persisting the queue also makes more sense to me, but I think that option might also already exist via `clear_queue_on_stop_disable`. I don't remember exactly how it works in restart situations, but perhaps you could test it?
