### ISSUE TITLE
Autostart airplay

### ISSUE THREAD

**Issue by Ulrichgau** [ejurgensen/forked-daapd#1098]
When I switch on my beolit external speaker which is connected to forked-daapd via airplay I have to manually switch it on in the webinterface. Is there a way to activate it automatically when detected?

**Comment by ejurgensen** [comment]
Was it selected previously, i.e. when you switched it off? If so it should be selected when you switch it on again. The only exception is if you have already started playback, because forked-daapd avoids enabling new speakers during playback.

**Comment by ejurgensen** [comment]
Closing, no feedback
