### ISSUE TITLE
Bad cover art alignment in Now Playing on Firefox with v0.8.0 interface

### ISSUE THREAD

**Issue by mill1000** [ejurgensen/forked-daapd#1102]
Running commit 43311539668b70f3efb932367e3adc068272c9f2 to test the new web interface from #1082 

Everything seems to be working OK except I the cover art is not styled as expected in the Now Playing page on Firefox. 

See the screenshot
![image](https://user-images.githubusercontent.com/6924622/96345286-a9afc500-1057-11eb-9e9a-ff54ffbf370f.png)

I double checked in Chrome and Edge, both those center and style the cover art as I would expect.

**Comment by chme** [comment]
@mill1000 Thanks for testing the web interface changes! Unfortunately I cannot reproduce this error. Firefox on my Windows 7 machine (as well as Firefox on Linux and Android) is showing the cover artwork correctly aligned. Which version of Firefox are you using on which operating system? Just to confirm, the alignment was correct before the changes from #1082 ?

**Comment by mill1000** [comment]
Looks like this might have just been a cache issue on my browser. I was inspecting with Developer Tools on the web interface and when it pulled the page without using it's cache everything came through correctly. False alarm!
