### ISSUE TITLE
Cannot make player web interface work

### ISSUE THREAD

**Issue by avigan** [ejurgensen/forked-daapd#1103]
I have installed forked-daaped from source on a raspberry pi 4, but for some reason I cannot make the player web interface work. When the daemon is started and I try to connect to the web interface, in my browser I just see a blank page with **Forbidden** written. The log from forked-daapd shows:

```
[  LOG]    httpd: Web interface request to '/' denied: No password set in the config
[DEBUG]    httpd: HTTP request: '/favicon.ico'
[  LOG]    httpd: Web interface request to '/favicon.ico' denied: No password set in the config
```

I have set a password in `forked-daapd.conf` from what I understand the problem seems to be in `httpd`. Not sure how to deal with this error, so any help would be appreciated.

 -- Arthur;

**Comment by ejurgensen** [comment]
Did you remember to uncomment the admin_password setting?

**Comment by avigan** [comment]
My bad, I had mistaken the admin_password and the password for the library. It is working fine now that I have uncommented the admin password!
