### ISSUE TITLE
Conflict installing `libcurl*-dev` on Debian 10.6

### ISSUE THREAD

**Issue by tobx** [ejurgensen/forked-daapd#1106]
I have a problem installing `libcurl*-dev` on Debian 10.6 with:

```bash
apt install libcurl*-dev
```

as described here:
https://github.com/ejurgensen/forked-daapd/blob/master/INSTALL.md#quick-version-for-debianubuntu-users

I get the following error message:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libcurl4-gnutls-dev : Conflicts: libcurl4-nss-dev but 7.64.0-4+deb10u1 is to be installed
                       Conflicts: libcurl4-openssl-dev but 7.64.0-4+deb10u1 is to be installed
 libcurl4-nss-dev : Conflicts: libcurl4-gnutls-dev but 7.64.0-4+deb10u1 is to be installed
                    Conflicts: libcurl4-openssl-dev but 7.64.0-4+deb10u1 is to be installed
 libcurl4-openssl-dev : Conflicts: libcurl4-gnutls-dev but 7.64.0-4+deb10u1 is to be installed
                        Conflicts: libcurl4-nss-dev but 7.64.0-4+deb10u1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

I could fix this and get `forked-daapd` running by installing the packages with `libcurl-*-dev` so that it would not match `libcurl3-*` and `libcurl4-*`, but I am not sure if version 3 or 4 would have been better.

**Comment by ejurgensen** [comment]
All versions should be fine, I will see if I can change the instructions so that they match any version.

**Comment by ejurgensen** [comment]
I've changed the instructions now, see commit https://github.com/ejurgensen/forked-daapd/commit/36d07baf2ce0339546f2f1ad084298b090702e10 (I put the wrong issue number in the commit text).
