### ISSUE TITLE
iOS remote app connection

### ISSUE THREAD

**Issue by Depechie** [ejurgensen/forked-daapd#1110]
So, I got forked-daap running in a container on an intel NUC with Debian. Also Home Assistant is installed on the same machine.
Everything is actually working fine, for what I can tell, my music is shown and I can use the web page to cast music to several airplay receivers.

The only thing I'm not able to get working is having the Remote app on my iPhone showing the forked-daap library.
The pairing is done, but nothing is shown in the Remote.

I have read the readme for the remote section, but can't pinpoint the issue.
The docker log shows:
2020-10-22T19:15:45.268894000Z [  LOG]   remote: Pairing succeeded with Remote 'Depechie’s iPhone' (id ....

So I thought things were ok.
Anyone done this in a simiral environment that can give me pointers on what I can validate to try to resolve this?

**Comment by jptrsn** [comment]
I can confirm that remote connection to Android running the app "Retune" works as expected with forked-daapd. That app also connects properly to my iTunes library on my PC. Do you have any other phones/tablets you can test with?

**Comment by Depechie** [comment]
Hey @jptrsn yeah using another tool works. That's because those tools use the MPD as connection, the Remote app will try through Bonjour and because Home Assistant ( with HomeKit addin ) is also running on the same device, those 2 conflict and the Remote app can't get a connection.
Underlying cause is this - mdns: Avahi state change: client collision
So 2 services trying to compete for the same registration.

Bit of a shame we can't run forked-daapd on same device than, but also not sure if we can work around this.

**Comment by ejurgensen** [comment]
Retune does not use MPD, it works like Remote on iOS, and it also uses mdns + pairs. You can see the [other Android Remote alternatives here](https://github.com/ejurgensen/forked-daapd/blob/master/README.md#supported-clients). None of those are MPD.

**Comment by Depechie** [comment]
Hmm ok, wel I do not have an Android. But using MPD clients on my iPhone do work.

**Comment by ejurgensen** [comment]
You are probably right about the underlying cause being a conflict, so I except Retune also wouldn't work. Might be interesting to verify, though.

**Comment by Depechie** [comment]
Yeah would love to try it to be sure of course... but like I said we don't own any android devices :/ is there something on Windows that would be useful to try out?

**Comment by ejurgensen** [comment]
Check the link above - it also has a Windows client, I think you can get it via Microsoft Store too.
