### ISSUE TITLE
Request failed  When select a speaker while playing music

### ISSUE THREAD

**Issue by Goven** [ejurgensen/forked-daapd#1118]
I'm using forked-daapd on Debian buster,version 27.2,airplay device is HomePod with software version 14.1 and AppleTV with software version 14.2,while playing music,if I select one of my AirPlay speakers,there's a error message shows on the Web UI,and there is no sound output,please help:

Error message on the Web UI:
Request failed (status: 500 Internal Server Error, url: http://10.0.0.6:3689/api/outputs/0/toggle)

And the log:

[  LOG]     raop: ANNOUNCE request failed in session startup: 400 Bad Request
[  LOG]   player: The AirPlay device 'Goven’s HomePod' failed to activate
[  LOG]      web: JSON api request failed with error code 500 (/api/outputs/233717570928032/toggle)
[  LOG]   laudio: Failed to attach mixer 'default': No such file or directory
[  LOG]   laudio: Could not open mixer 'default' ('(null)')
[  LOG]      web: JSON api request failed with error code 500 (/api/outputs/0/toggle)
[  LOG]     raop: ANNOUNCE request failed in session startup: 400 Bad Request
[  LOG]   player: The AirPlay device 'Goven’s HomePod' failed to activate
[  LOG]      web: JSON api request failed with error code 500 (/api/outputs/233717570928032/toggle

![image](https://user-images.githubusercontent.com/732774/98128542-03870a80-1ef3-11eb-820c-d8988e5c726c.png)
![image](https://user-images.githubusercontent.com/732774/98128573-08e45500-1ef3-11eb-8628-5b84c478932b.png)

**Comment by ejurgensen** [comment]
Have you checked [this issue](https://github.com/ejurgensen/forked-daapd/issues/902), which is similar?

**Comment by Goven** [comment]
Sorry for my bother,after setting in the home app > allow Speakers & TV Access > Anyone On the Same Network (or Everyone),the problem solved,thanks.
