### ISSUE TITLE
Possible to play a specific song via API?

### ISSUE THREAD

**Issue by HarmlessSaucer** [ejurgensen/forked-daapd#1119]
Hey!
I'm trying to use Forked DAAPD to make a music-playing-system for my daughter using AirPlay and Home-Assistant.
I've got some tracks that I've added to Forked-daapd, and I can play them to the HomePod etc okay, and I have Forked-DAAPD showing up in Home-Assistant okay.

However, what I'd like to be able to do is trigger a specific song via an automation in Home-Assistant, which I think the best way would be by the rest-API.  I can't seem to find a way to do that without chaining multiple commands to clear up-next, add a file to up next, etc..  am I missing something really obvious?  Can I send a command to play a specific songID?

**Comment by ejurgensen** [comment]
Yes, it is possible, but maybe not easy to find. I think what you are after is [the add items to queue API](https://github.com/ejurgensen/forked-daapd/blob/master/README_JSON_API.md#adding-items-to-the-queue), note the `playback` and `clear` options.

**Comment by HarmlessSaucer** [comment]
Thanks @ejurgensen !  I posted this... went and grabbed a drink... came back to the docs, and had another go.  Cracked it.  Can't believe I missed this!  In case it helps anyone else:
`curl -X POST "localhost:3689/api/queue/items/add?uris=library:track:1&clear=true&playback=start"`

I'm doing this via URI of the track, but you could obviously do it differently.
