### ISSUE TITLE
The instructions for the web interface on Debian make no sense

### ISSUE THREAD

**Issue by grpfl** [ejurgensen/forked-daapd#1124]
If the web interface files are in web Src directory, where is that directory?

**Comment by ejurgensen** [comment]
What instructions are you referring to?

**Comment by grpfl** [comment]
That is my point, but let’s start with the read me for this section.

**Comment by ejurgensen** [comment]
Sorry, I don't understand

**Comment by grpfl** [comment]
If I’m going to install the web interface, what do I do first? There is no web src directory on my machine.

**Comment by ejurgensen** [comment]
If you follow [these instructions](https://github.com/ejurgensen/forked-daapd/blob/master/INSTALL.md#quick-version-for-debianubuntu-users) you will get everything - but do you want _only_ the web interface?

**Comment by twolife** [comment]
I suppose that @grpfl is refering to the fact that the web-src directory is not included in the tarball "forked-daapd-27.2.tar.xz", i was confused as well the first time ^^
