### ISSUE TITLE
Can't remove podcast

### ISSUE THREAD

**Issue by rainerstandke** [ejurgensen/forked-daapd#1126]
"Podcast cannot be removed. Probably it was not added as an RSS playlist."

This is what's displayed in the web UI when I try to remove the NY Times The Daily podcast. I have rebuilt the database, and I have looked for files in the Podcast folder in the library - there is nothing in it.

What else can I try?

Thanks!

**Comment by ejurgensen** [comment]
Please set the log level to debug (in /etc/forked-daapd.conf) and try to get some logging of when the error happens. Don’t cut and paste lengthy log outtakes here on github. Instead, attach the log file.

**Comment by whatdoineed2do** [comment]
This error comes from the web when it tries to figure out the RSS id but it fails in some basic validation   Can you show the outputs:

* find intermediate id

   run: `sqlite3 /var/cache/forked-daapd/songs3.db "select id from files where path = (select filepath from playlistitems where playlistid=(select id from playlists where title like 'The Daily') )"`

    it should give you one value, like `15573`

* use result from above, put it in the string `http://forked-daapd.local:3689/api/library/tracks/`_your id here_`/playlists` into your browser or on the terminal via `curl` and paste the results
```
$ curl -s http://forked-daapd.local:3689/api/library/tracks/15573/playlists  | jq
{
  "items": [
    {
      "id": 16,
      "name": "The Daily",
      "path": "https://podcasts.apple.com/za/podcast/the-daily/id1200361736",
      "parent_id": "0",
      "type": "rss",
      "smart_playlist": false,
      "random": false,
      "folder": false,
      "uri": "library:playlist:16"
    }
  ],
  "total": 1,
  "offset": 0,
  "limit": -1
}
```
The expectation from the web code that theres only 1 entry and also the `type` is `rss` which your data fails for some reason.

**Comment by rainerstandke** [comment]
Thanks for following up!
Here is the curl call & result:
```
curl -X GET "http://forked-daapd.local:3689/api/library/tracks/20095/playlist"
<html>
<head>
<title>403 Forbidden</title>
</head>
<body>
<h1>Forbidden</h1>
</body>
</html>
```

Strangely, I could not run the squlite command - it yielded: `-bash: sqlite3: command not found` - but this is only a side note.

I ended up using a GUI tool to get the id. Wouldn't the problem be solved by deleting the playlist entry, either by way of the GUI tool, or by issuing an appraise curl to the API?

Thanks for your help!

**Comment by whatdoineed2do** [comment]
Sorry, cut/paste error (missing `s` at the end)

`curl -X GET "http://forked-daapd.local:3689/api/library/tracks/20095/playlists"`

If this comes back with no items (`{ "items": [ ], "total": 0, "offset": 0, "limit": -1 }`) then theres a bug somewhere that means theres some inconnsistency in the db.  do you recall deleting the podcast before?

The problem in this situation is that you can't delete this `podcast` by the web i/f and only through the db via `sqlite3`.

**Comment by whatdoineed2do** [comment]
One thing to confirm, this podcast ... this was added as an `rss` podcast or are the items added as local files to the `/Podcasts` directory?

If the latter then you can't delete this podcast via the web i/f

**Comment by rainerstandke** [comment]
With the `s` at then it now gives:
```
curl -X GET "http://forked-daapd.local:3689/api/library/tracks/20095/playlists"
<html>
<head>
<title>403 Forbidden</title>
</head>
<body>
<h1>Forbidden</h1>
</body>
</html>
```
... not much of a change.

I have started to muck with the database via the GUI tool, so far, no change.

It should be safe to just throw away the db file, and have it rebuilt, right?

**Comment by rainerstandke** [comment]
The good news is that removing via db GUI editor did work. Then adding The Daily podcast via web UI does yield the postcast episodes to show up. Doesn't play them though. But, getting back to the good news part, the pod cast can be removed as expected via web UI.

To add a little bit of background / history: The NYT website at `https://www.nytimes.com/2018/07/16/podcasts/the-daily/how-do-i-listen-to-the-daily.html` lists the podcast feed URL as: `http://feeds.podtrac.com/zKq6WZZLTlbM`

I had added that feed URL. When I `curl`'ed it it seemed to redirect a few times to: `http://rss.art19.com/the-daily`. This is the one that lists the episodes. I did try one of the URLs from the `curl`'ed feed, and it does play fine in a web browser.

Next, I'll try to do what @ejurgensen had asked, i.e. try to capture a log of what happens when I try to play an episode.

**Comment by ejurgensen** [comment]
I tried some of the podcasts from the feed, and the reason it fails is that for these streams the decoder requires a larger probe size than usual. I'm not sure why exactly that is. The default probe size is set low in forked-daapd for performance reasons. This is the first time I see it cause problems.

There is not much you can do to fix it unless you are building yourself. Then you can remove [this line ](https://github.com/ejurgensen/forked-daapd/blob/master/src/transcode.c#L829)+ the following line, and it should work.

If I can catch this type of decoder error I could probably make a fix so that it retries with a larger probe size.

**Comment by whatdoineed2do** [comment]
@ejurgensen - I remember this as a subtle design choice/side effect.


If you add an RSS (ie `http://localhost/rss` called "foo bar") an entry is added to the `playlist` and epsidoes to `playlistitems` tables.

If during a periodic RSS refresh any of the RSS sources (in ths case `http://localhost/rss`) is not reachable (because i stop the `lighttpd` hosting this), then this is dropped from `playlistitems`.

```
[ INFO]     http: Making request for http://localhost/rss
[  LOG]     http: Request to http://localhost/rss failed: Couldn't connect to server
[  LOG]      lib: Failed to fetch RSS from 'http://localhost/rss' (return -1, error code 0)
[  LOG]      lib: Could not get RSS/xml from 'http://localhost/rss' (id 72)
```
```
sqlite> select id,title from playlists where type=4;
id|title
72|foo bar
71|The Infinite Monkey Cage
70|The Boring Talks

sqlite> select * from playlistitems where playlistid=72;
sqlite> 
```

At this point, if you goto the `podcasts` page, you still see the "foo bar" podcast but you can NOT remove it, giving the ` Podcast cannot be removed. Probably it was not added as an RSS playlist. ` error message.  If you ask the server to 'rescan' your library, it will clear this out and "foo bar" RSS is no longer there.

If the RSS item comes back during the next period scan, you'll  get things back:
```
[ INFO]     http: Making request for http://localhost/rss
[ INFO]     scan: Added or updated 4 items from RSS feed 'http://localhost/rss' (id 72)
```
```
sqlite> select * from playlistitems where playlistid=72;
id|playlistid|filepath
981|72|http://localhost/rss1.mp3
980|72|http://localhost/rss2.mp3
979|72|http://localhost/rss3.mp3
978|72|http://localhost/rss4.mp3
```
Asking to remove the podcast from the web page now works.

It may be worth a small PR to update the error reported to avoid potential confusion for RSS and not allow removal for local podcast files.

**Comment by rainerstandke** [comment]
@ejurgensen, is there something you would need from me to 'catch this error'? Would it help if I tried to log it?

@whatdoineed2do, not sure this helps, but I only ever added that rss feed link via the web GUI.

**Comment by ejurgensen** [comment]
I've added a fix so that forked-daapd will retry if the small probe fails, and @whatdoineed2do has fixed an issue that could prevent a podcast from being deleted. So it should work now, @rainerstandke.

@whatdoineed2do I notice that adding the NY Times RSS is very slow because of the redirections and the ffmpeg scanning. I remember we considered removing the scan_metadata_stream() in rssscanner.c - do you remember why we kept it? Do you see any issues in removing it?

**Comment by whatdoineed2do** [comment]
From the comments and memory, the `scan_metadata_stream()` was to handle some RSS that gave streams but with bad/missing info on the actual RSS entry (no title etc) and thus this was the only way to get info.  I recall seeing a few instances where the RSS entry was missing title but instead it was set on the actual mp3.

As a workaround, I guess we can optimise this and only call `scan_metadata_stream()` if we determine the key entries from the RSS entry are missing.

If we were to drop the call, we'd still need most of the other `mfi` data fld updates from `scan_metadata_stream()`.

**Comment by rainerstandke** [comment]
thank you very much @ejurgensen for that fix - I was just getting started trying to figure out how to build on the rip, and did not looking promising...

I have done the usual update upgrade thing - but The Daily still behaves the same. Am I correct assuming that it'll take a while for the fix to propagate?

**Comment by whatdoineed2do** [comment]
@rainerstandke - if you are still looking at the deletion issue, I was able to get around this by forcing a library rescan (available from the top right burger menu and `Update Library`) - that would delete that RSS feed.

**Comment by rainerstandke** [comment]
I am not looking at deleting the podcast any more. I was referring to what you said a few hours ago: "I've added a fix so that forked-daapd will retry if the small probe fails, ... . So it should work now, @rainerstandke."

**Comment by ejurgensen** [comment]
@rainerstandke you didn't mention what platform+build you were using, but I see from your log it is an RPi, so I assume it is my Raspbian RPi build. If so, then yes, you will have to wait a bit for a new release with the fix.

@whatdoineed2do was there also something about the stream scan being there to determine if there is embedded artwork? Maybe a possible improvement would be to keep the scan, but [to do it async like so](https://github.com/ejurgensen/forked-daapd/commit/9b76eb72d0caac443a1374e77e5269e8674c9a6f).

**Comment by rainerstandke** [comment]
@ejurgensen, what would it take to build it on the rpi?

Thanks again for all your effort!

**Comment by ejurgensen** [comment]
@rainerstandke I have some test builds you can use. Do you need for Raspbian Stretch or Buster?

@whatdoineed2do please disregard the above async idea, I changed my mind about it, it would not be the right solution.

**Comment by rainerstandke** [comment]
@ejurgenson, thanks for the offer. I think I’ll wait for the new version, but I’d be interested in playing with the build process on Buster, if you have a ready-made recipe for me to look at.

**Comment by ejurgensen** [comment]
For Raspbian you can use the build process describer in INSTALL.md, but I would recommend against it. To avoid current and future conflicts, you would need to first remove the current version, incl. the apt source, and that means you will no longer automatically get updates.

I suggest you instead unpack and install the below deb (with "dpkg -i"), it is versioned in such a way that it will automatically be replaced when I release a newer version to the repository (and you run apt update + upgrade):
[forked-daapd_27.2.109~test1-3_armhf.zip](https://github.com/ejurgensen/forked-daapd/files/5588747/forked-daapd_27.2.109.test1-3_armhf.zip)

**Comment by ejurgensen** [comment]
Closing, no feedback
