### ISSUE TITLE
[web] Add podcast on web page does not display new podcast in list

### ISSUE THREAD

**Issue by whatdoineed2do** [ejurgensen/forked-daapd#1132]
cc @chme 

On http://localhost:3689/#/podcasts, if you add a new RSS the list of podcasts (at the bottom of the page) does not display a the newly added RSS podcast to the list.

This looks like its a browser/page caching issue.  I can resolve this by this small patch but don't know if this is the right place.  I'd expect the DB 
```
diff --git a/src/httpd_jsonapi.c b/src/httpd_jsonapi.c
index 15ed2ffe..85aedb5f 100644
--- a/src/httpd_jsonapi.c
+++ b/src/httpd_jsonapi.c
@@ -3335,6 +3335,10 @@ jsonapi_reply_library_albums(struct httpd_request *hreq)
          DPRINTF(E_LOG, L_WEB, "Invalid media kind '%s'\n", param);
          return HTTP_BADREQUEST;
        }
+
+      // Ask client not to cache this type of media since it can change
+      if (media_kind == MEDIA_KIND_PODCAST)
+        httpd_response_not_cachable(hreq->req);
     }
 
   reply = json_object_new_object();
```
I see in the browser inspector this sequence:
* 200 `api/library/add?url=....` - adding new podcast
* 304 **cached** `api/library/albums?media_kind=podcast` - call to get the list of podcasts never goes to server hence never updated
* 200 'api/search?type=tracks&expression=media_kind+is+podcast+and+play_count+%3D+0+ORDER+BY+time_added+DESC` - get the new RSS entries fetched and displayed

If i navigate away from the podcast page and back, the newly added RSS is now fetched.  So, can't tell if its a race condition on the db update.

The `library_item_add()` is sync so I can't quite tell if this DB-is-not-updated.

Using the patch above works everytime though.

**Comment by chme** [comment]
The server returns 304 because the db update timestamp is updated asynchronously (with a 5 second delay). So at the time we are doing the request to reload the podcasts, the old update time is still in the db and the server does not recognize that the browsers cached version is invalid.

I have opened PR #1134 to fix this by directly updating the timestamp after adding the podcast. Would be great, if you can give #1134 a try.
