### ISSUE TITLE
Cannot cast to Lenovo Smart Clock

### ISSUE THREAD

**Issue by jptrsn** [ejurgensen/forked-daapd#1137]
I have recently gotten a [Lenovo Smart Clock](https://www.lenovo.com/ca/en/smart-clock), which has a cast receiver (audio only). I can cast from youtube music or the google podcast app without any issue. However, I cannot use it as a speaker from Forked Daapd. As far as I can tell, the OS is Android Things, but I do not know if that has any relevance.

*Steps to reproduce:*
Select my clock as a speaker in the UI. See the red status error bar tell me that the server responded with a 500 error.

*Error Logs*
> [ INFO]     cast: Connection to 'James clock' established using TLS1.3
[ WARN]   player: Output delay detected: player is 3 ticks behind, catching up
[ WARN]     cast: Device 'James clock' could not launch app id '85CDB22F', trying '0F5096E8' instead
[  LOG]     cast: Device 'James clock' could not launch app id '85CDB22F' nor '0F5096E8' - aborting
[  LOG]   player: The Chromecast device 'James clock' failed to activate
[  LOG]      web: JSON api request failed with error code 500 (/api/outputs/2219439034)

*Version of forked-daapd*
Version 27.2

*Platform*
Docker 19.03.8 running `linuxserver/daapd` on Ubuntu Server.

**Comment by ejurgensen** [comment]
This means that forked-daapd can't start the receiver app on the device. It is not the same app as something like youtube uses, but it is the same that Chrome/Chromium uses for screen mirroring. So please test if that works. Here's how:

1. Start playback of an mp3 with Chrome/Chromium (just insert the path to the mp3 in the address bar, and it should start playing)
2. Right click on the playback widget and select Cast, wait for the device to be found, and then select it

If this doesn't work then there isn't much I can do. If it does work then we need to figure out which receiver app the browser is using, but first I hope you can do the above.

**Comment by jptrsn** [comment]
Interesting - the smart clock doesn't appear in the list of cast receivers from any web browser. I can't cast to it from youtube music on the web, and even the android app doesn't appear to pick up the speaker as a remote output.

However, I did manage to find a work-around. If I create a speaker group with only the smart clock in it, I can select that as an output and it works as expect. Very odd behaviour, but I can work around it, so I think for now, I'm all set. It's certainly an issue with the hardware/software on Lenovo's side, since native casting of audio doesn't work as expected.

Happy to share logs or anything else that may help, but for now, I'm closing the issue, since as far as I can tell, it's nothing to do with forked-daapd.

Thanks for the help!
