### ISSUE TITLE
Spotify on TrueNAS iocage

### ISSUE THREAD

**Issue by guliciuc** [ejurgensen/forked-daapd#1138]
just a question, 
I just installed this on a TrueNAS iocage, and it seems that "forked-daapd was either built without support for Spotify or libspotify is not installed." I just want to make sure if i did something wrong or there is no more support for spotify on freebsd installs.

**Comment by ejurgensen** [comment]
You would need libspotify, and I don't know if there is any way to get that for your platform. I think it also depends on the architechture. You would need to google around for that. If you manage to get it then it should work.
