### ISSUE TITLE
Clients don't get metadata + file access error in log

### ISSUE THREAD

**Issue by ddppddpp** [ejurgensen/forked-daapd#1139]
I'm running a setup with streaming from iOS -> shairport-sync -> forked-daapd->multiple outputs.
I also have forked-daapd integrated into Home Assistant (www.home-assistant.io) for fun and other automations.
I can see the correct artist/album/song+artwork metadata in the web interface on http://forked-daapd.host:3689 and in the iOS Remote app, but not in the home assistant integration.
I can also see errors logged in /var/forked-daapd.log in the following format

> <timestamp>[LOG] xcode: Cannot open '/tmp/forked-daapd.<random_string>.jpg' : No such file or directory

I guess this is probably an issue with the home assistant integration, however the curious thing is that there *is* a .jpg file in the /tmp directory, however the error is related to the artwork of the *previous* song. The file is owned by root with restricted rights (600).
Any idea how to troubleshoot further?

**Comment by ejurgensen** [comment]
The log message does indicate a forked-daapd error, but since you see the artwork in other clients I am not sure it is connected to the missing artwork in HA.

Please set the log level to debug (in /etc/forked-daapd.conf) and try to get some logging of when the error happens. I.e. you need to find the place where HA makes a request for artwork. Don’t cut and paste lengthy log outtakes here on github. Instead, attach the log file.

**Comment by ddppddpp** [comment]
You're right, turns out this is completely unrelated to Home Assistant.
A restart of Home Assistant fixed the not-showing metadata and artwork for me.
However, the error in the log persists - it is visible each time there a change of song. I'm attaching a debug log, example of the error can be seen at line 10667, you can search for the string xcode.
[forked-daapd.log](https://github.com/ejurgensen/forked-daapd/files/5609132/forked-daapd.log)

**Comment by ejurgensen** [comment]
Ok, the log message should be fixed now. It came because forked-daapd receives two images from the Shairport pipe right after eachother, and so when the read thread got around to probing the artwork the first image has already been replaced by the next.
