### ISSUE TITLE
How to start a radio station via API call?

### ISSUE THREAD

**Issue by cdlenfert** [ejurgensen/forked-daapd#1140]
I'm trying to figure out if there's a way to use the JSON API to start a radio station. I've had it set up to que a specific playlist ID (which is my station saved as an M3U file), but this doesn't work now from the API request. The request looks like `http://forked-daapd.local:3689/api/queue/items/add?uris=library:playlist:17?&clear=true&playback=start`. However I'd rather not have to use the playlist ID and instead would like to add the station via it's stream directly to my queue.

In the web interface, this is how the "Add Stream" button in the que screen works. Is the functionality already available and I just don't know the right commands?
![image](https://user-images.githubusercontent.com/17277745/100379581-5b84ce80-2fd2-11eb-8c16-bc03876c68aa.png)

If it's not possibly currently, would a possible workaround be to create a Smart Playlist and call for it by name with the "expression" query thing?

**Comment by ejurgensen** [comment]
I think you can do it with something like:
`/api/queue/items/add?uris=http:%2F%2Fsomeradio.com%2Fpath%2Fmorepath&shuffle=false&clear=true&playback=start`

**Comment by cdlenfert** [comment]
I was able to get that same call to work just before I was able to update/resolve this issue. Thank you! 
I'm also curious how to find out all of the types of values that can be passed to the `uris` object, or any other objects in the JSON API. Basically if I don't see an example in the README I don't know what will work (or what all the options are).

**Comment by nk-gears** [comment]
@cdlenfert You can capture all the requests going in and out using the Network Tab in your Browser with the web interface
