### ISSUE TITLE
cannot get Hifiberry working

### ISSUE THREAD

**Issue by kalle2000** [ejurgensen/forked-daapd#1142]
Hi,

i bought a HIFIberry DAC+ zero recently, however I cannot get it working with forked-daapd.

aplay -l:

**** List of PLAYBACK Hardware Devices ****
card 0: sndrpihifiberry [snd_rpi_hifiberry_dac], device 0: HifiBerry DAC HiFi pcm5102a-hifi-0 [HifiBerry DAC HiFi pcm5102a-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

log of forked-daapd:
laudio: Available ALSA playback mixer(s) on hw:0 CARD=sndrpihifiberry (snd_rpi_hifiberry_dac): (no mixers found)
laudio: Invalid CTL sndrpihifiberry[2020-12-01 12:03:34] [  LOG]   laudio: Failed to attach mixer 'sndrpihifiberry': No such file or directory

alsamixer tells me that this device has no controls.

So which settings do I have to make in forked-daapd.conf?
card="hw:0"
mixer=""
mixer_device="sndrpihifiberry

thx

**Comment by whatdoineed2do** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?p=1147994#p1147994

Looks like you need to add a _software control_ and then use that as your mixer.

**Comment by kalle2000** [comment]
thx. software control made the job. another howto: https://support.hifiberry.com/hc/en-us/community/posts/201847441-DAC-Lite-Software-volume-control
