### ISSUE TITLE
Request - Custom Speaker Names

### ISSUE THREAD

**Issue by cdlenfert** [ejurgensen/forked-daapd#1145]
I've been playing around with some iOS shortcuts recently, one of which can enable multiple speakers by name.
https://github.com/ejurgensen/forked-daapd/wiki/iOS-Shortcut-to-enable-any-speakers-by-voice

It works great, and as long as a speaker has name that Siri can understand when spoken then there is really no problem. However, I do have one speaker that I can't control/change the name of, and even though I can say "Genie" and control it, this isn't the best experience when I'd rather say "Living Room". Of course Siri has no idea what a "Eufy" is :)
![image](https://user-images.githubusercontent.com/17277745/101379672-c0adaf00-3871-11eb-9895-4f8590c06e60.png)

If it were possible in the config to set custom names for speakers, and in the JSON API to get that data, then I could label my EUFY GENIE-1490 whatever I wanted. I'm not sure how many people have these devices, but at least a couple years ago they were very cheap (8-20 US dollars), and they have Alexa capabilities which is a very nice combo.

**Comment by ejurgensen** [comment]
I could add a "nickname" option like there is for the local audio, which would mean that forked-daapd would use that name for it. Is it something like that you are thinking?

**Comment by cdlenfert** [comment]
@ejurgensen That sounds exactly like what I am thinking!

**Comment by cdlenfert** [comment]
I suppose also if the "nickname" could override and replace the actual "name" data, then changes to the API to support a nickname wouldn't be necessary as the nickname would replace the speaker name. Then queries for speakers names like I'm doing in my shortcut would work as-is. Do we care what the original name of a speaker is if we're giving it a nickname? You could always see the original name in the nickname assignment in the config file.

**Comment by ejurgensen** [comment]
I've made the required changes [here in this branch](https://github.com/ejurgensen/forked-daapd/tree/nickname1), but I haven't tested them yet. Please test if you can.

Yes, the name is completely replaced - forked-daapd doesn't need to know the original name, so in that sense it is simple.

**Comment by cdlenfert** [comment]
@ejurgensen thank you. I've installed, tested, and everything seems to be working great. Speaker name is updated, shortcut works, great solution!

**Comment by ejurgensen** [comment]
Good to hear, I have merged it now
