### ISSUE TITLE
The AirPlay device 'xxx' failed to activate

### ISSUE THREAD

**Issue by bkmar1192** [ejurgensen/forked-daapd#1147]
Getting the error The AirPlay device 'xxx' failed to activate. I have Forked-Daapd running on another computer (pi) and it is running there just fine. Trying to install on a Unbuntu computer and it won't connect to any of the speakers. I get the following errors regardless of which speaker I try to connect to.  

[DEBUG]     raop: startup_options: Sending ANNOUNCE to 'Kitchen'
[DEBUG]     raop: Local address: 192.168.1.xxx (LL: no) port 43624
[ INFO]        raop: Setting up AirPlay session 3432143465 (192.168.1.xxx -> 192.168.1.xxx)
[DEBUG]     raop: startup_announce: Sending SETUP to 'Kitchen'
[DEBUG]     raop: Negotiated AirTunes v2 UDP streaming session 1; ports s=6000 c=6001 t=6002
[DEBUG]     raop: startup_setup: Sending RECORD to 'Kitchen'
[DEBUG]     raop: RTP-Info is seq=56226;rtptime=1441310849
[DEBUG]     raop: device_stop: Sending TEARDOWN to 'Kitchen'
[  LOG]        raop: RECORD request failed in session startup: 500 Internal Server Error
[DEBUG]     raop: startup_cancel: Sending TEARDOWN to 'Kitchen'

**Comment by ejurgensen** [comment]
This might be because you have a firewall blocking incoming connections (the speaker will try to make a connection to forked-daapd). Try "sudo ufw disable".

**Comment by bkmar1192** [comment]
Thank you so much that did the trick.  Read more about issues with UFW and noticed that you can't just allow a particular port. I'll just add the ip addresses of my airplay devices to UFW.
