### ISSUE TITLE
Turn on via Home Assistant

### ISSUE THREAD

**Issue by kimme1024** [ejurgensen/forked-daapd#1149]
Hi!

As I'm trying to find a way to control my Spotify music through my HA-dashboard and play music via my Airplay enabled Yamaha receiver. With forked-daapd I'm coming very close to achieve what I want to do.

Now my issue is the following:

When I shut down my receiver the forked_daapd_server entity also shuts down. After that I can't toggle the server to on again so I have to go to the forked-daapd-webinterface and start playing a song. After that everything turns on again.

I guess this is related to the fact that shutting down the last playing receiver makes that the queue is emptied. So re-enabling requires a song/playlist to be selected before the receiver is triggered back to its on-state.

I don't know this makes sense but I hope someone could help me out with this issue.

Thanks in advance!

**Comment by ejurgensen** [comment]
I'm not sure I totally understand the issue, but maybe this is a setting that can help you:
https://github.com/ejurgensen/forked-daapd/blob/master/forked-daapd.conf.in#L382

**Comment by kimme1024** [comment]
I’ll look into it. Thanks.
I tried fixing it with a couple of automations and  so for it seems to work now but I’ll have to see if it remains that way.
