### ISSUE TITLE
Finally Found: Working Android Airplay receiver

### ISSUE THREAD

**Issue by Porco-Rosso** [ejurgensen/forked-daapd#1150]
Hello, I've been following the development of forked-daapd for some years, and I have to say it is one of my favorite github projects. Thanks for the great work and stewardship @ejurgensen 

I have been using it with my airplay receiver (Yamaha) without issue for some time, but was always looking for a working Airplay receiver for Android. Cheap android devices have flooded the market over the years, so they make a good candidate for turning "dumb" speakers into "smart" ones. 

Santa came early this year! After a long search I finally found a working app that does not require root to run. 
https://github.com/xfirefly/Airplay-SDK
Although the app is in Chinese, I can confirm it does work with forked-daapd  (although not itunes, weirdly enough).
You can grab the apk from the github repo. It requests location permissions, but does not require them to run.

If you would like I can add it to the wiki, as I'm sure others might find this useful.

**Comment by ejurgensen** [comment]
Good to hear from you, and yes, please do add this info to the wiki, it would be a good contribution that could hopefully help others.

**Comment by Porco-Rosso** [comment]
Thanks. 
Added to the wiki [here](https://github.com/ejurgensen/forked-daapd/wiki/Airplay-Android-Receiver-App)
