### ISSUE TITLE
m4p failed in Apple Music because it isn’t recognize as iTunes

### ISSUE THREAD

**Issue by 3frogx** [ejurgensen/forked-daapd#1152]
If you try to play an old m4p-file (digital-right-crippled) in Apple Music on MacOS its failed.
forked-daapd tries to transcode, obviously because it doesn’t recognize an iTunes as client. Transcoding failed.

As workaround I can add mp4a to the "no_decode"-option.

Is it possible that forked-daapd recognize Apple Music similar to iTunes?

forked-daapd 27.2 on debian buster
Apple Music on MacOS Catalina 10.15.7

**Comment by ejurgensen** [comment]
Sure, I would think so. Could you help determine the user-agent that Apple Music uses? If you set the log level to info in the config file, you can find via the log, look for a message that is like this:

[ INFO]     daap: Client 'XXX' logging in from [ip]

**Comment by 3frogx** [comment]
Shure, here is the line you are looking for:

daap: Client 'Music/1.0.6 (Macintosh; OS X 10.15.7) AppleWebKit/609.4.1 build/10 (dt:1)' logging in from ::ffff:xxx

**Comment by ejurgensen** [comment]
Ok, added now!
