### ISSUE TITLE
Spotify: Only add playlists rather than to the main library

### ISSUE THREAD

**Issue by john-a-harris** [ejurgensen/forked-daapd#1160]
Hi,

Could there be a way to only add my spotify playlists as playlists in forked-daapd, rather than adding the tracks to the main library? I'm finding I get duplicates in the library for albums which are in my local filesystem _and_ spotify.

Thanks again for this amazing software - I use it every single day!

**Comment by chme** [comment]
Hi @john-a-harris, 

thanks for the feedback! 
And yes, the duplicate albums from Spotify playlists are a bit annoying. And currently there is no perfect solution for it.

But there are two configuration options you can try that attempt to mitigate the problem. Maybe one of them suits your needs:

- https://github.com/ejurgensen/forked-daapd/blob/724cfa009366a101e804b3a5531bd93ed8fd6c76/forked-daapd.conf.in#L111-L115
  This configuration option works in Apple Remote and in the web interface. In the web interface, it will result in hiding albums that have less than 3 tracks.

- https://github.com/ejurgensen/forked-daapd/blob/724cfa009366a101e804b3a5531bd93ed8fd6c76/forked-daapd.conf.in#L351-L364

  These two configuration options will result in changing album artist and/or album name for Spotify songs during the scan. Tracks that only appear on Spotify playlists will then have "Various Artists" as album artist and/or the playlist name as album. Changing the metadata has obviously some drawbacks, so I personally do not use this.
