### ISSUE TITLE
Audio Stops with Error: Source is not Providing Sufficient Data

### ISSUE THREAD

**Issue by dustyberry1** [ejurgensen/forked-daapd#1162]
I'm using forked-daapd to listen to my turntable via Airplay. It works really well but every once in awhile the audio will pause for a few seconds, before resuming itself. When I look in forked-daapd.log I see an entry such as:

`player: Source is not providing sufficient data, temporarily suspending playback (deficit=264852/264600 bytes)`

My setup is
-Raspberry Pi 3B+ w turntable input via USB
-Named pipe that captures audio via arecord and is played by forked-daapd
-Forked-daapd out to airplay speaker
-Nothing else cpu/ram intensive running on the Pi

I have tried a few different things, including
-Increasing the arecord buffer
-Increasing the buffer of the pipe itself
-Using liquidsoap and cpiped to create the pipe
-Placing the pipe in memory via tmpfs
-Instead of a pipe Using liquidsoap and icecast2 to create a local radio station for forked-daapd, same error

Any suggestions? What exactly causes this error in forked-daapd? Thanks

**Comment by ejurgensen** [comment]
forked-daapd expects pipe input to have a samle rate of 44100, so will read precisely that many samples each second. If arecord is writing less than that the buffers will eventually run out, and you get the above error. I can't explain why that would happen, but there are different ways of measuring time, so probably arecord and forked-daapd are using different time sources, even if it is the same device.

Increasing the buffer sizes will affect how often this happens, but will not stop it from happening.

I think you might be able to fix the problem by telling arecord to write a bit more samples to the pipe, e.g. `arecord --rate=44110`. Finding the correct value can be tricky - too high a value and the buffers will overrun. If you can compile forked-daapd yourself you can [make it log how full the buffers are](https://github.com/ejurgensen/forked-daapd/blob/master/src/input.c#L760) and calcurate the rate, but that is somewhat complicated, so maybe trial and error is easier.

**Comment by dustyberry1** [comment]
Thanks your response was super helpful. I played with a bunch of sample rates for the pipe, as well as different pipe sizes and continued to get buffer overruns. Abandoned the pipe idea in favor of the icecast2 station at 48000khz and have had no issues so far. A little delay to encode pcm > oggflac but it does the job
