### ISSUE TITLE
start up with local output on pullsaudio

### ISSUE THREAD

**Issue by bendschs** [ejurgensen/forked-daapd#1164]
I  was able to configure the local output on pulseaudio just fine but have a problem with startup on systemd.
The local audio device (computer) becomes only available after i restart forked-daapd again after  a reboot. i figured this might have to do something with pulseaudio not yet being available at the time forked-daapd is started. plseaudio on raspberry ist started by the systemd/user (not systemd/system). therefor it does not seem that the tag 
"after=pulsaudio.service"  does not make forked-daapd wait for it if i put it in systemd/system/forked-daapd.service.  

after researching a bit it turned out that it is strongly recommended to run pulseaudio in usermode beacuse of securtiy reasons, so i would not want to change that behaviour.

is there any other option to delay the startup of forked-daapd other then just using the very sloppy method to put a "sleep=10" as a ExecPreStart in the unit?

cheers
bendsch

**Comment by p3ck** [comment]
Is your setup auto-logging into a user on boot up?  If so you could add it like this:

```console
$ cd ~/.config/autostart/
$ cat <<EOF > shairport-sync.desktop 
[Desktop Entry]
Name=shairport-sync
GenericName=Remote speaker
Comment=Sync your audio across computers
Exec=shairport-sync -o pa -a "Pi Speaker"
Terminal=false
Type=Application
Icon=shairport-sync
Categories=Network;
StartupNotify=false
X-GNOME-Autostart-Delay=10
EOF
```

**Comment by bendschs** [comment]
thank you, that seems to work after i gave ownership of /var/cache/forked-daapd/* and /var/log/forked-daapd.log to the user "pi".

thanks for the help!
bendsch

**Comment by bendschs** [comment]
i noteced there are a couple of disatvantages with this solution. im using mostly command line and don‘t really need the desktop so i am thinking about deactivating it. is there a simple way how to start forekd-daapd as a user with systemd after pulseaudio?

**Comment by ejurgensen** [comment]
You might be interested in this: https://lists.freedesktop.org/archives/pulseaudio-discuss/2016-August/026823.html
