### ISSUE TITLE
Kodi 18.6 airplay error: Missing/unexpected 'features' in TXT field

### ISSUE THREAD

**Issue by whatdoineed2do** [ejurgensen/forked-daapd#1167]
Seeing `airplay: AirPlay device 'Kodi (rpi4)' error: Missing/unexpected 'features' in TXT field` in master after `aplay2` work.

Could this be downgraded to an `INFO` log message or is kodi aplay broken?

**Comment by ejurgensen** [comment]
Can you share the output of `avahi-browse -r -k _airplay._tcp` for the Kodi?

I think some speakers announce _airplay._tcp but are only Airplay 1 that might be the case here. The current implementation doesn't really account for that, but everything should work nonetheless, since it probably also announces _raop._tcp.

**Comment by whatdoineed2do** [comment]
```
$ avahi-browse -r -k _airplay._tcp
+ enp2s0 IPv6 Kodi (rpi4)                                   _airplay._tcp        local
+ enp2s0 IPv4 Kodi (rpi4)                                   _airplay._tcp        local
= enp2s0 IPv4 Kodi (rpi4)                                   _airplay._tcp        local
   hostname = [rpi4.local]
   address = [192.168.0.152]
   port = [36667]
   txt = ["features=0x20F7" "srcvers=101.28" "model=Xbmc,1" "deviceid=DC:A6:xx:xx:xx:xx"]
= enp2s0 IPv6 Kodi (rpi4)                                   _airplay._tcp        local
   hostname = [rpi4.local]
   address = [2a00:23c7:ad18:4601:dea6:32ff:fe34:8167]
   port = [36667]
   txt = ["features=0x20F7" "srcvers=101.28" "model=Xbmc,1" "deviceid=DC:A6:xx:xx:xx:xx"]
```
How very odd .. `features` exists there - i restarted `forked-daapd` and i still see error msg
`airplay: AirPlay device 'Kodi (rpi4)' error: Missing/unexpected 'features' in TXT field`

The setup right now on the same wired subnet is:
* RPi4 hosting kodi
* forked-daapd/avahi-browse run on desktop

**Comment by ejurgensen** [comment]
Yes, I all the other receivers are sending e.g. features=0x445D0A00,0x1C340, so that's what the code expects. It's valid to do what Kodi does, but it also shows that Airplay 2 isn't supported, so I will add something so it is just ignored.

**Comment by ejurgensen** [comment]
Fixed like you suggested, I lowered the log level (+ changed the log message)
