### ISSUE TITLE
Forked-daapd and shairport-sync

### ISSUE THREAD

**Issue by orakelet** [ejurgensen/forked-daapd#1175]
I'm getting a lot of these in the log from forked-daapd:
[  LOG]   player: Output delay detected (behind=198, max=150), resetting all outputs
and then the sound from the shairport-sync device breaks.

Is this forked-daapd struggling with resources, or shairport-sync not receiving fast enough?
If forked-daapd, is there anything in the .conf I can change to fix it?

Forked-daapd is running on a ZeroW, shairport-sync is running on a Rpi 2b with a X300 hat (and it is handling output from a Mac without any breaks).

**Comment by ejurgensen** [comment]
What's the CPU load during playback? Maybe check on both sender and receiver device.

**Comment by orakelet** [comment]
Any favourable way to report CPU load? TOP shows forked-daapd using between 15%-30% of the CPU on the Zero (least when it breaks), shairport-sync is using 6% on the Rpi2

**Comment by ejurgensen** [comment]
I think top is fine.

This error happens when the player detects that preparing the packets (encryption + encoding), and sending them, is happening too slowly on the sender device. So I expected the CPU to be higher than what you see. Maybe there is another bottleneck, but finding that is difficult.

**Comment by orakelet** [comment]
And there would be no help in having a greater buffer or setting any of the timing-parameters higher?
I will see if there is anything unnecessary running on the Zero.
