### ISSUE TITLE
Catching named pipe from Kodi

### ISSUE THREAD

**Issue by beaune33** [ejurgensen/forked-daapd#1177]
Hi,

I tried forked-daapd and I am really impressed about the quality, how stable it works. There is only one point where I did not find a solution for.

My idea is to stream the audio output of Kodi with forked-daapd to my airplay devices. This could work, if it would be possible to redirect Kodis audio output to a named pipe, which then is used by forked-daapd. As I already learned forked-daapd is prepared to do things like this, but I am still missing a solution for the Kodi part.

Indeed I am pretty sure that this must be possible somehow. There is for example a snapcast solution for a special kodi distribution (LibreELEC), which probably does exactly what I need: redirecting audio. Unfortunately this addon is not available for Kodi on rasbian.

Therefore I thought I should ask this forum, if somebody already managed to redirect Kodi audio to a named pipe, or has an idea how to do this...any ideas?

Thanks in advance!

**Comment by ejurgensen** [comment]
I see no-one has been able to help you with this, so I will close the issue. Perhaps you will have better luck asking in a Kodi forum?

**Comment by fethom** [comment]
I use the same constellation on a raspberry pi4 (bullseye) with a virtual sound card on /etc/asound.conf .
 
1. load the loopback modul snd-aloop  on start up, do:`sudo nano  /etc/modules` and write in `snd-aloop` and save it
 
2. look for the alsa-loopback capture card, do: `arecord -l` ,in my case it is `card 0`

3. create a little script to create the fifo (pipe) where owntone is able to read it (in the /etc/owntone.conf you can choose the library or music folder), in my case it is the /media folder, do: `sudo nano /home/patch/Scripts/ramdisk.sh` and put that in it:
`!/bin/sh
sudo mkdir /media/ramdisk
sudo mount -t ramfs ramfs /media/ramdisk
sudo mkfifo /media/ramdisk/AUX
sudo chown patch /media/ramdisk/AUX
sudo chmod 777 /media/ramdisk/AUX`

that crates the script in the folder /home/patch/Scripts/ramdisk.sh
with this script you  create the fifo `AUX` in the ram of the computer but in the folder /media/ramdisk/ to get a better read/write performance. Make it executable, do: `chmod +x /home/patch/Scripts/ramdisk.sh`

4. create a new crontab to start this script on start, do  `sudo crontab-e` put the following in it:
`@reboot sh /home/patch/Scripts/ramdisk.sh`

5. write the virtual sound card, do: `sudo nano /etc/asound.conf`, put the following in it: 
`  pcm.AIR {
    type hw
    card 0
}

ctl.AIR {
    type hw
    card 0
}

pcm.myconvert {
    type plug
    slave {
        pcm „myrecord“
        format S16_LE
        rate 44100
        channels 2
    }
}

pcm.myrecord {
    type file
    format „raw“
    slave.pcm „AIR“
    file "| ffmpeg -f s16le -channels 2 -channel_layout stereo -thread_queue_size 8  -i pipe:0  -use_wallclock_as_timestamps 1 -force_key_frames 00:00:0.500 -channels 2 -acodec pcm_s16le -bufsize 44k -f s16le  -ar 44100  pipe:1 >/media/ramdisk/AUX“
}

pcm.!default{
   type asym
   playback.pcm „myconvert“
   capture.pcm „AIR“
}
`, and save it.
