### ISSUE TITLE
Directory =local can it be remote

### ISSUE THREAD

**Issue by GarethHards** [ejurgensen/forked-daapd#1184]
can i set the directory to be a pc on my lan,eth0,wlan0,wlan1 an specify the ip user, password or have a automatic login to enable daapd to get the info to display from there.

**Comment by GarethHards** [comment]
i just added music to my directory home folder music folder thats where it is, and the webpage doesnt display it as added

**Comment by ejurgensen** [comment]
Sorry, this issue is too unclear
