### ISSUE TITLE
Ipod Touch access

### ISSUE THREAD

**Issue by StephenAtty** [ejurgensen/forked-daapd#1186]
I've got a 7th gen Ipod Touch running apple music. It only seems to support Home Sharing (where you have to be signed in to apple and on the same network). So is it possible to get this ipod to connect to forked-daapd?

I've got the server up and running and Itunes can connect to it fine.

forked-daapd is version 27.2

**Comment by ejurgensen** [comment]
If it only supports Home Sharing then it wouldn't be possible. I don't know if it would be possible for forked-daapd to support Home Sharing, last I checked there were no open source implementations of it.

**Comment by StephenAtty** [comment]
OK thanks for letting me know.
