### ISSUE TITLE
Questions: AirPlay2 compatibility? synchronized multi room streaming?

### ISSUE THREAD

**Issue by maichai** [ejurgensen/forked-daapd#1188]
I have researched how I could create a multi room sound system from available smart speakers, I do not want to build something on my own based on RPi+Hifiberry+Speakers. So snapcast is out of the picture and forked-daapd seems to be the best solution so far, as it supports Airplay and Chromecast. On the market are many active speaker products available that offer Airplay and/or Chromecast compatibility.

One feature is important to me for a multi room sound system: the speakers should be able to
(a) simultaneously play different play lists in each room, and
(b) simultaneously play the same stream synchronously in all rooms

Does that work with forked-daapd combined, lets say with Apple/Ikea Simfonisk smart speakers or Apple HomePod speakers?

For (b) forked-daapd would need to be able to stream AirPlay2 (not only AirPlay1), right? Is it able to do that?

Does the synchronized multi room streaming work well in practice?
If not, is AirPlay2 on the roadmap and for when roughly?

I might not be the only person interested in the answers to these questions, it may be a good idea to make a statement about multi room capabilitoes in the documentation.

**Comment by ejurgensen** [comment]
> (a) simultaneously play different play lists in each room, and

To do this you would need to have multiple instances of forked-daapd running, which can be a bit tricky.

> (b) simultaneously play the same stream synchronously in all rooms

Yes, that should work for Airplay 1 + 2 and local audio. Real Chromecast sync isn't supported, there is only delayed playback to try and match Airplay.

> Does that work with forked-daapd combined, lets say with Apple/Ikea Simfonisk smart speakers or Apple HomePod speakers?

Well it should. Obviously can't give guarantees, and I don't have those speakers myself. Try searching the issues here to see what people are saying.

> For (b) forked-daapd would need to be able to stream AirPlay2 (not only AirPlay1), right? Is it able to do that?

Yes, forked-daapd supports Airplay 2, but it is a relatively new addition, so again, no guarantees.

> I might not be the only person interested in the answers to these questions, it may be a good idea to make a statement about multi room capabilitoes in the documentation.

Yes, I think you are right. Any suggestions on where people would expect to find this info?

**Comment by maichai** [comment]
> Yes, I think you are right. Any suggestions on where people would expect to find this info?

I think it would be best to have a small chapter on the possible use cases and their architectures and maybe also good to say what use cases do not work (yet). That chapter could be extended with time.

Architecture buiding blocks:

streaming sources: forked-daapd
streaming receiver: airplay1 or airplay2 or chromecast capable devices with speakers, e.g.  AVRs, HomePods, devices running KODI, .. (what you are calling clients), macOS Music app,...
streaming controllers: iOS Remote app, macOS Music app, ...

Example:

(a) streaming simultaneously and synchonously from sources to receivers, requires: source (forked-daapd), one or more receivers (see table with receivers...), for synchronous playback the receivers must all support AirPlay2 (see table of receivers...) and the version of forked-daapd must support AirPlay2 (version xyz or higher)

(b) streaming different streams simultaneously to groups of receivers: currently only 1 group of receivers is support by a given instance of forked-daapd, i.e. you cannot have different streams playing simultaneously on different speakers / in different rooms.

**Comment by maichai** [comment]
Regarding use case (b): what still could work is to send a stream to a group of speakers from forked daapd and to use the speakers outside of that group directly with your smartphone. Correct? So someone in a room who wants different music can stream that from their phone directly to the speaker in that room, while the group of other speakers plays the forked-daapd-stream? If that is so, it could also be mentioned in use case (b).

**Comment by ejurgensen** [comment]
Yes, that would work

**Comment by maichai** [comment]
Awesome. I posted a feature request for the (b) use case.
