### ISSUE TITLE
Feature request: make protocol timing parameters configurable

### ISSUE THREAD

**Issue by maichai** [ejurgensen/forked-daapd#1190]
The apple mDNS-based protocols usually only work within a flat network. If you have a routed network and components reside in different subnets/vlans, then you need an mDNS reflector such as AVAHI.

In general this works only partially, I am experiencing the same timeout problems with the Home Assistant to Apple Homekit bridge visibility in the Apple Home app, the forked-daap library visibility in macOS app Music, and the Airplay capable receivers visibility in forked-daapd.

The components are seen for some time, then a timeout of the visibility occurs, until they become visible some time later when they are again announced using mDNS. It seems that the timeout period is shorter than the mDNS interval (and it should be vice versa!). I have no clue why it works in the lat network architecture... maybe some announcements are just not reflected by AVAHI (please note I have turned off IPv6, so that should not be the problem).

Not sure if the timout period can be provided in the mDNS announcements, if so, it would help to provide a longer period in the announcements for forked-daapd. If not possible, please at least make the mDNS announcement interval configurable in the forked-daapd config so that forked-daapd gets announced before the macOS Music app forgets it. Also the timeout for the AirPlay receivers/speakers should be configurable to be able to make it longer, to ensure that an mDNS announcement is seen before the speaker is forgotten.

Any other keepalive mechanism may also work, but in the current version (27.2) both are popping in and out: the forked-daapd library, and the AirPlay receivers.

Any other hints on how to fix this by means of network configuration are welcome. The only thing I cannot do is going to a flat network architecture. The forked-daapd server will in my network always run in a different subnet than the stream receivers. I am able to control the multicast routing in my network and also got the nasty SSDP protocol routed to make UPnP streaming work. Maybe I am overlooking something here for AirPlay in addition to mDNS announcements?

**Comment by ejurgensen** [comment]
forked-daapd uses Avahi for mdns, so all it does is register the services it offers (daap etc.), and register the services it listens for (Airplay etc). So the actual mdns stuff is left to Avahi. There is no announcement interval that is set, it is also left to Avahi.

I don't know much about mdns, so I can't say why you are seeing the announcements disappear, but I doubt that it is something that should be fixed in forked-daapd. I think it is more likely an Avahi or router configuration issue.
