### ISSUE TITLE
scan: Unable to open smart playlist file

### ISSUE THREAD

**Issue by palayo** [ejurgensen/forked-daapd#1191]
Unable to open smart playlist file.  whtat's wrong?

> /va/log/forked-daapd.log
> scan: Unable to open smart playlist file /mnt/nas/music/__playlist/test.smartpl
> scan: Error parsing smart playlist '/mnt/nas/music/__playlist/test.smartpl'

$ ls -l /mnt/nas/music/__playlist/test.smartpl
> -rwxrwxrwx 1 pi pi 48  2月 10 07:31 /mnt/nas/music/__playlist/test.smartpl

$ cat  /mnt/nas/music/__playlist/test.smartpl
> "Test Album" {
>      album includes "Test"
>}

**Comment by whatdoineed2do** [comment]
File format is fine.  Does the user running the server have access to all directories to `test.smartpl`?  Running `namei -l  /mnt/nas/music/__playlist/test.smartpl` should help you to confirm.

**Comment by palayo** [comment]
I cannot find out what is wrong...
drwxr-xr-x root root /
drwxr-xr-x root root mnt
drwxr-xr-x root root nas
drwxrwxrwx pi   pi   music
drwxrwxrwx pi   pi   __playlist
-rwxrwxrwx pi   pi   test.smartpl

**Comment by whatdoineed2do** [comment]
The next thing to check is the ACLs which unfortuatnely `namei` does do for you - assuming you running `forked-daapd` as `pi` or as `daapd`?

On my old synology NAS there were strange things with ACLs that would prevent access access like this and i'd have to set this on the NAS's webui (there's no 'setfacl' / 'getfacl' on the system and i was exporting the fs over NFSv3).
