### ISSUE TITLE
Wrong cover association (Apple Music / ex iTunes)

### ISSUE THREAD

**Issue by stefan1983** [ejurgensen/forked-daapd#1195]
I've got problems with Apple Music showing the correct covers / artworks.
In Apple Music I can connect to the forked-daapd service, it plays fine everything.
Only the covers are wrongly associated:

![image](https://user-images.githubusercontent.com/8542806/108701111-d2653100-7507-11eb-9b9c-316fe933f6ff.png)

The files are mainly M4A and MP3 and all of them have a folder.jpg next to the files as well as ID3 tagged covers.

When connecting and playing via Apple Remote (iOS) and Forked-Daapd Web-IFC, everything looks fine tough:
<img width="576" alt="image" src="https://user-images.githubusercontent.com/8542806/108701415-37b92200-7508-11eb-892a-5097ad91221b.png">

- version of forked-daapd: 27.2 (Docker)
- platform: latest macOS Catalina

**Comment by ejurgensen** [comment]
This looks to be the same issue as #1193, so I will close this as duplicate. As you can see, it seems that Apple Music is not making any artwork requests to forked-daapd, so it is unclear how it decides what artwork to use.
