### ISSUE TITLE
Disable devices?

### ISSUE THREAD

**Issue by biiiink** [ejurgensen/forked-daapd#1200]
Is it possible to disable specific devices?

I have a Homepod, AppleTV, Yamaha Receiver and Computer listed as devices.  I really only need the Homepod.

**Comment by ejurgensen** [comment]
Yes, you can do that in the config file. To disable "Computer" set audio -> type = disabled, and for the Airplay devices you can use [the exclude option](https://github.com/ejurgensen/forked-daapd/blob/master/forked-daapd.conf.in#L300).

**Comment by biiiink** [comment]
Excellent.  This helped.  Just one more question.  How do i list the devices i want to exclude.

Thanks

**Comment by ejurgensen** [comment]
> How do i list the devices i want to exclude

I don't understand what you mean by that?

As you can see in the config file you should add instances of:
```
airplay "name of speaker" {
  exclude = true
}
```

**Comment by biiiink** [comment]
reading is hard in the morning :(. Got it working.  Thanks
