### ISSUE TITLE
Soundbridge "large" ALAC files fail to play

### ISSUE THREAD

**Issue by frankusb** [ejurgensen/forked-daapd#1210]
version 27.2 on Debian 10.8 with no_decode = { "alac" }

Playing an ALAC file of size 35.9MB takes a bit to start as it seems to start and then restart several times.

[small file.txt](https://github.com/ejurgensen/forked-daapd/files/6149534/small.file.txt)

Playing an ALAC file of size 408.9 MB results in failure.

[large file.txt](https://github.com/ejurgensen/forked-daapd/files/6149539/large.file.txt)

**Comment by frankusb** [comment]
Updated to 27.4 and the larger ALAC still fails to play.

**Comment by ejurgensen** [comment]
Took a quick look, and I'm not sure what is causing this. With the small file it looks like the Soundbridge is retrying a bunch of times, while with the large file it gives up right away. So I guess it is not happy with the responses it is getting, but I don't know exactly what the issue is.

**Comment by frankusb** [comment]
Let me know if I can pull more information for you, instrument the code, network captures, whatever helps.

**Comment by ejurgensen** [comment]
Would you be up to trying to fix the issue yourself, of course with some pointers from me? It would be difficult for me.

**Comment by frankusb** [comment]
That's why I offered to send you a Soundbridge (the offer still stands, I have spare 3 M1001s, 1 M1000, 1 M500).

And yes I would be up to trying to fix it with pointers.

**Comment by ejurgensen** [comment]
Sounds good. I'll pass again on the generous offer, I think it would be better if the maintenance of this was by someone who uses it. So I hope to get you involved :-) Here is how I would suggest going about it:

1. Install Wireshark, use it to watch the streaming and compare succesful streaming with unsuccesful
2. Make a script that stops forked-daapd, builds, runs and starts playback (you will need to do that a lot)
3. Open httpd.c, and find httpd_stream_file(). This is where the streaming is kicked off, so the bug could be here (e.g. incorrect response headers, incorrect parsing of input headers or something like that)
4. The actual streaming is done via the event "st->ev", which calls stream_chunk_raw_cb(), which sends a chunk (size STREAM_CHUNK_SIZE) of the file
5. As you can see, the reading of the file in stream_chunk_raw_cb() is with read(). I think that should be plenty fast, even for large files, and I don't see any potentially slow seeking during playback.

I can't say precisely what you should test/try, other than checking headers and maybe also trying with different values of STREAM_CHUNK_SIZE. And well, just experiment.

Also, perhaps you could try if Roku will help? Long shot, maybe, but who knows, perhaps a company like Roku will actually be willing to look into it.

**Comment by frankusb** [comment]
Good news, no code changes needed. I tried Twonky server and it behaved the same. I then downloaded a sample ALAC and found it's behavior better, a single TCP reset. Convinced it was the manner in which the ALAC was encoded I dug up the options that have worked for me in my limited testing.

`ffmpeg -i file.flac -acodec alac -c:v copy -movflags +faststart file.m4a`

This results in an additional output from ffmpeg.

`Starting second pass: moving the moov atom to the beginning of the file`

**Comment by frankusb** [comment]
For reference, I pursued ALAC over FLAC (or WAV from the Soundbridge perspective) because of wireless audio buffering. I mostly solved the audio buffering by setting up a dedicated access point only for the 802.11b Soundbridge devices on my network. But I was still getting audio disruptions which I tracked down to "Hangs" as logged by the Soundbridge (telnet to port 4444 and type log).

`1c294:rsp:wav:0:0:0:0:22afc:0:0:C:32b88:assert:0:Hang detected: stack=32b88 32cde 4be9c 199360 1bfb32 trace=32b84>171dd0 32b0a>32b32 32aec>32b04 34d4c>32ae6 17b444>34d3c 36fc0>17b43c 451d4>36fba 1be702>451cc 1be7cc>1be6ea 1be67e>1be7bc 1bf20e>1be65e 1bf1fc>1bf202 1bebf6>1bf1c2 1bf1be>1bebec 1bc8a4>1bf1be 1bf1ba>1bc8a4`

I never noticed this when streaming mp3 so I assumed it was bit rate related. Converting to ALAC should theoretically half the bit rate. Alas, it's worse with ALAC because not only do you get "Hangs", you get "Breaking scan locks" which result in audible white noise until the next track.

`2a218:rsp:alac:0:0:0:0:2339b:0:5d0:C:32b88:assert:0:Hang detected: stack=32b88 32cde 4be9c 199360 1bfb32 trace=32b84>171dd0 32b0a>32b32 32aec>32b04 34d4c>32ae6 17b444>34d3c 36fc0>17b43c 451d4>36fba 1be702>451cc 1be7cc>1be6ea 1be67e>1be7bc 1bf20e>1be65e 1bf1fc>1bf202 1bebf6>1bf1c2 1bf1be>1bebec 1bc8a4>1bf1be 1bf1ba>1bc8a4 
2a247:rsp:alac:0:0:0:0:2339b:0:5ff:C:300f4:assert:0:Breaking scan lock: stack=300f4 1862c6 1b58f6 126eda 126f0a 1b62de 184f20 4be9c 199360 1bfb32 trace=300f0>171dd0 2fbd0>300e6 2fbcc>2fbd0 3011a>2fbc4 30116>3011a 36c8e>300fa 1c73b0>36c88 1c730e>1c7330 1c7304>1c730a 1c72a4>1c72dc 36c84>1c7284 36c6c>36c78 36894>36c34 36c30>36886 36c74>36c22 300f6>36c6e`

Never one to give up easily, I decided to try the SD card slot that's present on the Soundbridge Radio, avoiding the wireless altogether. It's limited to 2GB cards I think (16GB did not work). But I found that ALAC files do not appear to be supported at all on the SD card slot.

So, AAC files it is on the SD card.

**Comment by ejurgensen** [comment]
Thanks for the follow-up
