### ISSUE TITLE
forked-daapd/forked-daapd.service.in still with only 2 restarts see issue #968 promised

### ISSUE THREAD

**Issue by Ulrichgau** [ejurgensen/forked-daapd#1211]
Hello, 
after every update of forked-daapd I have to manually adjust the StartLimitBurst in forked-daapd.service from 2 to 5. Otherwise in more than 50% of the cases forked-daapd will not start (See issue #1095). Is there a way to change it in the setup files to 5 as promised in #968?

**Comment by ejurgensen** [comment]
Yes, I forgot to update the service file that my RPi build uses. I have done that now, so the next Buster RPi build should have the value set to 5.
