### ISSUE TITLE
Library scanning but nothing showing in iTunes (Windows)

### ISSUE THREAD

**Issue by brimur** [ejurgensen/forked-daapd#124]
I created a VM running Ubuntu 14.10 Utopic and installed forked-daapd v21. I mounted my Music share via NFS which is on my NAS and I pointed forked-daapd at it. When I start forked-daapd with the -f param I can see it is scanning the Music folder with no issues.

The last line I see is...  scan: Bulk library scan completed in 641 sec 

The problem is when I go to iTunes on my Windows 7 machine I can see the server listed but when I select it I get the message "<ServerName> has no music". Is there a step I am missing? Nothing is showing in the verbose output after the line above. My NAS has an iTunes server running the older mt-daapd and I can connect from my Windows 7 machine and see the library so the issue seems to be with the new setup. Thanks

**Comment by ejurgensen** [comment]
See this: https://github.com/ejurgensen/forked-daapd/issues/100
