### ISSUE TITLE
Beats Music Support

### ISSUE THREAD

**Issue by snizzleorg** [ejurgensen/forked-daapd#125]
It appears that apples Beats Music Streaming service has got an API that allows streaming. So maybe it would be a good idea to enable streaming from beats in addition to spotify.

What do you think?

https://developer.beatsmusic.com/docs/read/libraries/Third_Party_Libraries

**Comment by ejurgensen** [comment]
I think it would be great. Don't know if it is anything I will be able to do in the near future, though.

**Comment by rollinc** [comment]
That would be awesome!

**Comment by adamdmoss** [comment]
Could probably be closed - the Beats service shut down a couple of years ago.
