### ISSUE TITLE
HTTP Live Streaming - almost works

### ISSUE THREAD

**Issue by pjrh** [ejurgensen/forked-daapd#134]
I really love forked-daapd, and use it all the time on a raspberry pi.

I was trying today to listen to the HTTP Live Streaming (HLS) streams from the BBC, because they've said they're going to close down the normal mp3 ones soon.  forked-daapd will play them, but there's a gap of about 3 seconds every 10 seconds or so, which isn't ideal.

I just put this url in a .m3u file: http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_low/llnw/bbc_radio_fourfm.m3u8

It doesn't look like it is using too much CPU, and the stream does run with avplay.  There doesn't seem to be any obvious information about it in the log file.

I just wondered if it was possible to get HLS streams to work with forked-daapd without playing intermittently?

No worries if not.  Thanks so much.

**Comment by ejurgensen** [comment]
No, not ideal at all! I tried your link on my RPi and it worked ok, but my version was probably not the same as yours. What exact version of forked-daapd and RPi are you using? Do you AirPlay or use local audio?

If you haven't already, you could also try setting the log level to debug and see if that turns up some suspicious pattern.

**Comment by pjrh** [comment]
The only thing unusual in the log is the message "raop: Got retransmit request, seq_start 15438 len 18" (the numbers change).  But it doesn't turn up every time the audio breaks.  I'm using shairport-sync as my audio - is that the problem?

**Comment by pjrh** [comment]
And if it is, then why would it only occur with HLS files? (it isn't just this one)

**Comment by pjrh** [comment]
The version I'm using is from commit 76fc9d89367fd87990f0aa6de619b9dc885d5231 on Saturday.

**Comment by ejurgensen** [comment]
Playback of HLS requires more cpu (on mine 30%, while mp3 is more like 14%), so maybe there are occasional underruns? I don't think shairport-sync is a problem.

You are using a newer version than I am, so I will try with an upgraded version a bit later.

**Comment by ejurgensen** [comment]
I tried playing your link a few times with an upgraded version on the RPi, and the error did not show. So I can't say what is happening or how to fix it.

**Comment by pjrh** [comment]
OK.  For what it's worth, I tried installing forked-daapd on a fresh install of Raspian on a RPi 2, so I don't think it's the CPU issue.  I'd guess there is a short gap between each HTTP chunk.

I am going to assume it is an issue I have locally, and close the issue.
