### ISSUE TITLE
Disable advertising the nonexistent web interface.

### ISSUE THREAD

**Issue by mrengles** [ejurgensen/forked-daapd#136]
How do I disable forked-daapd from advertising the "nonexistent web interface" thats automatically created because of dbus and avahi?

On all the Macs connected to my local subnet... Safari will display forked-daapd "Library Name" under the Bonjour menu.

I can supply the txt records and service info if needed, but its a basic _http._tcp. record with the DAAP service text records.

This should probably be removed... or code added for the option to disable. I guess it really just depends on which direction your going with this fork and if you might add a webif down the road.

**Comment by ejurgensen** [comment]
If you are building it yourself it is fairly simple to remove by just disabling line 271-273 in main.c. I don't know why it is there, actually, so I might disable it myself. I don't plan to add a web interface.

**Comment by mrengles** [comment]
I'm not compiling myself. Using your Debian packages for Raspberry Pi. Thanks for looking into this.

**Comment by ejurgensen** [comment]
It's disabled now

**Comment by mrengles** [comment]
Thanks I was just about to send over a pull request. But noticed it was already fixed. TY
