### ISSUE TITLE
UFW Forked-daapd Application Rule

### ISSUE THREAD

**Issue by mrengles** [ejurgensen/forked-daapd#141]
Here's a simple little ufw applications.d rule that can be created to help setup your uncomplicated firewall.

$sudo pico /etc/ufw/applications.d/forked-daapd

Add the follow text.

[DAAP]
title=Forked-daapd media server
description=Forked-daapd is iTunes media server software, which can be controlled by Apple Remote on iPod/iPad/iPhone or by an app like Retune or TunesRemote+ on Android. You can also stream music to iTunes itself. It can output audio locally, Airport Express, Apple TV or to most AirPlay devices.
ports=3689

Can this easily be added to this software somehow?

Thanks!

**Comment by ejurgensen** [comment]
Thank you. The ufw is an Ubuntu firewall, so the proper place to add the rule is in the Ubuntu packaging, which is not something I can do. At best I can add some info to the INSTALL file.

However, opening the firewall for forked-daapd is a bit more complicated than opening just port 3689, as you can see here: https://github.com/ejurgensen/forked-daapd/issues/96

**Comment by mrengles** [comment]
Sorry don't know how I missed that. Will you be tagging a new release soon, and will it be available via your Debian package repository for the Raspberry Pi?

**Comment by ejurgensen** [comment]
Yes, probably during the weekend.

**Comment by mrengles** [comment]
Wow great news!

**Comment by IngwiePhoenix** [comment]
I believe that I am, but not certainly, facing issues with UFW.

Version:
```
root@MacMini:/srv# forked-daapd --version
Forked Media Server: Version 25.0
Copyright (C) 2009-2015 Julien BLACHE <jb@jblache.org>
Based on mt-daapd, Copyright (C) 2003-2007 Ron Pedde <ron@pedde.com>
Released under the GNU General Public License version 2 or later
```

Installation was done via repository:
```
root@MacMini:/srv# apt-cache show forked-daapd
Package: forked-daapd
Architecture: amd64
Version: 25.0-2build4
Priority: optional
Section: universe/sound
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Multimedia Maintainers <pkg-multimedia-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 883
Depends: libantlr3c-3.2-0 | libantlr3c-antlrdbg-3.2-0, libasound2 (>= 1.0.18), libavahi-client3 (>= 0.6.16), libavahi-common3 (>= 0.6.16), libavcodec57 (>= 7:3.4.2) | libavcodec-extra57 (>= 7:3.4.2), libavfilter6 (>= 7:3.4.2) | libavfilter-extra6 (>= 7:3.4.2), libavformat57 (>= 7:3.4.2), libavutil55 (>= 7:3.4.2), libc6 (>= 2.14), libconfuse2 (>= 3.2.1~), libcurl3-gnutls (>= 7.16.2), libevent-2.1-6 (>= 2.1.8-stable), libevent-pthreads-2.1-6 (>= 2.1.8-stable), libgcrypt20 (>= 1.8.0), libgnutls30 (>= 3.5.6), libgpg-error0 (>= 1.14), libjson-c3 (>= 0.10), libmxml1, libplist3 (>= 1.11), libprotobuf-c1 (>= 1.0.1), libpulse0 (>= 5.0), libsodium23 (>= 0.6.1), libsqlite3-0 (>= 3.6.12), libswscale4 (>= 7:3.4.2), libunistring2 (>= 0.9.7), zlib1g (>= 1:1.1.4), avahi-daemon (>= 0.6.31-3~), adduser, lsb-base (>= 3.0-6), psmisc
Recommends: libavcodec-extra
Filename: pool/universe/f/forked-daapd/forked-daapd_25.0-2build4_amd64.deb
Size: 265376
MD5sum: f604d5701c90d10fec72dcce3a1546cf
SHA1: 5965475bbb160e1eafc981aee2ecf51b61ec9974
SHA256: de6c308c2b52281b85d58303a6df8f266958ea908aba1a0fba45d870fadb3e7d
Homepage: http://github.com/ejurgensen/forked-daapd
Description-en: DAAP/DACP (iTunes) server, support for AirPlay and Roku devices
 forked-daapd is an iTunes-compatible media server, originally intended
 as a rewrite of Firefly Media Server (also known as mt-daapd).
 .
 It supports a wide range of audio formats, can stream video to iTunes,
 XBMC and other compatible clients, has support for Apple's Remote
 iPhone/iPod application and can stream music to AirPlay devices like
 the AirPort Express.
 .
 It also features RSP support for Roku's SoundBridge devices and MPD support for
 Music Player Daemon clients.
 .
 Built-in, on-the-fly decoding support enables serving popular free music
 formats like FLAC, Ogg Vorbis or Musepack to those clients that do not
 otherwise support them.
Description-md5: f1d0e8dc6bfea957f2c87b8fb11d2694
```

I can see the library within iTunes, but I can not seem to load it's contents - after a while, iTunes will just throw me back to my own music without any notice - there isnt one in the logs either, which is why I am suspecting my firewall to be mean here.

I see that some work towards UFW had been done, but I can not really tell if they are in my ufw or not...as I am actually new to using ufw to managing things :)

Would be nice to have a sport pointer towards the right direction... Thanks!


Kind regards,
Ingwie
