### ISSUE TITLE
ipv6 does not work, even if it is enabled

### ISSUE THREAD

**Issue by rbalint** [ejurgensen/forked-daapd#147]
From https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=756084 :

Even if the ipv6 setting is enabled, forked-daapd will not listen on the
specified port using IPv6, but only using IPv4.

I've confirmed this using both netstat and by manually trying to connect with telnet.

**Comment by ejurgensen** [comment]
Thanks to both of you for reporting the problem, and also thanks for the fix @jelmer. I have included a modified version of that fix.
