### ISSUE TITLE
antlr version

### ISSUE THREAD

**Issue by kartikkannan** [ejurgensen/forked-daapd#151]
Hi,
The latest git pull of forked-daapd doesn't compile for me any more. Any suggestions :) ?
Am using /usr/share/java/antlr-3.4-complete.jar

I compiled two months ago on the same computer successfully though.

make[2]: Entering directory '/var/lib/forked-daapd-ejurgensen/src'
antlr3 -Xconversiontimeout 30000  DAAP2SQL.g
ANTLR Parser Generator   Version 2.7.7 (2006-11-01)   1989-2005
warning: grammar file must be last; ignoring other arguments...
error: file 30000 not found
antlr3 -Xconversiontimeout 30000  SMARTPL.g
ANTLR Parser Generator   Version 2.7.7 (2006-11-01)   1989-2005
warning: grammar file must be last; ignoring other arguments...
error: file 30000 not found
antlr3 -Xconversiontimeout 30000  SMARTPL2SQL.g
ANTLR Parser Generator   Version 2.7.7 (2006-11-01)   1989-2005
warning: grammar file must be last; ignoring other arguments...
error: file 30000 not found
make  all-am

**Comment by ejurgensen** [comment]
It seems the antlr3 wrapper is not pointing to the right version of antlr. As you can see it is trying to use ANTLR 2.7.7 back from 2006. antlr3 is probably in /usr/bin, so have a look at that. You can see in the INSTALL file what it should contain. Or you can look at what scripts/antlr34_install.sh does.

**Comment by kartikkannan** [comment]
Thanks a lot! worked! opensuse 13.2 stock had the wrong antlr version. somehow it worked on the git pull 2-3 months ago.
