### ISSUE TITLE
Start forked-daapd without avahi?

### ISSUE THREAD

**Issue by darkside40** [ejurgensen/forked-daapd#154]
Hi there,
i try to create a forked-daapd docker for my unraid server.

Unfortunately it seems that docker and avahi does not play nicely together with docker. 
So my plan is to use the avahi already installed on my unRaid (with a correct service file) and to only have forked-daapd running inside docker.
The problem is that forked-daapd does not start this way.

forked-daapd -f end up with "forked-daapd: client.c:791: avahi_client_errno: Assertion `client' failed."

Is there any way to start forked-daapd without avahi installed?

**Comment by ejurgensen** [comment]
Sorry, I don't think I can help you. I don't know much about docker, and I don't understand how it would be meaningful to run forked-daapd without Avahi.

**Comment by jkiddo** [comment]
Forked-daapd does not make sense without avahi - avahi makes the dns sd possible, which is how Apple designed the zero conf part.

**Comment by couteau** [comment]
I think what is being proposed as that the host advertising the service
through avahi and the host actually providing the service be different --
not that there be no dns sd at all. I don't know the zeroconf protocol
particularly well, but in theory, that sounds like it should work.  It
would require a machine running avahi to advertise the forked-daapd daap
service (and other dmap services forked-daapd offers), which can be
accomplished through service files.  Forked-daapd would then have to have
an option that would prevent it from registering its services with avahi on
the local machine.  Adding such an option would be fairly trivial.  If you
would also need to prevent it from linking against the avahi libs, it would
require changes to the autoconf/automake files, which would be a bit more
complicated.

**Comment by ejurgensen** [comment]
forked-daapd also uses Avahi to listen for announcements, which is needed for supporting AirPlay and Remote. Without that you would only have a straight DAAP server, but maybe that is all you are looking for? I guess you could achieve that, but you would need to go into the code and manually disable/remove the parts that integrate with Avahi.
