### ISSUE TITLE
Unknown error 1052488119

### ISSUE THREAD

**Issue by kartikkannan** [ejurgensen/forked-daapd#156]
Hi,

After successfully compiling and running forked-daapd on Suse Tumbleweed x64, and no errors during make or running, I was able to connect the iOS Remote app but only 2 folders were listing.

After checking, these two folders contained .flac files and none of the mp3 files had listed. Then the log file has this for all mp3 files/folders:

[ WARN]     scan: Cannot open media file '/media/music/AC-DC/1986 - Who Made Who/07.Shake Your Foundations.mp3': Unknown error 1052488119

My shared folder permissions are 775 and file permissions are 664

**Comment by ejurgensen** [comment]
This is an error from ffmpeg (or libav). Can you run: "ffprobe /media/music/AC-DC/1986 - Who Made Who/07.Shake Your Foundations.mp3" and see if it works? If you use libav then use avprobe instead of ffprobe.

If you set log level to debug you might also see some error messages from ffmpeg in the log?

**Comment by kartikkannan** [comment]
Strange... ffprobe give the following output: All my mp3's can't have got corrupted...

ffprobe version 2.6.2 Copyright (c) 2007-2015 the FFmpeg developers
  built with gcc 4.8 (SUSE Linux)
  configuration: --prefix=/usr --libdir=/usr/lib64 --shlibdir=/usr/lib64 --incdir=/usr/include/ffmpeg --extra-cflags='-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g' --optflags='-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g' --enable-pic --disable-stripping --enable-shared --disable-static --enable-runtime-cpudetect --enable-gpl --disable-openssl --enable-frei0r --enable-gnutls --enable-libcdio --enable-libdc1394 --enable-libfreetype --enable-libgsm --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libvpx --enable-pic --enable-pthreads --enable-vaapi --enable-vdpau --enable-x11grab --disable-encoders --disable-decoders --disable-muxers --disable-demuxers --enable-encoder='flac,gif,jpegls,libopenjpeg,libtheora,libvorbis,libvpx,png' --enable-decoder='flac,gif,jpegls,ljpeg,libopenjpeg,libtheora,libvpx,png,vorbis,vp3,vp5,vp6,vp6a,vp6f,vp8,vp9,webp' --enable-muxer='flac,gif,image2,image2pipe,matroska,matroska_audio,null,webm' --enable-demuxer='flac,gif,image2,image2pipe,matroska'
  libavutil      54. 20.100 / 54. 20.100
  libavcodec     56. 26.100 / 56. 26.100
  libavformat    56. 25.101 / 56. 25.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 11.102 /  5. 11.102
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
/home/backup.misc/music/AC-DC/1986 - Who Made Who/03.D.T.mp3: Invalid data found when processing input

**Comment by ejurgensen** [comment]
Try reinstalling ffmpeg (including the libav* libraries)

**Comment by kartikkannan** [comment]
I tried both versions of ffmpeg and libav libraries included in suse tumbleweed but both versions give the same error as above when using ffprobe.

I got the latest version of ffmpeg from github and compiled successfully. How can I compile forked-daapd against these libav libraries? Should the LIBAV_LIBS environment var point to the ffmpeg source folder?

**Comment by ejurgensen** [comment]
Well, after building ffmpeg you should install it, which should install the header files too. Then you can build forked-daapd normally. There will be no need for forked-daapd to know about the ffmpeg source folder.

**Comment by kartikkannan** [comment]
Hi thanks for the suggestions!
FFmpeg built successfully with default ./configure --prefix=/usr/local

forked-daapd faile make: 
make[3]: Entering directory '/var/lib/forked-daapd-ejurgensen/src'
gcc -DHAVE_CONFIG_H -I. -I..  -D_GNU_SOURCE -DDATADIR="\"/usr/share/forked-daapd\"" -DCONFDIR="\"/etc\"" -DSTATEDIR="\"/var\"" -DPKGLIBDIR="\"/usr/lib64/forked-daapd\"" -DALSA -D_REENTRANT   -I/usr/local/include -D_THREAD_SAFE -D_REENTRANT -I/usr/include/alsa  -g -O2 -Wall -D_LARGEFILE_SOURCE -MT forked_daapd-artwork.o -MD -MP -MF .deps/forked_daapd-artwork.Tpo -c -o forked_daapd-artwork.o `test -f 'artwork.c' || echo './'`artwork.c
artwork.c: In function âartwork_rescaleâ:
artwork.c:286:3: warning: âavcodec_find_best_pix_fmt2â is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:4953) [-Wdeprecated-declarations]
   dst->pix_fmt = avcodec_find_best_pix_fmt2((enum AVPixelFormat *)img_encoder->pix_fmts, src->pix_fmt, 1, NULL);
   ^
artwork.c:286:51: error: incompatible type for argument 1 of âavcodec_find_best_pix_fmt2â
   dst->pix_fmt = avcodec_find_best_pix_fmt2((enum AVPixelFormat *)img_encoder->pix_fmts, src->pix_fmt, 1, NULL);
                                                   ^
In file included from artwork.c:32:0:
/usr/local/include/libavcodec/avcodec.h:4953:20: note: expected âenum AVPixelFormatâ but argument is of type âenum AVPixelFormat *â
 enum AVPixelFormat avcodec_find_best_pix_fmt2(enum AVPixelFormat dst_pix_fmt1, enum AVPixelFormat dst_pix_fmt2,
                    ^
artwork.c:286:51: warning: passing argument 4 of âavcodec_find_best_pix_fmt2â makes integer from pointer without a cast [enabled by default]
   dst->pix_fmt = avcodec_find_best_pix_fmt2((enum AVPixelFormat *)img_encoder->pix_fmts, src->pix_fmt, 1, NULL);
                                                   ^
In file included from artwork.c:32:0:
/usr/local/include/libavcodec/avcodec.h:4953:20: note: expected âintâ but argument is of type âvoid *â
 enum AVPixelFormat avcodec_find_best_pix_fmt2(enum AVPixelFormat dst_pix_fmt1, enum AVPixelFormat dst_pix_fmt2,
                    ^
artwork.c:286:51: error: too few arguments to function âavcodec_find_best_pix_fmt2â
   dst->pix_fmt = avcodec_find_best_pix_fmt2((enum AVPixelFormat *)img_encoder->pix_fmts, src->pix_fmt, 1, NULL);
                                                   ^
In file included from artwork.c:32:0:
/usr/local/include/libavcodec/avcodec.h:4953:20: note: declared here
 enum AVPixelFormat avcodec_find_best_pix_fmt2(enum AVPixelFormat dst_pix_fmt1, enum AVPixelFormat dst_pix_fmt2,
                    ^
Makefile:992: recipe for target 'forked_daapd-artwork.o' failed
make[3]: *** [forked_daapd-artwork.o] Error 1
make[3]: Leaving directory '/var/lib/forked-daapd-ejurgensen/src'
Makefile:517: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/var/lib/forked-daapd-ejurgensen/src'
Makefile:540: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/var/lib/forked-daapd-ejurgensen'
Makefile:408: recipe for target 'all' failed
make: *** [all] Error 2

Do I need to enable any specific libraries when compiling ffmpeg?
Thanks in advance!

**Comment by kartikkannan** [comment]
Sorry. I got this problem sorted out...
ffmpeg with ./configure --prefix=/usr/local --enable-shared was not correct
ffmpeg with ./configure --prefix=/usr/local --disable-static --enable-shared worked!

**Comment by ejurgensen** [comment]
I must admit that this solution doesn't make a lot of sense to me, but in any case I'm happy you got it working.
