### ISSUE TITLE
Redefining count_info in db.h breaks oss4 build

### ISSUE THREAD

**Issue by freultwah** [ejurgensen/forked-daapd#157]
Trying to compile with OSS4:

In file included from laudio_oss4.c:39:
In file included from ./player.h:7:
./db.h:344:8: error: redefinition of 'count_info'
struct count_info {
       ^
/usr/include/sys/soundcard.h:922:16: note: previous definition is here
typedef struct count_info {
               ^
1 error generated.

I think this originates from here:

https://github.com/ejurgensen/forked-daapd/commit/b7d5b1650ea0cec2455a2124ceb341ff7362dcd2

I realise the code was probably written on a Linux machine and never tested with OSS4, so here it is. :-)

**Comment by ejurgensen** [comment]
Thanks for letting me know! Renamed it to filecount_info, which I hope solves the issue.
