### ISSUE TITLE
support for metadata entry "oeuvre" ?

### ISSUE THREAD

**Issue by Tonmeister20** [ejurgensen/forked-daapd#164]
I just started using forked daapd to organize and sort my classical music. in the german iTunes version, where i rip my CDs there is a tag called "Werk" to classify e.g. all movements of a symphony as one oeuvre. I'm not sure if this tag even exists in other languages.  When i moved my songs from local playback to the forked-daapd server the "oeuvre" tag dissappeard. Do you see a way to integrate that tag again? is there maybe a workaround? 
i'd be so happy to get some help with that.

**Comment by ejurgensen** [comment]
What does "avprobe [yourfile]" output? (or ffprobe if you use ffmpeg)

**Comment by Tonmeister20** [comment]
That's the output of ffprobe on the forked-daapd machine (debian 8, forked-daapd 23.1):
 (avprobe didnt get as much information as ffprobe)

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/media/music/Alban Berg Quartet/Strauss & Lanner Wal1 Marien-Walzer.m4a':
*  Metadata:
*    major_brand     : M4A
*    minor_version   : 0
*    compatible_brands: M4A mp42isom
*    creation_time   : 2015-05-27 13:45:36
*    title           : Marien-Walzer
*    artist          : Alban Berg Quartet
*    composer        : Lanner, Joseph (1801-1843)
*    album           : Strauss & Lanner Walzer
*    grouping        : Marien-Walzer, Op. 143
*    genre           : Classical
*    track           : 1/9
*    disc            : 1/1
*    date            : 1994
*    compilation     : 0
*    gapless_playback: 0
*    encoder         : iTunes 12.1.2.27
*    Encoding Params : vers
*    iTunNORM        :  000000DC 00000089 0000285F 00000F5F 00033A36 000792AE 00005E3C 00004EB78FF6 00079BC0
*    iTunes_CDDB_IDs : 9++
*    UFIDhttp://www.cddb.com/id3/taginfo1.html: 3CD3N84Q186262713U1280225A7C862115F994A43529EBD5P8
*  Duration: 00:08:28.43, start: 0.000000, bitrate: 599 kb/s
*    Stream #0:0(und): Audio: alac (alac / 0x63616C61), 44100 Hz, stereo, s16p, 598 kb/s (defa
*    Metadata:
*      creation_time   : 2015-05-27 13:45:36
*    Stream #0:1: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 300x300 [SAR 1:1 DAR 1:0k tbr, 90k tbn, 90k tbc

what appears as "Werk" in iTunes is here written in the grouping tag ( Marien-Walzer, Op. 143 )

**Comment by ejurgensen** [comment]
forked-daapd has support for the grouping tag, and it should also be sent over daap to clients, if they request it. To find out what is going on in this case I would need precise directions so I can reproduce the issue here.

**Comment by Tonmeister20** [comment]
i could solve it myself. while reading INSTALL i just did what "quick version" told me to do. after installing all tools and libraries from "long Version" correctly it works as you said. Many Thanks!
