### ISSUE TITLE
import internet radio from m3u list not working?

### ISSUE THREAD

**Issue by hgw77** [ejurgensen/forked-daapd#169]
Hi,

I am not sure that is an issue....I tryed to use a m3u file which contains a list of m3u links (as described here https://github.com/ejurgensen/forked-daapd#playlists-and-internet-radio) and if the m3u file (that are linked) contains more than a link it is not working. Here an example:

Working m3u: 
````
http://mp3channels.webradio.antenne.de/lovesongs
````

Not Working m3u:
````
#EXTM3U
#EXTINF:-1,apollo radio))) - bleiben Sie anders
http://apollo-stream.primacom.net:6300
````

it seems the parser cannot handle the extra information in the file?

**Comment by ejurgensen** [comment]
I'm a bit confused about the exact contents of the m3u? You wrote that you used a m3u with m3u links, but the links you provided seem to be to the streams, not to m3u's. Also neither the working m3u nor the non-working m3u contains more than one link?

Just want to be sure what I should look at.

**Comment by roblan** [comment]
I also had a problem with m3u created with iTunes
```
#EXTM3U
#EXTINF:-1,Indie 103.1 - 
http://in.icy1.abacast.com/entravision-indieaac-48

```
BUT when I created file in nano and copy-pasted content it worked...

**Comment by stephan-01010011** [comment]
A lot of m3u are messed up with encodings that do not conform to the (not officially existing) specification. At least this was my research result. I think the best reference is the Wikipedia article regarding m3u files (http://en.wikipedia.org/wiki/M3U). Currently forked-daapd is handling the m3u content as plain ASCII not Windows-1252.
In order to isolate the problem it is necessary to get the "incompatibly" m3u files. Is it possible to provide a download link?
@roblan are you sure that the "m3u" created by iTunes is not a m3u8 that contains, like specified, UTF-8 encoded content? It could be possible that you "corrected" the encoding by copy pasting the content.

**Comment by ejurgensen** [comment]
I cannot reproduce the problems mentioned here, so I will need more information to do anything about it. The information I require is a link to the actual m3u file, version numbers of forked-daapd and ffmpeg/libav, and also relevant log snippets.

When I test the above m3u contents work fine, exported m3u's from itunes also work, and so does utf-8. It is not correct that only plain ascii is supported. I did not test Windows-1252, but you are right that it is not supported. However, even if the m3u is encoded in Windows-1252, the stream should still be added, but the metadata might be wrong.

**Comment by hgw77** [comment]
Hi, and sorry for my delay!

thank you for the answer, I think it is related to the encoding. I checked the m3u's and all of them are windows encoded :-(

here some links to the m3u's

http://stream.apolloradio.de/APOLLO/mp3.m3u
http://avw.mdr.de/livestreams/mdr_figaro_live_128.m3u
http://avw.mdr.de/livestreams/mdr_info_live_128.m3u

@ejurgensen yes and you are right the stream is added but the meta are completely messed up

thank you all for help :-)

**Comment by ejurgensen** [comment]
As the referenced commit shows I fixed a problem which I observed with the links you provided. However, this problem had nothing to with character encoding and doesn't entirely match the descriptions you gave, so I am not sure if this closes your issue. I hope you can test for yourself and let me know.
