### ISSUE TITLE
Question about Artwork Constraints

### ISSUE THREAD

**Issue by mikebrady** [ejurgensen/forked-daapd#171]
Could you explain how the client gives artwork constraints to forked-daapd? I'm the developer of Shairport Sync and am struggling with errors due to very large artwork files being sent from iTunes. Sometimes iTunes just bogs down and stops sending control information of any kind. If there was a way of telling iTunes to send smaller artwork data, it would be just great.

Sorry to raise an "issue" – your program is great!

**Comment by ejurgensen** [comment]
Good to hear from you, and lots of thanks for continuously improving Shairport! Don't hesitate to let me know if there is anything I can do to improve the way forked-daapd works with Shairport Sync.

Unfortunately I don't have an answer to your question. If raop clients can give artwork constraints I have never noticed them, and forked-daapd would not be able to understand them. What prevents forked-daapd from sending very large artwork is that a max size of 600 x 600 is simply hard coded here: https://github.com/ejurgensen/forked-daapd/blob/master/src/raop.c#L785

So I guess you will need to listen in on the traffic to eg. an ATV to see what it does?

**Comment by mikebrady** [comment]
Thanks for the response. I was prompted to ask by the phrase in your README.md about artwork, where you write: "Your artwork must be in PNG or JPEG format, dimensions do not matter; forked-daapd scales down (never up) the artwork on-the-fly to match the constraints given by the client.". I was hoping that you might have discovered some general mechanism that enabled the client to tell the source of artwork (forked-daapd in this case) about any constraints it might have.

Thanks again for your work on forked-daapd.

**Comment by ejurgensen** [comment]
Ok. The "constraints given by the client" in the README is refering to DAAP clients. They will request an artwork size (with GET parameters), and forked-daapd will (well most of the time) honor this size request. But since it is DAAP, it doesn't really help you. I guess Shairport isn't actually even a client, but a server?

**Comment by mikebrady** [comment]
Okay, that explains it, thanks. Yes indeed, Shairport Sync is indeed a server.

**Comment by jkiddo** [comment]
I've digged into the RAOP protocol my self (in my Java version of Apple protocols - called Jolivia). I can't seem to remember that there is any limitation on how large the images transported over RAOP are. It can probably be found out - e.g. if you try to put a HUGE album art into a album and then stream it to some RAOP server.

**Comment by mikebrady** [comment]
It's certainly possible to have an 11 megabyte picture, and usually it will be properly transmitted, but occasionally, as I mentioned, iTunes will simply stop sending the data, or send it so slowly as to make it useless. Meanwhile, other packets get backed up... I filed a bug with Apple. It seemed to go away with an OS revision, but it still there occasionally.
