### ISSUE TITLE
OpenWrt (Trunk, r46076) forked-daapd stops on initializing database and quits without error

### ISSUE THREAD

**Issue by adriangith** [ejurgensen/forked-daapd#172]
OpenWrt (Trunk, r46076) forked-daapd stops on initializing database and quits without error.

**Comment by ejurgensen** [comment]
This is 22.3 rel 20150222, right? Which architecture?

**Comment by adriangith** [comment]
Yes, and ar71xx. It was working fine on CC RC2, not sure if it was the update that caused the problem...

**Comment by ejurgensen** [comment]
I just tested with OpenWrt r45992 (latest snapshot image) in a x86 vm, and that worked ok. Didn't test much more than the upstart, though. I don't have the option of testing on ar71xx at the moment, unfortunately. So I will need your help to find the problem. Could you set the log level to debug and let me know what the exact last lines of the log file are?

**Comment by adriangith** [comment]
I have returned to rc 2 so I could use forked-daapd (works). Before I did
though, I set the log level to 'spam', and initialising database was the
last thing mentioned. Can't remember what the last [log] was.

**Comment by ejurgensen** [comment]
Ok, guess it will be difficult to find the problem then. I will close the issue, and reopen later if it reappears.
