### ISSUE TITLE
not all artwork being processed

### ISSUE THREAD

**Issue by alien8ion** [ejurgensen/forked-daapd#175]
I store my iTunes library on the linux server and share it via netatalk and point iTunes to use it as it's library volume.

I've done quite a lot of clean up on my library, downloading artwork where available and assigning artwork via the Get Info > Artwork interface in iTunes where the download was unsuccessful.

in the iTunes library all of the artwork appears as expected, however; when accessing via the forked-daapd share (either on the same network or via dns-sd with older versions of iTunes) not all of the artwork is displayed. Actually quite a lot of it is missing (but not all) ...

I haven't had the opportunity to determine if this is related to downloaded artwork vs. imported (copy/paste) artwork although at quick glance I'm not sure there's a correlation there.

any ideas what might be the problem?

Regards

**Comment by ejurgensen** [comment]
Can you provide the output of ffprobe (or avprobe, if you use libav), when you probe one of the files without artwork?

**Comment by alien8ion** [comment]
neither ffprobe or avprobe were present on the system so i had to
install libav-tools

here's the output from one file:

$ avprobe "02 Virus.mp3"
avprobe version 9.18-6:9.18-0ubuntu0.14.04.1, Copyright (c) 2007-2014
the Libav developers
  built on Mar 16 2015 13:19:10 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
[mp3 @ 0xcc5ba0] max_analyze_duration reached
[mp3 @ 0xcc5ba0] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from '02 Virus.mp3':
  Metadata:
    title           : Virus
    artist          : Absolum
    TCM             : Christoph Drouillet
    album           : Inside The Sphere
    track           : 2/9
    encoded_by      : iTunes v4.2
    genre           : Electronica/Dance
    date            : 2004
  Duration: 00:07:53.47, start: 0.000000, bitrate: 160 kb/s
    Stream #0.0: Audio: mp3, 44100 Hz, 2 channels, s16p, 160 kb/s
# avprobe output

---- and here's output of a file that is properly displaying the artwork:

$ avprobe "01 Statement.mp3"
avprobe version 9.18-6:9.18-0ubuntu0.14.04.1, Copyright (c) 2007-2014
the Libav developers
  built on Mar 16 2015 13:19:10 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
[mp3 @ 0x1d85ba0] Unknown attached picture mimetype: JPG?, skipping.
[mp3 @ 0x1d85ba0] max_analyze_duration reached
[mp3 @ 0x1d85ba0] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from '01 Statement.mp3':
  Metadata:
    title           : Statement
    artist          : Koxbox
    album           : The Great Unknown
    track           : 1/10
    genre           : Electronica/Dance
    encoded_by      : iTunes v4.0.1
  Duration: 00:00:48.95, start: 0.000000, bitrate: 160 kb/s
    Stream #0.0: Audio: mp3, 44100 Hz, 2 channels, s16p, 160 kb/s
# avprobe output

hope this is helpfule.

Thanks,

Alan

**Comment by freultwah** [comment]
Does iTunes even include the artwork in the files' metadata when told to to download it? I have been under the impression that such artwork is stored somewhere in the directory iTunes/Album Artwork/ and not in the files themselves.

**Comment by ejurgensen** [comment]
There is no artwork in those files so I think freultwah is right. iTunes has the artwork somewhere else. You will need to make the artwork accessible to forked-daapd as described in the Readme.

**Comment by alien8ion** [comment]
if I open the second file I sent information for in kid3 (ID3 editor) it
shows that there is a picture embedded in tag 2 (see attached)... is it
possible that avprobe is only looking at tag 1?

**Comment by alien8ion** [comment]
nevermind.. that one actually displays and the one that doesn't
definitely doesn't have an image in the ID3 tags

I'll look into it further.
thanks for the help.
