### ISSUE TITLE
Optional ffmpeg suffix for FreeBSD?

### ISSUE THREAD

**Issue by freultwah** [ejurgensen/forked-daapd#176]
There are four versions of ffmpeg in the FreeBSD ports tree. All but the one deemed stable are appended a suffix – currently ffmpeg 0.7.16 gets to be ffmpeg0, ffmpeg 2.6.3 is installed as ffmpeg26 etc. (The one currently deemed stable and installed without a suffix is 2.3.6.) Similar suffixes are also added to the names of libraries and headers installed, so that instead of /usr/local/include/libav* etc we have /usr/local/include/ffmpeg26/libav* (which in itself is easy to fix), and instead of /usr/local/lib/libavcodec.so.56.26.100 we have /usr/local/lib/ffmpeg26/libavcodec26.so.56.26.100. Etc.

Is it possible to add such an optional configure switch for detecting a so-called non-stable ffmpeg on FreeBSD, so that configure could look for libavcodec26 instead of just libavcodec? pkgconfig would perhaps be able to point a way forward, but even those files are named with the same suffixes, so that the standard ./configure script has no way of picking them up. Something like --ffmpeg-suffix or something.

Example (libavcodec26.pc)

```
prefix=/usr/local
exec_prefix=${prefix}
libdir=/usr/local/lib/ffmpeg26
includedir=/usr/local/include/ffmpeg26

Name: libavcodec26
Description: FFmpeg codec library
Version: 56.26.100
Requires: 
Requires.private: libswresample26 >= 1.1.100, libavutil26 >= 54.20.100
Conflicts:
Libs: -L${libdir}  -lavcodec26 
Libs.private: -lssl -lcrypto -L/usr/local/lib -lx264 -lmp3lame -lfdk-aac -lm -llzma -lbz2 -lz -pthread -lpthread
Cflags: -I${includedir}
```

**Comment by ejurgensen** [comment]
I made an attempt at supporting this with --with-ffmpeg=VERSION. Don't know if it will suffice, I haven't tested it in FreeBSD. Can you test the branch referenced above?

**Comment by freultwah** [comment]
Hah, probably (or not) in order to celebrate my opening of the issue here, ffmpeg 2.7 was promoted to stable (and suffix-less) and almost all suffixed ports were removed from the tree, only ffmpeg 0.7.16 remained. So it's a non-issue now. Sorry for making you do unnecessary work.

**Comment by ejurgensen** [comment]
No problem. I'll close then.
