### ISSUE TITLE
Database request sending wrong mlcl size

### ISSUE THREAD

**Issue by jeanyvesb9** [ejurgensen/forked-daapd#180]
Hi!

First, I just want to sat thank you, for all the effort you are putting into this project. It´s really useful!

I think i may have found a problem (somebody please correct me if i´m wrong) with the server response of a database list request. Here are the hex values:

61 76 64 62 00 00 01 1e 6d 73 74 74 00 00 00 04
00 00 00 3f 6d 75 74 79 00 00 00 01 00 6d 74 63
6f 00 00 00 04 00 00 00 02 6d 72 63 6f 00 00 00
04 00 00 00 02    [6d 6c 63 6c] (mlcl)    [00 00 00 3f] (size is 63!?)    6d 6c 69
74 00 00 00 68 6d 69 69 64 00 00 00 04 00 00 00
01 6d 70 65 72 00 00 00 08 00 00 00 00 00 00 00
01 6d 64 62 6b 00 00 00 04 00 00 00 01 61 65 43
73 00 00 00 04 00 00 00 01 6d 69 6e 6d 00 00 00
08 50 52 4f 4a 45 43 54 75 6d 69 6d 63 00 00 00
04 00 00 00 3f 6d 63 74 63 00 00 00 04 00 00 00
06 6d 65 64 73 00 00 00 04 00 00 00 03 6d 6c 69
74 00 00 00 71 6d 69 69 64 00 00 00 04 00 00 00
02 6d 70 65 72 00 00 00 08 00 00 00 00 00 00 00
02 6d 64 62 6b 00 00 00 04 00 00 00 64 61 65 43
73 00 00 00 04 00 00 00 00 6d 69 6e 6d 00 00 00
05 52 61 64 69 6f 6d 69 6d 63 00 00 00 04 00 00
00 06 6d 63 74 63 00 00 00 04 00 00 00 00 61 65
4d 6b 00 00 00 04 00 00 00 01 6d 65 64 73 00 00
00 04 00 00 00

Clearly the size of the list isn´t 63 bytes. If i count the rest of the bytes individually, that results in 233. Am i missing something or i just discovered a bug?

Thanks in advance!
(Sorry about my bad english)

**Comment by jeanyvesb9** [comment]
github removed my comment:

61 76 64 62 00 00 01 1e 6d 73 74 74 00 00 00 04
00 00 00 3f 6d 75 74 79 00 00 00 01 00 6d 74 63
6f 00 00 00 04 00 00 00 02 6d 72 63 6f 00 00 00
04 00 00 00 02          6d 6c 63 6c  (mlcl)            00 00 00 3f  (size is 63?!)              6d 6c 69
74 00 00 00 68 6d 69 69 64 00 00 00 04 00 00 00
01 6d 70 65 72 00 00 00 08 00 00 00 00 00 00 00
01 6d 64 62 6b 00 00 00 04 00 00 00 01 61 65 43
73 00 00 00 04 00 00 00 01 6d 69 6e 6d 00 00 00
08 50 52 4f 4a 45 43 54 75 6d 69 6d 63 00 00 00
04 00 00 00 3f 6d 63 74 63 00 00 00 04 00 00 00
06 6d 65 64 73 00 00 00 04 00 00 00 03 6d 6c 69
74 00 00 00 71 6d 69 69 64 00 00 00 04 00 00 00
02 6d 70 65 72 00 00 00 08 00 00 00 00 00 00 00
02 6d 64 62 6b 00 00 00 04 00 00 00 64 61 65 43
73 00 00 00 04 00 00 00 00 6d 69 6e 6d 00 00 00
05 52 61 64 69 6f 6d 69 6d 63 00 00 00 04 00 00
00 06 6d 63 74 63 00 00 00 04 00 00 00 00 61 65
4d 6b 00 00 00 04 00 00 00 01 6d 65 64 73 00 00
00 04 00 00 00 03

**Comment by ejurgensen** [comment]
Yes, this looks like an error. It's a peculiar one, because the value of avdb (the first tag) is pretty much hard-coded to be the value of mlcl + 53. However, you seem to have an avdb of 286 (which is correct) and a mlcl of just 63.

Could you add the following line at line 55 in src/dmap_common.c, then rebuild & install, and then check what the log says about avdb and mlcl? The line is:
DPRINTF(E_LOG, L_DAAP, "Adding DMAP container: %s, len %d\n", tag, len);

I would like to see if the values passed to this function are really 286 and 63.

**Comment by jeanyvesb9** [comment]
Sorry for the late reply, been really busy.
It turned up being an issue in my code. The parser was flipping a couple of bits and making a total mess.
Thanks for your attention. Keep up with the great work!!
