### ISSUE TITLE
v23.2 w/ iTunes 12.2 on OS X Mac

### ISSUE THREAD

**Issue by kognitix** [ejurgensen/forked-daapd#181]
Hey there - great app here, thank you very much!

I've set up v23.2 successfully.. kind of.  All of my Linux machines see the DAAP server and play from it no problem (via Rhythmbox; Banshee doesn't work -- prob for another day). 

However, my Mac w/ iTunes is seriously sketchy.  It shows as being in the list of shared servers but, perhaps 10% of the time it will actually connect to it.  If I do manage to connect, it usually disconnects after about 8-15 minutes or so (again, randomly..).

Any thoughts on this?  Odd it's so random - I could understand not connecting at all being a compatability issue but, this seems weird.  The only thing in the log is "httpd: Done streaming file id xxxx"

Any help would seriously be appreciated by my hair!

UPDATE:  I was trying with iTunes 12.x.x; just tried with 11.x and it's even worse.. 11.x won't even attempt to connect, it just flips me back to my local music library like nothing happened.

**Comment by jkiddo** [comment]
Ive seen similar behavior in my own java implementation of the DAAP protocol. It could be related to the fact that iTunes does not handle IPv6 addresses. Try disable any assignments of IPv6 adresses on your network interfaces and restart your machines (the easy way to clear any broadcast info on your network).

**Comment by ejurgensen** [comment]
I wish I could help you with your hair! - but I tested with iTunes 12 on OSX and Windows yesterday, and I could not reproduce this behavior. Due to the randomness of the problem, I think @jkiddo is on to something about IPv6. Might also explain why I couldn't reproduce.

**Comment by jkiddo** [comment]
Not that I wan't to promote my app or anything - but if you have an Android device, try and install my app https://play.google.com/store/apps/details?id=org.dyndns.jkiddo&hl=en and see if that works in your setup - if you don't have the problem in the app, I might indicate that it could be related to the IPv6 issue, as I have embedded the IPv6 handling in the app. Now, if that works, @ejurgensen or some of his peers might should have to look into how Avahi is used in forked-daapd project and either disable IPv6 or something else (probably something of a configurable nature).

**Comment by ejurgensen** [comment]
IPv6 is already configurable, and it defaults to disabled. But there might be some IPv6 gotcha's I'm not aware of.
