### ISSUE TITLE
With newest libav 11.4 compile error on Debian

### ISSUE THREAD

**Issue by Qwertzi01** [ejurgensen/forked-daapd#187]
Hi,

after upgrading to the newest libav 11.4 on my debian i get
an error when i try to compile the latest stable forked-daapd:

`/usr/lib/gcc/i486-linux-gnu/4.7/../../../../lib/libavcodec.a(avpacket.o): In function "av_packet_rescale_ts": /usr/src/libav/libavcodec/avpacket.c:386: multiple definition of "av_packet_rescale_ts"
forked_daapd-transcode.o:/usr/src/forked-daapd-test/src/ffmpeg-compat.c:28: first defined here
collect2: error: ld returned 1 exit status`

With my old version of libav (libav11 alpha1) without problems.

Thank you.

**Comment by ejurgensen** [comment]
Thank you for the notice, maybe some of my recent changes have produced this problem. The configure script should detect whether av_packet_rescale_ts() is available or not, but it seems it did not work in this case. Can you run “grep HAVE_LIBAV* config.h” in your build dir and post the output? HAVE_LIBAV_PACKET_RESCALE_TS should be set to 1, but I’m guessing it isn’t.

If you didn’t already, then try to clean the build dir and run “autoreconf –vi” and configure again.

BTW, if you want a stable version right now, it is better to build the latest release, not trunk. On the other hand, I appreciate that you are giving trunk a go, because it helps me discover and iron out bugs.

**Comment by Qwertzi01** [comment]
Thanks for the fast reply. I have already given "autoreconf -vi" a chance  - but without success.

Output of running "grep HAVE_LIBAV* config.h" in build dir:

#define HAVE_LIBAVUTIL_CHANNEL_LAYOUT_H 1
#define HAVE_LIBAVUTIL_MATHEMATICS_H 1
/* #undef HAVE_LIBAV_ALLOC_OUTPUT_CONTEXT2 */
/* #undef HAVE_LIBAV_BEST_EFFORT_TIMESTAMP */
/* #undef HAVE_LIBAV_BUFFERSINK_GET_FRAME */
/* #undef HAVE_LIBAV_BUFFERSRC_ADD_FRAME_FLAGS */
/* #undef HAVE_LIBAV_COPY_PACKET */
#define HAVE_LIBAV_FRAME_ALLOC 1
/* #undef HAVE_LIBAV_GRAPH_PARSE_PTR */
/* #undef HAVE_LIBAV_PACKET_RESCALE_TS */

Helps you further? The last line is what you search or?

**Comment by ejurgensen** [comment]
Yes, the last line is the most interesting. I also wanted to see the other
lines to see if everything was unconfigured, but the rest looks ok.



libav 11 has av_packet_rescale_ts(), and the configure check for it is
here:
https://github.com/ejurgensen/forked-daapd/blob/master/configure.ac#L101



To me the check looks ok, so I don’t understand why
HAVE_LIBAV_PACKET_RESCALE_TS it is not set in config.h. Maybe AC_CHECK_LIB
is somehow checking against some old library version you have installed?



As a work-around, you can try just manually setting
HAVE_LIBAV_PACKET_RESCALE_TS to 1 in config.h and then running make.



2015-10-19 11:02 GMT+02:00 Qwertzi <notifications@github.com>:

**Comment by Qwertzi01** [comment]
> To me the check looks ok, so I don’t understand why HAVE_LIBAV_PACKET_RESCALE_TS it is not set in config.h. Maybe AC_CHECK_LIB is somehow checking against some old library version you have installed?

I checked it - there are no old libav library's.


>As a work-around, you can try just manually setting HAVE_LIBAV_PACKET_RESCALE_TS to 1 in config.h and then running make.

With manual setting in config.h "#define HAVE_LIBAV_PACKET_RESCALE_TS 1>" it works!

**Comment by ejurgensen** [comment]
I just tried installing in a fresh Debian Jessie with libav 11.4, and when I run configure I get:

#define HAVE_LIBAVUTIL_CHANNEL_LAYOUT_H 1
#define HAVE_LIBAVUTIL_MATHEMATICS_H 1
/* #undef HAVE_LIBAV_ALLOC_OUTPUT_CONTEXT2 */
/* #undef HAVE_LIBAV_BEST_EFFORT_TIMESTAMP */
#define HAVE_LIBAV_BUFFERSINK_GET_FRAME 1
/* #undef HAVE_LIBAV_BUFFERSRC_ADD_FRAME_FLAGS */
/* #undef HAVE_LIBAV_COPY_PACKET */
#define HAVE_LIBAV_FRAME_ALLOC 1
/* #undef HAVE_LIBAV_GRAPH_PARSE_PTR */
#define HAVE_LIBAV_PACKET_RESCALE_TS 1

That is correct and it also builds ok. So I don't know why you have a different outcome.

**Comment by Qwertzi01** [comment]
> I just tried installing in a fresh Debian Jessie with libav 11.4

A fresh system is an ideal case - but in practice almost impossible .
But good to hear that it compile without problems on new Jessie.

**Comment by Qwertzi01** [comment]
Hi ejurgensen,

thanks for the new version of forked-daapd. But compiling the new version give me now other errors:

In file included from transcode.c:38:0:
ffmpeg-compat.c:24:1: error: static declaration of ‘av_packet_rescale_ts’ follows non-static declaration
In file included from transcode.c:27:0:
/usr/include/libavcodec/avcodec.h:3465:6: note: previous declaration of ‘av_packet_rescale_ts’ was here
transcode.c: In function ‘filter_encode_write_frame’:
transcode.c:451:2: warning: ‘av_buffersink_read_samples’ is deprecated (declared at /usr/include/libavfilter/buffersink.h:69) [-Wdeprecated-declarations]
transcode.c:453:2: warning: ‘av_buffersink_read’ is deprecated (declared at /usr/include/libavfilter/buffersink.h:50) [-Wdeprecated-declarations]
transcode.c:467:7: warning: ‘avfilter_copy_buf_props’ is deprecated (declared at /usr/include/libavfilter/avfilter.h:899) [-Wdeprecated-declarations]
transcode.c:470:7: warning: ‘avfilter_unref_buffer’ is deprecated (declared at /usr/include/libavfilter/avfilter.h:219) [-Wdeprecated-declarations]
make[3]: *** [forked_daapd-transcode.o] Fehler 1

What goes wrong? Thanks for your help.

**Comment by ejurgensen** [comment]
This is the same error you had before, and you can work around it by editing config.h again. Every time you run 'configure' config.h is overwritten so you need to do it again. Or see if you can get libav cleaned up, so you get a permanent solution.

**Comment by Qwertzi01** [comment]
Ah ok. It work's. Thanks. Yes that is a cramp with my libav. ;-)
