### ISSUE TITLE
Support for AirPlay speakers with built-in controls

### ISSUE THREAD

**Issue by Japanuspus** [ejurgensen/forked-daapd#202]
I have a pair of AirPlay speakers with physical volume buttons on the device http://www.martinlogan.com/crescendo/. When connected to iTunes, this works well: the buttons remote control the iTunes volume.

As far as I can tell, this feature is not implemented in `forked-daapd`?  
From https://nto.github.io/AirPlay.html#audio-remotecontrol,  it appears that to make this work, `forked-daapd` would need to announce an additional `iTunes_Ctrl_...` service via avahi.

I would be happy to contribute to this -- especially if you have any suggestions as to the easiest way to integrate it with the current codebase? Or have you already considered this feature, and omitted it for a specific reason?

**Comment by ejurgensen** [comment]
I haven't considered this feature, but it sounds like it would be very appropriate to have. I would very much welcome your contribution.

The announcement would need to be added in main.c, similarly to the existing, and then you would need to add volumeup and volumedown to httpd_dacp.c.

**Comment by Japanuspus** [comment]
Sounds good -- and thanks a million for the pointers. I'll give it a go over at https://github.com/Japanuspus/forked-daapd/tree/remote_volume, but progress is likely to be glacially slow, working late evenings against a learning curve :)

**Comment by Japanuspus** [comment]
I now have the iTunes_remote service up. It turns out that the actual dacp commands coming back from the speaker are `setproperty` requests for `dmcp.device-volume` (as opposed to `dmcp.volume` as sent from the iOS remote):

    [DEBUG]     dacp: DACP request: /ctrl-int/1/setproperty?dmcp.device-volume=-28.250000

Do you have a suggestion for the correct way to apply this value? I have browsed through `player_volume_set` and friends, but it seems that there are a few issues to grok...

**Comment by ejurgensen** [comment]
I will have a look at it and make you a suggestion. One thing I notice is that there is no speaker id (or session id) in the request from the speaker? This would mean that the volume change would need to be applied for all speakers, which would be less desirable. Have you seen anything that you think could tell forked-daapd which speaker is making the request?

**Comment by Japanuspus** [comment]
Excellent -- much appreciated!

It should be possible to get the speaker id to be part of the request: The request includes an `Active-Remote` http header which is copied verbatim from an `Active-Remote` field which I have added to the raop headers. If getting the session id is enough, a solution could be to use the raop session id directly as the value for the `Active-Remote` field. 

If you would rather look at the code, everything is in [this commit](https://github.com/Japanuspus/forked-daapd/commit/ee7f17e1244c92839c99e05dac25bdc535e5998b) -- but it's only a sketch and not suited to go anywhere.

**Comment by ejurgensen** [comment]
If you can get the speaker id in the header, then here is a suggestion on how to handle the request https://github.com/ejurgensen/forked-daapd/commit/9445fc41806949689b07676b659b0ae1d977243f

**Comment by ejurgensen** [comment]
@Japanuspus did you give up on this? Or was there a problem getting the speaker id?

**Comment by ejurgensen** [comment]
FYI, with commit b6e1269 this should now be supported by forked-daapd
