### ISSUE TITLE
dockerized version

### ISSUE THREAD

**Issue by snizzleorg** [ejurgensen/forked-daapd#204]
for who is interested in i created a first attempt at running the latest forked-daapd (from this git) in a docker container. It's probably far from perfect but at least it compiles and runs in a container now.

here it is: 
https://github.com/snizzleorg/forked-daapd-docker

**Comment by sparklyballs** [comment]
https://github.com/linuxserver/docker-daapd

**Comment by snizzleorg** [comment]
hm.. that looks much more advanced than mine...

thanks

**Comment by bjoerns1983** [comment]
Used sparklyballs Docker for a long time with unRaid. Works like a charm.

**Comment by snizzleorg** [comment]
I just tried @sparklyballs docker container, however this one is not compiled with spotify support.

**Comment by snizzleorg** [comment]
I finally got it working on the raspberryPi: here is the repository for if someone is interested:

https://github.com/snizzleorg/rpi-forked-daapd

**Comment by ejurgensen** [comment]
Thanks for info, good to hear it is working

**Comment by escoand** [comment]
Old issue, I know, but is there an up-to-date docker image with spotify support? The linuxserver's one is updated but without spotify...

**Comment by ejurgensen** [comment]
Not sure if anyone here knows that, perhaps you could add a request for the linuxserver docker to support this?
