### ISSUE TITLE
Persistent ID

### ISSUE THREAD

**Issue by jeanyvesb9** [ejurgensen/forked-daapd#212]
Hi!

Can you tell me where in the code the Persistent ID for a song, and the 64bit ID for the albums and artists are generated? I'm curious about what algorithm are you using, and how do you deal with collisions (in case it's a Hash).

Thanks in advance!
(Sorry about my bad English)

**Comment by ejurgensen** [comment]
Sure, look here:
https://github.com/ejurgensen/forked-daapd/blob/master/sqlext/sqlext.c#L173

As you can see it is a hash of the names.

**Comment by jeanyvesb9** [comment]
And how do you deal with collisions?? Or are those extremely unlikely?

**Comment by ejurgensen** [comment]
This code was made before my time, but as far as I know, forked-daapd doesn’t do anything to deal with collisions. I can’t say I know the collision risk of the murmur hash.

In any case, the consequences of a collision would just be some artists/albums being mixed up. I haven’t heard of that happen, so my feeling is that collisions are not worth dealing with.
