### ISSUE TITLE
systemd unit file

### ISSUE THREAD

**Issue by larsimmisch** [ejurgensen/forked-daapd#213]
I think it would be nice if forked-daapd contained a systemd startup file.

I am currently using this one, maybe it helps:
```
[Unit]
Description=forked-daapd - DAAP (iTunes) Media Server
After=syslog.target network.target

[Service]
Type=forking
ExecStart=/usr/sbin/forked-daapd
Restart=on-abort

[Install]
WantedBy=multi-user.target
```

**Comment by ejurgensen** [comment]
Not sure what the best way to do this is. Maybe a better home for such a file would be the Debian repo: http://anonscm.debian.org/cgit/pkg-multimedia/forked-daapd.git/tree/debian? What would you recommend @rbalint?

**Comment by rbalint** [comment]
It can be put under debian/, but since systemd is used on Red Hat as well I would prefer integrating it here.

**Comment by larsimmisch** [comment]
I think it would be fine to just put my example under scripts and point to it in the documentation.

**Comment by ejurgensen** [comment]
Ok, I've added a service file for systemd. Hope it is ok, otherwise please let me know. Thanks for the suggestion.

**Comment by larsimmisch** [comment]
Thank you
