### ISSUE TITLE
23.2 - Not working for Nightingale / Songbird + DAAP addon

### ISSUE THREAD

**Issue by dreamcat4** [ejurgensen/forked-daapd#223]
Hi there,
I seem to have version 23.2 of your forked-daapd. The one that officially comes from APT in ubuntu 15.10. May I ask: is web interface entirely disabled in that prior version?

Ref: https://github.com/ejurgensen/forked-daapd/issues/136

I ask because what I notice in my client. Which is nightingale + daapclient_ng_compat-0.2.6-Darwin_x86-gcc3.xpi. When navigating to `daap://fdaapd` or `daap://fdaapd:3689` will ask for username + password. Nothing seems to work except for `admin:unused`, which seems for web interface... Then it goes to page "not found".

Also tried installing running a newer version in ubuntu `16.04` image but there was some other error going on it would not start up.

This nightingale DAAP addon (which I am using) can still be found here:

https://web.archive.org/web/20130706073055/http://addons.songbirdnest.com/addon/1355

https://web.archive.org/web/20121102152635/http://addons.songbirdnest.com/addon/1355/versions

http://wiki.getnightingale.com/doku.php?id=porting_songbird_addons

**Comment by ejurgensen** [comment]
Yes, it is disabled in 23.2. Notice that there has never been a web interface, so all that got disabled was a false Bonjour announcement that there was one. This wouldn't change the fact that when you actively try to navigate to the web interface, you don't get anything.

I have never tried the DAAP addon you mention, but if it works it would not need a web interface. It should find your forked-daapd library by itself. There would be no password or anything like that.

**Comment by dreamcat4** [comment]
Thanks! OK you are right. It is not necessary to browse to / login on web interface.

Have tried in windows, and can see it worked fine with Bonjour auto-discovery...

Just not on Mac, with mac version of nightingale + older plugin (compiled for mac). Not sure why. As all same works fine in iTunes (on same Mac client).

Theres no more recent version up there for mac binary, so must be re-compiled. It is an xpi firefox extension format.

Closing this issue.
