### ISSUE TITLE
Adding a file to the playlist triggers a "toggle" Event

### ISSUE THREAD

**Issue by LordMyschkin** [ejurgensen/forked-daapd#224]
I use forked-daapd mainly via mpd clients (it has replaced mpd an hour ago on my raspberry)

It is just a minor issue: but when you add a file via any mpd client, playback starts, when it was paused before. 

And - maybe wanted as it is - the playlist is NOT retained between restarts (as opposed to mpd).

**Comment by chme** [comment]
This is on my todo list. The intention, implementing it the way it currently is, was to mimic the behavior of the apple Remote app (or Retune). But it feels a bit awkward in some clients (that also offer a dedicated add+play option).

**Comment by LordMyschkin** [comment]
It will be difficult merging the functionalities of these two programs (forked-daapd and mpd) into one.
I also noticed that the "consume" mode does not seem to work - but you are certainly aware of that.

**Comment by chme** [comment]
> And - maybe wanted as it is - the playlist is NOT retained between restarts (as opposed to mpd).

@ejurgensen Keeping the playlist between restarts is probably not wanted. At least that is how iTunes does it. 
The solution would be to store the playlist/queue in the db. And i think this is a good idea. This would allow clients to access and edit the queue without going through the player thread. What do you think about this, is it worth looking into?

**Comment by ejurgensen** [comment]
I don't think the playlist should be kept between restarts. It might be good to have the queue separate, but I can't see any other features such a separation is required for? So in that light I am not sure it is worth spending time on.

**Comment by LordMyschkin** [comment]
Please reconsider this opinion. I do not know about the average user, but I can imagine that more and more users from the "mpd-side" switch to forked-daapd, since it offers more functionality and only lacks some functions whose number keeps decreasing. I am sure that you (obviously from the "remote-ReTunes-side") wont miss that feature - but especially during the testing and configuring-phase, losing the playlist with every restart is frustrating; I am sure the default behavior of mpd - keeping the state (playlist and the position) no matter if you stop mpd, switch off the raspberry or whatever - is indeed not only by me a highly appreciated  feature. Although I have no idea how much work this would take, so I have no vote on if its worth the time.

**Comment by ejurgensen** [comment]
I will think about it. I restart quite often as well, since I naturally do a great deal of testing, but I personally haven’t missed this feature.

Maybe I don’t understand the use case well enough. How do you create playlists? I normally just select a track from some view (artist/album/playlists), so it is hardly any effort that I lose between restarts. I do lose position and history, of course. I can’t remember if the mpd way of creating playlists is more involved?

**Comment by LordMyschkin** [comment]
You are right, my use scenario is quite different from yours. I usually create a playlist out of a dozen albums and randomly play song (french chansons, David Bowies discography, a dozen of "Cafe del mar" + some "Budda bar" compilation, or Annie Fischers Beethoven's sonatas), and use this as kind of personal "set it and forget it"-radio. And whenever I have the urge to get some music, I just open the output next to me an go on playing for some minutes. Digging into my (badly unsorted) collection just to play some tracks according to my mood takes almost as much time as I can hear the music before my gf turns the music down because it does not fit her mood.
But maybe thats a very special use case - i just got used to this in many years of using mpd.

**Comment by ejurgensen** [comment]
“I can hear the music before my gf turns the music down because it does not fit her mood”
Lol, that’s a use case I am well familiar with!

I will discuss persistent playlists with chme, but until then some sort of music organiser might be a more immediate solution for you? By that I mean some tool that is able to generate .m3u or .pls playlists.

**Comment by LordMyschkin** [comment]
This has long been implemented - I close that one
