### ISSUE TITLE
Spotify issue: Track not available for Playback

### ISSUE THREAD

**Issue by mdvries** [ejurgensen/forked-daapd#226]
forked-daapd seems to connect to spotify but says it can't find the tracks of all the playlists. Example:

2016-02-02 01:21:04] [  LOG]  spotify: Saving playlist (11 tracks): 'Coldplay - A Rush of Blood to the Head'
[2016-02-02 01:21:04] [  LOG]  spotify: Track not available for playback: 'Politik'
[2016-02-02 01:21:04] [  LOG]  spotify: Track not available for playback: 'In My Place'

ETC.

I read somewhere removing the .spotify file might solve this problem but this doesn't help as forked-daapd can't login after removing the .spotify file and restarting:

[  LOG]  spotify: Could not login into Spotify: No credentials stored

I understood that a authentication token should be saved in /var/cache/forked-daapd/libspotify but this directory stays empty. Never seen a file appear there.

So when looking in iTunes I see the forked-daapd server and Spotify Playlists but they are all empty.

**Comment by ejurgensen** [comment]
As it says in the [README](http://ejurgensen.github.io/forked-daapd/#spotify) you will not be able to play Spotify tracks in iTunes. So those playlists will always be empty. You must use a remote.

"Track not available" usually means that the track has been pulled from Spotify [(see this)](https://community.spotify.com/t5/Help-Desktop-Linux-Windows-Web/This-track-is-not-available/td-p/388002), but if you see it for all tracks, then it might be related to the third thing you wrote: That libspotify does not remember your login, and that the directory is empty.

My best guess on that is that either there is a permission problem, or that libspotify somehow tries to use the wrong directory for its settings. If either of these is the case, then you should be able to troubleshoot by editing the config file like so:
- Set uid to root
- In the "Spotify" section remove the commenting out (the #) of settings_dir and cache_dir. That should force the use of the right directories.

Hope this helps.

**Comment by mdvries** [comment]
Thanks a lot.

It seems indeed be realated to access rights of the daapd user. I didn't change those though on the directory but using uid "root" fixed it. Thanks a lot.

I missed the part on not being able to stream spotify in iTunes. Is that something that is impossible to implement or it's just not implemented. If the latter, do you plan to make this possible in the future?

**Comment by ejurgensen** [comment]
Not impossible, but there are two things going against it:
- The use case is unclear to me. If you are on a machine with iTunes then you probably also have the real Spotify application right there? Maybe you can shed some light on this.
- Probably not a feature Spotify or Apple would condone

**Comment by mdvries** [comment]
The use case for me would be that I can play all my music from within one application (iTunes). Ofcourse the music is accessible also through the spotify client but it would be conveniet to have it all in spotify. So necessesary? No. Convenient? yes.

Thanks for this great piece of software and your quick support response.
