### ISSUE TITLE
Service doesn't start after reboot

### ISSUE THREAD

**Issue by loup-brun** [ejurgensen/forked-daapd#228]
Hi,

I'm running forked-daapd on a Debian Wheezy server. When the server shuts down and reboots, the forked-daapd service does not take off automatically - I must start it manually. Is there a way to ensure that it does restart after a system shutdown?

Thanks!

**Comment by ejurgensen** [comment]
There might be a systemd file required. Since this has to do with the Debian packaging the right place to report it is here: https://bugs.debian.org/cgi-bin/pkgreport.cgi?repeatmerged=no&src=forked-daapd

Hope you don't mind submitting it there.
