### ISSUE TITLE
"make" error Debian 7

### ISSUE THREAD

**Issue by chesterdkat** [ejurgensen/forked-daapd#229]
I followed the "quick install tutorial":
 _git clone https://github.com/ejurgensen/forked-daapd.git
 cd forked-daapd
 autoreconf -i
 ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var
 make
 sudo make install_

When I typed "make" all I got was "make: *** No targets specified and no makefile found.  Stop."

**Comment by ejurgensen** [comment]
What did the "configure" command result in? It sounds like it may have failed, maybe due to a dependency not being met.

I tried in Debian 8 (don't have 7 around any more), and it worked ok.

Sorry about the late reply to this.

**Comment by ejurgensen** [comment]
Closing, no reply
