### ISSUE TITLE
Internet radio dropouts

### ISSUE THREAD

**Issue by john-a-harris** [ejurgensen/forked-daapd#230]
Hi,
Firstly a big thank you for all your work on forked-daapd - it's brilliant and is at the heart of my home multi-room set up.
I have a question about internet radio - I seem to experience dropouts on some stations. When that happens, playback stops, and I have to reselect the stream.
How are these steams actually played under the hood? Is there some way I can increase a buffer to reduce this behaviour? When it happens, I see something like this in the log:
`[2016-02-13 17:53:03] [  LOG]    xcode: Timeout while reading source (connection problem?)`

`[2016-02-13 17:53:03] [  LOG]   player: Error reading source 20352`

**Comment by ejurgensen** [comment]
Sorry for the late reply, I normally try to reply more quickly.

This problem sounds a lot like #218, which I hope I fixed a few weeks ago (note: but at the same time introduced a new bug, which I will fix in the next few days). I am wondering if you are using a version of forked-daapd from before then?

**Comment by ejurgensen** [comment]
Closing, no reply

**Comment by john-a-harris** [comment]
Sorry for the delayed response! I had some trouble getting the code I pulled to build (possibly something to do with my locally built ffmpeg), but I got there in the end. I do still seem to experience the occasional drop out, but it is certainly better that it was before. Thanks!
