### ISSUE TITLE
Cannot stream to multiple devices

### ISSUE THREAD

**Issue by zanzu** [ejurgensen/forked-daapd#240]
Hi,

I first would like to thank the teams for developing a mt-daapd replacement.  I've started using forked-daapd but realize I can only stream audio to one device at a time.  I have compiled forked-daapd on my home server (Ubuntu 14.04 LTS) and have a numerous endpoints (iTunes, Rhythmbox on Mint Linux, Daap clients for Android) in the house.  Is there a setting that I'm overlooking or is this a known issue?

Best Regards,
Charles

**Comment by ejurgensen** [comment]
Sounds like you might be affected by this:
https://github.com/ejurgensen/forked-daapd/blob/master/INSTALL#L38

Ubuntu only has libevent 2.0 so that would explain it. I'm afraid the only solution is to build a newer version yourself.

**Comment by zanzu** [comment]
Thank you for the quick reply.  I've compiled forked-daapd against libevent 2.1.5 beta about an hour ago and am now able to stream to multiple devices. I'll continue with the stress test but so far the results are very promising.
