### ISSUE TITLE
trouble streaming mp3

### ISSUE THREAD

**Issue by p3ck** [ejurgensen/forked-daapd#241]
This is more of a question then a bug.  I'm unable to stream mp3 over port 3869.  I know it relies on ffmpeg having mp3 encoding support but I think I have this correct.  ffmpeg is compiled with --enable-libmp3lame so I'm confused.

I am running on fedora23 with the following libraries from rpmfusion.

ffmpeg-libs-2.8.6-1.fc23.x86_64
lame-libs-3.99.5-5.fc23.x86_64

ldd /usr/lib64/libavcodec.so.56
	linux-vdso.so.1 (0x00007ffc6e93a000)
	libswresample.so.1 => /lib64/libswresample.so.1 (0x00007fc4b335c000)
	libavutil.so.54 => /lib64/libavutil.so.54 (0x00007fc4b30fa000)
	libva.so.1 => /lib64/libva.so.1 (0x00007fc4b2edd000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc4b2cc0000)
	libxvidcore.so.4 => /lib64/libxvidcore.so.4 (0x00007fc4b29ad000)
	libx265.so.68 => /lib64/libx265.so.68 (0x00007fc4b2480000)
	libx264.so.148 => /lib64/libx264.so.148 (0x00007fc4b2109000)
	libvpx.so.2 => /lib64/libvpx.so.2 (0x00007fc4b1d86000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fc4b1a83000)
	libvorbisenc.so.2 => /lib64/libvorbisenc.so.2 (0x00007fc4b17da000)
	libvorbis.so.0 => /lib64/libvorbis.so.0 (0x00007fc4b15ad000)
	libtheoraenc.so.1 => /lib64/libtheoraenc.so.1 (0x00007fc4b136d000)
	libtheoradec.so.1 => /lib64/libtheoradec.so.1 (0x00007fc4b1152000)
	libspeex.so.1 => /lib64/libspeex.so.1 (0x00007fc4b0f39000)
	libschroedinger-1.0.so.0 => /lib64/libschroedinger-1.0.so.0 (0x00007fc4b0c5c000)
	libopus.so.0 => /lib64/libopus.so.0 (0x00007fc4b0a0f000)
	libopenjpeg.so.1 => /lib64/libopenjpeg.so.1 (0x00007fc4b07eb000)
	libmp3lame.so.0 => /lib64/libmp3lame.so.0 (0x00007fc4b0573000)
	libgsm.so.1 => /lib64/libgsm.so.1 (0x00007fc4b0367000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fc4b0151000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fc4afd8f000)
	libsoxr.so.0 => /lib64/libsoxr.so.0 (0x00007fc4afb2c000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fc4af928000)
	/lib64/ld-linux-x86-64.so.2 (0x00005630b1bc6000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fc4af71f000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fc4af39d000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fc4af186000)
	libogg.so.0 => /lib64/libogg.so.0 (0x00007fc4aef7e000)
	liborc-0.4.so.0 => /lib64/liborc-0.4.so.0 (0x00007fc4aecfe000)
	libgomp.so.1 => /lib64/libgomp.so.1 (0x00007fc4aeadb000)

Errors from forked-daapd:
forked-daapd[5890]: [  LOG]    xcode: Error while feeding the filtergraph
forked-daapd[5890]: [  LOG]    xcode: Error occurred: Operation not permitted
forked-daapd[5890]: [  LOG]   stream: Could not encode silence buffer

Any ideas?  Thanks!

**Comment by ejurgensen** [comment]
I think your approach is correct and this is actually a bug in forked-daapd related to newer versions of ffmpeg. You can verify that you have encoding support with "ffmpeg -codecs | grep mp3". There should be an "E" for the mp3 codec. I am pretty sure you have that, otherwise forked-daapd would tell you straight away in the log that there is no support.

Your options are:
1. Remove ffmpeg and try with libav
2. Downgrade ffmpeg (not sure how much is required...)
3. Wait until I get this fixed

Now that you reported the issue I will try to accelerate solution 3. Within a week, I would guess.

**Comment by ejurgensen** [comment]
Seems this was an easier fix than anticipated. I cross my fingers that it works now.

**Comment by p3ck** [comment]
works well for me.  Thanks!
