### ISSUE TITLE
Does not work with iTunes 12.3.3.17

### ISSUE THREAD

**Issue by billxinli** [ejurgensen/forked-daapd#243]
Not sure if this is related to #100 but here goes. I checked out the master branch (42e68311eb14f84e029ce2bede43a3698a4fd081) and ran the following:

```
sudo apt-get install  build-essential git autotools-dev autoconf libtool gettext gawk gperf  antlr3 libantlr3c-dev libconfuse-dev libunistring-dev libsqlite3-dev  libavcodec-dev libavformat-dev libavfilter-dev libswscale-dev libavutil-dev  libasound2-dev libmxml-dev libgcrypt11-dev libavahi-client-dev zlib1g-dev  libevent-dev libcurl4-openssl-dev
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var  --enable-lastfm --enable-itunes --enable-chromecast
make
sudo make install
```

I modified `/etc/forked-daapd.conf` and the only value that I changed was `library > directories` to `	directories = { "/home/username/musics" }`

The server operating system:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
```

I started the service via `service forked-daapd start` and the log is of the following:

```
[2016-03-26 15:01:30] [  LOG]     main: Forked Media Server Version 23.4 taking off
[2016-03-26 15:01:30] [  LOG]     main: mDNS init
[2016-03-26 15:01:30] [  LOG]     mdns: Avahi state change: Client running
[2016-03-26 15:01:30] [  LOG]       db: Now vacuuming database, this may take some time...
[2016-03-26 15:01:32] [  LOG]       db: Database OK with 5326 active files and 6 active playlists
[2016-03-26 15:01:35] [  LOG]     scan: Scanned 200 files...
---SNIP---
[2016-03-26 15:01:56] [  LOG]     scan: Scanned 5200 files...
[2016-03-26 15:01:56] [  LOG]     scan: Bulk library scan completed in 22 sec
```

In iTunes, I see the remote library, I see all the songs with the cover art.

However when I try to play a song it shows the following repeatedly

<img width="452" alt="screen shot 2016-03-26 at 3 04 57 pm" src="https://cloud.githubusercontent.com/assets/1641464/14061962/ec687ac8-f364-11e5-8518-25981de7100f.png">

I thought it was maybe misconfigured, so I tried another client on Android and it was able to connect and play the library.

**Comment by ejurgensen** [comment]
iTunes 12.3.3.17 for Windows works fine for me. Looks like you are on a mac, but I don't have a mac at hand right know to test with.

It would be useful if you could set the log level to debug and then check what requests forked-daapd gets from iTunes when it fails. Might also say how the response is processed.

**Comment by sparklyballs** [comment]
i'm testing a new build of my docker in anticipation of xenial release, and it works fine in mac itunes 
12.3.3.17

**Comment by ejurgensen** [comment]
Closing, no feedback
