### ISSUE TITLE
Manipulating playlist or starting playback is not possible when no output selected

### ISSUE THREAD

**Issue by LordMyschkin** [ejurgensen/forked-daapd#244]
I noticed that, when no output selected, i cannot add files to a playlist or start playback.
This only seems logical at the first glance - because I'd like to prepare my playlist and THAN select an output, and since I listen often by grabbing the mp3-stream, wich is not selectable as output and therefore always active, I have to activate an output, THAN making the playlist and than muting that output again (because there is no problem in deactivating the output once the playback started) - which is kinda unexpected behaviour.
The log entrys are

[2016-03-28 14:37:26] [  LOG]     raop: OPTIONS request failed in session startup: 0 (null)
[2016-03-28 14:37:26] [  LOG]   player: Cannot start playback: no output started
[2016-03-28 14:37:26] [  LOG]      mpd: Error executing command 'play': Failed to start playback
[2016-03-28 14:37:39] [  LOG]     raop: OPTIONS request failed in session startup: 0 (null)
[2016-03-28 14:37:39] [  LOG]   player: Cannot start playback: no output started
[2016-03-28 14:37:39] [  LOG]      mpd: Error executing command 'play': Failed to start playback

**Comment by ejurgensen** [comment]
Can this be closed? I think you can do this now.

**Comment by LordMyschkin** [comment]
hm - the behaviour changed, thats right; now, a random (?) output get's activated when I start playback with all outputs switched off. I do think we discussed this anywhere else; since my usecase is often to start playback and than only grab the mp3-stream without an active speaker, this still is a rather special workaround (I sit in front of my pc in my work room, start playback, and the speaker in the kitchen  gets activated), but maybe this usecase is so special that it is not worth optimizing. But the error above in a strict sense is indeed gone.  So maybe it is okay to close this issue since there is no error any more

**Comment by ejurgensen** [comment]
Ok. Note that the setting "speaker_autoselect" can be used to stop a random speaker from being selected - doesn't that help?

**Comment by LordMyschkin** [comment]
ups - completly missed that one! thanks - please close issue!
