### ISSUE TITLE
Error from readdir_r before scanning

### ISSUE THREAD

**Issue by zanzu** [ejurgensen/forked-daapd#246]
Hi,

I have a fairly large music collection that I've collected over the last 20 years approx 1TB.  I notice in forked-daap logs, during the scan process I am getting 

scan: readdir_r error in <directory name removed>: File name too long

But the scanning continues.  Is this a bug?

Best Regards,
Charles

**Comment by ejurgensen** [comment]
Yes, it may well be a bug. The error message is supposed to show the file name in question (like “readdir_r error in [filename]: [error]”). In your case the path is empty, and I’m not sure how that can happen. If you set the log level to debug then there might be more clues. That would show what the scanner is doing before and after the error occurs.

Be aware that with a library your size, setting the log level to debug will produce a very large log.

To extract the relevant lines you could do something like:
grep “scan: “ /var/log/forked-daapd.log | grep -10 “readdir_r“

**Comment by zanzu** [comment]
I enabled debug mode for the logs. Same error message - seems it only happens during a trigger rescan.  My music folder is mounted ro via NFS on the music server box.

[2016-03-31 21:51:29] [  LOG]     scan: readdir_r error in <deleted dir>: File name too long
[2016-03-31 21:51:29] [DEBUG]     scan: Processing directory <deleted dir/filename> (flags = 0x3)
[2016-03-31 21:51:29] [DEBUG]     scan: Processing directory<deleted dir/filename> (flags = 0x3)
[2016-03-31 21:51:29] [DEBUG]     scan: Processing directory <deleted dir/filename> (flags = 0x3)
[2016-03-31 21:51:29] [DEBUG]     scan: Processing directory <deleted dir/filename> (flags = 0x3)

**Comment by ejurgensen** [comment]
Please include more from the log. There must be more leading up to the error?

**Comment by zanzu** [comment]
I've uploaded the more information from the logfile. Thanks

[readdir_error.txt](https://github.com/ejurgensen/forked-daapd/files/197781/readdir_error.txt)

**Comment by ejurgensen** [comment]
Ok, but now it is an other error because there actually is a path:
readdir_r error in /iTunes/iTunes Media/Music: File name too long

I'm afraid I don't know what to do about this. There is nothing that tells me why readdir is producing this error.

**Comment by zanzu** [comment]
After a little investigation, I don't think this is related to forked-daapd.  I'm mounting from OSX server the music filesystem via NFS to a computer (ubuntu) running forked-daapd.  I use iTunes to manage my music folder.  When I do a long listing in the mounted filesystem I get the same error (filename too long)

$ ls -l  | wc -l
ls: reading directory .: File name too long
<number of directories deleted>

But on the server where I'm exporting the filesystem, the same command does to produce the error
$ ls -l | wc -l
   <number of directories deleted>

I suspect this could be related to Ubuntu (music server where forked-daapd is running) or NFS.

Best Regards,
Charles
