### ISSUE TITLE
Spotify: Can't load Playlists with MPD Clients (Playlist not found for path..)

### ISSUE THREAD

**Issue by derd3000** [ejurgensen/forked-daapd#251]
Hello!
Thank you for your great work! Everything works just fine but there is a tiny problem which I'm not getting used to. I try to control forked-daapd with MPC but I'm not able to load a certain Spotify Playlist. MPC lists all playlists but I'm not able to load one. It always says e.g.:

`pi@raspberrypi:/opt/fhem/log $ mpc load spotify:/Starred
loading: spotify:/Starred
error: Playlist not found for path 'spotify:/Starred'`

and so on. Is it possible to load and play a specific playlist with an MPD Client? I only need the exact path....

mac lsplaylists shows this:
`mpc lsplaylists
spotify:/Chanson (XXXX)
spotify:/chic (XXXXX)
spotify:/daydreaming (XXX)
spotify:/ddd (XXXXXX)`

So there are all the playlists and they are also displayed in the Remote App and u can also start them in the Remote App, but it's not possible to start them with an MPD Client (MPC and FHEM tested till now).

**Comment by chme** [comment]
Hi, 
loading Spotify playlists should work with MPC. You need to pass the complete path including the (xxxx). E. g. `mpc load "spotify:/Starred (xxxxx)" `.

**Comment by ejurgensen** [comment]
Closing, no feedback
