### ISSUE TITLE
OpenWrt 15.05 Gargoyle installer

### ISSUE THREAD

**Issue by peterpux** [ejurgensen/forked-daapd#253]
First, excuse this misplaced question.
does this work with Gargoyle 1.9.x?
If so, is there something easier than compiling to get it installed on my wndr3800?
is there a package that's install-able on the router with .ipk file?

**Comment by ejurgensen** [comment]
I don't know Gargoyle, but OpenWrt 15.05.1 has an ipk. Here is a link for ar71xx:
https://downloads.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/packages/packages/

It is not spanking new, of course.
