### ISSUE TITLE
Apple Watch not reliably pairing

### ISSUE THREAD

**Issue by TomAlperin** [ejurgensen/forked-daapd#256]
When attempting to pair the Apple Watch, the connection is not consistently set. It is possible to pair the Apple Watch, but sometimes it takes several attempts. Forked-daapd logs include:
remote: Discoverd remote ‘Tom’s Apple Watch’ (id <id-for-my-watch>) at 10.0.1.3:54982, paircode <the-paircode>   <— I see this in the log twice.
remote: Read Remote pairing data (name ‘Tom’s Apple Watch’, pin ‘4451’) from /path/to/my/pairingfile.remote
remote: Remote ‘Tom’s Apple Watch’ not know from mDNS, ignoring

This occurs after scanning is complete when pairiing to iPad and iPhone is working reliably.

**Comment by ejurgensen** [comment]
Seems this was due to special chars in the Apple Watch Remote name. For anyone else with the same problem, try using the pairing helper script (https://github.com/ejurgensen/forked-daapd/blob/master/scripts/pairinghelper.sh).
