### ISSUE TITLE
Multiple Chromecast Audio devices - Enhancement?

### ISSUE THREAD

**Issue by zanzu** [ejurgensen/forked-daapd#263]
Hi,  I've decided to experiment with the Chromecast option and picked up a couple chromecast audio devices.  After recompiling with the enable-chromecast option, I am able to stream audio to the chromecast devices.  However, I'm not able to stream different songs to different devices (N:N) relationship.  Are there any plans to add a GUI to the server where the admin can select which playlist is streamed to which chromecast device?  Perhaps there is an application that has the ability to stream multiple source files/playlists to different chromecast devices.

**Comment by ejurgensen** [comment]
I have no plans of making a gui. There are already many gui's out there, especially mpd based. I haven't seen any that are made for playback of multiple streams, but they might exist. The simplest way to support multiple playback on the backend is to just run multiple instances. Changing forked-daapd so one instance can play multiple streams would be quite some work, and it doesn't match the behavior of iTunes nor Remote. So I don't plan on that.

**Comment by zanzu** [comment]
Understood.  Thanks for the reply.  Chromecast didn't meet my expectations.  Currently testing a pair of Bose Soundtouch speakers but looks like these speakers are not compatible with forked-daap.

Is there a user group where I can ask people which WIFI (not bluetooth, airplay or chromecast) speaker system they are using? I prefer to have each speaker function as a client with the ability to play different songs

Sorry for wasting your time on this, I'm sure you have more important things to do.

Best Regards,
Charles 

On May 29, 2016, ejurgensen <notifications@github.com> wrote:
>I have no plans of making a gui. There are already many gui's out
>there, especially mpd based. I haven't seen any that are made for
>playback of multiple streams, but they might exist. The simplest way to
>support multiple playback on the backend is to just run multiple
>instances. Changing forked-daapd so one instance can play multiple
>streams would be quite some work, and it doesn't match the behavior of
>iTunes nor Remote. So I don't plan on that. 
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ejurgensen/forked-daapd/issues/263#issuecomment-222328382

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by ejurgensen** [comment]
Don't know of such a user group. Well Sonos maybe? Note that when forked-daapd streams to Chromecast it is with mp3, so that will hurt the audio quality a bit. However, I believe Chromecast does support none-lossy formats, so perhaps other players can produce better audio.
