### ISSUE TITLE
Remote <GUID> not found in list

### ISSUE THREAD

**Issue by ajensenwaud** [ejurgensen/forked-daapd#273]
Hello, 
I have trouble adding my iPhone 6 iTunes Remote to forked-daapd running on FreeBSD 10.1. I follow the guide as shown on the web site (with a minimal library fully loaded) and add the device in a .remote file. However, after adding I get the following error: 

[  LOG]   remote: Discovered remote 'AJW' (id BE4F3236-9BBF-4060-B3E1-184024802C09) at 192.168.1.83:63275, paircode 30462F2C14563870
[ INFO]     scan: Deferring scan of newly created file /zdata/media/New_Music/dosh3.remote
[  LOG]   remote: Read Remote pairing data (name 'AJW', pin '9537') from /zdata/media/New_Music/dosh3.remote
[ INFO]   remote: Pairing succeeded with Remote 'AJW' (id BE4F3236-9BBF-4060-B3E1-184024802C09), GUID: 15774B5B0BB15D4D
[ WARN]   remote: Remote BE4F3236-9BBF-4060-B3E1-184024802C09 not found in list

(Phone is called 'AJW'.)

Any ideas on how to fix this? 

Some info:
FreeBSD razorfish.jensenwaud.com 10.3-RELEASE FreeBSD 10.3-RELEASE #0 r297264: Fri Mar 25 02:10:02 UTC 2016     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
razorfish# /usr/local/sbin/forked-daapd -v 
Forked Media Server: Version 24.1
Copyright (C) 2009-2015 Julien BLACHE <jb@jblache.org>
Based on mt-daapd, Copyright (C) 2003-2007 Ron Pedde <ron@pedde.com>
Released under the GNU General Public License version 2 or later

**Comment by ejurgensen** [comment]
If I remember this part correctly, this log output is actually normal. The last one is not an error, it just means that the Remote stopped the pairing announcement. The "not found in list" is because the Remote was removed from the "I want to pair"-list when the pairing succeeded, so when the stop message comes the Remote is no longer in the list - which should be fine.

Since it is not working for you there must be something else. What does Remote do when it says pairing succeeded in the log? Nothing?

If you don't mind trying with log level at debug then that might yield some clues.

**Comment by ajensenwaud** [comment]
Thanks for the quick follow up!`

Output from debug mode: 

[DEBUG]       db: Running query 'SELECT * FROM inotify WHERE wd = 26;'
[ INFO]     scan: Deferring scan of newly created file /zdata/media/New_Music/dosh6.remote
[DEBUG]     scan: Processing deferred file /zdata/media/New_Music/dosh6.remote
[DEBUG]     scan: File event: 0x8, cookie 0x0, wd 26
[DEBUG]     scan: File closed: /zdata/media/New_Music/dosh6.remote
[DEBUG]       db: Running query 'SELECT d.id FROM directories d WHERE d.virtual_path = '/file:/zdata/media/New_Music';'
[  LOG]   remote: Read Remote pairing data (name 'AJW', pin '3113') from /zdata/media/New_Music/dosh6.remote
[DEBUG]   remote: Remote 'AJW' found
[DEBUG]   remote: Pairing hash for BE4F3236-9BBF-4060-B3E1-184024802C09/AJW: A187D47A7CFF7317BC6FA5841517125F
[DEBUG]   remote: Pairing requested to /pair?pairingcode=A187D47A7CFF7317BC6FA5841517125F&servicename=770C69AA04442DDF
[ INFO]   remote: Pairing succeeded with Remote 'AJW' (id BE4F3236-9BBF-4060-B3E1-184024802C09), GUID: 5408FC4405AE406E
[DEBUG]       db: Running query 'DELETE FROM pairings WHERE remote = 'BE4F3236-9BBF-4060-B3E1-184024802C09';'
[DEBUG]       db: Running query 'INSERT INTO pairings (remote, name, guid) VALUES ('BE4F3236-9BBF-4060-B3E1-184024802C09', 'AJW', '5408FC4405AE406E');'
[DEBUG]     mdns: Avahi Browser: REMOVE service 'BE4F3236-9BBF-4060-B3E1-184024802C09' type '_touch-remote._tcp' proto 0
[ WARN]   remote: Remote BE4F3236-9BBF-4060-B3E1-184024802C09 not found in list
[ INFO]    cache: Timeout reached, time to update DAAP cache
[ INFO]    cache: DAAP cache updated

On my iPhone I get 'Remote can't connect to your iTunes library. Check your network settings and try again.'

**Comment by ajensenwaud** [comment]
Full log with log level = spam attached.
[forked-daapd.txt](https://github.com/ejurgensen/forked-daapd/files/367074/forked-daapd.txt)

**Comment by ejurgensen** [comment]
Looks like the pairing is going ok, but that Remote is not able to make a connection back again. You should test, eg with telnet, that port 3689 is accessible. You can also test this with iTunes.

**Comment by ejurgensen** [comment]
Closing, no feedback
