### ISSUE TITLE
Feature: Disable auto output selection

### ISSUE THREAD

**Issue by Lakritzator** [ejurgensen/forked-daapd#282]
See #275, coming from a non-apple world I do no want to have a "random" output enabled when the given one does not exist. Having a way to disable this "feature" would let me sleep better.

**Comment by Lakritzator** [comment]
Did have time to test this yet, I am a bit in stress before my holidays. I had a lot of problems with forked-daapd, as the process somehow doesn't have the MPD interface active. As soon as I have time I will write an email about it.

The **current** problem is that the source doesn't compile, maybe due to this:
https://github.com/ejurgensen/forked-daapd/commit/3d6d4e85217f7c13e111ef243a175ee0b3a39c92

```
gcc -DHAVE_CONFIG_H -I. -I..  -D_GNU_SOURCE -DDATADIR="\"/usr/share/forked-daapd\"" -DCONFDIR="\"/etc\"" -DSTATEDIR="\"/var\"" -DPKGLIBDIR="\"/usr/lib/forked-daapd\""  -D_REENTRANT  -I/usr/include/x86_64-linux-gnu -D_THREAD_SAFE -D_REENTRANT -I/usr/include/alsa -I/usr/include/p11-kit-1 -I/usr/include/json-c -g -O2 -Wall -D_LARGEFILE_SOURCE -MT forked_daapd-main.o -MD -MP -MF .deps/forked_daapd-main.Tpo -c -o forked_daapd-main.o `test -f 'main.c' || echo './'`main.c
main.c: In function 'main':
main.c:618:48: error: 'BUILDDATE' undeclared (first use in this function)
   DPRINTF(E_LOG, L_MAIN, "Built %s with:%s\n", BUILDDATE, buildopts);
```

I have the current master state, did a configure (with options) and make clean install

**Comment by ejurgensen** [comment]
Did you run "autoreconf -vi" before configure?

**Comment by Lakritzator** [comment]
Thanks, that worked.

I also noticed just that during the upgrade to Ubuntu 16 the avahi-daemon was gone :(
So I installed this and forked-daapd started again.
Now I can try to use it again, will have a look at this very nice feature!!!
