### ISSUE TITLE
Freebsd 100% cpu usage

### ISSUE THREAD

**Issue by Brampie66** [ejurgensen/forked-daapd#284]
I was very happy forked-daapd works on freebsd now but:
-You start daapd, cpu usage is normal
-You play something from an ipad on a airplay speaker, cpu usage goes up to 100%
-When playback stops, cpu usage is still 100%
-Service restart or kill doesn't work, you have to do kill -s KILL

**Comment by ejurgensen** [comment]
I was not able to reproduce this. Can you give a bit more detail? When you say "You play something from an ipad on a airplay speaker", do you mean that you start playback on forked-daapd with Remote? Also, what kind of file is it?

**Comment by Brampie66** [comment]
Hi,

Next week I'm at the customer who would like to use this, I'll check to 
see when the problem arises exactly and report back to you.
Yes, I mean start playback with the remote app.

thx
Bram

Op 25-08-16 om 20:09 schreef ejurgensen:

**Comment by Brampie66** [comment]
Hi,

This problem is fixed, it was caused by some old xml iTunes library 
files (the user had several of those) while scanning and not because of 
the actual playing.
After we removed the xml files, everything worked ok.

Thx
Bram

Op 25-08-16 om 20:09 schreef ejurgensen:

**Comment by ejurgensen** [comment]
Thank you for the feedback
