### ISSUE TITLE
Freebsd oss support

### ISSUE THREAD

**Issue by Brampie66** [ejurgensen/forked-daapd#285]
Is there a way to get audio output on the server using the freebsd oss implementation ?
Is there a know workaround, the config file or manual isn't very clear on this point.

**Comment by ejurgensen** [comment]
No, if you want local audio you must install the alsa library with "pkg install alsa-lib".

**Comment by Brampie66** [comment]
Ok, I'll try that

Op 25-08-16 om 19:42 schreef ejurgensen:
