### ISSUE TITLE
[LOG] laudio: SNDRV_PCM_IOCTL_SYNC_PTR failed (-32)

### ISSUE THREAD

**Issue by bklebke** [ejurgensen/forked-daapd#291]
Hi,

Recently installed and am attempting to play audio locally and remotely at the same time on an RPi 3. Playback works for a few minutes, slightly out sync, but continuously and at good quality. Then, without apparent cause, the local or  remote stream stops and I'm forced to restart daapd before being able to work with it again.

The remote audio protocol being used in airplay, and locally I'm playing through an ALSA audio hat.
FWIW my config for local looks like this:

>      # Local audio output
>audio {
>	''# Name - used in the speaker list in Remote
>	nickname = "Computer"
>	
>	# Type of the output (alsa or dummy)
>	type = "alsa"
>
>	# Audio device name for local audio output
>	card = "default"
>
>	# Mixer channel to use for volume control - ALSA/Linux only
>	# If not set, PCM will be used if available, otherwise Master.
>	mixer = "Output Mixer HiFi"
>
>	# If your local audio is out of sync with AirPlay, you can adjust this
>	# value. Positive values correspond to moving local audio ahead,
>	# negative correspond to delaying it. The unit is samples, where is
>	# 44100 = 1 second. The offset must be between -44100 and 44100.
>      # offset = 0
>}

**Comment by ejurgensen** [comment]
Not an error I have seen before, but perhaps it's an underrun (not enough audio samples passed to the sound card). A few questions:

1) Is this version 24.1?
2) Does AirPlay work on its own?
3) Does local audio work on its own?
4) Can you set the log level to debug and share the part before the error? (not everything)

BTW If you are using my RPi release, you can consider upgrading to the most recent, which supports Pulseaudio. It does require some setup, and does not support sync - but still would be interesting to know if it is more stable.

**Comment by ejurgensen** [comment]
Closing, no feedback
