### ISSUE TITLE
Forked-Daapd cannot wake up Apple TV 4 from Standby

### ISSUE THREAD

**Issue by ABrolund** [ejurgensen/forked-daapd#292]
Using Apple TV 4 as target for Airplay it does not wake up, while it is in Standby 
Using an Apple device as source it does. 

Tested with Apple devices IOS9 and 10
Tested with Forked-daapd from Master at 1 Okt. 
Tested with Apple AppleOS 10.0

**Comment by ejurgensen** [comment]
Sorry to hear this. I don't have an ATV4, and they are a bit pricey, so I can't do so much about it right now.

**Comment by ABrolund** [comment]
Anything I can help you with ?

**Comment by ejurgensen** [comment]
Only thing I can think of is to try and grab the traffic between iTunes and the ATV with Wireshark, and try to find out what is waking the ATV/keeping it alive. Could potentially be pretty difficult. Not sure how much encryption there is between the two these days.

**Comment by ABrolund** [comment]
What filter should I add to Wireshark or do you want me to capture everything ?

**Comment by ejurgensen** [comment]
Just capture all traffic to the ATV, the filters can be applied later. It would be best if you log out of iTunes before the test. That should reduce the Home Sharing/Fairplay traffic, which is hopefully irrelevant.

**Comment by ABrolund** [comment]
Hi,
this is the traffic recorded with Wireshark: 
Source: iTunes from my Mac
Dest: ATV4

Base condition: ATV in StandBy
[Wireshark iTunes to APTV4.pcapng.gz](https://github.com/ejurgensen/forked-daapd/files/516344/Wireshark.iTunes.to.APTV4.pcapng.gz)

Hope it helps !

**Comment by ejurgensen** [comment]
Thanks, I'll see if I can make sense of it. In the end I think a lot of trial and error will be required to fix this, so I'm going to borrow an atv4 for this.

**Comment by ejurgensen** [comment]
Contrary to the other issue, I couldn't reproduce this one. I did however notice some issues with selecting the Apple TV, when ipv6 was enabled in forked-daapd's config. I will need to investigate those. If you disable ipv6, does it then make a difference to this issue?

**Comment by ABrolund** [comment]
I can confirm that it is working now. Thank you so much, hope the workaround is not too bad!
Great job! Thx again.
Testing stability of connection now, looks stable for nearly2h to know. Will report my findings I the other ticket.
