### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by matthewdias** [ejurgensen/forked-daapd#302]
I'm getting a weird parse error
```
/etc/forked-daapd.conf:258: no such option ''
[FATAL]   config: Parse error in config file /etc/forked-daapd.conf
[FATAL]     main: Config file errors; please fix your config
```

The config file itself is only 257 lines so not sure whats going on here.
Here's my config: https://gist.github.com/89fe82cf87c9f2ce992c647068c979c0

**Comment by ejurgensen** [comment]
It's line 175-182. Certainly the missing closing bracket, and perhaps also the quote in the name. Since you aren't actually setting anything in that section you should just leave as it was.

**Comment by matthewdias** [comment]
oops, thanks for the catch
