### ISSUE TITLE
mpc error: Timeout

### ISSUE THREAD

**Issue by gingerlime** [ejurgensen/forked-daapd#308]
I'm bumping my head against the wall on this one, but can't connect any mpd client (mpc, mpod) to forked-daapd.

Installed on raspberrypi jessie using apt-get. I can see that it's running, that it's listening on the port. I've set up debug logs and see that it's loading music etc. I can even connect to it via curl, e.g.

```
root@raspberrypi:~# curl "http://localhost:3689/login?pairing-guid=0x1&request-session-id=50"
[2016-11-12 07:38:46]    httpd: Found query string
[2016-11-12 07:38:46]     daap: DAAP request: /login?pairing-guid=0x1&request-session-id=50
[2016-11-12 07:38:46]    httpd: Not gzipping; no Accept-Encoding header
[2016-11-12 07:38:46]       db: DAAP request handled in 1 milliseconds
```

But mpc times out, even on the same host, e.g.

```
root@raspberrypi:~# mpc -v -h localhost -p 3689 ls
error: Timeout
# (nothing shows up in the log, even though it's set to debug)
```

(same happens if I use an IP address, different commands etc)

What am I missing??

**Comment by LordMyschkin** [comment]
May I help out? Port 3869 is where the stream is delivered to
Port 6600 ist usually open for MPC control; When you have no instance of MPD running.
So try mpc -v -h localhost -p 6600 or just omit the "-p XXXX" option as 6600 is default.

**Comment by gingerlime** [comment]
Thanks @LordMyschkin. I don't see anything listening on port 6600 however... And nothing in the config either. Is MPD not compiled with the raspbian package / available by default?

**Comment by ejurgensen** [comment]
Yes, it is compiled with mpd and should be listening on 6600. When using mpc on localhost you don't need to specify any address or port. If a straight "mpc status" doesn't work then I'm not sure what is up.

**Comment by gingerlime** [comment]
Thanks for getting back @ejurgensen, but it doesn't seem to be the case unfortunately. I'm using the latest raspbian jessey and installed `forked-daapd` via apt-get. The only change I made to the config was to set the music folder. I can see that it's working with iTunes, but not with mpd, and nothing is listening on port 6600.

Happy to upload log files / run commands etc to debug this.

**Comment by LordMyschkin** [comment]
If you have a rather large file collections, it takes some time to scan the files for the very first time and write the metadata into the database.
During this process, MPC really gives a "timeout"
When the message "bulk library scan completed" appears in your log, MPC should be able to connect. Did you wait that long? With my collection on my RPI2, it took 45 minutes for the first scan.

**Comment by gingerlime** [comment]
I don't have a huge collection, and yes, this message appears:

`[2016-11-12 09:50:44]     scan: Bulk library scan completed in 51 sec`

**Comment by ejurgensen** [comment]
Sorry, gave you some wrong info. The version of forked-daapd in Jessie is 22.0, which does not have mpd support. So you need to upgrade. If you're up for building yourself, check the INSTALL file.

**Comment by ejurgensen** [comment]
And if you use Raspbian, use this: https://www.raspberrypi.org/forums/viewtopic.php?t=49928

**Comment by gingerlime** [comment]
Thanks for clarifying. Much appreciated.
