### ISSUE TITLE
Crash with URLs without any "." chars in the path

### ISSUE THREAD

**Issue by acmay** [ejurgensen/forked-daapd#311]
This seems to fix it for me.

diff --git a/src/http.c b/src/http.c
index 26c478c..c4ec73c 100644
--- a/src/http.c
+++ b/src/http.c
@@ -282,7 +282,7 @@ http_stream_setup(char **stream, const char *url)
   *stream = NULL;
 
   ext = strrchr(url, '.');
-  if (strcasecmp(ext, ".m3u") != 0)
+  if (!ext || strcasecmp(ext, ".m3u") != 0)
     {
       *stream = strdup(url);
       return 0;
--

**Comment by ejurgensen** [comment]
Fixed, thanks a million
