### ISSUE TITLE
Compile error on raspian jessie

### ISSUE THREAD

**Issue by ABrolund** [ejurgensen/forked-daapd#321]
Using newest sources from git, I am getting the following compile error: 

RANT -I/usr/include/alsa -I/usr/include/json-c  -g -O2 -Wall -D_LARGEFILE_SOURCE -MT forked_daapd-httpd.o -MD -MP -MF .deps/forked_daapd-httpd.Tpo -c -o forked_daapd-httpd.o `test -f 'httpd.c' || echo './'`httpd.c
httpd.c: In function ‘oauth_interface’:
httpd.c:209:20: error: storage size of ‘query’ isn’t known
   struct evkeyvalq query;
                    ^
httpd.c:226:28: error: invalid application of ‘sizeof’ to incomplete type ‘struct evkeyvalq’
   memset(&query, 0, sizeof(struct evkeyvalq));
                            ^
httpd.c:209:20: warning: unused variable ‘query’ [-Wunused-variable]
   struct evkeyvalq query;
                    ^
Makefile:939: recipe for target 'forked_daapd-httpd.o' failed
make[3]: *** [forked_daapd-httpd.o] Error 1

Any idea what is going wrong ?

**Comment by ejurgensen** [comment]
Yes, the reason is a forgotten include. Thanks for reporting. Should be fixed now.

**Comment by ABrolund** [comment]
confirmed to be fixed
