### ISSUE TITLE
feature-request: Support option for "Album by Artist" sort order

### ISSUE THREAD

**Issue by chucksense** [ejurgensen/forked-daapd#358]
iTunes has the ability to sort albums "by artist" rather than purely alphabetically.  When enabled, if using `Remote.app` when you go to the "Albums" view, it will really order by artists, but have a listing for each album.

Presently, it seems `forked-daapd` only sorts by album title itself.  It would be nice if the above behavior could be mimicked.

**Comment by chucksense** [comment]
Example of setup from iTunes: 
![screen shot 2017-03-03](https://cloud.githubusercontent.com/assets/199588/23540349/bd2d3d6e-ffae-11e6-910f-26bed47fe9e3.jpg)

**Comment by ejurgensen** [comment]
There is probably something I am missing here, but in my Remote the listing order is not affected by the order in iTunes? When I select the Album view in Remote I get the albums ordered by title, even when I setup iTunes like you showed.

**Comment by chucksense** [comment]
Here are the same libraries, one as served from iTunes, the other as served from forked-daapd. 

iTunes:
![img_4037](https://cloud.githubusercontent.com/assets/199588/23580350/09876c14-00ce-11e7-8dd1-368d9ffdbcc7.PNG)


forked-daapd:
![img_4038](https://cloud.githubusercontent.com/assets/199588/23580352/1007278c-00ce-11e7-9f6c-d8bdb0dc7397.PNG)

You can see the forked-daapd library is sorting albums by album title.  The iTunes library is sorting by artist like the desktop iTunes.

I'm not sure why yours isn't doing this behavior?  There is also this dialog that is reached at `View`->`Show View Options` (or `⌘-J`):
![view options-20170304113258](https://cloud.githubusercontent.com/assets/199588/23580374/7f871b44-00ce-11e7-8ba8-65fc40286284.jpg)

Perhaps that does it?

**Comment by ejurgensen** [comment]
Yes, the setting in Remote does the trick. I have fixed it now so that albums get sorted by artist when Remote requests it.
