### ISSUE TITLE
Support AppleTV using PlexConnect-like channel hijack hack

### ISSUE THREAD

**Issue by pipian** [ejurgensen/forked-daapd#36]
Recent versions of the AppleTV version of iOS do not support connecting to DAAP shares, but only Home Sharing shares.  As a result, forked-daapd will no longer work with recent versions of the AppleTV OS.  It is, however, possible to hack the AppleTV to hijack certain "channels" on the device to provide local content, as primarily demonstrated by the PlexConnect project, which acts as a bridge to a Plex Media Server.

It would be useful to embed a similar bridge server to stream content from forked-daapd to recent versions of the AppleTV instead of Plex Media Server.

This enhancement would likely involve studying the PlexConnect code to document the AppleTV protocol and then implement it as an additional server on top of the DAAP and Remote servers.

**Comment by olihey** [comment]
Hej, bypassing ftp-setup is very simple.
Example code: [https://github.com/nto/AirSpeaker/blob/master/AirTunes/AirTunesController.m#L237](url)

**Comment by martinhrpi** [comment]
Is there an update on this issue?

**Comment by ejurgensen** [comment]
No update, sorry. I don't think it is relevant anymore to do hijack originally proposed. I suppose Plex also has an app for that now. I don't imagine there are any daap capable Apple TV apps (I haven't checked), so either someone needs to make one, or Home Sharing needs to be supported by forked-daapd.
