### ISSUE TITLE
Embedded artwork often not showing, instead just black

### ISSUE THREAD

**Issue by chucksense** [ejurgensen/forked-daapd#367]
Many artworks are just showing as black:

![img_4065](https://cloud.githubusercontent.com/assets/199588/23827119/2fb9849c-067a-11e7-8bef-9dd5c4d7814a.PNG)

Attached is a sample file.

[01 Allophone.zip](https://github.com/ejurgensen/forked-daapd/files/836144/01.Allophone.zip)

**Comment by ejurgensen** [comment]
Thanks for notifying me. I'm guessing the files are png's, so the issue is likely the same as #345. I'm working on it...

**Comment by chucksense** [comment]
Ok. If it helps, the artwork does show in Now Playing, just not the Album or Artist views.

**Comment by ejurgensen** [comment]
Took another stab at this, and with the above commit I hope it is fixed. Let me know if it works for you. Remember to stop forked-daapd, close Remote and delete the cache (see path to the cache in the config) before testing.

**Comment by chucksense** [comment]
Sorry for the delay in checking.  I just built the latest version and can confirm artwork is now working as expected.  Thanks for fixing this!! :-)
