### ISSUE TITLE
Looking for airplay server with Echo Dot as source 

### ISSUE THREAD

**Issue by 1liminal1** [ejurgensen/forked-daapd#371]
Hi guys, im looking to use a Pi Zero with DAC to use as an Airplay Server, with audio from a Echo Dot for multi-room audio. But it also needs a simple API (like TuneBlade) so I can use HA-Bridge to control it. Also it needs to be ok with more then one server on the network (basically there will be a Pi Zero for each Echo, currently 2)

If this is not what im looking for, I'm very open to suggestions?

Currently using a power hungry mini PC running TuneBlade for each Echo

Thanks so much!

**Comment by ejurgensen** [comment]
There was a similar question here: https://www.raspberrypi.org/forums/viewtopic.php?p=1117662#p1117662

The gist of it is that you can feed audio from the Echo to forked-daapd via a named pipe, and then forked-daapd can distribute the audio to your AirPlay devices.

I don’t know how forked-daapd performs on a Pi Zero, haven’t tried that. Maybe someone else can pitch in. With a pipe input there will be no transcoding required, so that should reduce the cpu requirements. Otherwise consider employing more powerful Pi’s.

You can control forked-daapd with mpd or dacp/daap commands. The former is probably the easiest.

**Comment by 1liminal1** [comment]
I'm currently setting this up with a mini PC just to get it all working. If it works fine, then ill try the Zero. 

But the thing with what that guy was doing is he was still using the library, what I want to do is take whatever is coming in from the mic jack and output that to Airplay?  

Im Googleing around, but not much luck yet

**Comment by 1liminal1** [comment]
Ok, so what youre saying is I need to take the input from the mic jack, write it to a file and then pipe that output to the airplay devices. 

Could you give me an example of what something like that might look like?

Thanks

**Comment by 1liminal1** [comment]
Ok so it would be something like this im guessing 

arecord -f cd -d 10 -t raw | mkfifo /srv/music/Echo

And I can delete all other entries in the library other then?

I would just have one entry, I would really like to see a real life conf file to get an idea 

Im confused, but getting there lol

**Comment by ejurgensen** [comment]
The guy with the question I linked to is trying to do exactly the same as you, and he even has the same confusion about what a named pipe is.

> arecord -f cd -d 10 -t raw | mkfifo /srv/music/Echo

No, first make the pipe with mkfifo, then write to it with arecord -f cd.... > /srv/music/Echo

> And I can delete all other entries in the library other then?

Don't know what other items you have in your library, but it doesn't make any difference to this issue what you do with them.

**Comment by 1liminal1** [comment]
> The guy with the question I linked to is trying to do exactly the same as you, and he even had the same confusion about what a named pipe is.

Yeah, I got that in the end, Im very new to Linux, I just wish I could see his conf to get some context to all this.

> No, first make the pipe with mkfifo, then write to it with arecord -f cd.... > /srv/music/Echo

So, ive created the pipe, but do I need to run this all the time or 

# Pipe output
# Allows forked-daapd to output audio data to a named pipe
#fifo {
#       nickname = "fifo"
#       path = "/path/to/fifo"
#}

Just have this part filled out? But what needs to be un commented. 

I really wish I could see that guys conf for some better context lol

Anyway, thanks for your help with this, I know you must be busy.

**Comment by ejurgensen** [comment]
You don't need to do anything special in config file to do this, in fact the default config file may be fine as it is. So you would be none the wiser from getting that config. The "fifo" section of the config is not relevant to you, because, as it says, it is for "forked-daapd to output audio data" and you are not looking for audio output.

Once you have forked-daapd working normally (and please verify that first - like I said to the other guy: one step at a time is important), then make the pipe with "mkfifo" (test it - e.g. with "cat test.pcm > /srv/music/Echo"), then start writing to the pipe with "arecord".

What "arecord" does is take the audio from your sound card and write it to the pipe. Yes, it needs to run all the time, otherwise forked-daapd won't get any audio. When you have it working you can look into running it in the background.

BTW please format your posts properly.

**Comment by 1liminal1** [comment]
Ok I have forked-daapd working, I have to reboot the whole server whenever I want to change something in the .conf lol, but its working. 

But when I run the test pipe, nothing comes up in the remote. I have a named pipe set up. in a folder under my user called /airplay

shane@AIRLOUNGE:~/airplay$ cat test.pcm > /airplay

That works, but nothing shows up in the remote

I thought maybe it was the path, because its different here to the .conf. Linux paths are a little strange. 

shane@AIRLOUNGE:~/airplay$ cat test.pcm > /home/shane/airplay
-bash: /home/shane/airplay: Is a directory
shane@AIRLOUNGE:~/airplay$ mkfifo /home/shane/airplay
mkfifo: cannot create fifo '/home/shane/airplay': File exists

So I test that, it tells me the file already exists, great!

shane@AIRLOUNGE:~/airplay$ mkfifo /airplay
mkfifo: cannot create fifo '/airplay': File exists
shane@AIRLOUNGE:~/airplay$ cat test.pcm > /home/shane/airplay
-bash: /home/shane/airplay: Is a directory
shane@AIRLOUNGE:~/airplay$ cat test.pcm > /home/shane/airplay/airplay
cat: test.pcm: No such file or directory

But it cant find the fifo file, unless its /airplay

I tried to fix that formatting, But it doesn't change

**Comment by 1liminal1** [comment]
Sorry for the formatting, I did try to change it

I have forked-daapd working, remote is working. But Its not showing me anything to play when I run the pipe

Are you being literal about the cat test.pcm

`shane@AIRLOUNGE:~$ "cat test.pcm" > /airplay`

Its running, but nothing shows in Remote.

Also tried "arecord -f cd -t raw > /airplay"

Nothing, 

Also strangly it wont work if I try the to run it under the full path 


"cat test.pcm" > /home/shane/airplay

Tells me it's not a directory, but it shows in ls

**Comment by 1liminal1** [comment]
Anyway, I dont want to push my luck, 

If you can let me know if I should see a playable file in remote while running the pipe and if cat test is a real thing. Ill keep going on my own with the rest. Cant expect you to do it for me :)

**Comment by 1liminal1** [comment]
OK followed your advice, copied a test file and can confirm that it plays over both Airplay amps from the remote as a file, shows up perfectly 

But when I try to play the named pipe 

arecord -f cd -t raw > /airplay

It churns, like its playing, but I get nothing, I get nothing showing up in the remote, In guessing there should just be a file saying Airplay?

**Comment by 1liminal1** [comment]
OK, I missed some of what you wrote to that guy. 

You said as long as the pipe runs, it should begin automatic playback. But its not doing that, 

Ill keep tinkering

**Comment by 1liminal1** [comment]
Right, my whole issue with the pipe is that I tried to name it after the folder. So /airplay

After I changed it to /airplay/music 

shane@AIRLOUNGE:~/airplay$ arecord -f cd -t raw > /home/shane/airplay/music
Recording raw data 'stdin' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo

It now plays! and shows up in the remote!.... Except no sound comes out haha 

So close yet so far

Any ideas about this one, hit play on the remote and nothing happens??

**Comment by 1liminal1** [comment]
AHHHHH, god dam case sensitivity haha

shane@AIRLOUNGE:~/airplay$ arecord -f cd -t wav > /home/shane/airplay/Music
Recording WAVE 'stdin' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo

All working!!

Other things I did was had a lot of permissions issues. 

Make sure you add the user you create to the audio group

Thanks so much for your help, Ill let you know if I get it working on the Zero W i Ordered :)

**Comment by ejurgensen** [comment]
Good to hear you got it working, and also increased your Linux skills along the way.

Any particular reason you reopened the issue?

**Comment by 1liminal1** [comment]
Sorry mate, one more thing. 

MPD, curl commands? Any guides you know about.

All I want to do is volume up and down and connect to the different Airplay Devices 

Also, DO NOT press next on the remote, crashes the whole thing requiring a reboot it seems lol

And thanks for this great software,

**Comment by ejurgensen** [comment]
Curl is hardcore, as I mentioned MPD is easier. Google 'mpd commands' and you get them. You can use the mpc client, try running e.g. 'mpc outputs'.

I will look into that bug.

**Comment by 1liminal1** [comment]
Thank you!!!
