### ISSUE TITLE
Not really an issue but may help others with pairing iPhone

### ISSUE THREAD

**Issue by SearsPoncho** [ejurgensen/forked-daapd#380]
If you are like me and have forked-daapd on ethernet and try to connect with a wireless app like iTunes Remote, your router may not be allowing multicast between them.  I believe using that ssh connect trick you mention is a symptom of this.
On my ancient router I was able to whitelist multicast addresses under IGMP settings to get this working.  I used these values, but Apple Bonjour only uses a subset of these - I tried to just open everything up.
Multicast address                      Netmask
224.0.0.0                                  255.0.0.0
239.0.0.0                                  255.0.0.0

if you just want to open up multicast for Bonjour, this is probably a better solution 
224.0.0.251                              255.255.255.255

**Comment by ejurgensen** [comment]
Thanks a lot for this info, as you can see I have added it to the README so it is part of the documentation.
