### ISSUE TITLE
In Itunes My Music title Garbled,like Áú¾í·ç

### ISSUE THREAD

**Issue by yaogunfantuan** [ejurgensen/forked-daapd#386]
system:FreeDSB
Locale:zh_CN.UTF-8
itunes service is install my nas;FreeNas 9.10 Jail.however in my mac or windows itunes the music name "龙卷风"was garbled like.Áú¾í·ç.  so how can i fix this?i want to show chinese.

**Comment by ejurgensen** [comment]
Don't know, utf-8 should work. If you could share a file which shows up wrong I can take a look at it.

**Comment by yaogunfantuan** [comment]
i upload it，i set filename with utf-8 ,however it still error, i think may be is the ID3 is garbled.

**Comment by yaogunfantuan** [comment]
[longjuanfeng.pdf](https://github.com/ejurgensen/forked-daapd/files/1024619/longjuanfeng.pdf)
you need to change .pdf to .mp3, because can't upload mp3,so i changed  extension name

**Comment by ejurgensen** [comment]
The mp3 file doesn't seem to have any ID3 tags at all?

**Comment by yaogunfantuan** [comment]
em......... i just guess the ID3 is garbled.

**Comment by ejurgensen** [comment]
Please link to a proper file - or close the issue.
