### ISSUE TITLE
Webradio (shoutcast / icecast) metadata not being updated 

### ISSUE THREAD

**Issue by john-a-harris** [ejurgensen/forked-daapd#392]
Hi,
Having migrated from a custom built ffmpeg to ubuntu 14.04LTS libav-utils, I am now seeing some minor issues with my setup.

I am seeing messages like this in my log file:

`[2017-06-04 16:28:17] [ INFO]     http: Skipping Shoutcast metadata request for http://ice1.somafm.com/groovesalad-128.mp3 (requires libevent>=2.1.4 or libav 10)
`

And the metadata that my shairport sync devices display is not getting updated. I can see that my libevent version isn't high enough (how do I update that on Ubuntu 14.04 LTS?):

`pkg-config --modversion libevent`
`2.0.21-stable`

 but I don't know how to check the libav version (to get a version like 10 or 11 and so on).
I'm sorry if these are basic questions!
Thanks for your work on this - I use forked-daapd all day, every day for my multi-room audio - it's fantastic :)

john

**Comment by ejurgensen** [comment]
That's really good to hear!

Ubuntu 14.04 has libav 9 and libevent 2.0, so I think the options would be:
1) replace with newer ffmpeg or newer libav you build yourself, and then build forked-daapd yourself
2) find a newer, unofficial ffmpeg ubuntu package on lauchpad, and then build forked-daapd yourself
3) upgrade to 16.06

**Comment by john-a-harris** [comment]
Hi,
In the end, I went for option 2 (having tried option 3, and having to roll back after discovering that something else I rely on isn't supported on 16.06 :( ). All is now working as it should, so I am closing this issue. Thanks again for all your work - it really is appreciated!

john
