### ISSUE TITLE
Choose airport speakers with curl - script

### ISSUE THREAD

**Issue by mogensboegh** [ejurgensen/forked-daapd#396]
Hello
Thanks a lot for a brilliant tool.
I have forked-daapd set up on my raspberry pi 3 and i works excellently. I use it to start radio streaming to airport express every morning at 07:00.
It streams to the airports selected via my iphones remote app.
My question:
Can I add something to the curl statement in the initiating script to make shure it plays to chosen airports. This in the case I have chosen other airport expresses during the day via the remote app. This would ensure the "wake up play" always goes to defined airport expresses. ?

Best regards
Mogens Bøgh Mortensen

**Comment by ejurgensen** [comment]
Yes, you can do that. Instead of using curl I think you will find it easier to use the mpc tool. With "mpc outputs" you will get a list of speakers, and then you can make a script with "mpc enable xxx" and "mpc disable xxx".

**Comment by mogensboegh** [comment]
Thanks a lot for a quick reply
I will tamper with mpc then.
