### ISSUE TITLE
Errors during installation on a debian system

### ISSUE THREAD

**Issue by TribuneX** [ejurgensen/forked-daapd#398]
I am getting errors during the make and install process.

`make`

output:

> make[2]: Entering directory '/opt/forked-daapd/src'
make  all-am
make[3]: Entering directory '/opt/forked-daapd/src'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/opt/forked-daapd/src'
make[2]: Leaving directory '/opt/forked-daapd/src'
make[2]: Entering directory '/opt/forked-daapd'
make[2]: *** No rule to make target 'scripts/freebsd_install_10.1.sh', needed by 'all-am'.  Stop.
make[2]: Leaving directory '/opt/forked-daapd'
Makefile:613: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/opt/forked-daapd'
Makefile:454: recipe for target 'all' failed
make: *** [all] Error 2

`sudo make install`

output:

>   /bin/bash ../libtool   --mode=install /usr/bin/install -c forked-daapd '/usr/sbin'
libtool: install: /usr/bin/install -c forked-daapd /usr/sbin/forked-daapd
make[4]: Nothing to be done for 'install-data-am'.
make[4]: Leaving directory '/opt/forked-daapd/src'
make[3]: Leaving directory '/opt/forked-daapd/src'
make[2]: Leaving directory '/opt/forked-daapd/src'
make[2]: Entering directory '/opt/forked-daapd'
make[2]: *** No rule to make target 'scripts/freebsd_install_10.1.sh', needed by 'all-am'.  Stop.
make[2]: Leaving directory '/opt/forked-daapd'
Makefile:613: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/opt/forked-daapd'
Makefile:910: recipe for target 'install' failed
make: *** [install] Error 2

I had forked-daapd installed before. I just wanted to upgrade to the latest version in order to support tvOS 10.2 and device verification.

**Comment by ejurgensen** [comment]
Yes, just fixed it now... please pull and try again.

**Comment by TribuneX** [comment]
That was quick! It worked now. Thanks a lot!
