### ISSUE TITLE
spotify: Can't play music, not connected and logged in to Spotify

### ISSUE THREAD

**Issue by swilalaa** [ejurgensen/forked-daapd#400]
Hello,

I've installed libspotify, created a .spotify file in my library and authorized through oauth webservice.

Forked succesfully scanned my playslists and shows them within a Spotify Folder in the itunes library.

When I'm trying to select and play a song through remote I get always following error on the log:

[2017-07-07 14:03:40] [  LOG]  spotify: Can't play music, not connected and logged in to Spotify
[2017-07-07 14:03:40] [  LOG]   player: Failed to open 'spotify:track:4j7ZD7hYZha8S4IoTZcNMr' (id=4612, item-id=1)
[2017-07-07 14:03:40] [  LOG]     dacp: Could not start playback

Any ideas how to fix that?

Ideally I'd like to remotely select and play songs through the spotify connect feature.

Thanks in advance!

**Comment by ejurgensen** [comment]
What log messages did you see when you added the .spotify file? You should see something like:
"Spotify credentials file OK, logging in with username xxxx"

If the login fails you should also see some error message.

If you don't see the above message, then forked-daapd is not detecting the file. Are you adding it to a network drive? In that case look at this: https://github.com/ejurgensen/forked-daapd#your-library-is-a-network-mount

forked-daapd does not support Spotify Connect - if you just want that then https://github.com/plietar/librespot is probably a better choice.

**Comment by swilalaa** [comment]
I was adding the .spotify file too early so forked-daapd did not recognize it. Solved and now running!

Basically I'm just looking for a solution to play spotify from a pi via airplay to an AppleTV.

Unfortunately librespot does not support airplay as far as I understood. You did some great work adding that!

Many thanks again for your quick help.

**Comment by ejurgensen** [comment]
> Basically I'm just looking for a solution to play spotify from a pi via airplay to an AppleTV.

Yes, then you are the right place :-)

If you don't mind a bit of mucking around, I think librespot is able to output to a pipe, which you can then let forked-daapd play to your ATV. There will be a bit of lag, though.

**Comment by swilalaa** [comment]
I'm completely new to this so this probably will be a lot mucking around, but I will give it a try. Lag isn't an issue as I guess the commands will just take a couple of more seconds to arrive. 

Actually my main goal is to create a homebridge device which will start a dedicated playlist in spotify and stream it via Airplay to my Apple TV.

So in theory the activated Homekit "device" will then trigger a http call to play a spotify playlist via mpc and then stream it to the Apple TV.

I'll let you know about my progress :-)

Is there any donation page to spend you a couple of beer / coffee for your great work?

Cheers!

**Comment by swilalaa** [comment]
Working all pretty well together! I need a donation link 🥇
