### ISSUE TITLE
Spotify will shutdown libspotify on July 20th

### ISSUE THREAD

**Issue by snizzleorg** [ejurgensen/forked-daapd#404]
https://support.spotify.com/us/listen_everywhere/on_speaker/why-cant-i-use-the-spotify-app-on-my-speaker/

Looks to me as if forked-daapd will be affected by this since it is using lib spotify to play music - right?

**Comment by ejurgensen** [comment]
Could look like it, though it doesn't say clearly.

It really sucks that they aren't keeping their promise and providing an alternative. I'm not sure what other music services to turn to - Google Music perhaps?

**Comment by snizzleorg** [comment]
I would welcome apple music. Do they provide an API? soundcloud would also be nice.

But it seems to me that spotify is pushing their spotify connect... I have it set-up with forked-daapd via librespot. But it is not very elegant. There is a considerable delay between the spotify interface and the audio output and it is also crashing frequently... If spotty connect could be integrated into forked-daapd that might be a solution. But I think it would still be nicer to access the spotify catalogue through the remote app.

**Comment by ejurgensen** [comment]
Personally, I like to control my music from one app, be it Spotify, local audio or internet radios. But if there are no other alternatives I guess Spotify Connect could be an option. It would probably be possible to reduce lagging.

I don't think Apple Music has an API for playback, but I could be wrong. Soundcloud is probably worth checking, not sure how much of a catalogue they have.

BTW I did fix a crash bug related to pipes recently, don't know if that could have been affecting you:
https://github.com/ejurgensen/forked-daapd/commit/1549d0d4b57a9b52b0e20fd06ab8d3684598c92f

**Comment by snizzleorg** [comment]
Thanks!

In my case I think it's more librespot crashing. Anyways they have had problems with spotify authentication. So it's not working currently - however apparently they are in discussions with spotify and spotify asked for some minor changes. So my hopes are that it will be back soon.


I will try the latest git version and see if it becomes more stable.

**Comment by snizzleorg** [comment]
Apparently apple Music has the API now: https://medium.com/combo-fm/navigating-the-apple-music-ios-api-e9dd2c3ea65a

"
Stuff you can do with the Apple Music API
1. You can play tracks out Apple Music if the user is logged in and has a valid membership. And that’s rad.
2. Again, if you’re a subscriber, you can create Apple Music playlists & add tracks to them. Again, pretty sweet.
3. You may not delete anything from them. Guessing this is damage control from Apple’s side; I guess it wouldn’t be too difficult to write a couple of lines of horrible code that would wipe out any instance of My Chemical Romance from a designated playlist. And that would be terrible.
"

**Comment by ejurgensen** [comment]
Seems we are still good - for now, at least
