### ISSUE TITLE
getting started with Remote documentation incomplete

### ISSUE THREAD

**Issue by rainerstandke** [ejurgensen/forked-daapd#407]
I believe this this paragraph should include a description of what to do with the device name:

> Prepare a text file with a filename ending with .remote; the filename doesn’t matter, only the .remote ending does. This first line in the file must contain the 4-digit pairing code displayed by Remote.

This pertains to this page: http://ejurgensen.github.io/forked-daapd/

**Comment by ejurgensen** [comment]
For current master and the coming release, the instructions are correct. I have added a note with a link to the old instructions here http://ejurgensen.github.io/forked-daapd/#using-remote for users using older versions of forked-daapd.
