### ISSUE TITLE
no playback

### ISSUE THREAD

**Issue by Supersimo88** [ejurgensen/forked-daapd#411]
I just installed the Openmediavault plugin on an odroid xu-4 and this is the error I get in the log file

[2017-08-07 15:57:10]   player: Cannot start playback: no output started
[2017-08-07 15:57:10]     dacp: Could not start playback
[2017-08-07 16:27:17]     raop: Could not make OPTIONS request
[2017-08-07 16:27:17]     raop: OPTIONS request failed in session startup: 403 Forbidden

**Comment by ejurgensen** [comment]
What device are you trying to play to? Looks like it could be an Apple TV4 that requires device verification? The good news: forked-daapd supports this. The bad news: your version of forked-daapd is not recent enough to have this support (you will need version 25.0).

**Comment by Supersimo88** [comment]
i can't select the output device, Apple TV4 and computer, i can try to select one of that but nothing happens.
So i need to update forked-daapd on my openmediavault server?

**Comment by ejurgensen** [comment]
Yes, you need to update. I don't know anything about that platform, so I can't tell you how to do it.
