### ISSUE TITLE
Use HTTP put requests to connect to airplay devices 

### ISSUE THREAD

**Issue by 1liminal1** [ejurgensen/forked-daapd#415]
I know I've been asking about this for a long time, but I think not really been asking the right questions.

I want to use a HTTP Put request to connect to an Airplay device (and disconnect and control volume).

http://www.tuneblade.com/developer/TuneBlade%20Remote%20API%20v0.8.pdf

I have this working using Tuneblade remote API, but it requires a PC running, I want to use a Pi Zero and forked-daapd.. 

So the put request looks like this; 

http://192.168.1.50:6500/devices/00XXXXXXXX@Upstairs

with a http body of; 

{"Status": "Connect"}

or 

{"Status": "Disconnect"}

Its pretty simple.

Can forked-daapd do this?

**Comment by roblan** [comment]
You can already do this with dacp - login, getspekaers, setspeakers and logout
Although you must have daap/dacp parser to decrypt getspeakers

**Comment by ejurgensen** [comment]
It seems what you are asking about is if forked-daapd supports the Tuneblade Remote API, as you linked to. So not to use HTTP Put to connect to Airplay devices. I have corrected the title of your issue.

forked-daapd does not support the Tuneblade remote API, and I don't plan that it should.

As roblan says, you use dacp for remote control. You can also use mpd commands. Neither of these are HTTP Put, however.

**Comment by 1liminal1** [comment]
Hi there, 

Sorry, that's not what I'm saying at all, of course, it's completely different software. 

I'm asking if it does something similar, can I use simple HTTP requests, like the above, to control my airplay devices. 

I provided the above example of of how the tune-blade API works, hopefully someone can give me an example of how DACP or whatever is easier?

**Comment by 1liminal1** [comment]
> You can already do this with dacp - login, getspekaers, setspeakers and logout
Although you must have daap/dacp parser to decrypt getspeakers

> 

Thats great, but can you provide me an example of what that would look like? Like I provided the tuneblade example?

Thanks

**Comment by roblan** [comment]
```
curl "http://localhost:3689/login?pairing-guid=0x1&request-session-id=50"
curl "http://localhost:3689/ctrl-int/1/getspeakers?session-id=50"
curl "http://localhost:3689/ctrl-int/1/setspeakers?speaker-id=0xf0efab8c5d21,0x76fbf0ccd7fc&session-id=50"
curl "http://localhost:3689/logout?session-id=50"
```

The only tricky part is getting speaker ids, as returned data is not "plain text".
You could use https://github.com/mattstevens/dmap-parser or if you know a little nodejs even a https://github.com/roblan/daap-client which should simplify things a little bit.

**Comment by 1liminal1** [comment]
This is a real help, really, finally I can get an idea of where to start. 

I actually have the speaker IDs from Tuneblade, but these are not just static commands right?

So these curl commands, it creates a session with an ID of 50, does that need to be different every time?
Then it gets the speakers
Then connects to two of those speakers 
Then ends the session.

I will get this to work, if its the last thing I ever do haha

Thanks again!

**Comment by roblan** [comment]
As far as I know - the requested session-id can be the same every time.
I don't know if those speaker ids are the same every time though. If they are - then there is no need getting them every time.

**Comment by ejurgensen** [comment]
Yes, you can use the same session id, but use one that is less than 100 (as mentioned in the [README](http://ejurgensen.github.io/forked-daapd/#command-line-and-web-interface)).

The speaker ids generally do not change.

**Comment by 1liminal1** [comment]
Hi guys, 

Ok, I read the readme, installed sqlite3 and tried to get the title of some playlists, but im doing something wrong?

`pi@AirServer:/var/cache/forked-daapd $ sqlite3 songs3.db
SQLite version 3.8.7.1 2014-10-29 13:59:56
Enter ".help" for usage hints.
sqlite> select id,title from playlists
   ...>
`

So if I'm reading this right, your saying I can get the IDs for the Outputs?

select id,title from outputs

Anyway, cant get it to show me anything yet :)

**Comment by roblan** [comment]
I'm not sure why SQLite is even mentioned here as it has nothing to do with the speakers (?)

**Comment by ejurgensen** [comment]
You probably already found out that you were missing a semicolon. You can find the speaker id with "select * from speakers;". The above is for playlists.

**Comment by 1liminal1** [comment]
LOL, I really dont have a lot of luck with these things. 

@roblan I need the speaker IDs to connect to

@ejurgensen I cant open the DB, I stopped forked-daapd

```pi@AirServer:/var/cache/forked-daapd $ sudo /etc/init.d/forked-daapd stop
[ ok ] Stopping forked-daapd (via systemctl): forked-daapd.service.
pi@AirServer:/var/cache/forked-daapd $ sqlite3 songs.db
SQLite version 3.8.7.1 2014-10-29 13:59:56
Enter ".help" for usage hints.
sqlite> .table
Error: unable to open database "songs.db": unable to open database file
pi@AirServer:/var/cache/forked-daapd $ sqlite3 songs.db
SQLite version 3.8.7.1 2014-10-29 13:59:56
Enter ".help" for usage hints.
sqlite> select * from speakers;
Error: unable to open database "songs.db": unable to open database file```
