### ISSUE TITLE
remote pairing documentation instructions slightly misleading

### ISSUE THREAD

**Issue by ajax3712** [ejurgensen/forked-daapd#417]
> Prepare a text file with a filename ending with .remote; the filename doesn't matter, only the .remote ending does. This first line in the file must contain the 4-digit pairing code displayed by Remote.

Should be instead something like:

Prepare a text file with a filename ending with .remote; the filename doesn't matter, only the .remote ending does. This first line in the file must contain the name of your device (Foobar in this example). The second line of the file must contain the 4-digit pairing code displayed by Remote.

**Comment by ejurgensen** [comment]
The instructions are correct, it's because you are using an older version, where the device name was required. I will update the instructions to mention this.
