### ISSUE TITLE
Problems with TvOS 11

### ISSUE THREAD

**Issue by anjo03** [ejurgensen/forked-daapd#422]
My Apple TV4 just auto-upgraded to TvOS 11 and the connection to forked-daapd is not broken.
When trying to active it as an output it says this:

[root@server01 ~]# mpc enable 45970
mpd error: Speakers activation failed: 45969
[root@server01 ~]# mpc outputs

No pairing requests or anything else shows on the TV.
Am I doing something wrong or did Apple block this one again?

**Comment by ejurgensen** [comment]
Oh boy, not again.

I don't have a ATV4, and my ATV3 is still working, so can you set the log level to debug and try again? Then post a snippet of the part where you try to select the device.

I would also like to know what the line "Adding AirPlay device ........" says.

**Comment by anjo03** [comment]
Is your Apple TV3 updated to TvOS 11?

 

/Anders

**Comment by ejurgensen** [comment]
No, it can't be updated to tvOS11

**Comment by anjo03** [comment]
I will check tonight, when I come home.

 

/Anders

**Comment by anjo03** [comment]
OK, just tested and got the following debug output:

 

 

[root@server01 ~]# /usr/local/forked-daapd/sbin/forked-daapd -d 5 -f -D raop

[DEBUG]     raop: Timing IPv6 port: 42232

[DEBUG]     raop: Timing IPv4 port: 48936

[DEBUG]     raop: Control IPv6 port: 52677

[DEBUG]     raop: Control IPv4 port: 57864

[DEBUG]     raop: Event for AirPlay device RASPI (port 5000, id c3e9dab419d7)

[ INFO]     raop: Adding AirPlay device C3E9DAB419D7@RASPI: password: 0, verification: 0, encrypt: 1, metadata: 1, type AirPort Express 1 - 802.11g, address 192.168.0.5:5000

[DEBUG]     raop: Event for AirPlay device Tv-stue (port 7000, id c869cd5db391)

[ INFO]     raop: AirPlay C869CD5DB391@Tv-stue: no pw field in TXT record, assuming no password protection

[ INFO]     raop: Adding AirPlay device C869CD5DB391@Tv-stue: password: 0, verification: 1, encrypt: 0, metadata: 1, type AppleTV4, address 192.168.0.11:7000

 

 

 

 

 

 

[DEBUG]     raop: Building OPTIONS for 'RASPI'

[DEBUG]     raop: Local address: 192.168.0.1 (LL: no) port 36148

[DEBUG]     raop: Building ANNOUNCE for 'RASPI'

[DEBUG]     raop: Building SETUP for 'RASPI'

[DEBUG]     raop: token: unicast

[DEBUG]     raop: token: interleaved

[DEBUG]     raop: token: 0-1

[DEBUG]     raop: token: mode

[DEBUG]     raop: token: record

[DEBUG]     raop: token: control_port

[DEBUG]     raop: token: timing_port

[DEBUG]     raop: token: server_port

[DEBUG]     raop: Negotiated AirTunes v2 UDP streaming session 1; ports s=6001 c=6002 t=6003

[DEBUG]     raop: Building RECORD for 'RASPI'

[DEBUG]     raop: RAOP audio latency is 11025

[DEBUG]     raop: Building SET_PARAMETER for 'RASPI'

 

 

 

 

[ INFO]     raop: Failed to retrieve artwork for file id 1; no artwork will be sent

[DEBUG]     raop: Building SET_PARAMETER for 'RASPI'

[DEBUG]     raop: Building SET_PARAMETER for 'RASPI'

[DEBUG]     raop: Building POST for 'Tv-stue'

[ INFO]     raop: Making verification request step 4 to 'Tv-stue'

[DEBUG]     raop: Building POST for 'Tv-stue'

[ INFO]     raop: Making verification request step 5 to 'Tv-stue'

[ INFO]     raop: Verification of 'Tv-stue' completed succesfully

[DEBUG]     raop: Building OPTIONS for 'Tv-stue'

[DEBUG]     raop: Local address: 192.168.0.1 (LL: no) port 48756

[DEBUG]     raop: Building ANNOUNCE for 'Tv-stue'

[DEBUG]     raop: Building SETUP for 'Tv-stue'

[DEBUG]     raop: token: unicast

[DEBUG]     raop: token: mode

[DEBUG]     raop: token: record

[DEBUG]     raop: token: server_port

[DEBUG]     raop: token: control_port

[DEBUG]     raop: token: timing_port

[  LOG]     raop: Transport header lacked some port numbers in SETUP reply

[  LOG]     raop: Transport header was: RTP/AVP/UDP;unicast;mode=record;server_port=62638;control_port=56409;timing_port=0

[DEBUG]     raop: Building TEARDOWN for 'Tv-stue'

 

 

/Anders

**Comment by ejurgensen** [comment]
Ok, seems it is not announcing a timing port, but it looks like forked-daapd doesn't actually need it.

Are you building yourself? Then it would be great if you could check this branch out: https://github.com/ejurgensen/forked-daapd/tree/atv4_test1

In the branch, I've made a small change so forked-daapd will ignore the missing timing port.

**Comment by anjo03** [comment]
I am, so will try to compile from this branch and test it. 

Will get back to you soon.

 

/Anders

**Comment by anjo03** [comment]
I pulled the normal branch and applied the changes to raop.c as stated here:

 

https://github.com/ejurgensen/forked-daapd/commit/5de5a37f2809b4dac0cca7d3c141aea8c93f90ce#diff-19996faa07af1006b0609feaa21a0f21

 

It works perfectly now ☺

Thanks for a quick fix!!

 

/Anders

**Comment by ejurgensen** [comment]
Great, I have put the fix into master. Happy that there wasn't more to it - this time...

@rbalint I guess this fix would be nice to get into Debian pretty quickly. What would be the best way to do that? Should I make a 25.0.1-branch which would equal version 25.0 plus this commit?

**Comment by rbalint** [comment]
@ejurgensen I can just pick a patch without needing a new release. Do you have other patches in mind to pick for a package update?

**Comment by ejurgensen** [comment]
@rbalint I can't think of any other patches, I think the rest can wait to the next release

**Comment by rbalint** [comment]
I just cherry-picked to patch to 25.0-2.

**Comment by swilalaa** [comment]
@ejurgensen Thanks again for the quick finding! when will this update be available?
