### ISSUE TITLE
forked-daapd on top of an existing MPD

### ISSUE THREAD

**Issue by inquisition** [ejurgensen/forked-daapd#425]
Hello,

I have an MPD service (moOde audio player) running on my Raspberry and I would like to control moOde MPD using the iTunes Remote app on iOS. So I was thinking to install forked-daapd and using it to control my existing MPD install and its existing music library. Is such thing possible?

Thanks!
Arnaud

**Comment by ejurgensen** [comment]
No, forked-daapd cannot control another service. As you may know, forked-daapd comes with its own mpd service.
