### ISSUE TITLE
Unable to create db

### ISSUE THREAD

**Issue by chucksense** [ejurgensen/forked-daapd#429]
I get the following error on startup:
> db: Could not open database: unable to open database file

I deleted the database file, cache file, then even tried deleting the entire `/var/cache/forked-daapd` directory and still I get this error.

**Comment by LordMyschkin** [comment]
Are you sure you got the correct permissions in the directory?

**Comment by chucksense** [comment]
I'm not sure what it's supposed to be, but I tried switching directory to 777 and it still failed.

**Comment by ejurgensen** [comment]
How did you install forked-daapd? Depending on that it might be /usr/local/var/cache/forked-daapd that you should check permissions of.

**Comment by chucksense** [comment]
I followed the compilation instructions in [INSTALL](https://github.com/ejurgensen/forked-daapd/blob/master/INSTALL).  I'm running Ubuntu 17.10.

`/usr/local/var/cache` doesn't exist.

**Comment by ejurgensen** [comment]
It's actually silly that the path isn't logged by forked-daapd, makes troubleshooting a lot more tricky. So now I made commit #79b2cf4 which should mean you get the actual path in the log.

Can you try pulling from master, build again, run and then check the permissions on the path that appears in the log?

**Comment by chucksense** [comment]
I removed, reinstalled, and then `chown`'d the `/var/cache/forked-daapd/` directory to user `daapd` and everything is working once more.  Closing, thank you for the assistance!

**Comment by nguyendj** [comment]
> I removed, reinstalled, and then `chown`'d the `/var/cache/forked-daapd/` directory to user `daapd` and everything is working once more. Closing, thank you for the assistance!

Sorry to open this topic again, I'm not IT guide so Can you guide me how to set permission to folder /var/cache/forked-daapd in the right way

**Comment by Toby-Haynes** [comment]
To explicitly set the permissions of /var/cache/forked-daapd and all files and directories within to the `daapd` UID with `nogroup` GID. Switch to root user and

`chown -R daapd:nogroup /var/cache/forked-daapd`
