### ISSUE TITLE
forked-daapd core-dumps on exit

### ISSUE THREAD

**Issue by vbonline** [ejurgensen/forked-daapd#430]
log after systemctl stop forked-daapd.service:

Oct 30 21:21:42 castle systemd[1]: Stopping DAAP/DACP (iTunes), RSP and MPD server, supports AirPlay and Remote...
Oct 30 21:21:42 castle forked-daapd[20391]: [  LOG]     main: Got SIGTERM or SIGINT
Oct 30 21:21:42 castle forked-daapd[20391]: [  LOG]     main: Stopping gracefully
Oct 30 21:21:42 castle forked-daapd[20391]: [  LOG]     main: mDNS deinit
Oct 30 21:21:42 castle forked-daapd[20391]: [  LOG]     main: Remote pairing deinit
Oct 30 21:21:42 castle forked-daapd[20391]: [  LOG]     main: MPD deinit
Oct 30 21:21:42 castle systemd[1]: forked-daapd.service: Main process exited, code=dumped, status=11/SEGV
Oct 30 21:21:42 castle systemd[1]: Stopped DAAP/DACP (iTunes), RSP and MPD server, supports AirPlay and Remote.
Oct 30 21:21:42 castle systemd[1]: forked-daapd.service: Unit entered failed state.
Oct 30 21:21:42 castle systemd[1]: forked-daapd.service: Failed with result 'core-dump'.

System sets the service to failed after that and doesn't restart it after a reboot. A manual systemctl start forked-daapd.service starts without failure.

Version:

[2017-10-30 21:24:03] [  LOG]     main: Forked Media Server Version 25.0 taking off
[2017-10-30 21:24:03] [  LOG]     main: Built Oct 23 2017 with:
[2017-10-30 21:24:03] [  LOG]     main: - ffmpeg
[2017-10-30 21:24:03] [  LOG]     main: - iTunes XML
[2017-10-30 21:24:03] [  LOG]     main: - MPD
[2017-10-30 21:24:03] [  LOG]     main: - Device verification
[2017-10-30 21:24:03] [  LOG]     main: - ALSA

**Comment by ejurgensen** [comment]
Fixed, thanks for reporting the error.

**Comment by gerroon** [comment]
same on Debian Buster Systemd

**Comment by ejurgensen** [comment]
Can you provide a way of reproducing the error you observe in Debian Buster? If so then please open a new issue on that. I just tried (with the version of forked-daapd from the Debian repo, so 26.4+dfsg1-1) and it seemed ok, but I just made a pretty minimal test.

**Comment by gerroon** [comment]
I will thanks
