### ISSUE TITLE
Problems building v25 

### ISSUE THREAD

**Issue by john-a-harris** [ejurgensen/forked-daapd#434]
Hi,

I am seeing the error below when trying to build v25 (and the latest version too, for that matter). I am running ubuntu 14.04. I configured with the following:

./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-spotify

Please let me know what other information would be useful to figure out what's going on...

Thanks for all the awesome work that goes into this

depbase=`echo outputs/raop_verification.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
        gcc -DHAVE_CONFIG_H -I. -I..  -Wall -D_THREAD_SAFE -D_REENTRANT -I/usr/local/include   -D_REENTRANT -I/usr/include/json-c -pthread -I/usr/include/libxml2 -I/usr/include/alsa  -D_GNU_SOURCE -DDATADIR=\"/usr/share/forked-daapd\" -DCONFDIR=\"/etc\" -DSTATEDIR=\"/var\" -DPKGLIBDIR=\"/usr/lib/forked-daapd\"   -g -O2 -MT outputs/raop_verification.o -MD -MP -MF $depbase.Tpo -c -o outputs/raop_verification.o outputs/raop_verification.c &&\
        mv -f $depbase.Tpo $depbase.Po
outputs/raop_verification.c: In function ‘encrypt_gcm’:
outputs/raop_verification.c:788:51: error: ‘GCRY_CIPHER_MODE_GCM’ undeclared (first use in this function)
   ret = gcry_cipher_open(&hd, GCRY_CIPHER_AES128, GCRY_CIPHER_MODE_GCM, 0);
                                                   ^
outputs/raop_verification.c:788:51: note: each undeclared identifier is reported only once for each function it appears in
outputs/raop_verification.c:809:3: warning: implicit declaration of function ‘gcry_cipher_gettag’ [-Wimplicit-function-declaration]
   ret = gcry_cipher_gettag(hd, tag, AUTHTAG_LENGTH);
   ^
make[3]: *** [outputs/raop_verification.o] Error 1
make[3]: Leaving directory `/home/john/forked-daapd-latest/src'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/john/forked-daapd-latest/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/john/forked-daapd-latest'
make: *** [all] Error 2

**Comment by ejurgensen** [comment]
Looks like Ubuntu 14.04 might come with an old version of libgcrypt that does not support "GCRY_CIPHER_MODE_GCM"? I also think 14.04 doesn't have libsodium, which I would imagine configure complained about? Maybe you installed it manually?

If you won't be needing support for Apple device verification then the easiest solution is to just disable it (so add --disable-verification to the configure arguments). Otherwise I suppose you will need to upgrade libgcrypt.

**Comment by john-a-harris** [comment]
It seems that way. I did manage to add libsodium from an external repository. Is Apple device verification only required for Apple TV? If yes, then I'll skip it for now. I can imagine that an off-piste upgrade of libgcrypt may not be trivial. Thanks again!



-----Original message-----

**Comment by ejurgensen** [comment]
Yes, it is only required by Apple TV 4.
