### ISSUE TITLE
Died silently when trying to activate Chromecast

### ISSUE THREAD

**Issue by yantoz** [ejurgensen/forked-daapd#455]
forked-daapd died silently when trying to activate chromecast sink, leaving nothing in the log after [DEBUG]   player: Activating Chromecast device '...' before it dies.

I pin pointed the issue happened when it was going through interfaces to find a family match.
For whatever reason, my system has null pointer in between the list, so blindly dereference it will result in segmentation fault. 

Skipping it seems to fix the issue.

~~~~
diff --git a/src/outputs/cast.c b/src/outputs/cast.c
index de9ff39e..f028c460 100644
--- a/src/outputs/cast.c
+++ b/src/outputs/cast.c
@@ -457,6 +457,10 @@ stream_url_make(char *out, size_t len, const char *peer_addr, int family)
   getifaddrs(&ifap);
   for (ifa = ifap; !found && ifa; ifa = ifa->ifa_next)
     {
+      if (!ifa->ifa_addr) {
+       DPRINTF(E_LOG, L_CAST, "Skipping null pointer\n");
+       continue;
+      }
       if (ifa->ifa_addr->sa_family != family)
        continue;
~~~~

**Comment by ejurgensen** [comment]
Thanks a lot, especially for also doing the debugging. I've added the fix + also missing check of getifaddrs() return value.
