### ISSUE TITLE
Artwork for Radio playlists and Shairport-Sync not displayed/retransferred?

### ISSUE THREAD

**Issue by we5** [ejurgensen/forked-daapd#456]
Hi,

this is more of a question rather than a problem, because I assume I have something missed with the configuration or capabilities:

There is no single cover/artwork showing up in the iOS Remote app for neither a stream provided via Shairport-Sync (Music.app@iPhone -> Shairport-Sync -> forked-daapd -> Remote.app@iPad) or a radio played directly through forked-daapd.

I also can think of a problem with shairport-sync, however I am seeing some metadata coming into the metadata pipe. Is this just me?

**Comment by ejurgensen** [comment]
forked-daapd doesn't (yet) have support for artwork from Shairport Sync pipes - only text metadata.

It will get artwork from radio stations if they provide links to the images in the stream's ICY metadata. Many radio stations don't, however, so for those forked-daapd would have to get the artwork from a third party artwork library. Never got around to doing that, maybe one day...
