### ISSUE TITLE
forked-daapd json api to control connection to speakers

### ISSUE THREAD

**Issue by 1liminal1** [ejurgensen/forked-daapd#462]
Hey guys, 

I've had the makers of HA Bridge reply to my long standing query to communicate to forked-daapd using an Echo Dot and they advise;  

```
Looked at this a bit, if you can manage multiple calls you could use the forked-daapd json api with http calls. I did not find the api spec for the json calls.
```

Is this possible? Is there any info on this?

**Comment by ejurgensen** [comment]
I think it depends on what kind of control you are looking for. Is it speaker selection and volume?

The json api is a pretty new creation by @chme - he might be able to key you into how you can use it. I think you can see the basic commands here: https://github.com/ejurgensen/forked-daapd/blob/master/src/httpd_jsonapi.c#L981

**Comment by 1liminal1** [comment]
Hey, 

Yeah that's it... still trying to do the same thing lol. Trying to use an Echo dot to control speaker selection and the volume though something like HA Bridge.

**Comment by 1liminal1** [comment]
@chme Could you please give me some idea if this can be done? Would be great!

Thanks

**Comment by chme** [comment]
Hi @1liminal1,

it can probably be done, but i have zero experience with home automation. I think, some users have achieved this using the mpd protocol.

Here are some informations for the speaker/output json api endpoints:
 
Return the list of available speakers/outputs: `http://[ip-address]:3689/api/outputs`

```
{
  "outputs": [
    {
      "id": "132809939795710",
      "name": "Kueche",
      "type": "AirPlay",
      "selected": false,
      "has_password": false,
      "requires_auth": false,
      "needs_auth_key": false,
      "volume": 10
    },
    {
      "id": "198018693182577",
      "name": "Wohnzimmer",
      "type": "AirPlay",
      "selected": false,
      "has_password": false,
      "requires_auth": false,
      "needs_auth_key": false,
      "volume": 50
    },
    {
      "id": "0",
      "name": "Computer",
      "type": "ALSA",
      "selected": true,
      "has_password": false,
      "requires_auth": false,
      "needs_auth_key": false,
      "volume": 7
    },
    {
      "id": "100",
      "name": "daapd-fifo",
      "type": "fifo",
      "selected": false,
      "has_password": false,
      "requires_auth": false,
      "needs_auth_key": false,
      "volume": 50
    }
  ]
}
```

Setting the master volume: `http://[ip-address]:3689/api/player/volume?volume=50`
Setting the volume of an individual speaker/output: `http://[ip-address]:3689/api/player/volume?volume=50&output_id=0`
(Volume range is 0-100 and output_id is the id given in /api/outputs)

Changing selected speakers/outputs: `http://[ip-address]:3689/api/select-outputs`
This has to be a POST request with the body holding the speaker/output ids that should be active.

```
{"outputs":["132809939795710","0"]}
```

**Comment by snizzleorg** [comment]
This sounds pretty nice. Is this already in the master branch?

**Comment by chme** [comment]
Yes, it is already in git master.

**Comment by snizzleorg** [comment]
Cool. Will try once I get some time.

**Comment by 1liminal1** [comment]
Lot of people have told me about the MPD route, but it doesn't work with HA-Bridge. This looks far more promising. 

Ill try it in the next few days. 

Thanks for taking the time to send the info :)

**Comment by 1liminal1** [comment]
@snizzleorg did you get a look @ this yet? 

Im getting bad request on the request for outputs

http://[ip-address]:3689/api/outputs

It should just show me in a browser right guys?

**Comment by ejurgensen** [comment]
It should work in a browser. How recent is your build of forked-daapd? It is not so long ago since this feature was added.

**Comment by snizzleorg** [comment]
I haven't tried yet. I'm currently not running the github version but a the packaged version (deb http://www.gyfgafguf.dk/raspbian jessie/armhf/). I'm currently not able to get forked-daapd to compile with spotty etc because of some dependency problems... As soon as I can fix this I will try to run the most recent version.

**Comment by snizzleorg** [comment]
I'm currently using: 25.0.62.gitb71b324-1.
Does this version already has the json api?

**Comment by ejurgensen** [comment]
No, that is too old. You should at least get the newest RPi build (64). Follow these instructions:
https://www.raspberrypi.org/forums/viewtopic.php?t=49928

I'm not sure even that build is recent enough for your needs, but should that be the case I can make a new build that you can easily get via an apt upgrade (when you have added the repo as described).

**Comment by snizzleorg** [comment]
Thats exactly what I currently use. So the build via the above forum post is too old..

**Comment by ejurgensen** [comment]
Sorry, should have elaborated: You are also using an old version of the repo (deb http://www.gyfgafguf.dk/raspbian jessie/armhf/), so you need to change that following the above mentioned instructions. You will note that the path is slightly different now.

I had to change repo address to support Stretch, and I don't know of any way of telling the user through apt that the repo has moved (maybe there is one... will check that later).

**Comment by snizzleorg** [comment]
Thanks. I probably should have read the thing.... Now I'm on (25.0.64.git04dc595-1).

But I still get 

```
curl http://192.168.178.94:3689/api/outputs
<html><head><title>401 Unauthorized</title></head><body>Authorization required</body></html>
```

**Comment by ejurgensen** [comment]
Pushed the planned release 65 a bit ahead, so now you can get that with an apt update + upgrade. That should work for your goal.

If you still get Unauthorized then check in the config file that "trusted_networks" in the config file is commented out (or entirely absent), so that you are using the default. Also try with a browser and check that it doesn't prompt you for authorization.

**Comment by snizzleorg** [comment]
cool. Thanks. maybe I was trying too fast but i get:
```
W: Failed to fetch http://www.gyfgafguf.dk/raspbian/forked-daapd/dists/jessie/contrib/binary-armhf/Packages  Hash Sum mismatch```

when doing ```apt-get update```

**Comment by ejurgensen** [comment]
Dunno, seems to work ok here. Googling the error provides a bunch of suggestions, e.g.:
https://askubuntu.com/questions/41605/trouble-downloading-packages-list-due-to-a-hash-sum-mismatch-error

**Comment by 1liminal1** [comment]
Just updated to the latest version, set the local network and I am now able to get the Curl to work (or in a browser) But strangely the admin console does not work in Chrome. Edge is displaying ok. 

Little confused about the versioning its saying on the dashboard 

forked-daapd - version 25.0

**Comment by snizzleorg** [comment]
@ejurgensen Thanks! it is working. However I still have to authenticate, even when on the same network. trusted_networks is entirely absent in my config.

**Comment by snizzleorg** [comment]
I must also say what a great thing to have. The web interface looks very nice as well. Thanks for all that work!

**Comment by snizzleorg** [comment]
@chme looking at how the api works it is currently not possible to enable/disable a specific speaker without also setting the state of the others? the son has to contain the ids of all speakers to be enabled/disabled? It would be good to be able to switch a specific speaker without affecting the state of the others.

**Comment by chme** [comment]
> it is currently not possible to enable/disable a specific speaker without also setting the state of the others?

Yes, that's true. What do you think of something like:

```
http://<ip>:3689/api/outputs/enable?id=<speaker-id>
http://<ip>:3689/api/outputs/disable?id=<speaker-id>
http://<ip>:3689/api/outputs/select?ids=<speaker-id>
```

We could then also support enable/disable by speaker name 

```
http://<ip>:3689/api/outputs/enable?name=<speaker-name>
http://<ip>:3689/api/outputs/disable?name=<speaker-name>
http://<ip>:3689/api/outputs/select?names=<speaker-name>
```

> As far as I can see I can only set it at the moment.

That's true as well. Maybe omitting the "volume" parameter could be interpreted as a request to read the volume.

```
http://<ip>:3689/api/player/volume
http://<ip>:3689/api/player/volume?output_id=0
```

We could also use different request methods. PUT to change the volume and GET to read it.

**Comment by snizzleorg** [comment]
I’m impartial. All of the above would be fine from my point of view...

**Comment by snizzleorg** [comment]
Looking at home-assistant again it would be good if the api would be behaving like described here: https://home-assistant.io/components/switch.rest/

**Comment by snizzleorg** [comment]
And here: https://home-assistant.io/components/sensor.rest/

**Comment by chme** [comment]
@snizzleorg I started implementing it and documented what i am going for in: https://github.com/chme/forked-daapd/blob/jsonapi_outputs/README_JSON_API.md#outputs--speakers

**Comment by snizzleorg** [comment]
the link should be this: https://github.com/chme/forked-daapd/blob/master/README_JSON_API.md
- right?

**Comment by snizzleorg** [comment]
This is not yet  merged - right? Would be great to test this but I'm hesitating a bit to screw up my working forked-daapd system (via apt) since it is used mostly all day....

**Comment by chme** [comment]
The change is already merged (it was a part of #490), so the correct link to the documentation is now https://github.com/ejurgensen/forked-daapd/blob/master/README_JSON_API.md

I think, @ejurgensen has plans to release a new version in the near future.

**Comment by snizzleorg** [comment]
@ejurgensen thanks for the release. Can you also push it to the repo?

**Comment by ejurgensen** [comment]
Done :-)

**Comment by snizzleorg** [comment]
Thanks!
