### ISSUE TITLE
Pipe autostart fails until restart if ignored

### ISSUE THREAD

**Issue by jshep321** [ejurgensen/forked-daapd#465]
Hi, 
The (shairport-sync) pipe autostart is ignored if something is already playing.  Even if I stop the player, the autostart is not detected until I restart forked-daapd.

**[  LOG]   player: Data arrived on pipe '/home/pi/music/rx1' - ignoring, player is busy**

Personally, I'd assume that a newly arrived pipe takes precedence over the background--I'm only going to source something new if I'm ready to change. 

Workaround:  It does work again once I select the pipe name from the list in Remote.  After selecting this, the autostart works again, regardless of selected song as long as it is paused.

This could be a bug or feature, depending on your preferred operation method. :)

**Comment by ejurgensen** [comment]
I can see I [quite deliberately made it like this](https://github.com/ejurgensen/forked-daapd/blob/master/src/inputs/pipe.c#L505), even knowing there would be this problem. However, I agree with you that it would seem ok to just start playing the pipe, and I can't remember why I chose not to do that.

So I will try changing it and test to see if there are some problems I have forgotten about.

**Comment by ejurgensen** [comment]
I've now changed it so that data written to a pipe will autostart playback, even if playback is already running. I tested a bit, and it seemed to work ok. Let me know if you find otherwise.
