### ISSUE TITLE
Support for POSIX ACL

### ISSUE THREAD

**Issue by groinwood** [ejurgensen/forked-daapd#474]
I'm using forked-daapd 24.2 on Debian Stretch. In my situation I do have to use POSIX ACL. The medialibrary is used by several processes and it is also available by a samba share which is maintained from windows ACL.

I don't know if it is a bug or a missing feature, but I stumbled at the problem that forked-daapd does not honour the extended ACL's. Well, it does honour when only a named user equal to the user of the forked-daapd process (daapd) is listed. But when a default ACL is added, forked-daapd cannot access the directory anymore.

When I do login/su as the user daapd, I can enter the directory just fine.

Forked-daapd behaves like expected on minimal ACL's. When changing the owner of the directory with extended ACL's to user daapd, forked-daapd enters the directory. This is also when the group is changed to a group where daapd is a member of this group.

Expected behaviour is that the proces honours the named user permissions and enters the directory according to the permissions and like a su to daapd makes it possible to enter the directory.

I have created a VM to reproduce this behaviour. The following examples are from this VM

Example of ACL where forked-daapd can enter the directory:
```
vm31:/srv# getfacl music
# file: music
# owner: root
# group: root
user::rwx
user:daapd:rwx
group::r-x
mask::rwx
other::---
```

Previous example where a default ACL is added:
```
vm31:/srv# setfacl -d -m u:daapd:rwx music
vm31:/srv# getfacl music
# file: music
# owner: root
# group: root
user::rwx
user:daapd:rwx
group::r-x
mask::rwx
other::---
default:user::rwx
default:user:daapd:rwx
default:group::r-x
default:mask::rwx
default:other::---
```

The log says right after adding the default ACL:
```
[  LOG]     scan: Directory access to '/srv/music' failed: Permission denied
```

Switch to user daapd. The user can enter the directory.
```
vm31:/srv# su - daapd
daapd@vm31:~$ cd /srv/music
daapd@vm31:/srv/music$ ls -al
total 16
drwxrwx---+ 4 root root 4096 Dec 26 22:04 .
drwxr-xr-x  3 root root 4096 Dec 26 21:02 ..
-rw-r--r--  1 root root    0 Dec 26 21:57 .full-rescan
-rw-rw----+ 1 root root    0 Dec 29 21:25 .init-rescan
drwxrwx---+ 2 root root 4096 Dec 26 21:34 test
drwxrwx---+ 2 root root 4096 Dec 26 21:47 test2
```

**Comment by ejurgensen** [comment]
Don't know much about these ACL's, but from the source I can see that the call to euidaccess(path, (R_OK | X_OK)) is returning access denied. I don't recall why forked-daapd is checking for executable rights. I also don't know if euidaccess() needs special care when dealing with ACL's... a quick Google did not provide an answer.

In any case, euidaccess() is only used by forked-daapd when directory or file attributes change. What happens if you just restart forked-daapd after setting the ACL you want? Do you get some other error message?

**Comment by groinwood** [comment]
After the restart of forked-daapd the directory with a default ACL is accessible again by forked-daapd in above described example. 

The same applies also for adding new items to the library. It results in a Permission Denied error. After a restart of forked-daapd, the new items are added to the library and can be streamed.

**Comment by ejurgensen** [comment]
I've tried to recreate your setup, but I need a bit of help. I am just getting "Permission denied", even when just trying to enter the directory through command line. I notice you have this `user:daapd:rwx`, which I don't get when I run getfacl on the directory. I also don't get the mask line. What am I missing?

I did find some notes in the source code of euidaccess that might indicate it doesn't work with ACL's:
https://github.com/coreutils/gnulib/blob/master/lib/euidaccess.c#L131

But before I can look into alternatives I need to be able to reproduce.

**Comment by groinwood** [comment]
First let me wish you a happy new year. 

To enable ACL's you need to enable it on the filesystem. You can do this by adding the option `acl` to the list of options for the partition in the file `/etc/fstab`

Then you can add access ACL's to a dir by `setfacl -m u:daapd:rwx`.  A default ACL can be added by `setfacl -d -m u:daapd:rwx`

**Comment by ejurgensen** [comment]
I think the above change could fix the issue. Do you have the opportunity to build from the fix_acl1 branch + try it?

**Comment by groinwood** [comment]
Okay. I'm not very skilled in building, but I'll try to build the package. I'll come back to you.

**Comment by groinwood** [comment]
I can confirm that ACL's are now supported very well with the commits in the fix_acl1 branch.

Thank you.
