### ISSUE TITLE
Playback of internet radio streams suddenly stopped working

### ISSUE THREAD

**Issue by mynameisdaniel32** [ejurgensen/forked-daapd#483]
Hi - I've been using forked-daapd for ages now with a few shairport-sync receivers. Earlier this week my radio stream (which I've been using with this setup for 18 months now) suddenly stopped working.

In the error logs, whenever I ask it to play, I get:
`[2018-01-26 11:39:48] [  LOG]   player: Source is not providing sufficient data, temporarily suspending playback (deficit=188)`

The stream is loaded into my library as a .pls file and is an AAC stream.
Downloaded from here:
http://www.abc.net.au/res/streaming/audio/aac/triplej.pls

The same stream works quite happily using iTunes (latest) on mac and windows computers. I've updated to the latest forked-daapd release/build without change.

Any ideas?

**Comment by mynameisdaniel32** [comment]
Thanks for checking it out - mine is actually on a barebones Debian Stretch VM and ffmpeg isn't installed, the VM is basically just dedicated to forked-daapd and mpc. It broke without me doing any updates for probably 2-3 weeks which makes me think something on the stream itself has changed and upset forked-daapd.

Should I perhaps look into installing/building the latest ffmpeg version? Or will that complicate things more than necessary?

**Comment by ejurgensen** [comment]
I made a change so now forked-daapd will ignore errors like this one from from ffmpeg. With this change I was able to play the stream, though occasionally when I start the stream ffmpeg throws another error about "please submit a patch". The latter error is not ignored, it seems less safe to do so.

So I guess the best way of fixing would be to upgrade ffmpeg, but if you would rather not, you can check if the above fix is ok for you.

**Comment by ejurgensen** [comment]
Now ffmpeg gave an "Invalid argument" error when I tried starting the stream, which doesn't make much sense. I also see the internal ffmpeg logging varies a bit. There are none of these hickups with the newer ffmpeg version, so that is my recommendation.

**Comment by mynameisdaniel32** [comment]
Thank you very much - your change has fixed it up and it's working perfectly once more :)

Something always goes wrong when I try to install/update ffmpeg so trying not to touch it as I've only just won a battle to install the latest version in another VM :)
