### ISSUE TITLE
Web interface strange error

### ISSUE THREAD

**Issue by tgiachi** [ejurgensen/forked-daapd#485]
Hi all,
I've compiled last git version.
copied web interface.

When i try to get admin.html the page is broken

![image](https://user-images.githubusercontent.com/942730/35730223-8b81a572-0811-11e8-87c6-d2738909d3d1.png)

why? Thanks!

**Comment by ejurgensen** [comment]
Pinging @chme on this.

Not sure what you mean by "copied web interface"?

**Comment by mill1000** [comment]
I too am having an issue with the web interface. Following instructions from INSTALL.md on a Raspbian Stretch build gives me an install with non-existent web interface.

Console output:
```
[  LOG]     main: Forked Media Server Version 25.0 taking off
[  LOG]     main: Built Feb  8 2018 with: --enable-itunes --enable-verification --with-alsa
[  LOG]     main: mDNS init
[  LOG]     mdns: Avahi state change: Client running
[  LOG]       db: Could not check database version, trying DB init
[  LOG]       db: Database OK with 0 active files and 6 active playlists
[  LOG]     scan: Skipping library directory /srv/music, could not dereference: No such file or directory
[  LOG]     scan: Bulk library scan completed in 0 sec
[  LOG]      lib: Library init scan completed in 0 sec
[  LOG]    cache: Beginning DAAP cache update
[  LOG]    cache: DAAP cache updated
[  LOG]    httpd: Could not lstat() /usr/share/forked-daapd/webface/: No such file or directory
```

@ tgiachi may have tried to manually copy the missing interface directory

**Comment by mill1000** [comment]
Ah looking at issue #480 it may be that I just need to pull from Git instead of the tarball

**Comment by tgiachi** [comment]
@mill1000  Hi Mill1000, yes i've manually copied the web interface, but seems cut html results

**Comment by ejurgensen** [comment]
Ok. closing this then

**Comment by chme** [comment]
@tgiachi Have you compiled and installed forked-daapd from git? Or did you install via apt-get (on which system/os)? It looks like an error that would happen in a version of forked-daapd that did not come with the web interface. Manually copying the web interface should not be necessary as `make install` will copy them to the correct location.

**Comment by lancelon** [comment]
hmmm, just done a apt install forked-daapd to upgrade forked daapd. everything seemed to go well but the admin page now won't load

**Comment by chme** [comment]
The forked-daapd package in debian/ubuntu does not include the web interface (neither the admin nor the player web interface). To get the web interface you need to manually copy the files (source for a specific forked-daapd version can be found under releases) under `htdocs`.
