### ISSUE TITLE
Make install overrides existing forked-daapd.conf

### ISSUE THREAD

**Issue by mill1000** [ejurgensen/forked-daapd#488]
Executing ``make install`` overwrites the existing forked-daapd.conf. To simply upgrades it would be good if the script could check for this file before copying the default

**Comment by ejurgensen** [comment]
This has been brought up before, see issue #17. I recognize the problem, but I don't know of a good way of solving it. Custom scripts and renaming the file doesn't seem ok. The solution needs to work with various distributions and be relatively "standard".

@sshambar you seem to be well versed in the world of makefiles, perhaps you have an idea?

**Comment by Porco-Rosso** [comment]
With the new release, is the "best-practice" approach still to just backup the config file, install forked-daapd like new, and restore the config?

**Comment by ejurgensen** [comment]
Yes, still haven't found a good solution for this

**Comment by ejurgensen** [comment]
Closing since I can't find a good solution...

**Comment by mill1000** [comment]
Take a look at [shairport-sync](https://github.com/mikebrady/shairport-sync). The generated Makefile performs a check for a config file, if not found a default is copied, otherwise it's left alone.

The command in question is:
` [ -f $(DESTDIR)$(sysconfdir)/shairport-sync.conf ] || cp scripts/shairport-sync.conf $(DESTDIR)$(sysconfdir)/shairport-sync.conf``

**Comment by ejurgensen** [comment]
Thanks @mill1000, I will consider it. Looks a bit homebrewn to me (eg mkdir instead of MKDIR_P, cp instead of INSTALL_DATA), so I'm not sure. For now it is in the branch no_cfg_overwrite.
