### ISSUE TITLE
Smart playlist language doesn't have "Starts with"

### ISSUE THREAD

**Issue by jimmiedave** [ejurgensen/forked-daapd#491]
Not a burning issue, but I used to be able to set up a playlist of songs that started with "My " (for example. Note that the space is part of the substring, not removed as a delimiter), but forked-daapd doesn't offer me that particular substring functionality (where, I _think_ mp-daapd did, and a previous Perl .m3u generator I used definitely did). I can imagine a few other uses for this feature in playlists.

**Comment by ejurgensen** [comment]
@chme this one is for you, I think
