### ISSUE TITLE
Unable to configure Airport Express with password

### ISSUE THREAD

**Issue by luisspuerto** [ejurgensen/forked-daapd#492]
Hi! 

Sorry if this is a stupid issue but I can't configure forked-daapb with my Airport Express that have password. I've tried several combinations of what I have to uncomment in the config file and I didn't have success. 

I thought that the correct way is this: 

```
#Airport Express device
apex "The Name of my ApEx" {
#   AirTunes password
   password = "mypassword"
}
```

But I got 

```
lpuerto@opl-cubox:~$ sudo forked-daapd
/etc/forked-daapd.conf:57: no such option 'apex'
[FATAL]   config: Parse error in config file /etc/forked-daapd.conf
[FATAL]     main: Config file errors; please fix your config
```

If any of you can help me it's really appreciated. 

Thanks.

**Comment by ejurgensen** [comment]
The keyword is "airplay", not "apex"

**Comment by luisspuerto** [comment]
Thanks!
