### ISSUE TITLE
Soundcard Line in streaming

### ISSUE THREAD

**Issue by cdobrow** [ejurgensen/forked-daapd#493]
Is it possible to use the line in of a USB sound card as a source which can then be streamed via AirPlay in forked-daapd?

**Comment by ejurgensen** [comment]
If you use a tool like `arecord` you can record from line in and have it write the audio as 44100 PCM16LE to a named pipe in forked-daapd's library.  So basically:

```
mkfifo /your/library/LineIn
(and then chmod/chown so that arecord can write and forked-daapd can read)
arecord -f cd /your/library/LineIn
```

Then forked-daapd should automatically start playback of the audio. Haven't actually tried this, so there may be more to it than the above :-)

**Comment by cdobrow** [comment]
Thanks worked like a charm!
