### ISSUE TITLE
Web Interface Issue

### ISSUE THREAD

**Issue by GrahamCrack3r** [ejurgensen/forked-daapd#517]
I just installed this on my ubuntu server and I can start the service no problem. If I enable the websocket_port in forked-daapd.conf I get a repeating error upon startup of the service. Anyone have any ideas?

**Job for forked-daapd.service failed because the control process exited with error code.
See "systemctl  status forked-daapd.service" and "journalctl  -xe" for details.
-- Logs begin at Tue 2018-03-27 20:01:49 EDT, end at Mon 2018-04-02 20:05:40 EDT. --
Apr 02 20:01:26 TGServer afpd[8075]: main: no servers configured
Apr 02 20:01:27 TGServer netatalk[706]: Restarting 'afpd' (restarts: 13876)
Apr 02 20:01:27 TGServer afpd[8076]: No suitable network config for TCP socket
Apr 02 20:01:27 TGServer afpd[8076]: no suitable network address found, use "afp listen" or "afp interfaces"

**Comment by ejurgensen** [comment]
1. It would be nice if you did not paste all the repetitions... I get the idea after the first ones.
2. The errors are about another service not starting (afpd is the Apple Filing Protocol daemon). It doesn't seem related to forked-daapd, but perhaps the websocket port you set is the one that afpd expected to use?
3. The websocket_port is enabled by default, so enabling it in the config shouldn't really make a difference - unless you are also changing the value of it?

**Comment by GrahamCrack3r** [comment]
I removed the repeitions and believe me that wasn't all of them. Sorry for that, it was late and my brain was fried. As for the afpd I had a hunch that it had something to do with another service. I am running netatalk as a time machine service. In the config, websocket_port is commented out and if I leave it that way the forked-daapd service starts without an issue. If I uncomment it I get all of the errors. Last night I did try changing the port value which still gave me the same errors. When running the service with the websocket_port commented out as it is by default I get a connection refusal when trying to accsess the web interface.

**Comment by ejurgensen** [comment]
Sounds strange. You should be able to access the web interface no matter what the websocket setting is. Can you check the following in the log (/var/log/forked-daapd.log):

1. What version of forked-daapd you are running (it will be in the top)
2. What gets logged when you try to access the web interface

**Comment by ejurgensen** [comment]
Closing, no feedback

**Comment by GrahamCrack3r** [comment]
I finally got back around to figuring this out. The solution... I'm f*cking retarded. All is good now, there was no problem to begin with. Next time I'll try to lay off the reefer. Thanks for your support!!
