### ISSUE TITLE
Support of AirPlay 2 possible?

### ISSUE THREAD

**Issue by kalle2000** [ejurgensen/forked-daapd#520]
With the newest beta of iOS (11.4) AirPlay2 seems to be (partially) available. Any chance to get it supported by forked-daapd at any point of time?

If not: is it recommended to not update iOS for time being?

**Comment by ejurgensen** [comment]
What particular part of Airplay 2 are you thinking of? forked-daapd already has multiroom.

I imagine it is fine to upgrade iOS, since forked-daapd doesn't really interface with anything in iOS. It would only be if they have updated the Remote app with something that is incompatible.

**Comment by kalle2000** [comment]
thx for the clarification
