### ISSUE TITLE
X library supports. 

### ISSUE THREAD

**Issue by Mattpenfold** [ejurgensen/forked-daapd#523]
I am looking to install forked-daapd, but cannot seem to do an install unless the X libraries are downloaded and installed. I going to be running it on a headless server, so do not want (nor will be able to use) those libraries. 

Is there an optional to compile without X support, and use the web gui instead?

**Comment by ejurgensen** [comment]
You don't ever need X for forked-daapd. Did you follow the instructions in the INSTALL file?

**Comment by Mattpenfold** [comment]
I found the problem. Debian was pulling X libraries when I was installing  libavcodec-dev, Looking at that package it has video as well as audio codecs. I will look at how to stop it pulling the X stuff for install.
