### ISSUE TITLE
Latest Commit Broke Compilations?

### ISSUE THREAD

**Issue by AlekLT** [ejurgensen/forked-daapd#526]
I think the latest batch of commits might have broken compilations? The latest master branch doesn't mark anything as a compilation. But if I checkout commit [acd5bd3](https://github.com/ejurgensen/forked-daapd/commit/acd5bd3272bfdd7eb19a6578d3e2ef59f0d0bd3b) (`acd5bd3272bfdd7eb19a6578d3e2ef59f0d0bd3b`), compilations are back and working again with the exact same config. I've only tested on one machine, so not super confident there's a problem, but thought I'd mention it. Maybe someone else can confirm or deny.

**Comment by ejurgensen** [comment]
Thanks for the notice. @chme can you look into this?

**Comment by AlekLT** [comment]
Actually I think this is human error, maybe just ignore this.

I tried to reproduce it and couldn't, but also couldn't get compilations working (as I thought they should) at all with either version. I think I must have accidentally been comparing a local library with forked-daapd. Which would be pretty stupid, but I can't see how else I could've got such different results.

I think I must also be misunderstanding what the intended functionality actually is. On my local iTunes library, the files tagged as compilations are separated into a 'Compilations' section at the bottom of the albums view. I thought that was the aim of selecting a directory for compilations in forked-daapd, but it seems it's just to overwrite the album artist? Either way, forked-daapd doesn't separate compilations in the same way as a local library and files that are tagged as part of a compilation in a local library are shown in a forked-daapd shared library as _not_ part of a compilation.

The album sort tag also doesn't seem to be correctly filled:
`[2018-04-20 10:37:22] [DEBUG]       db: Running query 'INSERT INTO files (id, path, fname, title, artist, album, genre, comment, type, composer, orchestra, conductor, grouping, url, bitrate, samplerate, song_length, file_size, year, track, total_tracks, disc, total_discs, bpm, compilation, artwork, rating, play_count, seek, data_kind, item_kind, description, time_added, time_modified, time_played, db_timestamp, disabled, sample_count, codectype, idx, has_video, contentrating, bits_per_sample, album_artist, media_kind, tv_series_name, tv_episode_num_str, tv_network_name, tv_episode_sort, tv_season_num,  songartistid, songalbumid,  title_sort, artist_sort, album_sort, composer_sort, album_artist_sort, virtual_path, directory_id, date_released)  VALUES (NULL, '/mnt/Music/Various Artists/Mozart 225/Disc 001/39 - The London Sketchbook - Minuet in E Flat Major K.15ee.m4a', '39 - The London Sketchbook - Minuet in E Flat Major K.15ee.m4a', TRIM('The London Sketchbook - Minuet in E Flat Major, K.15ee'), TRIM('Florian Birsak'), TRIM('Mozart 225: Chamber - a1'), TRIM('Classical'), TRIM('Mozart 225, 1: Chamber - a1 - Nannerl Notenbuch Excerpts; London Sketchbook (1761-1765)'), 'm4a', TRIM('Wolfgang Amadeus Mozart'), TRIM(NULL), TRIM(NULL), TRIM(NULL), NULL, 808, 44100, 50960, 5151525, 2016, 39, 51, 1, 200, 0, 8, 2, 0, 0, 0, 0, 2, 'Apple Lossless audio file', 1524186442, 1524057861, 0, 1524186442, 0, 0, 'alac', 0, 0, 0, 16, TRIM('Various Artists'), 1, TRIM(NULL), TRIM(NULL), TRIM(NULL), 0, 0, daap_songalbumid(LOWER(TRIM('Various Artists')), ''), daap_songalbumid(LOWER(TRIM('Various Artists')), LOWER(TRIM('Mozart 225: Chamber - a1'))),  TRIM('London Sketchbook - Minuet in E Flat Major, K.00015ee'), TRIM('Florian Birsak'), TRIM('Mozart 00225: Chamber - a00001'), TRIM('Wolfgang Amadeus Mozart'), TRIM('Various Artists'), TRIM('/file:/mnt/Music/Various Artists/Mozart 225/Disc 001/39 - The London Sketchbook - Minuet in E Flat Major K.15ee.m4a'), 262, 1451615400);'
`

From my local iTunes library (see second image, 'album' and 'sort as'): 
![itunes1](https://user-images.githubusercontent.com/7753160/39027474-409c3eca-4491-11e8-9653-91015c92bda0.png)
![itunes2](https://user-images.githubusercontent.com/7753160/39027473-40677c94-4491-11e8-9be0-a7c1c3193ba0.png)

If this is all intended behaviour then feel free to just close this. Sorry for the confusion/rambling.

**Comment by chme** [comment]
Thanks for the thorough testing, and good to know i did not accidentally brake something :smile: 

forked-daapd has its own logic to create the sort tag. If i remember correctly, numbers get prefixed with zeros to make sure that "track 1 something" is before "track 10 something".

Not sure about the compilation flag, it should be part of the metadata send to iTunes.

**Comment by ejurgensen** [comment]
Compilations in forked-daapd set the artist name, as it says in the config, and also sends the flag to iTunes (the asco tag), like @chme says. However, iTunes doesn't seem to use it for the grouping you mention, so maybe there is some other metadata or container it expects. I looked into it once, but wasn't able to figure out what would make iTunes put tracks in "Compilations".
