### ISSUE TITLE
Makefile error when compiling in FreeNAS 11.1 jail

### ISSUE THREAD

**Issue by floogs** [ejurgensen/forked-daapd#527]
I'm attempting to build release 26 in a jail on FreeNAS 11.1 (so essentially FreeBSD 11.0), and while the install script gets all the dependencies and companion services going (avahi-daemon and dbus are both running), it's throwing an error when it tries to make forked-daapd itself.

```
Should the script install forked-daapd and add service startup scripts? [y/N] y
gmake: *** No rule to make target 'install'.  Stop.
```

Thanks for any help (and for authoring this in the first place) -- I realize troubleshooting build errors on esoteric platforms is probably not a huge priority, but my *nix competence is unfortunately not up to snuff to diagnose this myself. Since it never even starts to compile, maybe it's something as simple as the definition of 'install' not being interpreted properly in the makefile or something similar? I'm out of my league here, just a guess.

I saw in another issue (which I can't seem to find now) that a similar error came up a couple of years ago with FreeNAS, but the recommended fix--adding a line to the install script to force the compiler to use the current release version--didn't work for me. Let me know if I can provide any feedback or logs or anything to aid development, happy to help where I'm able.

**Comment by ejurgensen** [comment]
How did the step "Should the script build forked-daapd?" go? The error is just an indication that either autoreconf or configure have not been run (with succes).

**Comment by floogs** [comment]
Hey, thanks for the quick response. On the first run of the install script in a fresh jail I get
```
Should the script build forked-daapd? [y/N] y
Cloning into 'forked-daapd'...
remote: Counting objects: 22067, done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 22067 (delta 38), reused 57 (delta 36), pack-reused 22004
Receiving objects: 100% (22067/22067), 13.76 MiB | 3.50 MiB/s, done.
Resolving deltas: 100% (15408/15408), done.
gmake: *** No rule to make target 'clean'.  Stop.
```
Then quite a bit more stuff that seems to execute successfully (can post the full log if it's helpful), culminating in this before the next query.
```
checking for SQLITE3... yes
checking for sqlite3_initialize... no
configure: error: Unable to link function sqlite3_initialize
Should the script install forked-daapd and add service startup scripts? [y/N] y
gmake: *** No rule to make target 'install'.  Stop.
sed: /usr/local/etc/forked-daapd.conf: No such file or directory
```
On your suggestion I tried running autoreconf and configure after the first build failed (autoreconf didn't seem to be available in my jail before I ran the install script the first time) and got this:
```
root@forked:~/forked-daapd-26.0 # ls
_config.yml             ChangeLog               forked-daapd.service.in Makefile.am             README.md
.gitignore              configure.ac            forked-daapd.spec.in    NEWS                    scripts
.travis.yml             COPYING                 htdocs                  README_JSON_API.md      sqlext
AUTHORS                 forked-daapd.8          INSTALL                 README_PULSE.md         src
build-aux               forked-daapd.conf.in    m4                      README_SMARTPL.md       UPGRADING
root@forked:~/forked-daapd-26.0 # autoreconf
configure.ac:14: error: required file 'build-aux/compile' not found
configure.ac:14:   'automake --add-missing' can install 'compile'
configure.ac:21: error: required file 'build-aux/config.guess' not found
configure.ac:21:   'automake --add-missing' can install 'config.guess'
configure.ac:21: error: required file 'build-aux/config.sub' not found
configure.ac:21:   'automake --add-missing' can install 'config.sub'
configure.ac:10: error: required file 'build-aux/install-sh' not found
configure.ac:10:   'automake --add-missing' can install 'install-sh'
configure.ac:21: error: required file 'build-aux/ltmain.sh' not found
configure.ac:10: error: required file 'build-aux/missing' not found
configure.ac:10:   'automake --add-missing' can install 'missing'
sqlext/Makefile.am: error: required file 'build-aux/depcomp' not found
sqlext/Makefile.am:   'automake --add-missing' can install 'depcomp'
autoreconf-2.69: automake failed with exit status: 1
root@forked:~/forked-daapd-26.0 # ./configure
configure: error: cannot find install-sh, install.sh, or shtool in build-aux "."/build-aux
```
Running the install script a second time produced the same behavior, which I guess is expected since autoreconf seems to have failed.

**Comment by ejurgensen** [comment]
Normally you need to run "autoreconf -vi", not just "autoreconf". Does that still give all those errors?

This one looks like the real culprit:
"configure: error: Unable to link function sqlite3_initialize"

It says that either the sqlite3 libraries are missing, or that configure can't find them. If it is the latter, then look at line 86 and 87 for an example of how to set flags with locations for configure.

**Comment by floogs** [comment]
Sure enough, autoreconf with those switches seems to have completed successfully (nothing that looks like an error to me, anyway).

Running the configure script afterward, it quits out at this:
```
checking for SQLITE3... yes
checking for sqlite3_initialize... no
configure: error: Unable to link function sqlite3_initialize
```
I'm assuming the initialize function is part of the main sqlite3 library, which does seem to be present? I did `pkg version` and it says sqlite3-3.23.0 is installed. (Again I'm punching way above my weight here.)

Which file did you mean to look at those lines in for setting locations? I looked at configure.ac, the configure script, and the install script but wasn't sure what you're referring to, except possibly the commented out export commands in the install script.

**Comment by floogs** [comment]
Feel free to close this issue -- I switched to iocage for jail management, which has a FreeBSD 11.1 template, and managed to compile forked-daapd without much trouble (I had to manually build libav and ffmpeg ahead of time to enable LAME and AAC support).

Where is the best place to look for general help on this? It's not currently seeing my iOS Remote pairing requests or my AirPlay speaker. Connecting from an empty iTunes library on my Windows machine randomly either works or doesn't work between restarts of the service (can't see anything in the log file to explain why it works sometimes but not others), and it occasionally drops the connection and disappears from the network after it does connect. But while it's connected it streams music and pulls album art just fine. So close!

I suspect at least some of this is down to an mDNS or similar networking issue, but realize Github probably isn't the best place to troubleshoot usability issues, so if you can point me somewhere more appropriate I'd appreciate it.

**Comment by ejurgensen** [comment]
Good to hear about the progress, but also sorry to hear that there are still issues. Yes, your current issue is likely mdns/network. Both Remote and AirPlay make announcements, and they get picked up by avahi running on your forked-daapd device. A common reason for this to fail is that the device with Remote/Airplay is on a different network than the one Avahi is on. Another possible reason is that your router is blocking the announcements.

The iTunes issue could also be network, but that is more hard to diagnose (given the randomness and the lack of log file info).

I don't know of a better place to point you to, except of course some googling of avahi and mDNS. The "avahi-browse" utility can also help you diagnose which services avahi is picking up.

**Comment by floogs** [comment]
Thanks for the reply. I tried some of the suggestions mentioned in the readme, but didn't get any feedback from avahi-browse and didn't have any luck after trying the trick of establishing another connection between my iPhone and forked-daapd's IP either.

I suspect my older router (Asus RT-N66U) isn't allowing multicast packets between wired and wi-fi devices; seems to be a fairly common issue. I'll keep digging around online, but I wonder if this is beyond the capabilities of that particular router...
