### ISSUE TITLE
High CPU usage (~90%) if idling/stopped

### ISSUE THREAD

**Issue by we5** [ejurgensen/forked-daapd#534]
Hi there,

i have forked-daapd running on a Raspberry 3 and are pretty happy with it. It is automated and controlled by a FHEM installation and bridged into HomeKit for using Siri to play Radio stations or control outputs.

The only problem I have is that if I stop the server (either by Apple Remote or FHEM/MPD) the CPU very often rises up to ~90%. Only if I start playing again (a radio station or the shairport-sync input) the CPU is going back to normal.

If I restart the service after killing it the CPU also rises to ~90%.

Any suggestions on how to further debug this?

**Comment by ejurgensen** [comment]
You could maybe use something like htop to see what thread is causing the CPU usage? Or you can yank up the log level to "debug" and see if the log says anything about what the server is doing. It should of course not use much CPU when idle.

**Comment by we5** [comment]
Oh, i actually found by rising the log level that there is a playlistcollection request from MPD daemon which originates from the FHEM/MPD module I guess. 

Because if enabled the module somehow is throwing out some playlistinfo (also most 100 per second)

```
[2018-05-24 16:56:20] [DEBUG]      mpd: MPD message: playlistinfo
[2018-05-24 16:56:20] [DEBUG]       db: Running query 'BEGIN TRANSACTION;'
[2018-05-24 16:56:20] [DEBUG]       db: Starting enum 'SELECT * FROM queue WHERE 1=1 ORDER BY pos ASC;'
[2018-05-24 16:56:20] [DEBUG]       db: End of queue enum results
[2018-05-24 16:56:20] [DEBUG]       db: Running query 'END TRANSACTION;'
```

So I guess this is not the fault of forked-daapd. Sorry for bothering at first. I will contact the module author.
