### ISSUE TITLE
Request: forked-daapd as qpkg

### ISSUE THREAD

**Issue by bendschs** [ejurgensen/forked-daapd#541]
Is it possible to provide a package for qnap nas (https://www.qnap.com/de-de/) as a qpkg. I would do it mayself if my linux-skillset would be sufficient. Here are the guidelines for wrapping qpkg's: https://wiki.qnap.com/wiki/QPKG_Development_Guidelines

cheers
Bendsch

**Comment by ejurgensen** [comment]
I don't offer packages for platforms I don't have, but if you want to give it a shot yourself I will be happy to help.
