### ISSUE TITLE
make: *** No targets specified and no makefile found.

### ISSUE THREAD

**Issue by vespino** [ejurgensen/forked-daapd#542]
I was hoping to use this project to stream live streams to my HomePod from a Ubuntu machine instead of using my iPhone or Synology DSM. I have followed the [installation instructions](https://github.com/ejurgensen/forked-daapd/blob/master/INSTALL) to the letter, but I'm getting this error:

make: *** No targets specified and no makefile found.  Stop.

The files "Makefile.am" and "Makefile.in" are in the forked-daaped directory. Also when running ./configure the following error appears:

configure: error: Default web interface requires libwebsockets

Is there another way of installing or some work around for the make error?

**Comment by ejurgensen** [comment]
You can't build if ./configure fails :-)

Seems like you haven't got libwebsockets-dev installed?

**Comment by vespino** [comment]
I will start from scratch and try again. To be sure: will this project allow me to do what I want which is streaming internet radio from Ubuntu to HomePod?

**Comment by ejurgensen** [comment]
Yes. Don't have a HomePod myself, but there was at least one other user that had it working.

**Comment by ejurgensen** [comment]
Hang on, I actually get the same error here even with websockets installed. Seems there is a bug in the config script, I will look into it asap.

**Comment by ejurgensen** [comment]
Wasn't as such a bug, the problem is that libwebsockets in Ubuntu 16.04 isn't recent enough. I've made that more clear in the error message. However, libwebsockets is not required for anything else than the player web interface, which you probably don't need. So just run "./configure --disable-webinterface" and it should work fine.

**Comment by vespino** [comment]
Turning off the web interface allowed me to complete the install. When running "/usr/sbin/forked-daapd restart" I'm now getting these errors:

[FATAL]   config: Could not lookup user daapd: Success
[FATAL]     main: Config file errors; please fix your config

I have commented out almost all settings since I won't be using my local music library (for now). Is there a way to bug fix?

**Comment by ejurgensen** [comment]
I wouldn't recommend commenting out everything. Just leave the defaults and then do like it says in the quick guide: https://github.com/ejurgensen/forked-daapd/blob/master/forked-daapd.conf.in#L1

You will probably need the local music library to save your internet radio playlists.

**Comment by vespino** [comment]
I reinstalled the entire thing as root, set the uid to root, now when I'm starting, I'm presented with this:

[  LOG]     main: Forked Media Server Version 26.0 taking off
[  LOG]     main: Built with:
[  LOG]     main: - ffmpeg
[  LOG]     main: - iTunes XML
[  LOG]     main: - MPD
[  LOG]     main: - Device verification
[  LOG]     main: - ALSA

Good?
