### ISSUE TITLE
Can't authorize spotify

### ISSUE THREAD

**Issue by fredericdepuydt** [ejurgensen/forked-daapd#546]
I can't authorize spotify, the webpage is blank when I click the button on the website.
How does the redirect url work? Does the spotify webpage need to be able to connect to that url? Since it's forked-daapd.local:3689/oauth/spotify.

I'm asking this because I run my Raspberry Pi headless (no webbrowser). So I open the forked-daapd webpage from a local PC in my network.

**Comment by ejurgensen** [comment]
Yes, it works very much like you say. To be precise:

1. forked-daapd announces that the device has the address forked-daapd.local
2. On any device on your lan you browse to http://forked-daapd.local:3689
3. You select Spotify auth and get sent to spotify.com, where you enter credentials
4. spotify.com redirects to http://forked-daapd.local:3689/oauth/spotify with the auth key

So the step that isn't working for you is number 2? Which probably means the client isn't registering the announcement in step 1. Advice for troubleshooting:

- make sure you only have one instance of forked-daapd running on the lan (to avoid name conflict)
- try from another browser/device (IE never works for me, Chrome sometimes, Safari on iOS every time)
- still fails? manually add the address of forked-daapd.local to the hosts file of the client computer

**Comment by fredericdepuydt** [comment]
I already added forked-daapd.local to my hosts file.
Did the test with multiple webbrowsers, and it is the spotify website itself that stayed blank.
The redirection didn't even happen.

After some testing I noticed it was my Pi-Hole who blocked the dns query for the spotify authorization.
Disabling Pi-Hole for 30 seconds allowed me to authenticate succesfull.
