### ISSUE TITLE
See what's being access through the shared library

### ISSUE THREAD

**Issue by jptrsn** [ejurgensen/forked-daapd#548]
Is there any way to view if/when a remote player is accessing the shared library, and to see what they're playing? For example, if I open iTunes on a different computer, and connect to forked-daapd and begin playing a song, does forked-daapd have any event that logs what song is being played?

I'd like to gain visibility into what's being listened to, and display that information in my home automation platform (Home Assistant). I can do that currently when I'm playing something directly through forked-daapd, but there's no visibility into when I'm using iTunes on a computer to access the shared library and playing that way.

**Comment by ejurgensen** [comment]
You could grab from the log. There isn’t any other interface for this. Note what iTunes does is basically downloading the track, which ends before playback ends. So you will have to calculate the end using start time and length of track.

**Comment by jptrsn** [comment]
Okay, that makes sense. Sounds like a potentially unreliable way to do it, I guess I'll move on to the next idea.
