### ISSUE TITLE
Question about License 

### ISSUE THREAD

**Issue by bantomak17** [ejurgensen/forked-daapd#550]
Hi.

I have a question about license with forked-daapd.

Forked-daapd have license with GPLv2. so it can use commercial.

but forked-daapd use libunistring, it have license with GPL-v3, so i can`t use it.

Do you know forked-daapd do not use libunistring ?

Thank you

**Comment by ejurgensen** [comment]
Not sure I understand the question, but yes forked-daapd uses libunistring (and has always done), and I have no plans about changing it.

**Comment by bantomak17** [comment]
Does old version of forked daap use libunistring ??

**Comment by bantomak17** [comment]
Thank you ^^

you are so kind. !!!

Have a nice day.
