### ISSUE TITLE
Weird scrobbling behaviour

### ISSUE THREAD

**Issue by magnate** [ejurgensen/forked-daapd#553]
I thought I had seen a thread about this before but I can't find it so creating this one - apologies if it's a duplicate. 

I'm using the @rbalint's Debian Stretch package of forked-daapd 24.2. I am seeing the following lastfm scrobbling behaviour: 

1. After not playing anything for a while, the first few tracks do not get scrobbled
2. Some tracks played are not scrobbled 
3. Some tracks played are scrobbled twice or three times

You can see the first two of these at https://www.last.fm/user/linuxmagnate/library?page=1 - today I played 7 Bad Company tracks but only the 5th and 7th got scrobbled, followed by 4 Midnight Oil tracks where the 2nd one didn't get scrobbled. 

Further down that page is a set of Zero 7 tracks which I have tidied up - each was scrobbled two or three times instead of once (each scrobble was one or two minutes apart, shorter than the track). 

Happy to test things. With a little effort I'm capable of building from source if you want me to test patches etc.

**Comment by ejurgensen** [comment]
If you set the log level to info in forked-daapd's config then you can see from the log exactly when it tries to scrobble, and what the result of the request to LastFM is.

**Comment by magnate** [comment]
Thanks, will try that and report back

**Comment by ejurgensen** [comment]
Closing, no feedback
