### ISSUE TITLE
Use only iTunes library file

### ISSUE THREAD

**Issue by roblan** [ejurgensen/forked-daapd#555]
Is there a way to use only iTunes library file as library info source for forked-daapd?
When I pointed it in config on whole directory all other files (ringtones, etc) were also added to the library. And is there a way to ignore songs that are mark as "unchecked" in iTunes library?

I’m trying to use it as library where 1:1 iTunes backup is the source.

**Comment by ejurgensen** [comment]
No, but you can take a look at the "filepath_ignore"-option, perhaps that can help you.

**Comment by roblan** [comment]
So there is no way to ignore those unchecked ones? Bummer...

**Comment by ejurgensen** [comment]
Not exactly sure what you mean by "unchecked"?

**Comment by roblan** [comment]
<img width="294" alt="screen shot 2018-07-09 at 20 02 52" src="https://user-images.githubusercontent.com/1079841/42467808-42b33dd8-83b3-11e8-8298-feb35a3d55e2.png"> those without this checkbox checked

**Comment by ejurgensen** [comment]
Can you check if this is a field in the xml? If so I think mapping it to disabled forked-daapd would be quite simple.

**Comment by roblan** [comment]
It have Disabled key set to true `<key>Disabled</key><true/>`

**Comment by ejurgensen** [comment]
Turns out it wasn't so easy to do as thought. The disabled flag in forked-daapd has some special uses which don't blend well with letting the iTunes XML decide its value.
