### ISSUE TITLE
Too many songs in "up next”

### ISSUE THREAD

**Issue by roblan** [ejurgensen/forked-daapd#556]
Using remote app on iPhone with iTunes library there are about 25 songs shown in queue (even when I’m listening to the whole library). In forked-daap it seems to be the whole playlist (whole library in my scenario) which hangs Remote when I try to rearrange some songs.

**Comment by ejurgensen** [comment]
Yes, that doesn't sound so good

**Comment by roblan** [comment]
There are 20 songs max in iTunes to be exact :)

**Comment by Albibox70** [comment]
Using Retune app on Android, when I start playing a single song ( tapping on a single song), all songs belonging to the album of that song are automatically added to queue ("up and next").
It should add only the selected song, not the whole album.
I don't know if it's related to the same problem.

**Comment by chme** [comment]
@Albibox70 that is the expected behavior. Tapping on a song always adds the current context to the queue (e. g. the album or playlist) and starts playing the song. 

@roblan I opened #588 that should fix this bug by limiting the number of items shown in "Up next"
