### ISSUE TITLE
[enchancement] searching by genre (PR included)

### ISSUE THREAD

**Issue by whatdoineed2do** [ejurgensen/forked-daapd#561]
I would like to include support to searching by `genre`, in which albums that include given genre are returned.

This would be coupled with an update to the web UI (which I've also made).

In many scenarios, I may want to play all music by a given genre (classic for instance) – at the moment, I would have to add individual albums or artists instead.

I have created a pull request for forked-daapd (https://github.com/ejurgensen/forked-daapd/pull/559) that has this functionality - included in the same PR is a link to the generated HTDOCs files that provides the enhanced UI functionality:  from the UI we have a tab that lists all genres and clicking an individual genre takes you to the albums.  Searching also looks at genres

Please consider the PR / functionality to merge.
Thanks

**Comment by ejurgensen** [comment]
Sounds good, thanks for this. I won’t have time for review before in a week or two. I will close this issue since the pr is sufficient.
