### ISSUE TITLE
Volume calibration for non-linear (log?) clients

### ISSUE THREAD

**Issue by jshep321** [ejurgensen/forked-daapd#564]
Is it possible to change the calibration settings to offset the volume per speaker?  

My hifiberry dac+ on a raspberry pi (that is also running the forked-daapd server) has a very odd response.  The volume has to be about 3/4 of the way up in the remote app (and web browser) before it gets the alsamixer out of the quiet zone.  examples attached.
Remote screenshot (with alsamixer at 52%):
<img width="375" alt="remote with alsamixer at 52" src="https://user-images.githubusercontent.com/12618683/43725194-e431c9b0-9969-11e8-8c95-8965e28310a5.png">
Alsamixer at 52%:
![alsamixer - 52](https://user-images.githubusercontent.com/12618683/43725195-e691a3ba-9969-11e8-9bae-8d520692f9dc.JPG)
Remote screenshot (with alsamixer at 28%):
<img width="375" alt="remote with alsamixer at 28" src="https://user-images.githubusercontent.com/12618683/43725205-e9880564-9969-11e8-8fb6-8bc5dd060a04.png">
Alsamixer at 28% (almost inaudible):
![alsamixer - 28](https://user-images.githubusercontent.com/12618683/43728486-475e99c4-9973-11e8-9b90-1b18322bc4de.JPG)

**Comment by jshep321** [comment]
Also, I have skimmed through the hifiberry forums and found that the analog settings are correct.  100% volume (the left one) and 0% boost (the right one).  Digital volume is the "PCM" / default settings.   I have tried to set this manually with amixer sset in a boot-time command, but it reverts to the above behavior after restart.

**Comment by ejurgensen** [comment]
No there isn’t a setting for that. Forked-daapd just sets the volume in percentage (applies to both ALSA and Pulseaudio). 

I imagine you would be better off if you can find an ALSA fix for the issue you have - then it will work for all applications, not just forked-daapd?
