### ISSUE TITLE
confused on how to upgrade forked-daapd

### ISSUE THREAD

**Issue by dln949** [ejurgensen/forked-daapd#565]
Ubuntu 18.04, currently have forked-daapd 25.0-2build4 installed.  

Near the bottom of this site, [https://github.com/ejurgensen/forked-daapd](url) , I see that there is already a version 26.2 of forked-daapd available.  

Will forked-daapd on my system upgrade itself to 26.2?  If so, when?  

Or, does Ubuntu control the upgrade?  

Or, What can I do in order to upgrade to 26.2 (and not lose all my settings)?

**Comment by ejurgensen** [comment]
The process is that new versions go into Debian, and then Ubuntu includes from that in their next release. The Debian part is currently halted by issue #552. 

So there won’t be an official Ubuntu update any time soon, and I also don’t know of any Launchpad you can use. To update you therefore need to build yourself following the instructions in the INSTALL file. To keep settings just remember to backup forked-daapd.conf.

**Comment by dln949** [comment]
Thank  you.  

If I install this from source, then.......  

1)  How do I uninstall it, should I need to?  

2) After I install it from source, then when future updates of forked-daapd become available, I assume my system will NOT inform me of that like what happens with programs installed with debian packaging - Am I correct?  

3)  If the debian package for the newer version of forked-daapd does become available, do I need to uninstall forked-daapd that I installed from source before I install the debian package?

**Comment by ejurgensen** [comment]
1. “sudo make uninstall” from the build dir
2. Yes, correct. However, you could try *not* uninstalling your current deb version before installing from source. It should just be overwritten, and whenever a new official deb comes, apt would overwrite the source install. Not really clean, but I think it would work. 
3. Not necessarily, see 2. 

Note that when you install from source you don’t get startup scripts, but you already have them if you don’t uninstall the deb version. Just make sure to configure with the right paths, those that are in the INSTALL file. 

I understand you are hesitant, at can become messy.

**Comment by dln949** [comment]
Thank you.  One followup question:  

You wrote for #1, "'sudo make uninstall' from the build dir."  

I am sorry, what is the "build directory"?  And, what, if anything, needs to be inside the "build directory"?
