### ISSUE TITLE
AirPlay 2 not working with forked-daapd

### ISSUE THREAD

**Issue by mb888** [ejurgensen/forked-daapd#566]
FYI. . . I just updated my Denon AVR-X4300H with a firmware update that included AirPlay 2 support. Your web app shows the Denon as an available speaker but will not activate it.

**Comment by snizzleorg** [comment]
Probably related: https://github.com/ejurgensen/forked-daapd/issues/557

**Comment by ejurgensen** [comment]
Yes it is likely the same. Let’s keep it on 557, so will close this. I’ve renamed it to be more clear.
