### ISSUE TITLE
Omega 2+ no web interface

### ISSUE THREAD

**Issue by DrUlysses** [ejurgensen/forked-daapd#568]
Hi, i do have no web interface. 
Log:
`
[2018-08-13 00:16:57] [  LOG]     scan: Scanned 200 files...
[2018-08-13 00:16:57] [  LOG]     main: File scanner deinit
`
http://forked-daapd.local:3689/ and http://192.168.3.1:3689/ are with ERR_NAME_NOT_RESOLVED
/etc/config/network has
`config interface 'wlan'
        option type 'bridge'
        option proto 'static'
        option ipaddr '192.168.3.1'
        option netmask '255.255.255.0'
        option ip6assign '60'
`

Can be also what I have forgot something (mb is helpful, what I have set uid on root)

**Comment by ejurgensen** [comment]
Have you checked that forked-daapd is running? Looks like it isn't starting.

**Comment by ejurgensen** [comment]
Closing, no feedback
