### ISSUE TITLE
Android app - error on Retune command "Play Next" 

### ISSUE THREAD

**Issue by Albibox70** [ejurgensen/forked-daapd#574]
Hi,
using the command "Play Next" on the Retune android app, result in:
"forked-daapd[1869]: [  LOG]     daap: Invalid query '$Q&session-id=1949158037' in request: '/ctrl-int/1/genius-shuffle?$Q&session-id=1949158037'".
Forked-daap 26.2 running on PI2.
Regards
Alberto

**Comment by ejurgensen** [comment]
Not sure why Retune is making a genius query in this case, but those are not supported by forked-daapd - and shouldn't be necessary for play next. I suggest you write to the Retune dev, he is very helpful.
