### ISSUE TITLE
AirPort Express, new firmware: 456 Header Field Not Valid

### ISSUE THREAD

**Issue by amaccuish** [ejurgensen/forked-daapd#577]
Error is:

> SET_PARAMETER request to 'Alex's Bedroom' failed for metadata/artwork/progress: 456 Header Field Not Valid

**Comment by ejurgensen** [comment]
So to get this one fixed I hope you can help with some Wiresharking:

1. Have Wireshark listen to all tcp traffic to the Airport
2. Connect with forked-daapd and start playback on the ApEx
3. Stop playback
4. Connect with Airfoil and start playback on the ApEx
5. Stop Wireshark listening, save the pcapng and send it to me espenjurgensen@gmail.com

What I am interested in learning is precisely which SET_PARAMETER gets the error, and whether Airfoil gets the same error. If not, I would like to see what differences are in the headers.

**Comment by ejurgensen** [comment]
Closing, no feedback
