### ISSUE TITLE
unable to exclude an airplay device

### ISSUE THREAD

**Issue by beaudett** [ejurgensen/forked-daapd#579]
Hello,
I first would like to say that forked-daapd is a great software. It has been running smoothly for months on my raspberry pi, streaming music to various devices. 

I have setup a second forked-daapd server on a different raspberry for my son.
It is using version 26.2 from the repository on a raspbian jessie. 
To avoid that he accidentally send the sound to the main device of the house, I would
like to exclude it. Therefore, I have added the following 
**airplay "0006780D50C5@marantz" {
       exclude = true
}**
in /etc/forked-daapd.config .

But, it does not seem to work: on the next reboot the marantz is still listed
as available (both on the web interface or with mpc outputs) and the log shows:

**[DEBUG]     mdns: Avahi Browser: NEW service '0006780D50C5@marantz' type '_raop._tcp' proto 0
[DEBUG]     mdns: Avahi Resolver: resolved service '0006780D50C5@marantz' type '_raop._tcp' proto 0, host marantz.local, address 192.168.0.50
[DEBUG]     raop: Event for AirPlay device marantz (port 1339, id 6780d50c5)
[ INFO]     raop: Adding AirPlay device 0006780D50C5@marantz: password: 0, verification: 0, encrypt: 0, metadata: 1, type Other, address 192.168.0.50:1339**

Did I miss anything in the config file syntax ? Is there an additional test that I could do ?
Thanks

**Comment by ejurgensen** [comment]
Just put airplay “marantz” (so without the 00067...), and it should work

**Comment by beaudett** [comment]
Indeed, it does. Thanks a lot for the quick answer !
