### ISSUE TITLE
many warnings during build

### ISSUE THREAD

**Issue by cosinekitty** [ejurgensen/forked-daapd#580]
Hi @ejurgensen .  I'm building forked-daapd for the first time. This is on Debian Stretch 9.4.0.  I notice many build warnings (see console log below).  I would like to help fix these warnings.  Would you be supportive of me contributing a pull request to fix these warnings?  I wanted to check with you before spending much time on it.

```
/usr/bin/antlr3 -Xconversiontimeout 30000  -fo . RSP.g
warning(24):  template error: context [/outputFile /parser] 1:1 could not pass through undefined attribute filterMode
warning(24):  template error: context [/outputFile /parser /genericParser /_sub45 /ruleAttributeScopeFuncMacro] 1:4 no such property or can't access: null.attributes
warning(24):  template error: context [/outputFile /parser /genericParser /_sub45 /ruleAttributeScopeFuncMacro] 1:4 no such property or can't access: null.attributes
warning(24):  template error: context [/outputFile /parser /genericParser /_sub45 /ruleAttributeScopeFuncMacro] 1:4 no such property or can't access: null.attributes
warning(24):  template error: context [/outputFile /parser /genericParser /_sub45 /ruleAttributeScopeFuncMacro] 1:4 no such property or can't access: null.attributes

[...]

depbase=`echo RSPLexer.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I..  -Wall -I/usr/include/x86_64-linux-gnu -I/usr/include/json-c -D_THREAD_SAFE -D_REENTRANT -D_REENTRANT -pthread -I/usr/include/alsa  -D_GNU_SOURCE -DDATADIR=\"/usr/share/forked-daapd\" -DCONFDIR=\"/etc\" -DSTATEDIR=\"/var\" -DPKGLIBDIR=\"/usr/lib/forked-daapd\"   -g -O2 -MT RSPLexer.o -MD -MP -MF $depbase.Tpo -c -o RSPLexer.o RSPLexer.c &&\
mv -f $depbase.Tpo $depbase.Po
RSPLexer.c: In function ‘mESCAPED’:
RSPLexer.c:2674:16: warning: unused variable ‘_type’ [-Wunused-variable]
  ANTLR3_UINT32 _type;
                ^~~~~
RSPLexer.c: In function ‘mDIGIT09’:
RSPLexer.c:2781:16: warning: unused variable ‘_type’ [-Wunused-variable]
  ANTLR3_UINT32 _type;
                ^~~~~
RSPLexer.c: In function ‘mDIGIT19’:
RSPLexer.c:2828:16: warning: unused variable ‘_type’ [-Wunused-variable]
  ANTLR3_UINT32 _type;
                ^~~~~

```

**Comment by ejurgensen** [comment]
Would be great to get rid of the warnings, but a few questions:
1. Are you familiar with antlr3? Or other parsers/lexers?
2. How would you go about testing? And securing that your changes work across different versions of antlr3?
3. How would you do it? I suggest you don't do all at once, but start with a small fix to serve as an example of how you would fix the rest.

**Comment by cosinekitty** [comment]
No, I'm not familiar with antlr3. I see now why this isn't as easy as I thought. There are 2 groups of warnings in the build output, as you know:

1. The warnings printed by antlr3 itself, that look like `warning(24): template error`
2. The warnings printed by gcc when it compiles the C code generated by antlr3.

I have a proposed change to address the first case: https://github.com/cosinekitty/forked-daapd/commit/f0d31bed96592ae3f77cfff6a4e5813601e520db
What do you think about this? Would you consider a pull request for it?

The second case is more difficult, because I don't see an easy way of turning off the warnings only for the antlr3-generated C code without also turning them off for all the other C code as well. I would like to think a little more about that to see if I can come up with a fix that only ignores warnings in the antlr3 code.

**Comment by ejurgensen** [comment]
I'm not interested in just turning off the warnings. They are there are for a reason, which is to tell us that the grammar files need some love.

**Comment by cosinekitty** [comment]
OK. Well, how about at the very least, I can add some notes to the INSTALL document, saying that these warnings can be safely ignored for now?

**Comment by ejurgensen** [comment]
Yes, that's fine :-)

**Comment by cosinekitty** [comment]
OK. I created a pull request:  https://github.com/ejurgensen/forked-daapd/pull/582

**Comment by ejurgensen** [comment]
Merged, thanks
