### ISSUE TITLE
I can't get past make

### ISSUE THREAD

**Issue by jlawton-adaptavist** [ejurgensen/forked-daapd#589]
outputs/raop_verification.c: In function ‘encrypt_gcm’:
outputs/raop_verification.c:795:51: error: ‘GCRY_CIPHER_MODE_GCM’ undeclared (first use in this function)
   err = gcry_cipher_open(&hd, GCRY_CIPHER_AES128, GCRY_CIPHER_MODE_GCM, 0);
                                                   ^
outputs/raop_verification.c:795:51: note: each undeclared identifier is reported only once for each function it appears in
outputs/raop_verification.c:823:3: warning: implicit declaration of function ‘gcry_cipher_gettag’ [-Wimplicit-function-declaration]
   err = gcry_cipher_gettag(hd, tag, AUTHTAG_LENGTH);
   ^
make[3]: *** [outputs/raop_verification.o] Error 1
make[3]: Leaving directory `/home/jamesl/forked-daapd/src'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/jamesl/forked-daapd/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/jamesl/forked-daapd'
make: *** [all] Error 2

---
I am not sure how to proceed at this point.

**Comment by ejurgensen** [comment]
Looks like you either don't have libgcrypt (incl header) or it is some version of libgcrypt that I haven't seen before. The configure script checks for libgcrypt, so I don't quite understand how you got past that.

If you are on debian you probably need the package libgcrypt11-dev.

**Comment by fergalom** [comment]
Afraid I'm seeing exact same issue on Centos 7
```
`depbase=`echo outputs/raop_verification.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I..  -Wall -I/usr/include/ffmpeg   -I/usr/include/json-c -D_THREAD_SAFE -D_REENTRANT -D_REENTRANT   -pthread -I/usr/include/libxml2 -I/usr/include/alsa  -D_GNU_SOURCE -DDATADIR=\"/usr/share/forked-daapd\" -DCONFDIR=\"/etc\" -DSTATEDIR=\"/var\" -DPKGLIBDIR=\"/usr/lib/forked-daapd\"   -g -O2 -MT outputs/raop_verification.o -MD -MP -MF $depbase.Tpo -c -o outputs/raop_verification.o outputs/raop_verification.c &&\
mv -f $depbase.Tpo $depbase.Po
outputs/raop_verification.c: In function ‘encrypt_gcm’:
outputs/raop_verification.c:795:51: error: ‘GCRY_CIPHER_MODE_GCM’ undeclared (first use in this function)
   err = gcry_cipher_open(&hd, GCRY_CIPHER_AES128, GCRY_CIPHER_MODE_GCM, 0);
                                                   ^
outputs/raop_verification.c:795:51: note: each undeclared identifier is reported only once for each function it appears in
outputs/raop_verification.c:823:3: warning: implicit declaration of function ‘gcry_cipher_gettag’ [-Wimplicit-function-declaration]
   err = gcry_cipher_gettag(hd, tag, AUTHTAG_LENGTH);
   ^
make[3]: *** [outputs/raop_verification.o] Error 1
make[3]: Leaving directory `/home/admin/forked-daapd/src'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/admin/forked-daapd/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/admin/forked-daapd'
make: *** [all] Error 2
`
```

```
[admin@dockerhost forked-daapd]$ sudo yum install libgcrypt*
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.heanet.ie
 * elrepo: mirrors.coreix.net
 * epel: mirrors.coreix.net
 * extras: ftp.heanet.ie
 * nux-dextop: mirror.li.nux.ro
 * updates: ftp.heanet.ie
Package libgcrypt-1.5.3-14.el7.x86_64 already installed and latest version
Package libgcrypt-devel-1.5.3-14.el7.x86_64 already installed and latest version
Nothing to do

```


I think this indicates the issue
[https://stackoverflow.com/questions/48082836/macro-not-found-in-libgcrypt-on-centos-7](url)
