### ISSUE TITLE
Help Wanted! Can it be used as a server for my TV

### ISSUE THREAD

**Issue by RienduPre** [ejurgensen/forked-daapd#592]
Hi, 
Let me explain in simple words what I like to do.

I have 2 HomePod's (and some other airplay speakers but the HomePod's are in my living room)
I Have a new LG TV which has a Optical Digital Audio Out port.

Can forked-daapd receive the digital audio input from the TV and stream (airplay) this to my HomePod's?

If yes, can you tell me some details how to do this ?

Thank you in advance,

Rien

**Comment by ejurgensen** [comment]
Yes and no. If you have a device with a sound card that has Optical In, and that forked-daapd can run on, you can get the audio out to the HomePod's. However, there will be a lag of 3-4 seconds, which means that is not a viable solution for TV audio.

**Comment by ejurgensen** [comment]
No, not really.
