### ISSUE TITLE
web: Error converting timestamp to uint32_t

### ISSUE THREAD

**Issue by jptrsn** [ejurgensen/forked-daapd#593]
I'm seeing a lot of these errors showing up in the log after I restart the service. Full message is
```
[2018-09-17 12:10:34] [  LOG]      web: Error converting timestamp to uint32_t: 675924773175296
[2018-09-17 12:10:34] [  LOG]      web: Error converting timestamp to uint32_t: 675924773175296
[2018-09-17 12:10:34] [  LOG]      web: Error converting timestamp to uint32_t: 675924773175296
[2018-09-17 12:10:34] [  LOG]      web: Error converting timestamp to uint32_t: 675924773175296
[2018-09-17 12:10:34] [  LOG]      web: Error converting timestamp to uint32_t: 675924773175296
[2018-09-17 12:10:34] [  LOG]      web: Error converting timestamp to uint32_t: 675924773175296
[2018-09-17 12:10:34] [  LOG]      web: Error converting timestamp to uint32_t: 675924773175296
[2018-09-17 12:10:34] [  LOG]      web: Error converting timestamp to uint32_t: 675924773175296
[2018-09-17 12:10:34] [  LOG]      web: Error converting timestamp to uint32_t: 675924773175296
[2018-09-17 12:10:34] [  LOG]      web: Error converting timestamp to uint32_t: 675924773175296
```

Running version 26.3, importing xml from iTunes db. I can provide more info if it will help.

**Comment by cosinekitty** [comment]
I don't know what is causing this, but here is a possible clue. In hex, 675924773175296 = 0x266c000000000.  The 26 followed by 6c look likes ASCII characters: `&l`. It could be something is wrong in parsing JSON? Extracting the wrong part of a URL?

**Comment by jptrsn** [comment]
I believe it's trying to parse those values when loading my smart playlists, and throwing that exception. Looks like it's a timestamp that's coming back with a value greater than the possible values for a uint32_t variable. Timestamp values this high are likely not the seconds elapsed since 1970, but milliseconds elapsed, so a conversion would be required.

**Comment by ejurgensen** [comment]
Yes, the value looks suspicious, but as far as I can tell the invalid value comes from your database. The web interface tries to convert it as it says. So a track has an invalid time_played, time_skipped, time_added or date_released, or the admin table has invalid timestamps. The only timestamp that is imported is "date_released", which comes from a file's id3 tag, so that is a candidate.

You could try to run "sqlite3 /var/cache/forked-daapd/songs3.db", and then "SELECT * FROM admin;" and then "SELECT path,time_added,time_played,time_skipped,date_released FROM files;" and maybe you will spot the culprit.

@chme for debugging it would probably be good if the key was also logged.

**Comment by ejurgensen** [comment]
Correction: When importing iTunes XML time_added, time_played and time_skipped may be imported as well.

**Comment by jptrsn** [comment]
Looking at the database, when I run this query, I get back my full set of files. That means somehow time_skipped is being set in _milliseconds_ rather than _seconds_. Could only be happening from iTunes itself. Could it be related to new functionality implemented in latest version?

```
sqlite> SELECT COUNT(*) FROM files WHERE (time_played > 4294967295);
0
sqlite> SELECT COUNT(*) FROM files WHERE (time_added > 4294967295);
0
sqlite> SELECT COUNT(*) FROM files WHERE (time_skipped > 4294967295);
3177
```

**Comment by ejurgensen** [comment]
Yes, I kind of assumed that the XML "time_skipped" was a unix timestamp of when the file was skipped, but maybe it is indeed something else. Can you check that the XML file actually contains the value 675924773175296 in one of these fields? Even if it is in ms I'm not sure I understand what that value would mean.

**Comment by jptrsn** [comment]
None of those values appear in the XML file. Looks like they're just showing up in the database.

**Comment by ejurgensen** [comment]
Then it could be the parsing of the fields in the xml. I will check if I can produce the error, if not I will need your XML.

**Comment by jptrsn** [comment]
Happy to share xml file with you privately. Let me know if you need it.

**Comment by ejurgensen** [comment]
The problem turned out to be a mismatch between a print mask and the size of time_skipped. It should be fixed now, thanks for reporting.

**Comment by jptrsn** [comment]
How do I get the fixed code running on my pi? I've run apt-get update and apt-get upgrade. Do I need to do anything to the database to purge the erroneous records?

**Comment by ejurgensen** [comment]
Good point, like my mom taught me I better clean up my own my mess, so I've added a commit that should remove the invalid values. I haven't made a RPi build with the fix yet, I would like to throw some more stuff in before I do that. It will probably be during the weekend.

**Comment by ejurgensen** [comment]
If you use my RPi repo you should be able to get the fixed version now (debian package version number ends with gitaa3aa38).
