### ISSUE TITLE
AirPlay speakers out of sync with ALSA sound card

### ISSUE THREAD

**Issue by cosinekitty** [ejurgensen/forked-daapd#600]
Forgive me if this is already documented somewhere, but I have not been able to find it.

When I use forked-daapd to play simultaneously to an AirPlay speaker and the server's internal sound card (ALSA on Debian Stretch 9.4.0), the internal sound card is not in sync with the AirPlay speaker. The AirPlay speaker lags behind the internal sound card. The delay is variable, sometimes a fraction of a second, sometimes more than 1 second.

I have some development experience in another (closed source) C# code base with synchronizing audio across multiple AirPlay and wired speakers.  I am familiar with NTP packets, dealing with drift from multiple clocks, etc.  So I would be happy to help fix this, if it's not just a simple configuration option that already exists.  I could probably use a clue where to start looking in the source.

Please let me know how I can help diagnose and fix this!

**Comment by ejurgensen** [comment]
Sync is very important, so it would be great if you could look at it. There should be sync between ALSA and Airplay, the original implementation of that was done a long time ago, before my time. However, I spent a lot of time on it a year or two ago, because there were some issues with the ALSA part.

It is rather complicated, and as I remember there where device-dependent issues with ALSA. So I am happy to hear you have some experience with this.

I have forgotten a lot of the details, but here are some pointers to get started:
src/player.c: This would be the starting point. It has the playback timer, and outputs like ALSA and Airplay will ask about playback position with player_get_current_pos().
src/outputs/alsa.c: Here you can see sync-check(). You will see that snd_pcm_avail_delay() is used to get the delay from ALSA.
src/outputs/raop.c: Here you can see that there is a Airplay clock service, that the output should be using.

I suppose the first step here would be to find out what it is that is not working, since the outputs are not in sync. Who is not following the clock: ALSA or the Airplay speaker?

**Comment by cosinekitty** [comment]
Here is what I have figured out so far.  I was able to get the ALSA device mostly in sync with the AirPlay speaker by setting `audio { offset = -10000 }` in `/etc/forked-daapd.conf`. 

However, I would like to leave this issue open for now because there a couple of things that bother me:

- The sync technique causes audible clicks in the ALSA output: it works by sometimes dropping entire packets (352 samples = 8ms) or double-writing entire packets.  I want to see if it is possible to adjust the sound card's internal clock rate slightly above or below 44100 Hz using feedback control logic, which is how I have solved the sync problem in other code.  (I did that using the BASS library; I have no idea whether ALSA supports this.)

- The debug prints indicate that the sync just isn't working.  I keep seeing bigger and bigger numbers for the latency. Here are a few randomly chosen excerpts from my log file:

```
[2018-10-09 15:28:00] [ INFO]   laudio: Taking action to compensate for ALSA latency of 916 samples
[2018-10-09 15:29:31] [ INFO]   laudio: Taking action to compensate for ALSA latency of 1087 samples
[2018-10-09 15:31:52] [ INFO]   laudio: Taking action to compensate for ALSA latency of 1359 samples
[2018-10-09 15:33:02] [ INFO]   laudio: Taking action to compensate for ALSA latency of 1488 samples
```

If I take this log output at face value, it means the drift is larger than can be compensated by an 8 ms adjustment every 10 seconds.

**Comment by ejurgensen** [comment]
>  I want to see if it is possible to adjust the sound card's internal clock rate slightly above or below 44100 Hz using feedback control logic, which is how I have solved the sync problem in other code.

Sounds great! Much better than the rather crude method used right now.

**Comment by cosinekitty** [comment]
Minor update: I keep playing audio and the drift has become audible. It sounds something like 0.1 seconds? The debug log is now printing values like:

```
[2018-10-09 15:48:37] [ INFO]   laudio: Taking action to compensate for ALSA latency of 3223 samples
```

**Comment by cosinekitty** [comment]
I have been studying the code and I have a plan I would like to implement. Here are my current thoughts.

- I now have the existing (crude) sync algorithm working on my system.  I had to set the configuration sample offset to -10000, as mentioned above, and I had to change the code to adjust drift every 5 seconds instead of every 10.  So I will make this check interval configurable, and probably make it default to 5 seconds.

- Question: do we know what other users are setting the ALSA sample offset to in the config file?  I wonder if there is a way of calculating that instead of manually setting it, e.g. using `delay` obtained from `snd_pcm_avail_delay(hdl, &avail, &delay)`. On my system, `delay` ends up being around 14500 samples.  So maybe a formula like `4500 - delay` would be a good estimate for `offset`?

- There is an assumption that there is a single offset across all ALSA devices. This will not be true for systems with more than one sound card. In general, we will need a separate offset for each ALSA device. That will probably be very rare, but the existing code does allow for any number of ALSA devices. So this is another reason it would be nice to calculate `offset` instead of configuring it. But I don't dare make a change like this without other people to help me test it!

- And now for the fun stuff. Instead of dropping or double-writing entire 352-sample buffers, I would like to use [sinc-window resampling](https://ccrma.stanford.edu/~jos/resample/Theory_Ideal_Bandlimited_Interpolation.html) of the audio before writing it to each ALSA device. This is really a form of FIR filtering with the coefficients calculated such that we can non-linearly interpolate between samples with minimal audible distortion.  

- I will adjust the code so that every 5 seconds (configurable), we re-evaluate the drift, and correct a "resampling rate" by a tiny amount to bring the drift back toward zero over time.  For example, if the ALSA card is lagging behind the AirPlay stream, we will calculate an increase in its effective sampling rate slightly above 44100 Hz, for example, maybe 44102 Hz.  Each time the resampling rate is adjusted, we have to recalculate the FIR coefficients and store them in a lookup table, for efficiency.  The adjustments have to be very gradual (never more than a few Hz at a time) and clamped to a small range (never outside a quarter percent, or plus or minus 100Hz of the original sampling rate, based on my experience and studies of psychoacoustics).

- CPU usage will be of concern. I will take measurements of CPU overhead before and after the change, and come up with default values that provide a good balance between low overhead and high fidelity audio.  There will be a new configuration setting for the FIR table size so users may opt for lower values on systems with slower CPUs, or higher values for more audiophile quality.

@ejurgensen This is a significant amount of work I am willing to do, so I just want to make sure you are comfortable with this before I go off and spend the time on it.  Please let me know what you think about this.

**Comment by cosinekitty** [comment]
> That your drift needs correction every 5 sec sounds peculiar - I mean modern clocks are very precise, so is the root cause something else?

I am not surprised to see more than 8 ms of drift each 10 seconds. This is about one part per thousand disagreement between the sound card's clock and the system clock.  I have seen some sound cards whose clocks show twice this amount of drift, some running fast, others slow.

> Not sure if I understand what you mean, but back when I tested the offset of 0 was ok on my devices. How do you measure sync? I just used my ears, but better would be to use a microphone and compare the spectrum. I also think you would need to test on a range of devices before being able to conclude anything about offset. In general, and as you say, testing will be important, because ALSA is device dependent.

I'm just using my ears too. And I agree about the necessary testing. I just wanted to mention the idea, but I would like to limit the scope of this PR to leaving the configuration of `audio { offset }` the way it is.  

> As I remember, some adjustments would be required to support multiple soundcards? See the TODO in line 50.

I won't worry about independent offset for multiple sound cards either at this point.  I think it will be a good idea for me to focus on replacing the rate sync algorithm only right now. However, the new rate sync will handle multiple sound cards just like the current drop/double-write algorithm does.

> What are your thoughts about the implementation? Would you add the algorithms to alsa.c, or would you be using a library (ffmpeg?).

My intention is to add new code in alsa.c. The formulas will not be very difficult, and I think it will avoid any surprises from dependencies on an external library, even one currently in use by forked-daapd. I predict there will be a few nuances from having to adjust the resampling rate dynamically that would  be easier for me to code myself than having to figure out how to get someone else's code to work.

> One enhancement I would love you to include is to make the sample rate less hard coded. Supporting other quality levels than 44100/16 is on my "roadmap", but it is a very large task, so needs to be done in steps. Getting ALSA ready for it would be great.

Now this is interesting. I assume you mean converting to very different sampling rates like 22050 or 48000 for an ALSA device, while continuing to play 44100 to AirPlay?  What I'm thinking about doing would be a good first step. To make the resampling rate this much lower than 44100 would require a little extra work in pre-filtering the input to remove frequencies above the target rate's Nyquist frequency (half the sampling rate).  I think it will allow a target frequency like 48000 or 96000 without any extra work.  So yes, I will study that idea, and if it's easy to do, I will include it in the PR.  Otherwise, I would consider doing it in a follow-up PR.

**Comment by cosinekitty** [comment]
@chme Thanks for the tips! I will look at shairport-sync and libsoxr to see how they work.

**Comment by ejurgensen** [comment]
@cosinekitty I suppose you got caught up with other things, but I wanted to mention that I have now made some of the changes discussed above. As you can see alsa.c has been changed a great deal, and now it will resample to stay in sync with the clock, like you suggested. The actual resampling is done by ffmpeg, and to be honest I have no idea how it does it. I have also changed the measurement of sync - it now tries to calculate both drift and latency based on an evaluation of 100 measurements, and then tries to compensate accordingly.

ALSA playback is now also done using the source sample rate and sample format, so no longer fixed at 44100.

**Comment by cosinekitty** [comment]
Wow, that is awesome!  I will take a look.  Yes, I did start down the road of doing a bunch of math and got bogged down. Sorry I didn't mention this.  I hope I didn't delay you working on it.
