### ISSUE TITLE
Web interface

### ISSUE THREAD

**Issue by snizzleorg** [ejurgensen/forked-daapd#601]
I understand that the web interface is now in the release. However I only see the admin interface. 

Is there some specific configuration necessary to activate the webinterface?

Thanks

**Comment by chme** [comment]
I guess, you are building forked-daapd from git? The web interface requires libwebsockets 2.0.2+ otherwise it is disabled during configure/build.

**Comment by snizzleorg** [comment]
no I'm installing via apt: http://www.gyfgafguf.dk jessie/contrib

**Comment by ejurgensen** [comment]
Jessie doesn't have the required libwebsockets... you would need to upgrade to Stretch
