### ISSUE TITLE
Exclude local audio from output list

### ISSUE THREAD

**Issue by Phontana** [ejurgensen/forked-daapd#607]
I can't find a way to exclude "Computer" (the local audio output) from the speaker list. Is there a way to exclude "Computer" from the speaker list?

**Comment by cosinekitty** [comment]
I’m curious why you want to exclude it. I’m not trying to change your mind; rather, I’m interested to know what your motivation is because I’m working on a feature related to local audio.

**Comment by snizzleorg** [comment]
you put disabled as type in the local auto section of the config file:

```
# Local audio output
audio {
        # Name - used in the speaker list in Remote
        nickname = "Computer"

        # Type of the output (alsa, pulseaudio, dummy or disabled)
        type = "disabled"
```

**Comment by Phontana** [comment]
@snizzleorg thank you very much, I completely missed that option.

**Comment by tobx** [comment]
When setting `type = "disabled"` the AirPlay icon in Apple's "Remote" app disappears and I cannot select any AirPlay devices anymore.
