### ISSUE TITLE
Feature request: Include Composer in Api and Web interface

### ISSUE THREAD

**Issue by LordMyschkin** [ejurgensen/forked-daapd#614]
I love the new interface and use it regularily, but it has a major downside: When I listen to classical Music, I get the Artist (e.g. "Rudolf Buchbinder" who plays the track) and the title, but for this kind of music, it would be great if it would be possible to show "Composer" e.g. "Ludwig van Beethoven" as well.

**Comment by chme** [comment]
I'll look into this

**Comment by whatdoineed2do** [comment]
urgh, trust me not to refresh this issue before sending the PR....
