### ISSUE TITLE
Support Audio CD

### ISSUE THREAD

**Issue by BergenSoft** [ejurgensen/forked-daapd#616]
I want to play titles from my Audio-CD with this project.

To play Audio-CDs with mpd I found the following page:
https://volumio.org/forum/playing-cds-directly-from-mpd-t2411.html#p14328

I had to add the input "cdparanoia" to the mpd.conf file.
After that I was able to call `mpc add cdda:///1` and play the cd track 1.

Is it possible to combine this with this project to add cd Tracks to the Playlist?

Thanks in advance

**Comment by BergenSoft** [comment]
As I understand, this forked-daapd works as a mpd server. Is there any config, where I can define the inputs as in the mpd package?

**Comment by ejurgensen** [comment]
Maybe there is some trickery that can be done so that a CD appears as media files in your library, but other than that I can't see a way of doing this with forked-daapd
