### ISSUE TITLE
Feature Request: stream audio from web interface

### ISSUE THREAD

**Issue by Porco-Rosso** [ejurgensen/forked-daapd#621]
Seeing as forked-daapd-web has been merged into this repo, I thought I would bring up this request again: https://github.com/chme/forked-daapd-web/issues/2

I am requesting a button or checkbox on the webui that would open this stream in the background: http://forked-daapd.local:3689/stream.mp3

Maybe a tooltip could warn that the output will not be in sync with the rest of the outputs?

**Comment by Porco-Rosso** [comment]
@chme Any chance of including this in your upcoming webui version bump? 
I thought about it a little bit in terms of UI. I think a menubar toggle, with a tooltip would be a good solution. It could be labeled "browser stream" or "http stream" or "http pipe".

I don't know Vue or Bulma otherwise I would try it myself and submit a pull request.

**Comment by chme** [comment]
I'll look into it. Sadly, simply including an audio tag did not work so well, but i found an example project, that has given me an idea how to implement it.
