### ISSUE TITLE
bitrate

### ISSUE THREAD

**Issue by bendschs** [ejurgensen/forked-daapd#622]
is there a way to manually set the bitrate of mpd-player? as far as i can see it allways puts out at 128 kbps and 44.1 kHZ, to all devices (airplay and local).

I think the quality is much too low. Even the premium account of spotify (which you need in order to use spotify in forked-daapd) makes no sense in this context. High quality mp3s in 320 kbps will be downcoded to 128 kbps. (I am not even speaking about my flacs here ...)

cheers
bendsch

**Comment by ejurgensen** [comment]
I'm not sure what you mean by "mpd-player", but isn't this the same issue as #395?

**Comment by bendschs** [comment]
probably it is, i just wanted to point out that this is also affecting airplay output, not only local audio output.

cheers
bendsch

**Comment by ejurgensen** [comment]
Ok, will close it here. Enhanced quality should be for all outputs, so I have changed the title of 395.
