### ISSUE TITLE
Clarification on local audio capabilities

### ISSUE THREAD

**Issue by MatejLach** [ejurgensen/forked-daapd#624]
First of all, thanks for working on forked-daapd, it's very much appreciated. 

I am a bit unclear regarding the local audio capabilities of forked-daapd.

Is it possible to send system audio, (that is whatever is playing on my forked-daapd host machine, but say in Firefox), or is it limited to playing whatever is added to the music library and sync it with local output?

In other words, is it possible for forked-daapd, to take a pulseaudio sink as input and send it to AirPlay devices?

PA has this capability natively, but it doesn't seem to work with AirPlay2 devices like the HomePod and I was wondering whether forked-daapd could help here.

Thanks.

**Comment by ejurgensen** [comment]
It is only possible by getting Pulseaudio or alsa to write the system audio to a fifo/named pipe in the library. There will be a significant lag on the audio, so it probably won't be something you are happy with.

**Comment by MatejLach** [comment]
@ejurgensen Makes sense. Thanks for the quick response.
