### ISSUE TITLE
feature request: UI enhancements

### ISSUE THREAD

**Issue by whatdoineed2do** [ejurgensen/forked-daapd#631]
@chme  - FYI A small tracker for the merged items that has gone on in the background but require some discussion around the UI enhancements, particularly:

- [x] index tab navigation (closed by https://github.com/ejurgensen/forked-daapd/pull/634)
~~https://github.com/ejurgensen/forked-daapd/pull/598~~
~~https://github.com/ejurgensen/forked-daapd/pull/598#issuecomment-435469176~~
~~Concerns around the second horizontal scrollbar on some pages, to consider an alternative~~

- [ ] `composer` on `now playing` page
Accepted PR https://github.com/ejurgensen/forked-daapd/pull/619 does NOT incl composer on `Now Playing` page
https://github.com/ejurgensen/forked-daapd/pull/619#issuecomment-441822452
PR https://github.com/ejurgensen/forked-daapd/pull/681 to address some concerns and incls `composer` on `Now Playing page.

**Comment by chme** [comment]
I added the index based navigation to #634 with some changes:

- use vue-router to navigate to the index
- use button list for index
- button list is scrolled out of the viewport when opening artists, albums, genres pages and is reachable by scrolling upwards
- always show all index buttons and disable those that are not available

Using vue-router has the benefit of being able to navigate back to the index with the browser back button. The scrolling animation we get with vue-scrollto is nice and but i think it is more important to be able to use the browser navigation. There are probably ways to make use of vue-scrollto in combination with vue-router, but i am not sure if it is worth investigating. 

![image](https://user-images.githubusercontent.com/1037620/49684128-a9dff080-facf-11e8-932e-18a175c7b0ce.png)

**Comment by chme** [comment]
I changed the implementation to generate a dynamic list. There are some ugly edge cases with special chars that are not allowed to be used as id/selectors. I opted to remove these from the generated list.

The button list is initially not visible, you need to scroll up to see it. But i went with a smaller button size to save some space. By the way, the tabs "browse", "artists", etc. is now fixed and does not scroll with the rest of the content.

**Comment by whatdoineed2do** [comment]
I've submitted a PR https://github.com/ejurgensen/forked-daapd/pull/681 that displays composer on `Now Playing` page if:
* `composer` tag available
* track genre matches criteria (genre of track in a whitelist) that is user configurable at the server side

@chme - can you take a look to see this resolves your previous concerns?
