### ISSUE TITLE
Compound JSON api search

### ISSUE THREAD

**Issue by ejurgensen** [ejurgensen/forked-daapd#641]
@chme, I am playing around with voice control of forked-daapd using Google Home Mini and IFTTT, which makes it possible to add custom commands. I've got basic controls working, like for instance play/pause, volume and next. So next thing to try is commands like "play $something" and "enable speaker $name". It seems like Google will be able to voice-to-text $something and $name if they are English (and other major languages), and it can then make a web request to forked-daapd containing the values. However, it will only make a single request, so using the JSON api with search + add to queue + play is a bit difficult.

So I am thinking of adding parameters to the search api to not just search, but also queue and play the results, so it can be done in one request. Sort of like DACP's playqueue-edit. Does that sound ok to you?

**Comment by ejurgensen** [comment]
Do you have a link with more info?

**Comment by chme** [comment]
I have given this some more thought and i think, that a new endpoint is not necessary. Instead extending the queue/items/add endpoint would be the best approach. 

The web interface could also make use of this. Currently the web interface in some places queries the tracks to add (in the genre pages and in the coming files pages) and adds their uris to the queue. It would be handy, if it would be possible to pass the query expression to the queue/items/add endpoint.

The queue/items/add endpoint could also be extended to have a parameter to start playback after adding the items and maybe support clearing the queue prior to adding the new items.

I have given the first part (adding new items to the queue by query) a try: https://github.com/chme/forked-daapd/commits/jsonapi_files (commit 3ec98b3023048c45767805832c9ecf59c1e06e88 for the implementation and commit 01befdc529f8dfb1459e303e03501ebf8d6c8726 for the documentation).

What do you think?

**Comment by ejurgensen** [comment]
Sounds good to me. I hadn't started any work on "searchadd" anyway, because I could accomplish most of what I wanted via dacp. Still think it would be good to also have json support for it, so good to hear you already are looking at it.
