### ISSUE TITLE
Manually add artwork for external (blank) streams

### ISSUE THREAD

**Issue by jshep321** [ejurgensen/forked-daapd#656]
Hi,
I have a streaming station that doesn't offer any artwork.  Any possibility to inject a jpg/png into a playlist in order to avoid the emptiness of space? 

The best reference of M3U I could find doesn't provide any easy options: 
http://forums.winamp.com/showthread.php?t=65772

I've tried just sticking the artwork jpg in the M3U, but no dice.

**Comment by ejurgensen** [comment]
For playlists in your library, say /foo/bar.m3u, then for any http streams in the list, forked-daapd will look for /foo/bar.{jpg,png}. However, there are situations where it doesn't work in the web interface, but I think @chme may be working on a solution for that, ref. pr #629

**Comment by jshep321** [comment]
Yeah, that was a super simple solution that I failed to try. Much thanks!
