### ISSUE TITLE
Troubles with libgcrypt20-dev dependency during installation

### ISSUE THREAD

**Issue by TiMESPLiNTER** [ejurgensen/forked-daapd#657]
When I try to install forked-daapd according to the provided installation guide in the `INSTALL` file for my Debian 9 Stretch installation:

```
sudo apt-get install \
  build-essential git autotools-dev autoconf libtool gettext gawk gperf \
  antlr3 libantlr3c-dev libconfuse-dev libunistring-dev libsqlite3-dev \
  libavcodec-dev libavformat-dev libavfilter-dev libswscale-dev libavutil-dev \
  libasound2-dev libmxml-dev libgcrypt11-dev libavahi-client-dev zlib1g-dev \
libevent-dev libplist-dev libsodium-dev libjson-c-dev libwebsockets-dev
```

 I get this:

```
The following packages have unmet dependencies:
 libgcrypt11-dev : Depends: libgcrypt20-dev (>= 1.7.6) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Couldn't find a way to fix it. When I try to run 

```
sudo apt-get install libgctypt20-dev
```

I get

```
The following packages have unmet dependencies:
 libgcrypt20-dev : Depends: libgpg-error-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Then I try:

```
sudo apt-get install libgpg-error-dev libgcrypt20-dev
```

and finally I end up with this error message:

```
The following packages have unmet dependencies:
 libgpg-error-dev : Depends: libgpg-error0 (= 1.26-2) but 1.33-3~bpo9+1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by ejurgensen** [comment]
It sounds like you need a apt-get update + apt-get upgrade, but I think you will probably get better help googling the error message from apt. The issue doesn't really have much to do with forked-daapd, so I will close it here.

**Comment by TiMESPLiNTER** [comment]
My system is fully up to date. Upgrade will affect 0 packages. So it's kind of a dependency problem and I'm not sure why it's conflicting. As forked-daapd wants to install an older version maybe it's possible to upgrade that dependency from 1.26-2 to 1.33-3?

**Comment by ejurgensen** [comment]
forked-daapd doesn't really care so much about the version, libgcrypt20-dev should work fine. I also have Debian 9, and have both libgcrypt20-dev and libgcrypt11-dev installed, so that can work too. My libgpg-error-dev and libgpg-error0 are both 1.33, so not sure why you have 1.26. That was why I was thinking an apt upgrade might be needed.
