### ISSUE TITLE
database overwritten during forked-daap update

### ISSUE THREAD

**Issue by Albibox70** [ejurgensen/forked-daapd#663]
Hi,
maybe I make a mistake, but each time I upgrade forked-daapd version (last time 26.2->26.4) I see my songs.db overwritten and then recreated.
What am I doing wrong?
Each time I lose all of my ratings... and it's really time wasting to recreate them.
I upgrade on raspberry using "apt-get update" and then "apt-get upgrade" (or "apt-get install forked-daapd")

Thanks in advance
Alberto

**Comment by ejurgensen** [comment]
Yes, this is a bug. It should be fixed here on Github, so if you build from here it shouldn't happen. The fix was this commit 9929832b5fc0d7e21711b054bfe5094b887a4e4c, so pretty recent. If you are using my RPi build it doesn't include the fix yet, but I will update it soon.

**Comment by Albibox70** [comment]
Hi,
I'm trying to update on raspberry using "apt-get install forked-daapd" but it seems that only 26.4.76 version is available (no 25).
Am I doing something wrong?
Regards
Alberto

**Comment by ejurgensen** [comment]
I can't say why that is (I expect you did run "apt update", right?). I have checked the repo, and it seems ok. On my RPi apt finds the updated version:

```
pi@stretch ~ $ apt-cache show forked-daapd
Package: forked-daapd
Version: 26.5.80.git8e474df-2
Architecture: armhf
```
If you can't make it work, here is the direct download link:
http://gyfgafguf.dk/raspbian/forked-daapd/pool/contrib/f/forked-daapd/

**Comment by Albibox70** [comment]
Hi and sorry for wasting your time! 
I thought I had run the "apt update" command... but I didn't.
Once done, the app updated correctly with ""apt-get install forked-daapd".
Regards
Alberto
