### ISSUE TITLE
Creating an effective antlr3 file on Gentoo 

### ISSUE THREAD

**Issue by MarkGannon** [ejurgensen/forked-daapd#666]
Following the instructions for building from source at https://github.com/ejurgensen/forked-daapd/blob/master/INSTALL , I get a file not found error from antlr during the compile phase.

antlr3
```
#!/bin/sh
CLASSPATH=/usr/share/antlr-3.5/lib/antlr-runtime.jar:/usr/share/antlr-3.5/lib/antlr-tool.jar:/usr/share/stringtemplate-4/lib/stringtemplate.jar
exec /usr/bin/java -cp $CLASSPATH org.antlr.Tool "@"
```
If I run the file manually by itself (without specifying a file , I get the following results:
```
error(7):  cannot find or open file: @; reason: java.io.FileNotFoundException: @ (No such file or directory)
```
I get the same results from running antlr3 RSP.g in  the src directory.

Running make fails with the following output:
```
/usr/local/bin/antlr3 -Xconversiontimeout 30000  -fo . RSP.g
error(7):  cannot find or open file: @; reason: java.io.FileNotFoundException: @ (No such file or directory)
make: *** [Makefile:1233: RSPLexer.c] Error 1
```
Thanks for your assistance!

**Comment by MarkGannon** [comment]
As is often the case, I found the issue just after posting this.  Instead of the last line of antlr3 ending with "@", it should end with "$@".  The latter symbol is all of the command line arguments from the scripts command line.  Perhaps it would be worth updating the documentation?

Thanks for the great software!

**Comment by ejurgensen** [comment]
Thanks, I have updated the INSTALL file. Perhaps worth mentioning is that if you install from a release tarball you don't need to worry about antlr, as the files are included. Of course now that you have it working, you can get the latest from trunk, which is also good :-)
