### ISSUE TITLE
Question: Could forked-daaph be used to route MPD music from another place to my Airplay / Chromecast speakers?

### ISSUE THREAD

**Issue by imbaimbaimba** [ejurgensen/forked-daapd#667]
Hi everyone,

I built a Phoniebox for my daughter. Reference: https://github.com/MiczFlor/RPi-Jukebox-RFID
What it does, it start playing her favorite music when an RFID tag is read by an attached reader. All works great, except for the fact that I want it to play from our living room speaker instead of speakers attached to the Raspberry.

Our wireless speaker supports airplay 1, airplay 2 and chromecast, but I just need to figure out a way to route everything it plays(which is via MPD) to the speaker. I stumbled upon this project, and it seemed like it could be the way to go.

I am sorry, but I am almost completely a newbie with coding/raspberries and all this stuff. I don't expect you guys to spent a lot of time giving me a lenghty answer, I would just like to know if I should look more into this project?

**Comment by snizzleorg** [comment]
You would need to install forked-Daapd on the new Phobie-Box and set up mod to output the audio to a pipe which then would be read by forked-Daapd which would then output to airplay. Be aware however that this will introduce a several second delay.... maybe not very user friendly and always for your daughter if she expects playback and that only starts five seconds later...

**Comment by imbaimbaimba** [comment]
> You would need to install forked-Daapd on the new Phobie-Box and set up mod to output the audio to a pipe which then would be read by forked-Daapd which would then output to airplay. Be aware however that this will introduce a several second delay.... maybe not very user friendly and always for your daughter if she expects playback and that only starts five seconds later...

Thank you for you reply. I've really been digging into this, but just cannot make it happen.

The default MPD output for Phoniebox works perfectly, and plays through the HDMI to my TV:
```
#
audio_output {
        type            "alsa"
        name            "My ALSA Device"
#       device          "hw:0,0"        # optional
#       mixer_type      "hardware"      # optional
#       mixer_device    "default"       # optional
        mixer_control   "PCM"           # optional
#       mixer_index     "0"             # optional
}
#
```

So I assume it is the pipe output I need to put in, and I tried to fill that in. However, when I uncomment and put something there, nothing plays. Even the ALSA output does not work anymore. What I have tried to put in is:

```
#
audio_output {
        type            "pipe"
        name            "my pipe"
        command         "aplay -f cd 2>/home/pi/RPi-Jukebox-RFID/shared/audiofo$
## Or if you're want to use AudioCompress
#       command         "AudioCompress -m | aplay -f cd 2>/dev/null"
## Or to send raw PCM stream through PCM:
#       command         "nc example.org 8765"
#       format          "44100:16:2"
}
#
```
`/home/pi/RPi-Jukebox-RFID/shared/audiofolders` is the standard folder for phoniebox media, so I thought putting it in the same place would make it simple.

Can you guide me?

**Comment by snizzleorg** [comment]
i've got no idea of how mad pipe output is working. But if it works it makes sense that you do not get any output. instead the output will be directed to the pipe specified (```/home/pi/RPi-Jukebox-RFID/shared/audiofo```).

This pipe now has to be read by forked-daapd. So it should be in forked-daapds music folder.

**Comment by imbaimbaimba** [comment]
I can't seem to get it to work. Nothing ends in the pipe output unfortunately.

**Comment by snizzleorg** [comment]
did you create the pipe (mkfifo) first?

**Comment by ejurgensen** [comment]
Closing, no feedback
