### ISSUE TITLE
inconsistency conffile.c and airplay code

### ISSUE THREAD

**Issue by th0u** [ejurgensen/forked-daapd#688]
Hello,
I just compiled the latest code.
forked-daapd reports in messages: no such option 'permanent'.
This option is in my config under airplay.
After removing this option, forked-daapd crashes with assertion error
forked-daapd: confuse.c:255: cfg_opt_getnbool: Assertion `opt && opt->type == CFGT_BOOL' failed.
due to this line in raop.c

if (airplay && cfg_getbool(airplay, "permanent") && (port < 0))
    {
      DPRINTF(E_INFO, L_RAOP, "AirPlay device '%s' disappeared, but set as permanent in config\n", at_name);

      return;
    }

So, imho possible solutions:
add  CFG_BOOL("permanent",cfg_false,CFGF_NONE) to airplay in  conffile.c 
drop code from raop.c

Workaround for precompiled binaries:
remove airplay reference from conf-file to prevent crash

Kind regards, T.

**Comment by ejurgensen** [comment]
Thanks for reporting, should be fixed now. Guess I must I have forgotten to include conffile.c in the commit, otherwise I don't understand how that could happen.
