### ISSUE TITLE
Docs - avahi-daemon has to be installed manually on Ubuntu 16.04.05

### ISSUE THREAD

**Issue by TomHarrop** [ejurgensen/forked-daapd#696]
Just installed the current version of `forked-daapd` on a fresh Ubuntu server 16.04.05 VM (can't use a newer ubuntu VM on my version of FreeNAS).

I also had to install `avahi-daemon` manually via apt, as it wasn't installed as a dependency of the packages you have listed in the README.

https://github.com/ejurgensen/forked-daapd/blob/09c1cf15639766853f1cb8f3e7c92916791bda95/INSTALL#L29-L34

BTW I was starting fresh from an ancient version of `forked-daapd`, and everything is working great. Thanks a lot!

**Comment by ejurgensen** [comment]
Thanks, I have added this to the docs. Since it isn't strictly a build dependency, I have added it in the post-build instructions at the end of the INSTALL file.
