### ISSUE TITLE
How would you deal with this scenario?

### ISSUE THREAD

**Issue by lancelon** [ejurgensen/forked-daapd#707]
On a daily basis using a cron job, I'm downloading two podcasts. The file format is AAC and the MP4s don't acquire proper tags ID3 during the downloading process. So in my library I have "unknown artist" for my two very different podcasts. I want to automatically stream them to my speakers.
I'm able to select them by looking up their "id" in the library and then play them with the API. But that's a manual process and presumably the "id" will change daily for both files as the files change.
Any ideas how I can reliably select the files based on either PATH or FILENAME?
Thank you for this software!
(Or option C that I haven't thought of and which is superior!)

**Comment by lancelon** [comment]
Looking at smart playlists...maybe the answer is a smart playlist where the smart playlist is concerned with the path? So long as the path also includes the filename that might do it? To experiment.
`"Smart Playlist" { path is /home/pi/media/podcast.mp4 }`

**Comment by chme** [comment]
Using a smart playlist based on the path should work reliably.

A somewhat recent addition is the support for adding items to the queue (and starting playback) by a smart playlist query expression: https://github.com/ejurgensen/forked-daapd/blob/master/README_JSON_API.md#adding-items-to-the-queue

```
curl -X POST "http://localhost:3689/api/queue/items/add?expression=path+is"%2Fhome%2Fpi%2Fmedia%2Fpodcast.mp4"&shuffle=false&clear=true&playback=start
```

(clears the current queue, turns shuffle off, adds the file `/home/pi/media/podcast.mp4` to the queue and starts playback)

**Comment by lancelon** [comment]
Hmm, thanks, currently use of smart playlists causes forked-daapd to lockup. Either on initial boot or if you click "update library". The error is "forked-daapd.service: Failed with result 'signal'."

The smart playlist contains:

"Woman's Hour" path is /home/pi/macmini/WH.mp4 but I also tried
"Woman's Hour" { path is /home/pi/macmini/WH.mp4 }

**Comment by lancelon** [comment]
Don't know if it's linked but can't get your curl POST command to work either. I don't get any response from forked-daapd but THIS works as an example of a command which does function.

`curl -X PUT "http://192.168.0.12:3689/api/queue/clear" && curl -X POST "http://localhost:3689/api/queue/items/add?uris=library:playlist:68,library:artist:6893583638538127757" && curl -X PUT "http://192.168.0.12:3689/api/player/play"`

**Comment by chme** [comment]
forked-daapd has issues if the smart playlist does not follow the syntax.
It should work, if you add the missing `"` to the path:

```
"Woman's Hour" { path is "/home/pi/macmini/WH.mp4" }
```

The curl command i posted is only available, if you are building forked-daapd from git (it is not yet part of a released version).

**Comment by lancelon** [comment]
Is there any way to upgrade the forked-daapd I installed using the Raspbian instructions to include this (beta release?) command? Is the Raspbian install more of a binary? When I tried to follow the Debian instructions it wanted to install a HUGE amount of extra dependencies.

**Comment by ejurgensen** [comment]
I expect to make a new RPi release within a couple of days, so then you should be able to get the improvement with a simple apt update.

**Comment by ejurgensen** [comment]
I have now made a release (26.5) + an RPi build update (26.5.80).

**Comment by lancelon** [comment]
Thanks - strange - I'm on Pi version 27 but CURL commands like

`POST "http://192.168.0.124:3689/api/queue/items/add?expression=path+is"%2Fsrv%2Fmusic%2Fr4.m3u"&shuffle=false&clear=true&playback=start`

don't work, but

`curl -X PUT "http://192.168.0.124:3689/api/queue/clear" && curl -X POST "http://192.168.0.124:3689/api/queue/items/add?urilist:8" && curl -X PUT "http://192.168.0.124:3689/api/player/play"`

does?!

When I do the former command, I get a prompt `> ` and I have to send the clear/break command to exit that sub prompt.

Probably something silly I'm doing wrong?!

**Comment by chme** [comment]
In the first command you need to escape the `"` in the url and there is a `+` missing after "path+is":

```shell
curl -X POST "http://192.168.0.124:3689/api/queue/items/add?expression=path+is+"%2Fsrv%2Fmusic%2Fr4.m3u"&shuffle=false&clear=true&playback=start
```

But this request will lead to zero items being added. The query language allows to select songs and this query would require a song to have the path `/srv/music/Fr4.m3u`. If you want to add the tracks of a playlist, the only supported way is to add it with its uri:

```shell
curl -X POST "http://192.168.0.124:3689/api/queue/items/add?uris=library:playlist:68&shuffle=false&clear=true&playback=start
```

You can find out the uri of a playlist by fetching the list of playlists: https://github.com/ejurgensen/forked-daapd/blob/master/README_JSON_API.md#list-playlists
