### ISSUE TITLE
No autostart at boot

### ISSUE THREAD

**Issue by dmikhalsky** [ejurgensen/forked-daapd#712]
Hw: RPI3A+ SW: latest Stretch
I've installed forked-daapd from a repository as per manual. When I boot and then try to access the service via: http://myip:3689, I've got no connection.
**systemctl status forked-daapd**  shows "**started**", but the connection restores only if I stop/start the service via sytemctl.
I do not see **forked-daapd.service** file in **/etc/systemd/system**. Shall it be there?

**Comment by whatdoineed2do** [comment]
Try running:
```
$ systemctl status forked-daapd
```
and look for *enabled*
```
forked-daapd.service; enabled; vendor preset: enabled
```
If that is not set, run the below and that should do it.
```
$ sudo systemctl enable forked-daapd
```

**Comment by dmikhalsky** [comment]
I've tried `$ sudo systemctl enable forked-daapd `, it doesn't help

**Comment by ejurgensen** [comment]
The service file should be installed here: /lib/systemd/system/forked-daapd.service. I have tested with "apt install forked-daapd" on my RPi and the file does get installed. Are you running Raspbian Stretch?

Like @whatdoineed2do says you should also check what `systemctl status forked-daapd` outputs.
