### ISSUE TITLE
Can only access web interface from localhost

### ISSUE THREAD

**Issue by mananapr** [ejurgensen/forked-daapd#719]
I am running forked-daapd 26.5 on macOS 10.10

In my config I have added `any` in the `trusted_networks` field as shown below: 
` trusted_networks = { "localhost", "192.168", "fd", "any" }`

Even after adding this and restarting the server I cannot open the web interface from any other device in the local network. I noticed the following line in my log which I think may be causing this issue:
`[2019-04-12 13:33:52] [  LOG]    httpd: Could not bind to port 3689 with IPv4, listening on IPv6 only`

What is going on here? Let me know If I need to provide any other information.

**Comment by ejurgensen** [comment]
This is typically the error if the previous instance of forked-daapd is still running. So before you start it, make sure to stop/kill any existing instances.

**Comment by mananapr** [comment]
Thanks for replying, but I am still facing this issue. I did the following to make sure I was running a single instance of forked-daapd:

- Rebooted my machine
- Confirmed `forked-daapd` wasn't running by checking the output of `ps aux | grep forked-daapd` and `dns-sd -B _daap._tcp`
- Then started `forked-daapd` using `sudo /usr/local/sbin/forked-daapd`. Both `ps aux | grep forked-daapd` and `dns-sd -B _daap._tcp` confirmed `forked-daapd` was running.
- Web interface worked on the same machine itself, but accessing the web interface from other devices on the LAN gave a connection timed out error after some time.

[log](https://pst.moe/paste/tjmhse)
[config](https://pst.moe/paste/tpqgjs)

**Comment by ejurgensen** [comment]
Ok, that's odd. Then maybe something else is using port 3689? I'm not sure how to check that with macOS (does it have netstat?). Maybe it is iTunes itself?

**Comment by mananapr** [comment]
There is no instance of iTunes running. macOS does has netstat but I don't know much about netstat. Also I tried changing the port to 3680 in the config but I am still getting the same error

**Comment by mananapr** [comment]
I am now able to access the server from other devices. I just had to disable the firewall as shown [here](https://coderwall.com/p/zt8aqa/disable-mac-osx-firewall-from-command-line). But now I am just greeted with a blank screen. The logs show the following errors:

`[2019-04-12 15:57:57] [  LOG]    httpd: Could not open /usr/local/share/forked-daapd/htdocs/player/css/app.css: Too many open files`
`[2019-04-12 15:57:58] [  LOG]    httpd: Could not open /usr/local/share/forked-daapd/htdocs/player/js/chunk-vendors.js: Too many open files`
`[2019-04-12 15:57:58] [  LOG]    httpd: Could not open /usr/local/share/forked-daapd/htdocs/player/js/app.js: Too many open files`
`[2019-04-12 15:57:59] [  LOG]    httpd: Could not open /usr/local/share/forked-daapd/htdocs/apple-touch-icon.png: Too many open files`

**Comment by ejurgensen** [comment]
I can't really help you much with mac OS, my only suggestion would be to google "Too many open files", perhaps mac OS has much lower limit than Linux

**Comment by mananapr** [comment]
I fixed it by changing the limit from 512 to 4096. Thanks!
