### ISSUE TITLE
Player pop/click when change of sample rate

### ISSUE THREAD

**Issue by whatdoineed2do** [ejurgensen/forked-daapd#722]
With the new player implementation I find that when we start playing next tracks of different sample rates (going from a 44.1khz to a 48khz track) I hear an audioable pop and click.

This wasn’t apparent in the previous version but I assume this was because the output sample rate never changed (locked at 44.1).

I recall seeing issues like before in other s/w and can not determine if fixes are in the kernel driver or whether this can be alleviated in appl code.

I only notice this on my RPi3 which has an allo boss dac as output - my RPi1 with audio out via headphone jack is not so apparent.

**Comment by ejurgensen** [comment]
Yes, I imagine that a possible cause is that the new player changes the sample rate while the device has audio in its buffer. Perhaps the device reacts to that by dropping the buffer? So I think I will change alsa so the sample rate isn't changed until the device buffer is empty. It requires a bit of work, so can't do it right now.
