### ISSUE TITLE
All playlists are duplicated

### ISSUE THREAD

**Issue by chesterdkat** [ejurgensen/forked-daapd#723]
All my playlists are duplicated in forked-daapd. My iTunes library is Rsynced every night from my Mac and the "--delete" command is present. Config files are not duplicated on my forked-daapd instance. I have forked-daapd running on a Raspberry Pi, Stretch.

Thanks...

**Comment by ejurgensen** [comment]
Playlists are id'ed by the path to the file, so perhaps rsync is making a temporary copy and forked-daapd doesn't register when it gets deleted or moved? You can check if this is the issue with:
```
sqlite3 /var/cache/forked-daapd/songs3.db
select id,title,path from playlists;
.quit
```

**Comment by ejurgensen** [comment]
Closing, no feedback
