### ISSUE TITLE
websocket binding to IPv6 even when IPv6 is disabled in config

### ISSUE THREAD

**Issue by ali-graham** [ejurgensen/forked-daapd#725]
This may have just been down to a broken network configuration on my side (running in a FreeBSD jail), but the web server was listening at port 3689 over IPv4 and the websocket at port 3688 over IPv6. The simplest thing for me to do to fix this was the following:

```diff
diff --git a/src/websocket.c b/src/websocket.c
index 6cb41a2b..e2b43026 100644
--- a/src/websocket.c
+++ b/src/websocket.c
@@ -381,6 +381,8 @@ websocket_init(void)
   memset(&info, 0, sizeof(info));
   info.port = websocket_port;
   info.protocols = protocols;
+  if (!cfg_getbool(cfg_getsec(cfg, "general"), "ipv6"))
+    info.options |= LWS_SERVER_OPTION_DISABLE_IPV6;
   info.gid = -1;
   info.uid = -1;
```

I just thought I'd put this here in case people are having similar problems, make it searchable -- please close the issue if it's not a change you want to make.

**Comment by chme** [comment]
The change looks correct. Do you want to submit a pull request or should i commit the change?

**Comment by ali-graham** [comment]
Thanks for looking at it, just submitted the PR.
