### ISSUE TITLE
Mp3 support

### ISSUE THREAD

**Issue by BipBip1981** [ejurgensen/forked-daapd#727]
All my mp3 files never show on library, it's normal or not?

**Comment by whatdoineed2do** [comment]
Not normal.  Some basic checks against your `forked-daapd.conf`:

* `directories = { "/export/public/music" }` - are the paths in the `{` .. `}` where you are adding your mp3s and does the user running the server have access to this dir
* `filescan_disable = false` - is this commented out or `false`?  If not, set this as `false` and restart your server

The other Q is are any music files added shown up in your library?  And how are you verifying files are not being added?  Are you able to see anything on the web inerface?

Setting the `loglevel = debug` in cfg and restarting should also give you an idea of what might be not expecting.

**Comment by BipBip1981** [comment]
Thank a lot, with you advise to activate loglevel = debug i find my mistake on file rights & owner
have a good day
