### ISSUE TITLE
Am I right that forked-daapd isn't that suitable for audiobooks?

### ISSUE THREAD

**Issue by lancelon** [ejurgensen/forked-daapd#728]
I am trying to stream audiobooks to my son in his bedroom but I'm finding I can't move the playhead - the files are often 1hr long (or longer). Where is this limitation coming from? The server, the iPhone remote control or forked-daapd itself?

Thanks

**Comment by whatdoineed2do** [comment]
I'm scrubbing a ~50 minute long mp3 file using forked-daapd's web interface and it works as expected.  I can't seem to get iphone Remote appl to pair at the moment to test though

**Comment by jptrsn** [comment]
@lancelon are you running it on a Raspberry Pi 3 B+? I've had no issues moving play head, but there is some latency between my commands (either from the web interface or using Retune android app) and the response. I would say that audio books would be a challenge, as there doesn't appear to be any facility to retain the progress in a partially-played track.

**Comment by ejurgensen** [comment]
There shouldn't be any limit on how long a track can be. I will test with a few long tracks to see if I can reproduce. @jptrsn if a track is recognised as an audio book, forked-daapd should save the play position and resume from that position, thus retaining progress.

**Comment by lancelon** [comment]
Hi, I'm running Forked-Daapd on a Zero W with 512mb of RAM (the audiobooks are hosted on an old Mac Mini mounted using SMB)

**Comment by lancelon** [comment]
[I've made a GIF!](https://imgur.com/G6KB8bZ)

**Comment by ejurgensen** [comment]
Can you share the mp3? My email is espenjurgensen@gmail.com

**Comment by lancelon** [comment]
https://www.dropbox.com/s/ryy1367i0ya1jwn/BK_BBCW_003202UK.mp3?dl=0
I'll take it down in a few days to avoid any copyright issues!

**Comment by ejurgensen** [comment]
Thanks for the file. I can reproduce the issue on my RPi2, though the max position is further ahead than yours. On my dev machine the issue does not reproduce, so I will have to debug via the RPi2, which is a bit more cumbersome.

**Comment by lancelon** [comment]
Interesting, thanks. I wonder what causes it. Processing power (or lack of?) on the RPi?

**Comment by ejurgensen** [comment]
I have found the cause, and it is because forked-daapd has a 15 second timeout (here: https://github.com/ejurgensen/forked-daapd/blob/master/src/transcode.c#L53) on this type of operation. The log actually says it, but somehow I missed it.

Seeking in a large mp3 file like yours takes a while for ffmpeg on devices like the zero and my RPi2. I will check if there are any ways of speeding up that seek. If not, there is only the option of extending or removing the timeout, but I'm not sure that is a good idea.

**Comment by chme** [comment]
Yesterday i ran into this timeout too. In my case it was opening a music file located on my NAS (mounted with nfs). The NAS needed to wake up from its power saving mode and this can take some time (apparently sometimes even more than 15 seconds).

I think a timeout needs to be in place but maybe we can increase it to 30 seconds?

**Comment by ejurgensen** [comment]
Ok, I have increased the timeout to 30 seconds

**Comment by lancelon** [comment]
Is there an easy way to keep the raspberry pi 'edition' of forked-daapd up to date? Last time I tried to update I think I did it via Git and[ it borked the setup](https://github.com/ejurgensen/forked-daapd/issues/843?email_source=notifications) ! :-D

**Comment by ejurgensen** [comment]
I would recommend that you use apt, so like this:
https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=49928

I keep the RPi build fairly updated.
