### ISSUE TITLE
does FD server icy/shoutcast metadata?

### ISSUE THREAD

**Issue by whatdoineed2do** [ejurgensen/forked-daapd#730]
I have an Roku Soundbridge M1000 that connects to forked-daapd's mp3 stream. - the Roku doesn't display any metadata updates (no artist/title etc) but I can't tell if the server is not sending the right metadata or if the Roku is not requesting it.

I connected ffmpeg to stream.mp3 (from before anything starts to play) but I also dont see any metadata except for `icy-name`
```
$ ffmpeg -hide_banner -icy 1 -icy_metadata_headers 1 -icy_metadata_packet 1 -i http://localhost:3689/stream.mp3 -f null /dev/null
Input #0, mp3, from 'http://localhost:3689/stream.mp3':
  Metadata:
    icy-name        : My Music on beats
  Duration: N/A, start: 0.000000, bitrate: 128 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 128 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mp3 (mp3float) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, null, to '/dev/null':
  Metadata:
    icy-name        : My Music on beats
    encoder         : Lavf58.12.100
    Stream #0:0: Audio: pcm_s16le, 44100 Hz, stereo, s16, 1411 kb/s
    Metadata:
      encoder         : Lavc58.18.100 pcm_s16le
size=N/A time=00:04:53.04 bitrate=N/A speed=   1x    
```
In `http.c` I see references to `icy` tags.

Does the server support sending meta and does it send meta for when songs change?

**Comment by whatdoineed2do** [comment]
Having had a dig around, it looks like when we request `stream.mp3` and the underling input is a file in the library, the internals are not setup to deliver `icy` metadata - this metadata is only delivered when the input type is of type `DATA_KIND_HTTP`

The interval to re-read the meta:
```
transcode_encode_setup(...)
  ...
  if (ctx->settings.icy && src_ctx->data_kind == DATA_KIND_HTTP)
    {
      bps = av_get_bytes_per_sample(ctx->settings.sample_format);
      ctx->icy_interval = METADATA_ICY_INTERVAL * ctx->settings.channels * bps * ctx->settings.sample_rate;
```
and the `metadata_get` callback is not set for `INPUT_TYPE_FILES`:
```
struct input_definition input_file =
{
  .name = "file",
  .type = INPUT_TYPE_FILE,
  .disabled = 0,
  .setup = setup,
  .play = play,
  .stop = stop,
  .seek = seek,
};

struct input_definition input_http =
{
  .name = "http",
  .type = INPUT_TYPE_HTTP,
  .disabled = 0,
  .setup = setup_http,
  .play = play,
  .stop = stop,
  .metadata_get = metadata_get_http,
};
```
I'll see if I can patch this

**Comment by whatdoineed2do** [comment]
For those interested, the Roku Soundbridge does support ICY stream metadata (as per memory from the early 2000s) but server does not currently support sending.

PR submitted to honor ICY meta requests in the server.

**Comment by whatdoineed2do** [comment]
Some notes for testing/working players (as per merge: 0941cf51ff6ed46e9f223ed9c2fad896312b5ed5)

Requests `Icy-MetaData` and displays `StreamTitle` meta data contents:
* Roku SoundBridge M1000 - sometimes struggles when streaming whilst song in mid play
* Roku SoundBridge M500
* linux/mpv
* linux/ffmpeg 4.0.3 - does not respond to track changes (`ffmpeg -i http://forked-dapp.local:3689/stream.mp3 -f null -` to observe)

Does NOT request `Icy-MetaData`
* web browsers (firefox/safari/chrome)
* windows VLC 3.0.7.1
* windows itunes 12.9

**Comment by gorshunovr** [comment]
Thanks @whatdoineed2do for the correct `-icy 1 -icy_metadata_headers 1 -icy_metadata_packet 1` options. For those searching on how to reuse Icecast metadata in [ffmpeg drawtext metadata](https://ffmpeg.org/ffmpeg-filters.html#Text-expansion) – I couldn't find the way.
