### ISSUE TITLE
Spotify failing to connect

### ISSUE THREAD

**Issue by cdlenfert** [ejurgensen/forked-daapd#731]
I have 2 devices, similar hardware, on Debian Stretch. At work my device has updated Forked-Daapd via the install process and Spotify authenticates and works fine. Trying to do the same process on the home device fails. Here are some of the errors I'm hitting:

In the browser after clicking "authorize web api access" from the FD admin page - "Error: Did not get a reply from Spotify"

In my log file says:
```
Login to Spotify succeeded (libspotify)
OAuth request: '/oauth/spotify?code='loooong token here'
Request to https://accounts.spotify.com/api/token failed: Problem with the SSL CA cert (path? access rights?)
```
Some things I've tried:

update-ca-certificates
libcurl4-gnutls-dev is installed
rebuilding and reinstalling doesn't help
rebooting server doesn't help
date/time are correct when I check
tried different browsers
made sure I was not going through an ad blocker (pihole)

Everything else in the install seems to be working fine. What else can I try?

**Comment by cdlenfert** [comment]
I finally decided to delete my "forked-daapd" folder where the git repo is cloned and rebuild from scratch. After doing this the Spotify authorization worked on the first try. I'm not sure why that is the case, but my issue is resolved.

**Comment by cdlenfert** [comment]
Just an update I tried building again from the existing forked-daapd folder after reverting the git repo to tag 26.5 and after the build I'm getting the same Spotify error. I did the same on another device with no issue continuing to connect to Spotify. Didn't need to re-authenticate in that case.

**Comment by cdlenfert** [comment]
re-opening this because the same solution I used before (recreating the forked-daapd install folder) didn't allow me to log in again. I also vanquished the spotify credentials folder `rm -r /var/cache/forked-daapd/libspotify`

**Comment by cdlenfert** [comment]
Another difference between the working and not working devices is that I'm running a VPN server on the device that's not working. I'm not very familiar with certificates and Spotify authentication, but maybe that's creating the issue. Previously when troubleshooting I disabled the VPN server and that could have helped get the Spotify authentication working again. [The VPN server script I'm using is here](https://github.com/hwdsl2/setup-ipsec-vpn).

**Comment by cdlenfert** [comment]
It's lonely in this issue (as it should be :) I think I figured it out though. I'm guessing the VPN server script removed one of the dependencies for forked-daapd. Specifically `libcurl4-nss-dev` was removed and replaced with `libcurl4-gnutls-dev` Here's the terminal output from reinstalling the dependencies:

```
root@pogoplug:~/forked-daapd# apt-get --reinstall install build-essential git autotools-dev autoconf automake libtool gettext gawk gperf antlr3 libantlr3c-dev libconfuse-dev libunistring-dev libsqlite3-dev libavcodec-dev libavformat-dev libavfilter-dev libswscale-dev libavutil-dev libasound2-dev libmxml-dev libgcrypt20-dev libavahi-client-dev zlib1g-dev libevent-dev libplist-dev libsodium-dev libjson-c-dev libwebsockets-dev libcurl4-gnutls-dev libspotify-dev

Reading package lists... Done

Building dependency tree       

Reading state information... Done

The following packages were automatically installed and are no longer required:

  libcurl3-nss libprotobuf-c1

Use 'apt autoremove' to remove them.

Suggested packages:

  libcurl4-doc libcurl3-dbg libgnutls28-dev libidn11-dev libkrb5-dev libldap2-dev librtmp-dev libssh2-1-dev

The following packages will be REMOVED:

  libcurl4-nss-dev

The following NEW packages will be installed:

  libcurl4-gnutls-dev
```
Once I reinstalled the deps I didn't even have to reauthenticate Spotify. It just worked.

**Comment by ejurgensen** [comment]
Thanks for the update. Well done finding the cause, sounds like it was pretty hidden.
