### ISSUE TITLE
Sort artistname

### ISSUE THREAD

**Issue by johnappletree** [ejurgensen/forked-daapd#735]
Hi there, 

is there a possibility to change the sorting style of the artist name? Currentlly  "amy winehouse" gets listed at the "w" section but I would like it to appear in the "a" section. Is this configurable?

Thanks!

JA

**Comment by whatdoineed2do** [comment]
It’s probably the metadata on the file where you will have `artist` and `artist_sort` / `album_artist_sort` set.. one of the latter tags will have “Winehouse, Amy” which is causing this server to sort like this


You can verify using `ffprobe -hide_banner -i foo-meta.mp3` and seeing what tags are in the file and then updating accordingly

**Comment by johnappletree** [comment]
Exactly that's it! Did not known this was baked into the metadata.  Thanks!
