### ISSUE TITLE
macOS & mxml?

### ISSUE THREAD

**Issue by ajmas** [ejurgensen/forked-daapd#737]
I have followed the steps for the Mac, using Macports:

```
sudo port install \
  autoconf automake libtool pkgconfig git gperf libgcrypt \
  libunistring libconfuse ffmpeg libevent json-c libwebsockets
```

Then later when I run `./configure` I get told `No package 'mxml' found`.

I can't seem to find this library in MacPorts. Will I need to request this package from the MacPorts maintainers or is there another way you would recommend?

BTW INSTALL file I am looking at is the latest on matser (a5674cb).

Same issue with release 26.5.

**Comment by ejurgensen** [comment]
I can't offer a lot of help with MacOS, other people contributed with the compability plus instructions, and they are probably not around any more.

The INSTALL file has the following instructions. did you try these:

> Download, configure, build and install the Mini-XML library:
>   http://www.msweet.org/projects.php/Mini-XML
