### ISSUE TITLE
Initiate Adding/Playing http streams via web for item not in library without a .m3u playlist

### ISSUE THREAD

**Issue by whatdoineed2do** [ejurgensen/forked-daapd#739]
I use `forked daapd` as my main music server - it sits running off a headless raspberry pi connected to my amp and it's controlled via my phone or tablet.

I frequently discover (adhoc) podcasts or internet radio stations that I'd like play through `forked daapd` - this currently means I need to `ssh` onto the RPI and add these URLs to a playlist file that exists in the library.

Is there appetite to let the `web ui` queue and play arbitrary http streams?

The server will only play items that are in the library already (the json api's `queue add` endpoint lets you queue/play using a SMART expression that can include `path is /export/music/some-file-in-my-library.mp3`) so the db itself looks like it doesn't care how the item was added, but to play an item, it must be first added to the db (via file scan or as part of a playlist).

To allow such streams to be removed from library, and to keep within current strucutre, this could be implemented by automagically creating playlist files under a special directory (like the `Audiobooks`) so the server will auto scan and add the item to library.

Thoughts?

**Comment by chme** [comment]
It is already possible to play any http stream with forked-daapd. It is not required, that this stream is in a playlist / scanned into the library.

The JSON API supports this by calling `queue/items/add?uris="http://path/to/mp3.stream"`. It is just not (yet) exposed in the web interface.

**Comment by whatdoineed2do** [comment]
Would you be comfortable with a button on the `Queue` web page that brings up a modal to allow entering the URL and then calling to the back to add?  If so I'll make the change for the PR -- it'll be better than having ot ssh into the box every time to do this....

**Comment by whatdoineed2do** [comment]
Theres a minor fix required to play some internet podcasts now (they're behind a `https`) and the filescanner only allowed `http` streams.  I've added this to the currenttly open PR (https://github.com/ejurgensen/forked-daapd/pull/718) - let me know if you prefer this on its own
