### ISSUE TITLE
chromecast exclude option removed from master

### ISSUE THREAD

**Issue by whatdoineed2do** [ejurgensen/forked-daapd#743]
This commit 741825d086136d0019a0bb37cbcbf81d78286f4b allows us to exclude chromecast devices from speaker/output list.

However it no longer in master and was removed in f8b0147b.  Was there a problem with such chromecast exclusions?

**Comment by ejurgensen** [comment]
No, the exclude option is/was fine, so that was a mistake. Not sure how it happened, but I will put it back in.

**Comment by ejurgensen** [comment]
The option should be working again now
