### ISSUE TITLE
Forked-daapd no longer "makes" on Debian Jessie

### ISSUE THREAD

**Issue by marioscube** [ejurgensen/forked-daapd#749]
What I did:

apt-get install ...... = all ok
git clone https://github.com/ejurgensen/forked-daapd.git
cd forked-daapd
autoreconf -i
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --disable-webinterface
make

Then I get the error:
mv -f $depbase.Tpo $depbase.Po
library/filescanner_ffmpeg.c: In function ‘scan_metadata_ffmpeg’:
library/filescanner_ffmpeg.c:441:35: error: ‘AVStream’ has no member named ‘codecpar’
       codec_type = ctx->streams[i]->codecpar->codec_type;
                                   ^
library/filescanner_ffmpeg.c:442:33: error: ‘AVStream’ has no member named ‘codecpar’
       codec_id = ctx->streams[i]->codecpar->codec_id;
                                 ^
library/filescanner_ffmpeg.c:443:36: error: ‘AVStream’ has no member named ‘codecpar’
       sample_rate = ctx->streams[i]->codecpar->sample_rate;
                                    ^
library/filescanner_ffmpeg.c:444:35: error: ‘AVStream’ has no member named ‘codecpar’
       sample_fmt = ctx->streams[i]->codecpar->format;
                                   ^
Makefile:782: recipe for target 'library/filescanner_ffmpeg.o' failed
make[3]: *** [library/filescanner_ffmpeg.o] Error 1
make[3]: Leaving directory '/home/debian/source/forked-daapd/src'
Makefile:548: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/debian/source/forked-daapd/src'
Makefile:613: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/debian/source/forked-daapd'
Makefile:454: recipe for target 'all' failed
make: *** [all] Error 2

A version from git on april 8th worked.
Tried on 2 PC's with Debian Jessie.

**Comment by ejurgensen** [comment]
Yes, I have dropped support for Jessie's version of ffmpeg, it is pretty old. The latest release of forked-daapd (26.5) does however support it, so if you don't want to upgrade you should be able to build that.

**Comment by raufis27** [comment]
Which version of ffmpeg do we need ?
I have 4.2.1 installed but build fails:

library/filescanner_ffmpeg.c: In function ‘scan_metadata_ffmpeg’:
library/filescanner_ffmpeg.c:442:35: error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’
       codec_type = ctx->streams[i]->codecpar->codec_type;
                                   ^
library/filescanner_ffmpeg.c:443:33: error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’
       codec_id = ctx->streams[i]->codecpar->codec_id;
                                 ^
library/filescanner_ffmpeg.c:444:36: error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’
       sample_rate = ctx->streams[i]->codecpar->sample_rate;
                                    ^
library/filescanner_ffmpeg.c:445:35: error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’
       sample_fmt = ctx->streams[i]->codecpar->format;
                                   ^
library/filescanner_ffmpeg.c:446:33: error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’
       channels = ctx->streams[i]->codecpar->channels;

- ffmpeg -version
ffmpeg version 4.2.1-2~16.04.york2 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 20160609
