### ISSUE TITLE
Working with Windows 10

### ISSUE THREAD

**Issue by vdbpeter** [ejurgensen/forked-daapd#753]
Hi
Looking for clues to solve an end-to-end issue relating to Microsoft Windows and forked-daapd.

My forked-daapd server is v24,2 (part of Openmediavault NAS 4 on Debian 9 Stretch). The server works fine with my Roku Soundbridge 1001 (although it's probably using RSP),  Android "DAAP  Media Client" and Amarok w/DAAP on Debian 9 Stretch KDE.

It refuses to work on Windows 7 & 10. I have tried iTunes 12.7 (now know that will never work), WinAMP w/DAAP plugin (Network Media group is visible, but no DAAP server), Amarok with DAAP plugin enabled.

I have the Bonjour service running on Windows 7 & 10. I can verify Zeroconf registrations using "Bonjour Browser" on the Windows machine. The PC firewall is off.

All machines have consistent Zeroconf data:
 avahi-browse -r  _daap._tcp
+ enx001e0631a142 IPv4 My Music on omv7                              iTunes Audio Access  local
= enx001e0631a142 IPv4 My Music on omv7                              iTunes Audio Access  local
   hostname = [omv7.local]
   address = [10.0.0.141]
   port = [3689]
   txt = ["ffid=41bd78fa" "Password=false" "Version=196610" "iTSh Version=131073" "mtd-version=24.2" "Machine Name=My Music on omv7" "Machine ID=C6505D92" "Database ID=C6505D92" "txtvers=1"]

Am looking for any experience getting DAAP working on Windows.

Thanks

**Comment by ejurgensen** [comment]
Please be more specific about what “doesn’t work” means. Does the library not show up?

I do test with iTunes on Windows, last time a few weeks ago, and it worked ok.

**Comment by vdbpeter** [comment]
Correct. The Library or server does not show up in any of the apps.

Your experience offers some hope. Can you describe how you set up iTunes on Win10, please? What version? Was it installed from the Microsoft Store? (Only way to get it now).

I suspect the issue is somewhere in Win10. I have set up 2 Win10 machines, each with iTunes 12.9.5.7 (sorry- not 12.7 as above), each sharing a Music Library, each registering Zeroconf, each machine with firewall off, but still nothing.

Thanks

**Comment by vdbpeter** [comment]
Feeling quite silly...I found the issue and iTunes does work. 

I found my servers/libraries listed in the "Music" button dropdown top left of the app.

The others apps still dont appear to work, but at least it's not a "forked-daapd" issue.

Thanks for your help.

**Comment by ejurgensen** [comment]
Good to hear iTunes is still working, you never know what Apple is up to.

When I get the chance I will check the other clients out.
