### ISSUE TITLE
Spotify queue only offers Stop button in web interface

### ISSUE THREAD

**Issue by cdlenfert** [ejurgensen/forked-daapd#759]
I've built FD from source a couple days ago and I'm finding that when queuing a Spotify list of songs only a stop icon is offered which resets the to beginning of the queue. When playing tracks from my local library the pause option is available and works as expected. I tried restarting FD and no change.

I can gladly get a debug log if it's helpful, but for now I'm guessing it's an easy issue to replicate.

**Comment by chme** [comment]
I noticed this too. It is fixed with #758 (will be merged in the next days).
