### ISSUE TITLE
No Buster Support

### ISSUE THREAD

**Issue by ScharV** [ejurgensen/forked-daapd#762]
This is a very nice fork I used it every day.
Yesterday my PI crashes so I had to set it up new.
I used Raspbian buster but now your api doesn't work anymore.
Would it be possible to add support for Buster?

**Comment by ejurgensen** [comment]
Yes, absolutely. I wasn't aware Raspbian Buster had been released. Also gives me an excuse for buying a new RPi :-)

**Comment by ScharV** [comment]
Sounds good....so there will be a Version thats supports Buster too in Future?

**Comment by ejurgensen** [comment]
Yes, absolutely. I've made a Buster build now, you can get it by following the instructions here: https://www.raspberrypi.org/forums/viewtopic.php?t=49928

Just change stretch to buster when you add the repo to sources.list. So the line to add is:
`deb http://www.gyfgafguf.dk/raspbian/forked-daapd/ buster contrib`

Let me know if it works.

**Comment by ScharV** [comment]
Thanks for this fast Job. I will Check asap and let you know if it works👌🏼

**Comment by ScharV** [comment]
@ejurgensen I have Bad news my Homebridge doesn‘t run correctly under buster before i could Check so i grad to Go back to Stretch....I am sorry 😐

**Comment by orakelet** [comment]
I entered deb http://www.gyfgafguf.dk/raspbian/forked-daapd/ buster contrib into /etc/apt/sources.list and got the error: 
E: Typen «deb http://www.gyfgafguf.dk/raspbian/forked-daapd/ buster» er ukjent i linje 4 i kildelista /etc/apt/sources.list

Any idea why?

**Comment by ejurgensen** [comment]
I'm not an apt expert, but the line looks fine to me, and it is the same I have working on my RPi Buster. Did you add the key? With `wget -q -O - http://www.gyfgafguf.dk/raspbian/forked-daapd.gpg | sudo apt-key add -`

**Comment by orakelet** [comment]
wget -q -O - http://www.gyfgafguf.dk/raspbian/forked-daapd.gpg
wget: nettadresse mangler
Bruk: wget [VALG] … [NETTADRESSE] …
I had to wget without -q and -O manually and then sudo apt-key add forked-daapd.gpg. apt-key returned OK.

**Comment by orakelet** [comment]
Still the same error when i try "sudo apt update"

**Comment by ejurgensen** [comment]
Both are working fine for me, not sure why you are getting those errors.

```
pi@buster:~ $ wget -q -O - http://www.gyfgafguf.dk/raspbian/forked-daapd.gpg
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1

mQENBFm8Wy8BCADtE7tHY4W6701wA2+w6FWjumVmXHW5dM8KIDZW11yUOiSb+WDi
1BPV+WASvYgeR6a4L9z7c9oDG5Msf0mlbf5Z3RrMjMr2GAPaRdK9B5QTk12f9VuS
+bA0La3AKV8cO+mXYDNQmKjTj6dCfbFQZP+eaxiuHdVyNDeRVcn40tB+9bDIOOND
+IH4TuDVAxRzDsc8C0aisccCyEtOAHxD5p9ATOjrN43pGipUmxdhUDAd+tLp2RGF
Vfwi8eELbOgMYZCUS1u+E1vbB8VpKtnOVG4nFMXeuvXMaAaZ28rMxMlGlp5aoi49
Kpm3pAG7eQoK8MW6QquttxkgZjhJ8sediAj7ABEBAAG0NEVzcGVuIErDvHJnZW5z
ZW4gPGVzcGVuanVyZ2Vuc2VuK3Jhc3BiaWFuQGdtYWlsLmNvbT6JATgEEwECACIF
Alm8Wy8CGwMGCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJEPYnkzGYcPT1M+UH
/1BqQlyfo43Gz8iTkp27yEFhkVvtbOqg0lC4R5cqsc5ASDE6tL8TcmgQnzveFJJq
e0ITzZFkfacgu3wYzbqDXiWyAjrfPaF/BAQxJ/qr06hZ/iIr+zsNFUm8bvHA4RAW
W/1MVai8MEADemMgOO6qjh0u42WAv1jM2jRXVWm2BdVCHftEXttQdh9vgep6xd7I
jvaTxp69tGjPMCgoFHTKnqMoMa8Jc1vVtJn41hVk1axX/WdnrnFDQ9DXOiXyzgOD
75VyGTPAXvOtVEyxVhra+ZVTLR41vvt78kF7lUGIF1ON7+rzpYSkv5HCzHjzEIFS
+Ze1Kl/Q2qf+p2ir5zTFb3G5AQ0EWbxbLwEIAN4BYP738akayRD2Xh52zmMnxXtB
wLlyiNw70PhiUYvntPQF4h7CgetUpsHFyIRgcbOnd1UJPUeUZja7d0tyTgC/V5sD
TvtklOgeDrPXnTles3ilikj0DH2FheXpHWS96v2IvO28EpwWXgjbs9TXSNumY7dn
S9/FvLXzwraSrs36OjWO0SwLrtew9aDMl2lrK5HHMWkKToM0kuJWJWM6DVa+NGpM
Ve71GayBPvnxw962piwW8yQui1yeVX0fYo16ObM5BY6fR/K2CKouBA82b76KjEMn
c7q9A1LyYyikMx5eXlcHRtVdqOUwPpvTtnYZDe11uKHpDawbcv4M181etUUAEQEA
AYkBHwQYAQIACQUCWbxbLwIbDAAKCRD2J5MxmHD09XW9B/9av2+Zs6d74NCraFl/
ZMjpfn7OsQFWpYuzXVvTopZNWuf1YsF16O3UpM374pcds+ixRQeZNREzGtG/bjLv
wjJjpe4F6nToB20NX5gOlem3DPwLrJckqLkMTPtX0JCGvsG96DrduBm7uLPIfY1q
MHT/1Z6sK/OD50Hg0R+O81dl9JX5obbPM1jKuWYfmq+7Oda5x1UeO+Qt4xf/POQA
F2oZdbCLFWyQ/2l1BxyyLM8243AJp7L+aJM2lyL5DK5J7Z0sKmwbA/vdMaCT7Sn5
kTGk/4WA9W0ox9IkQQ0Ez+llCd6OhfYflemZHIDcs9w0UM6KVleSoHY0z0HtGzcP
2qom
=V9XJ
-----END PGP PUBLIC KEY BLOCK-----

pi@buster:~ $ sudo apt update
Hit:1 http://www.gyfgafguf.dk/raspbian/forked-daapd buster InRelease
Hit:2 http://archive.raspberrypi.org/debian buster InRelease
Hit:3 http://raspbian.raspberrypi.org/raspbian buster InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.

```

**Comment by orakelet** [comment]
Thanks for your efforts. There must have been some invisible code included when I copied into sources.list
It worked when I manually entered the full line into sources.list
