### ISSUE TITLE
Seek not working for http url streams 

### ISSUE THREAD

**Issue by varadhawriter** [ejurgensen/forked-daapd#764]
I am currently using forkeddaapd 24.2 version.I am not able to seek the http_url stream even after doing all the above changes.
I am able to seek forward.but backward when i try to seek,the seek bar is going to zero.

**Comment by ejurgensen** [comment]
What is the URL?

**Comment by varadhawriter** [comment]
I will give you a sample url http://192.168.0.187:8989/getFile?fileName=Local.mp3 streaming from local mobile app

**Comment by ejurgensen** [comment]
Can you provide a public URL?

**Comment by varadhawriter** [comment]
The mobile songs are sent as Http URL based on the router and gets decoded in the libav.
I am not sure about the public url

**Comment by ejurgensen** [comment]
I have tested this with the current version of forked-daapd, and it worked as expected. I suggest you upgrade and see if that does it.
