### ISSUE TITLE
Web front end sometimes loses access to server

### ISSUE THREAD

**Issue by beniamino38** [ejurgensen/forked-daapd#776]
If I queue up a few tracks, let them play for 15 mins or so, then try to queue up some more, I often find that the web frontend can't connect to the server -- I get a red 'reconnecting' box, my library seems empty and no controls work. This usually clears up after 5 minutes or so and everything works again.

I'm running on a Pi Zero, with a music library of 70 gigabytes. Perhaps this is just a general performance issue, but the music continues to play fine while this is happening, and the CPU load is not high. I'd be happy to spend some time trying to debug this, so would be grateful for any similar experiences or suggestions about what might be happening.

A sample DEBUG level log is attached. In this case, I noticed that the front end stopped working at 21:45 (though it could have been happened earlier). Everything started working again at 21:48. CPU load was 20% according to top.

[forked-daapd.log](https://github.com/ejurgensen/forked-daapd/files/3413985/forked-daapd.log)

**Comment by ejurgensen** [comment]
Thanks, the log didn't show any obvious issues, so I'll have to dig more into it. Next time you notice that the error happens, could you then try to directly make a request to http://[your_zero_ip]:3689/api/config and http://[your_zero_ip]:3689/api/player from a browser? I'm curious if the server responds to those.

**Comment by ejurgensen** [comment]
I haven’t had much luck reproducing this, and as mentioned the log also didn’t give me a clue. If you’re willing to do some debugging it would be great, and also required since I can’t progress. My advice would be to start by checking if the server is totally unresponsive (temporarily) or if it does handle other requests.

**Comment by beniamino38** [comment]
I have not seen this for a month or two now.
