### ISSUE TITLE
Shared playlists from Spotify not listed

### ISSUE THREAD

**Issue by alex-voigt** [ejurgensen/forked-daapd#780]
When I mark a Spotify playlist as shared/collaborative it is not displayed in forked-daapd anymore. As soon as I revert it back it is listed again. Is there any chance to fix that?

**Comment by ejurgensen** [comment]
If Spotify provides the playlist via their api then yes. If you set the log level to debug I think you can see it from the log. It will take a while before I can check it, but perhaps @chme has the opportunity.

**Comment by chme** [comment]
Looks like we need additional permissions to access collaborative playlists: https://developer.spotify.com/documentation/general/guides/working-with-playlists/#reading-a-playlist

I will prepare a pr for it.

**Comment by alex-voigt** [comment]
@chme thanks for fixing! is there any plan for a new release?
