### ISSUE TITLE
Looking for a downstream maintainer LinuxServer.io

### ISSUE THREAD

**Issue by thelamer** [ejurgensen/forked-daapd#788]
I hope this is OK and this is not an issue with your development so feel free to close this issue if you would like. 

Downstream at https://github.com/linuxserver/docker-daapd we no longer have any active team members that have this software setup to test and debug issues that arise from wrapping it in a Docker container. 
We want to put the effort into getting it building again and putting releases out, but as it stands right now we would be unable to test functionality. 

I am reaching out to see if anyone in this community would be interested in being the maintainer for our Downstream container. Really we need someone familiar with the software, we have the Docker expertise to share with anyone willing to be a maintainer. 

Thank you and again if this is not OK please feel free to close this.

**Comment by ejurgensen** [comment]
That's fine, hope you find someone. I don't use Docker myself, but can of course help with forked-daapd if someone wants to be a maintainer.

**Comment by thelamer** [comment]
No maintainers found

**Comment by BernsteinA** [comment]
Annoyingly I didn’t get any notifications from GitHub until an issue I was subscribed to was closed, so I missed the generous 2 month warning.
I’ll volunteer to maintain a docker image of this if nobody else will.
@thelamer @ejurgensen

**Comment by ejurgensen** [comment]
That's good to hear. I'll be happy to help you with forked-daapd issues. I can't help you on how to become maintainer, that would be @thelamer, or perhaps you can find info online.

**Comment by thelamer** [comment]
@BernsteinA can you hop on our Discord and ping me directly ? 
https://discord.gg/YWrKVTn
We can discuss what is involved with maintenance.
