### ISSUE TITLE
Alsa underrun issue

### ISSUE THREAD

**Issue by varadhawriter** [ejurgensen/forked-daapd#794]
When I am trying to play audio file with different Sample Rate.I am getting Following Alsa error.

SNDRV_PCM_IOCTL_SYNC_PTR failed

**Comment by whatdoineed2do** [comment]
Repeat of this issue https://github.com/ejurgensen/forked-daapd/issues/742 ?

**Comment by ejurgensen** [comment]
There is not information in this issue to do anything about it.

**Comment by varadhawriter** [comment]
How to make forkeddaapd play with different sample rate ?

**Comment by ejurgensen** [comment]
Insufficient issue description
