### ISSUE TITLE
Support for OpenWrt Barrier Breaker 14.07, Kernel 3.10.49 (unable to install forked-daapd)

### ISSUE THREAD

**Issue by jkiddo** [ejurgensen/forked-daapd#80]
root@OpenWrt:~# cat /proc/version 
Linux version 3.10.49 (bb@builder1) (gcc version 4.8.3 (OpenWrt/Linaro GCC 4.8-2014.04 r42625) ) #3 Wed Oct 1 14:51:04 CEST 2014
root@OpenWrt:~# opkg install forked-daapd
Installing forked-daapd (21.0-20140616) to root...
Downloading http://www.gyfgafguf.dk/openwrt/attitude_adjustment/12.09/brcm47xx/packages/forked-daapd_21.0-20140616_brcm47xx.ipk.
Multiple packages (libgcc and libgcc) providing same name marked HOLD or PREFER. Using latest.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for forked-daapd:
 * 	kernel (= 3.3.8-1-f57f4e4b03f8756fe7965db2671c97f6) * 	kernel (= 3.3.8-1-f57f4e4b03f8756fe7965db2671c97f6) * 
 * opkg_install_cmd: Cannot install package forked-daapd.

**Comment by ejurgensen** [comment]
Seems you are trying to install the AA version on BB :-)

Look here for a link to the BB version: http://wiki.openwrt.org/doc/howto/forked-daapd

**Comment by jkiddo** [comment]
Right ... seems fair. I fixed it ... now other stuff arrives at my terminal

root@OpenWrt:~# opkg update
Downloading http://www.gyfgafguf.dk/openwrt/barrier_breaker/14.07/brcm47xx/packages/Packages.gz.
Updated list of available packages in /var/opkg-lists/forked-daapd.
root@OpenWrt:~# opkg install forked-daapd
Installing forked-daapd (22.0-20141016) to root...
Downloading http://www.gyfgafguf.dk/openwrt/barrier_breaker/14.07/brcm47xx/packages/forked-daapd_22.0-20141016_brcm47xx.ipk.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for forked-daapd:
 * 	libgpg-error * 	libgcrypt * 	libgdbm * 	zlib * 	libexpat * 	libevent * 	libdaemon * 	confuse * 	glib2 * 	alsa-lib * 	libffmpeg-full * 	mxml * 	avahi-daemon * 	libavahi-client * 	sqlite3-cli * 	libplist * 
 * opkg_install_cmd: Cannot install package forked-daapd.

**Comment by ejurgensen** [comment]
> root@OpenWrt:~# opkg update
> Downloading http://www.gyfgafguf.dk/openwrt/barrier_breaker/14.07/brcm47xx/packages/Packages.gz.
> Updated list of available packages in /var/opkg-lists/forked-daapd

It only updated from the forked-daapd repo, so it looks like you removed or disabled the standard Openwrt repo's :-)

**Comment by jkiddo** [comment]
Great to be the newbie for once ;) Thx - got it all fixed. Now I just have to get acquainted with extroot

**Comment by jkiddo** [comment]
Just so you know - some of the forked-daapd dependencies needs packages from http://downloads.openwrt.org/barrier_breaker/14.07/brcm47xx/generic/packages/oldpackages/ which might be fine for now. It's just the name 'oldpackages' - is doesn't sound like those packages are gonna stick around forever

**Comment by ejurgensen** [comment]
Thanks,  but it is actually fine. The name oldpackages is because OpenWrt changed their package maintenance system to GitHub. Only packages which initially had a maintainer were moved, and the rest left in 'oldpackages'. However, since then I've had forked-daapd's dependencies moved over (as well as had forked-daapd added):
https://github.com/openwrt/packages/pulls?q=is%3Apr+author%3Aejurgensen+is%3Aclosed
