### ISSUE TITLE
Suggestion: Save current queue as a playlist

### ISSUE THREAD

**Issue by beniamino38** [ejurgensen/forked-daapd#806]
It would be cool if I could queue up a list of songs using the web interface (without playing them), then hit 'save' to save the queue as a playlist.

**Comment by chme** [comment]
If you are building forked-daapd from git, that is already possible (#718, #747) .
It requires setting the "allow_modifiying_stored_playlists" to true and setting a default playlist directory in the forked-daapd.conf file (and the user running forked-daapd needs write permissions on this directoy).

```
	# Allows creating, deleting and modifying m3u playlists in the library directories.
	# Only supported by the player web interface and some mpd clients
	# Defaults to being disabled.
#	allow_modifying_stored_playlists = false

	# A directory in one of the library directories that will be used as the default
	# playlist directory. forked-dapd creates new playlists in this directory if only
	# a playlist name is provided (requires "allow_modify_stored_playlists" set to true).
#	default_playlist_directory = ""
```
