### ISSUE TITLE
Request: Spotify playlists in subdirectory of Web Interface (same as iOS Remote App)

### ISSUE THREAD

**Issue by cdlenfert** [ejurgensen/forked-daapd#807]
I'd like the option (through config, or the new web interface settings page) to have my Spotify playlists be in a subdirectory within the "Playlists" page. This would be similar to the way the iOS app works currently. I prefer the web interface to the iOS app but would like to separate my playlists by source (local vs. Spotify). Is this already possible?

**Comment by chme** [comment]
That's not possible at the moment. It's something, i like to implement someday ...
