### ISSUE TITLE
Distorted audio when sending to HomePod (using forked-daapd + cpiped)

### ISSUE THREAD

**Issue by linetrimmer** [ejurgensen/forked-daapd#810]
I'm running a 3.5 mm cable from my projector into a usb adapter plugged into my raspberry pi 3 b+ and then using cpiped and forked-daapd to AirPlay the audio to my HomePod. After a couple days of trying this I'm surprised I actually got sound coming out of the HomePod, except it's very distorted and crackly. It is also distorted when plugging the aux cable into my computer (i.e. it's not limited to the tv). Any help would be appreciated--this is pretty much all I have left to deal with before I can use my HomePod as my projector’s speaker.

**Comment by ejurgensen** [comment]
The first step would be isolating what is producing the crackling. I think the most likely is the sound card's audio input. So try to record the input with arecord and then check if it is also crackling. If yes -> audio input issue - perhaps changing some settings (mixer volume?) will help. If no -> check if cpiped is making the crackling. You do this by stopping forked-daapd, and then after starting cpiped you can run "cat /your/pipe > out.wav". Play the wav file and check for crackling.

**Comment by linetrimmer** [comment]
It was the sound card! I tried a different adapter and now it comes in great. Thanks so much.

 I’m assuming there’s still no way to adjust for the 5 second delay? I’m getting around this now with the synchronization settings in my video player.

**Comment by cdlenfert** [comment]
Very cool! @linetrimmer I was thinking there would be a large delay on the audio. The only thing I know of that can output airplay audio and play videos in sync natively is an Apple TV.

**Comment by ejurgensen** [comment]
I can’t think of a way adjusting the delay. Those seconds are not spent “inside” forked-daapd, they are spent communicating with the device and on device buffering. It would be possible to fix the time, ie delay playback further to start it at a precise time, but also rather complicated to do.
