### ISSUE TITLE
Saved playlists are not updated correctly in "Playlists" tab of web UI

### ISSUE THREAD

**Issue by beniamino38** [ejurgensen/forked-daapd#814]
The new "save queue" feature is cool but I find there are some problems. This is running on an Ubuntu machine with default configuration except for uid="root", and modifying playlists is enabled.

For example, when using the web UI:

1. New playlists often don't appear in the "playlists" tab, e.g.:
* `rm /var/cache/forked/daapd/*.db`
* Delete all files from playlists directory
* start `forked-daapd`
* Queue up some songs
* Save playlist "test"
* Go to playlists tab -- "test" should appear but often doesn't
* Go to search tab and search for "test" -- it appears correctly in the search results
* Restart `forked-daapd` -- test still doesn't appear in the playlists tab
* `rm /var/cache/forked/daapd/*.db`
* Restart `forked-daapd` -- now the test playlist appears correctly

2. Deleted playlists do not disappear from the "playlists" tab, e.g.:
* Follow the steps above to create a playlist "test" and ensure that it appears in the "playlists" tab
* Stop `forked-daapd`
* Delete playlist file "test.m3u"
* Restart `forked-daapd`
* Go to playlists tab -- "test" still appears, but clicking it generates an error
* Click the playlist -- it appears as normal despite being deleted
* Trying to play the whole playlist fails
* Individual tracks from the playlist can still be played

**Comment by beniamino38** [comment]
In 2 above, I incorrectly wrote '"test" still appears, but clicking it generates an error'. Actually, clicking it displays the contents of the now-deleted playlist.

**Comment by beniamino38** [comment]
From calling the api directly, it looks like the database is correct when this happens, but the browser is showing an old, presumably cached, version of the "playlists" tab. Force-reloading the web UI seems to update the list correctly. This happens in Safari and Firefox.

**Comment by ejurgensen** [comment]
@chme I seem to remember you proposed a solution for this a while back, and perhaps I never got around to responding to it? In any case it would be great if you can find a fix.
