### ISSUE TITLE
web interface directory empty on new install

### ISSUE THREAD

**Issue by jshep321** [ejurgensen/forked-daapd#816]
Hi,
Was having gremlins with an older experimental version so decided to try a fresh/official install on my new pi4 (raspbian buster) today.  sudo apt-get install forked-daapd, no problem.

v26.4 installed fine and works...  except the /usr/share/forked-daapd/htdocs/ directory is totally empty, therefore the web interface doesn't work (404 on http://10.0.0.16:3689/)

Any ideas of why this happened?  I copied the htdocs directories from my old installation and fixed it, but wanted to raise attention on the install error.

**Comment by chme** [comment]
The debian package of forked-daapd does not ship the web interface (it is mentioned in the debian [changelog](https://metadata.ftp-master.debian.org/changelogs//main/f/forked-daapd/forked-daapd_26.4+dfsg1-1_changelog) and some information about this can be found here https://github.com/ejurgensen/forked-daapd/issues/552#issuecomment-412605268).

@ejurgensen provides builds for raspbian, best to follow the guide on http://www.raspberrypi.org/phpBB3/viewtopic.php?t=49928 to get all a build with all features enabled.

**Comment by jshep321** [comment]
Ah ok, thanks.  I forgot how I got it working originally (on the private repo).

Perhaps adding this as a note to the instructions? (http://ejurgensen.github.io/forked-daapd/#web-interface)

**Comment by ejurgensen** [comment]
Good idea, I have added a note
