### ISSUE TITLE
Web UI does not show pipe artwork

### ISSUE THREAD

**Issue by ejurgensen** [ejurgensen/forked-daapd#817]
@chme, I have added support for reading artwork from Shairport metadata pipes, but for some reason the artwork is not displayed in the web UI. It does show up in Remote and it also is shown when calling the /artwork/nowplaying endpoint. Hope you have chance to look into it.

**Comment by ejurgensen** [comment]
Here is how to reproduce without Shairport, which might save you some time:

1. Make two pipes in the library, one with the metadata suffix. Say "pipe" and "pipe.metadata"
2. Convert a track to wav, say "track.wav"
3. Get this test [metadata.txt](https://github.com/ejurgensen/forked-daapd/files/3664488/metadata.txt)
4. Run "cat track.wav > pipe". Check that playback has started.
5. In another terminal, run "cat metadata.txt > pipe.metadata". Check in the log that forked-daapd reads this data. You should also see a jpg appear in /tmp. Remote should also show artwork (Gorillaz).
6. Go to the web UI, which won't show a artwork.

**Comment by chme** [comment]
Thanks for the instructions! I could reproduce the issue and have opened a pr to fix this.
