### ISSUE TITLE
Add support for MPD password

### ISSUE THREAD

**Issue by TanyaEleventhGoddess** [ejurgensen/forked-daapd#827]
I've not found any hint of support for a password function.

This means everyone on a network can download a list of stored music and/or play music, and should be avoided

**Comment by chme** [comment]
You can set a library password in the forked-daapd.conf file. This will then require mpd clients to first authenticate using the mpd password command.

https://github.com/ejurgensen/forked-daapd/blob/547222ec2b63b79e9f97aa6f9ad59781302c2c81/forked-daapd.conf.in#L67-L68

**Comment by chme** [comment]
Closing this one. Feel free to reopen it, if it does not work for you.
