### ISSUE TITLE
Contents of release archives not indentical

### ISSUE THREAD

**Issue by thecb1** [ejurgensen/forked-daapd#829]
The contents of the release archives are not the same. The .tar.gz is missing the antlr3 stuff which is included in the .tar.xz

I did not check for other differences and did not look into the .zip.

Cheers

**Comment by ejurgensen** [comment]
Yes, the zip and the tar.gz are autogenerated by github, I don’t think I can do anything about their content. For the next release I can try to attach my own tar.gz, but then there will probably be two, which could be confusing.
