### ISSUE TITLE
mp3 compilation flag not preserved

### ISSUE THREAD

**Issue by andreas-p** [ejurgensen/forked-daapd#83]
I got quite some compilation CDs that are correctly tagged as compilation (using iTunes, checked using different tools). If these CDs are used from iTunes via forked-daapd 22.1, the compilation flag (probably asco) seems to be missing so all titles are presented grouped by artist, not cd.

**Comment by ejurgensen** [comment]
I'm not sure forked-daapd is able to understand an id3 compilation tag. It does, however, support the "asco" flag, and will set it for tracks that you have in your library in a "Compilations" directory. These will by default be grouped as "Various artists", so not by artist.

**Comment by andreas-p** [comment]
You're right, I've been caught by issue #17 because I "make; make install" 'ed forked-daapd and lost my old /etc/forked-daapd.conf. When re-configuring, I missed the compilations setting. make install really shouldn't copy over an existing conf file.
Still, not examining the compilations id3 tag appears surprising to me, I suggest to add this.

**Comment by ejurgensen** [comment]
Support for the compilations id3 tag should now be in place. Thanks for reporting this!
