### ISSUE TITLE
faulty raop_volume float2string conversion giving wrong results

### ISSUE THREAD

**Issue by andreas-p** [ejurgensen/forked-daapd#84]
I have an AirMobi iReceiver with latest firmware, which is working as expected with iTunes, including volume control.

When using the AirMobi as loudspeaker for forked-daapd 22.1, changing volume frequently forces the AirMobi to reboot, with forked-daapd logging "raop: SET_PARAMETER request failed for stream volume: 0 (null)"

**Comment by andreas-p** [comment]
Ok, so I found out what's going wrong by comparing raop network traces of iTunes and forked-daapd. The volume parameter will be always 0 or something negative with iTunes, but forked-daapd will sometimes set the volume to 0.300000 or so, which results in crashing the iReceiver.
The problem is the hand-made float-to-string conversion in raop.c:raop_set_volume_internal (the comment says "Don't let locales get in the way here"). If raop_volume is -0.3, int(-0.3) is 0 so the converted string gets positive. Adding two minus chars will solve this:
  .... "volume: -%d.%06d\r\n", -(int)raop_volume,  -(int)...

**Comment by ejurgensen** [comment]
A bug report followed by a precise and simple solution – that’s just excellent! Will fix asap.
