### ISSUE TITLE
Multiple active fifo creates race condition

### ISSUE THREAD

**Issue by jshep321** [ejurgensen/forked-daapd#844]
Hi,
Low prio issue here.

I have an airplay fifo (shairport-sync) AND a spotifyconnect fifo (raspotify) on the same system and was playing around with what happens when trying to play from both.  
1. When starting with spotifyconnect then starting airplay, I get skipping on the airplay stream. 
2. When starting airplay and then spotify connect, the airplay stream skips.  
In both cases as soon as the raspotify fifo is empty, the airplay signal works fine.  A connect of the spotify stream is needed to reinstate audio.

I suspect this is simply an untested use case that was never considered (2 fifos on a single system).   I haven't setup 2 shairport-sync fifos, but that might be fun too.

**Comment by ejurgensen** [comment]
I don't fully understand this issue. Would you mind spelling out the steps to reproduce? Also please state if pipe_autostart is enabled.

**Comment by jshep321** [comment]
Will do in the future.  Other prio tasks right now.
