### ISSUE TITLE
error MINIXML in compiling

### ISSUE THREAD

**Issue by lindien954** [ejurgensen/forked-daapd#845]
hello,
i have this error in compiling:

checking for MINIXML... no
configure: error: Package requirements (mxml) were not met:

No package 'mxml' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables MINIXML_CFLAGS
and MINIXML_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
../../mk/spksrc.configure.mk:50: recipe for target 'configure_target' failed
make[1]: *** [configure_target] Error 1
make[1] : on quitte le répertoire « /home/pascal/spksrc/cross/forked-daapd »
../../mk/spksrc.cross-cc.mk:137: recipe for target 'arch-rtd1296' failed
make: [arch-rtd1296] Error 2 (ignorée)

**Comment by ejurgensen** [comment]
Well, as the error message says you are missing mxml. There isn't much more to it. Please consult the INSTALL file for more info on building/installing.
