### ISSUE TITLE
Server name change (or upgrade) causes greyed out "itunes library" on remote.

### ISSUE THREAD

**Issue by jshep321** [ejurgensen/forked-daapd#847]
Hi,
After updating from 26.5 to 27, I noticed that my 3 iOS remote devices show the server greyed out.  It still functions normally if I tap it, but doesn't appear that it will.

It's almost certainly because I was using the %v in the server string in forked-daapd.conf, so 26.5 -> 27.0.

Easy fix is to remove the version name if this is an iOS restriction (and perhaps add a note in the .conf file), and then re-pair

**Comment by ejurgensen** [comment]
Thanks for this, good diagnosis. I have updated the config file as you can see above.
