### ISSUE TITLE
No way to get out of 'admin' apart from via the 'back button' ?

### ISSUE THREAD

**Issue by lancelon** [ejurgensen/forked-daapd#848]
Is it just me, or is there no way to get out of the admin page, apart from via the back button?

http://forked-daapd.local:3689/admin.html

**Comment by cdlenfert** [comment]
That's true. I've thought this could be improved in the past as well. I discovered when you're on iOS (since the web app goes full screen) if you swipe right from the left edge of your screen it works as  a back button (where one doesn't actually exist).

**Comment by ejurgensen** [comment]
Yes, perhaps @chme can find a solution for this?

**Comment by chme** [comment]
I've opened a pr with a quick fix by turning the "forked-daapd" title on the admin page into a link to the player web interface. I'd like to include all functionality of the admin page into the player web interface, but that will take while ...
