### ISSUE TITLE
Yocto recipe for forked-daapd?

### ISSUE THREAD

**Issue by chme** [ejurgensen/forked-daapd#851]
I am curious, has someone created or tried to create a [yocto](https://www.yoctoproject.org/) image with forked-daapd? 
I got stuck at building the libantrl3c dependency (the build fails and i have not yet figured out why).

**Comment by Ramias1** [comment]
The LinuxServer.io docker package (https://github.com/linuxserver/docker-daapd) which appears to be no longer maintained has the same build issue with libantrl3c.

**Comment by chme** [comment]
The build error on the docker image is different from the error i had with yocto. There is a work in progress pr for the docker build error (https://github.com/linuxserver/docker-daapd/pull/31).

If someone is interested in it, i have solved the issue with building libantrl3c with yocto. It required a little change to the libantlr3c makefile. The recipe can be found here: https://github.com/chme/meta-daapd (it is still work in progress, but i managed to build an image with forked-daapd).
