### ISSUE TITLE
[db] time_added always updated on file meta updates

### ISSUE THREAD

**Issue by whatdoineed2do** [ejurgensen/forked-daapd#852]
When modifying the meta on a file that has already been added, the db's `time_added` field is always updated.

This means that when we use a smartpl to find tracks added 'today' (which uses the `time_added` column) this gives you unexpected results

```
"Music added today" {
  data_kind is file
  and media_kind is music
  and time_added after today
}
```
I would expect that 'time_added' is only for new files (via `db_file_add()`) and not existing files (via `db_file_update()`) where it should be excluded from the update.

A simple fix:
```
diff --git a/src/db.c b/src/db.c
index 17dad936..891b91e9 100644
--- a/src/db.c
+++ b/src/db.c
@@ -190,7 +190,7 @@ static const struct col_type_map mfi_cols_map[] =
     { "item_kind",          mfi_offsetof(item_kind),          DB_TYPE_INT,    DB_FIXUP_ITEM_KIND },
     { "description",        mfi_offsetof(description),        DB_TYPE_STRING },
     { "db_timestamp",       mfi_offsetof(db_timestamp),       DB_TYPE_INT },
-    { "time_added",         mfi_offsetof(time_added),         DB_TYPE_INT,    DB_FIXUP_TIME_ADDED },
+    { "time_added",         mfi_offsetof(time_added),         DB_TYPE_INT,    DB_FIXUP_TIME_ADDED, DB_FLAG_NO_ZERO },
     { "time_modified",      mfi_offsetof(time_modified),      DB_TYPE_INT,    DB_FIXUP_TIME_MODIFIED },
     { "time_played",        mfi_offsetof(time_played),        DB_TYPE_INT,    DB_FIXUP_STANDARD, DB_FLAG_NO_ZERO },
     { "time_skipped",       mfi_offsetof(time_skipped),       DB_TYPE_INT,    DB_FIXUP_STANDARD, DB_FLAG_NO_ZERO },
@@ -3022,6 +3022,7 @@ db_file_update(struct media_file_info *mfi)
   mfi->db_timestamp = (uint64_t)time(NULL);
 
   fixup_tags_mfi(mfi);
+  mfi->time_added = 0;
 
   ret = bind_mfi(db_statements.files_update, mfi);
   if (ret < 0)
```
If this is acceptable Ill send a PR

**Comment by ejurgensen** [comment]
Yes, I could reproduce this, thanks for notifying. I will look into the fix you propose.

**Comment by whatdoineed2do** [comment]
Great.  It looks like we can't drop the `DB_FIXUP_TIME_ADDED` from `time_added` as it used on new file inserts - hence the addition of `DB_FLAG_NO_ZERO` and the reset of `mfi->time_added = 0` after the `fixup`.

**Comment by ejurgensen** [comment]
Should be fixed now. The fix is pretty much like you proposed, just "inverted" so that db_file_update() doesn't undo a fixup.
