### ISSUE TITLE
API use not sure where the fault lies?

### ISSUE THREAD

**Issue by lancelon** [ejurgensen/forked-daapd#854]
If i do 

`curl -X GET 192.168.0.124:3689/api/player
`
straight away I get a response 

`{ "state": "stop", "repeat": "off", "consume": false, "shuffle": false, "volume": 29, "item_id": 0, "item_length_ms": 0, "item_progress_ms": 0 }`

If I do 

`curl -X PUT 192.168.0.24:3689/api/queue/clear
`
I eventually get a timeout error

If I do 

`curl -X PUT 192.168.0.124:3689/api/player/play
`
I get 

```
<html>
<head>
<title>500 Internal Server Error</title>
</head>
<body>
<h1>Internal Server Error</h1>
</body>
</html>
```

**Comment by whatdoineed2do** [comment]
For your last item (play when Q is empty) it was mentioned in #805 - the fix to prevent (most) users seeing this was done at the web UI side rather than in the server.

**Comment by chme** [comment]
Yeah, the error handling of the json api is not that great ... 

But the second command should return right away (and it does for me). The second command has a different IP address than the first command. Are you sure this is the correct IP (`24`vs `124`)?
