### ISSUE TITLE
Websocket not connecting

### ISSUE THREAD

**Issue by kinglouie** [ejurgensen/forked-daapd#861]
I'm currently trying to get this package to work inside docker to no avail using this image https://github.com/chme/docker-daapd/tree/fixbuild

When logging into the webinterface I get the error message `Connection Lost Reconnecting` and in the browser dev console this is printed `WebSocket connection to 'ws://0.0.0.0:3688/' failed: WebSocket is closed before the connection is established.`

The port 3688 is set in the config file of this package and is also forwarded by docker.
On every attempt to connect to the websocket forked-daapd prints this to the log:
`[DEBUG]      web: notify callback reason: 71`
which lets me believe that the webclient can reach the websocket but somehow a stable connection can't be established.

Unfortunately I don't really understand the docs of libwebsocket where it says the following for code 71

`
LWS_CALLBACK_EVENT_WAIT_CANCELLED | This is sent to every protocol of every vhost in response to lws_cancel_service() or lws_cancel_service_pt(). This callback is serialized in the lws event loop normally, even if the lws_cancel_service[_pt]() call was from a different thread.
`

I would really appreciate if someone could point me directions where this error might originate from.

**Comment by chme** [comment]
I did have a look at that, but could not figure out why this disconnect happened. We don't call `lws_cancel_service` in forked-daapd. So i don't have a clue why this happens on alpine linux. Will try to give it another shot.

**Comment by kinglouie** [comment]
Today I gave it another try and did some research, it seems that other people also had trouble with libwebsockets and alpine so I tried updating the used alpine image to 3.11 in the dockerfile and voila, it is working now :)

**Comment by BernsteinA** [comment]
@kinglouie maybe you can help me over here https://github.com/linuxserver/docker-daapd/pull/32
