### ISSUE TITLE
How to make playlist folders?

### ISSUE THREAD

**Issue by palayo** [ejurgensen/forked-daapd#862]
Thanks a lot for your graet works.

I have a lot of playlists and smart playlists on my itunes and want to move them to forked-daapd.
I need to make playlist folders to manage my playlists.
But I could not find out how to make playlist folders.

If the playlist folder is not supported, I really ask you to implement it.

**Comment by ejurgensen** [comment]
I suppose you can say that the "frontend" part of this isn't made in forked-daapd yet, but the backend part is. So with a bit sql you may be able to do this. Here is a very lightly tested recipe:

1. Make empty m3u's in your library with the names of the folders you want. So for instance "Daddy.m3u" and "Mommy.m3u".
2. Run "sqlite3 /var/cache/forked-daapd/songs3.db" with write privilege, so maybe with sudo.
3. Run "select id,path from playlists;". Note the id's of Daddy.m3u and Mommy.m3u, and of the playlists you want inside the folders.
4. For each folder, run "update playlists set type=1 where id=[folder id];". This tells forked-daapd that it is a folder playlist.
5. For each child playlist, run "update playlists set parent_id=[folder id] where id=[playlist id];". This tells forked-daapd where each playlist belongs.

Now you should get what you want in Remote and iTunes. However, it doesn't seem the web interface will show the playlist folders. @chme perhaps that is something to consider supporting?

**Comment by chme** [comment]
Yes, playlist folders would be nice to support. But it i think, we should figure out first how to properly set them up (modifying the database does not sound so good to me ;-)).

One option would be to define a playlists root folder (some sort of that we already have with the `default_playlist_directory` in the conf file). And then add all subfolders as playlist folders during the scan.

**Comment by ejurgensen** [comment]
I have actually started on this, just a simple solution where a folder is created by having a m3u/pls anywhere in the library with one or more m3u/pls paths inside. It doesn't look like it will take too much to support that, but I probably will refactor a bit while I'm at it (e.g. updating db_pl_add/update to use prepared statements like db_file_add/update).

**Comment by ejurgensen** [comment]
With the latest commits I have added playlist folder support into the master branch of forked-daapd - i.e. you can make "parent" playlists (.m3u files), which contain children playlists (also m3u's). It should work in iTunes and Remote-type clients. The web interface does not currently support displaying this, I will open another issue for that.
