### ISSUE TITLE
cross-compil for nas synology

### ISSUE THREAD

**Issue by lindien954** [ejurgensen/forked-daapd#863]
Currently I am doing a cross-compilation of forked-daapd for a Synology nas. But I am facing errors with "Avahi" at runtime. (Avahi and dbus already present on Synology). (I tested a compilation with "- without avahi" but compilation errors). see error at runtime. Can you help me. Thank you.

./forked-daapd -c ../etc/forked-daapd.conf -f
[  LOG]     main: Forked Media Server Version 27.0 taking off
[  LOG]     main: Built with:
[  LOG]     main: - ffmpeg
[  LOG]     main: - iTunes XML
[  LOG]     main: - MPD
[  LOG]     main: - Device verification
[  LOG]     main: - Websockets
[  LOG]     main: - Webinterface
[ INFO]     main: Initialized with ffmpeg 4.2.1
[DEBUG]     main: Initialized with gcrypt 1.8.2
[  LOG]     main: mDNS init
[DEBUG]     mdns: Initializing Avahi mDNS
forked-daapd: client.c:791: avahi_client_errno: Assertion `client' failed.
Aborted (core dumped)

**Comment by ejurgensen** [comment]
This is an error from Avahi because it isn't able to create a mdns client when forked-daapd requests one.

You say that Avahi and dbus are present, but are they also running? Have you tested if avahi-browse works? For instance with "avahi-browse -r -k _raop._tcp".

**Comment by lindien954** [comment]
Avahi and dbus are present, and work. But "avahi-browse -r -k _raop._tcp" not work!

 sudo synoservice -status avahi
Service [avahi] status=[enable]
required upstart job: 
	[avahi] is start. 
sudo synoservice -status dbus
Service [dbus] status=[enable]
required upstart job: 
	[dbus-system] is start. 
	[dbus-session] is start. 

sudo ./avahi-browse -r -k _raop._tcp
./avahi-browse: invalid option -- 'k'

 sudo ./avahi-browse -r _raop._tcp
Failed to create client object: Daemon not running

**Comment by ejurgensen** [comment]
Ok seems clear enough then, Avahi isn’t running
