### ISSUE TITLE
[outputs] support multiple alsa output devices

### ISSUE THREAD

**Issue by whatdoineed2do** [ejurgensen/forked-daapd#865]
Openned PR #864 
 
I want the server to support multiple local ALSA output devices instead of the default single alsa device - the functionality for other output types support multiple devices is available for other output types such as `cast` or `airplay` output devices.

I have a raspberry pi has an onboard headphone output and also an add-on DAC hat that feeds into my amp: this means this device has multiple h/w output devices which I want to be selectable by the server.

Currently to support use the headphones jack or the DAC/amp on the RPi I have to run 2 instances of the server and thus both maintaining 2 different `songs3.db` files.

Please let me know if this PR is acceptable/going in the right direction.

**Comment by ejurgensen** [comment]
Closing this, let's keep the conversation on the pr.
