### ISSUE TITLE
Trusted Docker Version?

### ISSUE THREAD

**Issue by Ramias1** [ejurgensen/forked-daapd#871]
Is there a good, trusted docker version of the latest daapd?  I was using LinuxServer's but it seems to be orphaned.

**Comment by ejurgensen** [comment]
@BernsteinA considered adopting it, see issue #788, but other than that I don't know what the state is

**Comment by BernsteinA** [comment]
Hi yes I started and I got this far:
https://github.com/linuxserver/docker-daapd/pull/31

**Comment by chme** [comment]
@BernsteinA in case you have not seen #861: @kinglouie fixed the websocket disconnection problem by updating the base alpine version to 3.11

**Comment by BernsteinA** [comment]
Had not seen that. Much simpler
