### ISSUE TITLE
Better remote support from shairport-sync

### ISSUE THREAD

**Issue by jorbas** [ejurgensen/forked-daapd#873]
I'm converting some old speakers into Airplay speakers for use with my home forked-daapd setup by running [shairport-sync](https://github.com/mikebrady/shairport-sync) on them. On these speakers I'd like to add a volume knob or buttons so I can control the volume of that speaker without having to open up the web interface on another device.

Shairport-sync has a D-Bus interface which allows me to send events back up to the audio source. There are 2 remote interfaces, `RemoteControl` and `AdvancedRemoteControl`. Using the `AdvancedRemoteControl` interface, I can get and set the playback volume, but not all audio sources support the `AdvancedRemoteControl` interface. iTunes/Music.app/forked-daapd do, but I also want the volume knob/buttons to work when playing from iOS devices, which to my knowledge, don't support this interface. Also, this interface requires you to specify an absolute volume, which isn't ideal. 

Alternatively, there is the `RemoteControl` interface. Parts of this interface are already supported in forked-daapd, I can send `Play`/`Pause`/`Stop` events from the speaker and forked-daapd will respond. But forked-daapd _doesn't_ seem to support the `VolumeUp`/`VolumeDown`/`ToggleMute` events from this interface (as of 27.0), nothing happens on the forked-daapd side when using these. I've confirmed that they work when playing to shairport-sync using another audio source (Music.app). This should also work on iOS devices and the relative stepping changes in the volume are ideal for my use case.

Would it be possible to add support for these commands?

**Comment by ejurgensen** [comment]
Yes, should be easy enough to support. I just need to know what requests are being sent to forked-daapd. If you set the log level to debug you should be able to grab them from the log. You can grep the log for "dacp", and then find the lines that say something like: dacp: DACP request: '/ctrl-int/1/xxxxx'

**Comment by jorbas** [comment]
`ToggleMute`:
```
Jan 03 14:41:47 base forked-daapd[1025]: [DEBUG]     dacp: DACP request: '/ctrl-int/1/mutetoggle'
Jan 03 14:41:47 base forked-daapd[1025]: [  LOG]     dacp: Unrecognized path '/ctrl-int/1/mutetoggle' in DACP request: '/ctrl-int/1/mutetoggle'
```

`VolumeUp`:
```
Jan 03 14:43:41 base forked-daapd[1025]: [DEBUG]     dacp: DACP request: '/ctrl-int/1/volumeup'
Jan 03 14:43:41 base forked-daapd[1025]: [  LOG]     dacp: Unrecognized path '/ctrl-int/1/volumeup' in DACP request: '/ctrl-int/1/volumeup'
```

`VolumeDown`:
```
Jan 03 14:45:43 base forked-daapd[1025]: [DEBUG]     dacp: DACP request: '/ctrl-int/1/volumedown'
Jan 03 14:45:43 base forked-daapd[1025]: [  LOG]     dacp: Unrecognized path '/ctrl-int/1/volumedown' in DACP request: '/ctrl-int/1/volumedown'
```

When using Music.app as the audio source, the volume up/down commands seem to step the volume by 4%, 5% or 6%, but it is 5% on average.

**Comment by ejurgensen** [comment]
I've added support for those three commands now. I've yanked it straight into master since the change doesn't carry any risk of breaking something. Note that the way I have done mute isn't ideal, because it isn't actually adjusting volume. Instead it disables/enables the speaker, which means that there will be a delay when unmuting.

**Comment by jorbas** [comment]
Just tried the latest commit, works as exactly as I'd hoped. Thank you for the very quick turnaround on this!
