### ISSUE TITLE
Disable Spotify After Build? 

### ISSUE THREAD

**Issue by mixographer** [ejurgensen/forked-daapd#881]
Hi. Thanks for a great product. it works great. 

I was trying to keep a really clean library of just my own files that I ripped at the settings I like. Everything was going great, but I just did a rescan library and now my interface is cluttered up with tonnes of junk I don't even know. I think it must be coming from spotify playlists. I can't find my files from all the junk artists I don't want. I used the simple install from the INSTALL file. I guess that builds it with spotify - access? I get a lot of these in syslog: 

[  LOG]  spotify: Can't register music, not connected and logged in to Spotify

Any advice on why my library would suddenly be cluttered. 

Anyway, I'm using FD to stream my turntable to all my airplay devices, and it works great for that. Although now it may take some time to find my unknown/unknown turntable FIFO file. 

Oh yeah, can the FIFO file support a same named covert file? like if my FIFO is called turntable, can I have a turntable.png covert file. 

Maybe this isn't a bug, is there a forum where these questions should go? 

Thanks

**Comment by ejurgensen** [comment]
It's fine to ask questions here.

The issue is difficult to explain with the info you have given, forked-daapd won't get your Spotify playlists unless you log in to Spotify via forked-daapd, and it doesn't sound like you have done that? If you use the web interface you can see the path of some of the unwanted items. Click the three dots to the right of the listed item. That should tell you were they are coming from.

Looking at the code it doesn't look like you can get a cover with turntable.png for pipes (which actually might be a bug), but perhaps it will work if you name the file cover.png.

**Comment by mixographer** [comment]
In my Admin panel, it says "Spotify Web API: access authorized for mixographer," so I have authorized something. I'm also not Spotify Premium, so all the extra files that are showing up in my library can't be played. The error in that case is a pop-over that says:

"Request failed (status: 500 Internal Server Error, url: http://192.168.0.46:3689/api/library/albums/1071710900848852200)"

I don't know how to undo whatever access I've given spotify. It would be nice if it was configured in the conf file. "use Spotify = false"

I can rebuild if that is the solution. I should do anyway, just to set up all the users and permissions in a different way than they are now. 

interesting about the cover.png, how would it associate the cover with the particular turntable file? There are other files in the same library. Maybe I'm organizing the files wrong anyway?

Thanks for looking!

**Comment by ejurgensen** [comment]
I'm actually not sure how to stop the web API access without deleting the database (which is an option - forked-daapd will regenerate it again when it starts). @chme do you have some advice on this?

Yes, cover.png will be associated with all files in the directory (the normal use case is that you have a bunch of tracks in the directory and then one file with cover art).

**Comment by mixographer** [comment]
I will try deleting the database.

Thanks

**Comment by mixographer** [comment]
Deleting the database worked:

"[2020-01-12 19:56:43] [  LOG]  spotify: No spotify refresh token found"

Once I got that message, none of the other files appeared. Thank you!
