### ISSUE TITLE
Podcast cover art must be loaded for each track separately

### ISSUE THREAD

**Issue by retrography** [ejurgensen/forked-daapd#883]
FDAAPD loads the cover art from one of the tracks in each album and then applies it to all the tracks in the album. This is a correct approach for the songs in a music album, but leads to issues when loading cover art for podcasts, as each episode of a podcast may have a different cover art.

**Comment by ejurgensen** [comment]
Try enabling this option:
https://github.com/ejurgensen/forked-daapd/blob/master/forked-daapd.conf.in#L135

**Comment by retrography** [comment]
Hadn't seen that option. I will pass, though, because enabling that will probably multiply my cache size by ten (it is already pretty large right now). But maybe there is a point in enabling this option by default only for podcasts, because the artwork for podcast episodes is supposed to be different, while the opposite is true for music albums. 

Given that I am unaware of the amount of work this takes, consider it with a grain of salt.
