### ISSUE TITLE
Issues building on 'Raspberry Pi 3 Model B Rev 1.2' with Raspbian buster

### ISSUE THREAD

**Issue by ajmas** [ejurgensen/forked-daapd#884]
I am trying to build the head version of forked-daapd on a 'Raspberry Pi 3 Model B Rev 1.2' with Raspbian buster.

My first point failure is with `scripts/antlr35_install.sh`, which fails with:

```
configure: creating ./config.status
config.status: creating Makefile
config.status: creating antlr3config.h
config.status: executing depfiles commands
config.status: executing libtool commands
make  all-am
make[1]: Entering directory '/home/pi/antlr35.tmp/libantlr3c-3.4'
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -Iinclude    -m32  -O2  -Wall -MT antlr3baserecognizer.lo -MD -MP -MF .deps/antlr3baserecognizer.Tpo -c -o antlr3baserecognizer.lo `test -f 'src/antlr3baserecognizer.c' || echo './'`src/antlr3baserecognizer.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -Iinclude -m32 -O2 -Wall -MT antlr3baserecognizer.lo -MD -MP -MF .deps/antlr3baserecognizer.Tpo -c src/antlr3baserecognizer.c  -fPIC -DPIC -o .libs/antlr3baserecognizer.o
gcc: error: unrecognized command line option '-m32'; did you mean '-mbe32'?
make[1]: *** [Makefile:449: antlr3baserecognizer.lo] Error 1
make[1]: Leaving directory '/home/pi/antlr35.tmp/libantlr3c-3.4'
make: *** [Makefile:308: all] Error 2
Build of libantlr3c failed!
Files remain in /home/pi/antlr35.tmp...
```

I did decide to try my luck by using the antlr version available via apt, but that only appears to be 3.2.  Anyhow, did try continuing on with `autoreconf -i` and then that also fails, starting with:

```
configure.ac:105: warning: macro 'AM_ICONV' not found in library
configure.ac:168: warning: macro 'AM_PATH_LIBGCRYPT' not found in library
configure.ac:171: warning: macro 'AM_PATH_GPG_ERROR' not found in library
configure.ac:107: warning: AC_LIB_PREPARE_PREFIX is m4_require'd but not m4_defun'd
m4/fork_checks.m4:59: _FORK_VARS_ADD_PREFIX is expanded from...
```

Can anyone provide me a recipe for building on a Raspberry Pi?

BTW have attached logs:

[antlr35_install.log](https://github.com/ejurgensen/forked-daapd/files/4051743/antlr35_install.log)
[autoconf.log](https://github.com/ejurgensen/forked-daapd/files/4051744/autoconf.log)

**Comment by ejurgensen** [comment]
Have you checked the Debian quick instructions in the INSTALL file?

I wouldn't bother with building antlr. The version you get with apt is fine.

**Comment by ajmas** [comment]
Ok, just managed to sit down on the Pi. Installed the dependencies per:

```
 sudo apt-get install \
  build-essential git autotools-dev autoconf automake libtool gettext gawk \
  gperf antlr3 libantlr3c-dev libconfuse-dev libunistring-dev libsqlite3-dev \
  libavcodec-dev libavformat-dev libavfilter-dev libswscale-dev libavutil-dev \
  libasound2-dev libmxml-dev libgcrypt20-dev libavahi-client-dev zlib1g-dev \
  libevent-dev libplist-dev libsodium-dev libjson-c-dev libwebsockets-dev
```

Now at the configure step, I run:

```
./configure --prefix=/usr/local --sysconfdir=/etc --localstatedir=/var --enable-chromecast  --enable-spotify --enable-lastfm  
```

Here it fails:

```
...
checking sys/event.h presence... no
checking for sys/event.h... no
checking whether htobe16 is declared... yes
checking for LIBAV... yes
checking for av_init_packet... no
configure: error: Unable to link function av_init_packet
```



BTW did also try with the following, but same issue:

```
./configure --prefix=/usr/local --sysconfdir=/etc --localstatedir=/var
```

Logs attached:

[config.log](https://github.com/ejurgensen/forked-daapd/files/4067360/config.log)
[configure.log](https://github.com/ejurgensen/forked-daapd/files/4067361/configure.log)

**Comment by ejurgensen** [comment]
Well, there is something wrong with your libavcodec. Perhaps you have conflicting installs if you have also tried to build it manually.

You are aware that I have a repo that offers a deb for Raspbian Buster, right? Otherwise, check the INSTALL file. It is fairly up-to-date and includes the web interface. Plus you can use apt, which is always good.

**Comment by ajmas** [comment]
I'll look. 

I was aware of the version in the raspbian apt repo, but the latest version there was version 26, while latest release here is 27. Is there another repo? I didn't see anything in http://ejurgensen.github.io/forked-daapd/

**Comment by ejurgensen** [comment]
Err, you seem not to be reading what I wrote (and what it says in the INSTALL file). Here is a link:
https://github.com/ejurgensen/forked-daapd/blob/master/INSTALL#L16

**Comment by ajmas** [comment]
I did indeed misread and I have now been able to install the latest version, per instructions.

Thank you for your time and patience.
