### ISSUE TITLE
New Segmentation fault 

### ISSUE THREAD

**Issue by lindien954** [ejurgensen/forked-daapd#885]
[DEBUG]      web: JSON api request: '/api/player'
[DEBUG]   player: Player status: stopped
[DEBUG]       db: Running query 'BEGIN TRANSACTION;'
[DEBUG]       db: Starting enum 'SELECT * FROM queue f WHERE pos = 0 ORDER BY pos;'
[DEBUG]       db: End of queue enum results
[DEBUG]       db: Running query 'END TRANSACTION;'
[DEBUG]      web: JSON api request: '/api/library'
[DEBUG]       db: Starting query 'SELECT COUNT(*), SUM(song_length), COUNT(DISTINCT songartistid), COUNT(DISTINCT songalbumid) FROM files f WHERE f.disabled = 0;'
[DEBUG]       db: Running query 'SELECT value FROM admin a WHERE a.key = 'start_time';'
[DEBUG]       db: Running query 'SELECT value FROM admin a WHERE a.key = 'db_update';'
[DEBUG]      web: JSON api request: '/api/library/count?expression=media_kind%20is%20audiobook'
[DEBUG]       db: Running query 'SELECT value FROM admin a WHERE a.key = 'db_update';'

Thread 8 "forked-daapd" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 13166]
0x0000007fb1da3e34 in memcpy () from /lib64/libc.so.6
(gdb) backtrace
#0  0x0000007fb1da3e34 in memcpy () from /lib64/libc.so.6
#1  0x0000007fb237fe0c in newPtr8 () from /var/packages/forked-daapd/target/lib/libantlr3c.so
#2  0x0000007fb237ca0c in antlr38BitSubstr () from /var/packages/forked-daapd/target/lib/libantlr3c.so
#3  0x0000007fb2377c78 in getText () from /var/packages/forked-daapd/target/lib/libantlr3c.so
#4  0x0000007fb2378578 in toString () from /var/packages/forked-daapd/target/lib/libantlr3c.so
#5  0x0000007fb2373f44 in toStringTree () from /var/packages/forked-daapd/target/lib/libantlr3c.so
#6  0x0000007fb2374004 in toStringTree () from /var/packages/forked-daapd/target/lib/libantlr3c.so
#7  0x0000000000457008 in parse_input (smartpl=0x7facf9c2d0, input=0x7f940d41e0) at smartpl_query.c:94
#8  0x00000000004573d0 in smartpl_query_parse_string (smartpl=0x7facf9c2d0, expression=0x7f940d4630 "\"query\" { media_kind is audiobook }")
    at smartpl_query.c:211
#9  0x00000000004468f8 in jsonapi_reply_library_count (hreq=0x7f9406f7d0) at httpd_jsonapi.c:3416
#10 0x00000000004479f8 in jsonapi_request (req=0x7f94021ac0, uri_parsed=0x7f9406f590) at httpd_jsonapi.c:3962
#11 0x000000000042ff90 in httpd_gen_cb (req=0x7f94021ac0, arg=0x0) at httpd.c:848
#12 0x0000007fb226ad80 in evhttp_handle_request () from /var/packages/forked-daapd/target/lib/libevent-2.0.so.5
#13 0x0000007fb2266878 in evhttp_connection_done () from /var/packages/forked-daapd/target/lib/libevent-2.0.so.5
#14 0x0000007fb2268b28 in evhttp_get_body () from /var/packages/forked-daapd/target/lib/libevent-2.0.so.5
#15 0x0000007fb2268e48 in evhttp_read_header () from /var/packages/forked-daapd/target/lib/libevent-2.0.so.5
#16 0x0000007fb2268d98 in evhttp_read_firstline () from /var/packages/forked-daapd/target/lib/libevent-2.0.so.5
#17 0x0000007fb2266fa4 in evhttp_read_cb () from /var/packages/forked-daapd/target/lib/libevent-2.0.so.5
#18 0x0000007fb22533ec in _bufferevent_run_readcb () from /var/packages/forked-daapd/target/lib/libevent-2.0.so.5
#19 0x0000007fb2254fec in bufferevent_readcb () from /var/packages/forked-daapd/target/lib/libevent-2.0.so.5
#20 0x0000007fb2243df0 in event_persist_closure () from /var/packages/forked-daapd/target/lib/libevent-2.0.so.5
#21 0x0000007fb2243f1c in event_process_active_single_queue () from /var/packages/forked-daapd/target/lib/libevent-2.0.so.5
---Type <return> to continue, or q <return> to quit---
#22 0x0000007fb2244214 in event_process_active () from /var/packages/forked-daapd/target/lib/libevent-2.0.so.5
#23 0x0000007fb22448d0 in event_base_loop () from /var/packages/forked-daapd/target/lib/libevent-2.0.so.5
#24 0x0000007fb22442cc in event_base_dispatch () from /var/packages/forked-daapd/target/lib/libevent-2.0.so.5
#25 0x000000000042fcf4 in httpd (arg=0x0) at httpd.c:767
#26 0x0000007fb1e8fde0 in ?? () from /lib64/libpthread.so.0
#27 0x0000007fb1eaf000 in ?? () from /lib64/libpthread.so.0
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

**Comment by ejurgensen** [comment]
Sorry, here we are deep in libantlr land, and I can't help with that.

**Comment by lindien954** [comment]
I temporarily solved the problem with: --disable-webinterface
