### ISSUE TITLE
last.fm support not handling last.fm auth file

### ISSUE THREAD

**Issue by atomicus** [ejurgensen/forked-daapd#89]
Me again:/

I've done:
<code>
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-lastfm
 make
 sudo make install
</code>
All without errors.
But forked-daapd seems to not find my .lastfm file, I can see in debug log that file is found (it tries to get metadata), but does not trigger lastfm support (theres no lastfm: log domain output at all).

lasfm is available as log domain, so I assume it was included in build as it should.

**Comment by ejurgensen** [comment]
Sounds like a build problem? Maybe try a fresh build. Can you see if
lastfm.o is built? You should also see -DLASTFM during compilation.
tir. 20. jan. 2015 kl. 01.23 skrev atomicus <notifications@github.com>:

**Comment by atomicus** [comment]
Indeed, a build problem.
Despite the changed configuration, build was not finding changes and used old, compiled code.
<code>
make clean
</code>
does the trick.

Or you can just remove folder and clone repo once again.
