### ISSUE TITLE
when i am running forked-daapd, error is coming. My forked-daapd build version is 26.

### ISSUE THREAD

**Issue by Nitmukesh** [ejurgensen/forked-daapd#893]
When running "/usr/sbin/forked-daapd restart" I'm now getting these errors:

[FATAL] config: Could not lookup user daapd: Success
[FATAL] main: Config file errors; please fix your config

please suggest me, what should i do.

**Comment by Porco-Rosso** [comment]
Something in your `/etc/forked-daapd.conf` file is set wrong. 
Try checking the log file `/var/log/forked-daapd.log` for hints on what might be wrong.

**Comment by Nitmukesh** [comment]
Hello Porco,

I checked second line path "/var/log/foked-daapd.log" file is not existing. and also i am giving exact path i.e. "sudo src/forked-daapd forked-daapd.conf", but still same issue is coming. 

error log: 
[FATAL]   config: Could not lookup user daapd: Success
[FATAL]     main: Config file errors; please fix your config

**Comment by ejurgensen** [comment]
If your config file has errors and can't be parsed then there will be no log file, because the location of the log file is a config file option.

If you can't find the error in your config file I would recommend you remove it and reinstall forked-daapd.

**Comment by Nitmukesh** [comment]
I have done, what you suggest me. previous issue resolve, you have to specify the location of "forked-daap.conf" file. 
you should compile code in forked-daapd location. i.e.
  
                                         cd forked-daapd-26/forked-daapd-26.0/
                                         command- "sudo src/forked-daapd -c forked-daapd.conf -f"
but i am getting new issue related to db. 

error log- [  LOG]       db: Could not open '/var/cache/forked-daapd/songs3.db': unable to open database file
[FATAL]     main: Database init failed
[  LOG]     main: mDNS deinit
[  LOG]     main: Exiting.

please let  me know how to solve this issue.
