### ISSUE TITLE
I have forked-daapd 26.0 and i want to play song by using my local machine(Computer)/Pendrive.

### ISSUE THREAD

**Issue by Nitmukesh** [ejurgensen/forked-daapd#894]
How to play songs from local machine(Computer)/Pen drive with forked-daapd binary.

Command- 
sudo src/forked-daapd -c forked-daapd.conf -f /media/nm/EMBEDDED/02.SHAPE\ OF\ MY\ HEART.mp3  

Log:

[  LOG]     main: mDNS init
[  LOG]     mdns: Avahi state change: Client running
[  LOG]       db: Now vacuuming database, this may take some time...
[  LOG]       db: Database OK with 0 active files and 6 active playlists
[  LOG]   laudio: Adding Pulseaudio sink 'Built-in Audio Analog Stereo' (alsa_output.pci-0000_00_1f.3.analog-stereo) with name 'Computer'
[  LOG]     scan: Skipping library directory /srv/music, could not dereference: No such file or directory
[  LOG]     scan: Bulk library scan completed in 0 sec
[  LOG]      lib: Library init scan completed in 1 sec (0 changes)
[  LOG]     mdns: Avahi Resolver failure: service '33095BA7C86A@Kitchen_68:8A' type '_raop._tcp' proto 0: Timeout reached

Please let me know, how to play media song on laptop.

**Comment by ejurgensen** [comment]
I suggest you read the instructions: http://ejurgensen.github.io/forked-daapd/.

If you don't have the web interface, then consult an old version of the instructions: https://github.com/ejurgensen/forked-daapd/blob/25.0/README.md
