### ISSUE TITLE
How to enable Spotify

### ISSUE THREAD

**Issue by errorkallu** [ejurgensen/forked-daapd#896]
Hi 
I am using forked-daaped for past 6 months.
Recently I took spotify  Account .
Who do I enable Spotify.
I have my Spotifiy Client ID.Where should I save it

Please Help Me 

Thanking you
-sri

**Comment by ejurgensen** [comment]
Check the help here: http://ejurgensen.github.io/forked-daapd/#spotify. I have just updated it.
