### ISSUE TITLE
Dacp not accepting song-spec parameter

### ISSUE THREAD

**Issue by m42i** [ejurgensen/forked-daapd#90]
I use Retunes for Android[1] with forked-daapd. When trying to rate a song it gives the following error:
dacp: Missing item-spec parameter in dacp.userrating query

The debug log shows this request being sent:
dacp: DACP request: /ctrl-int/1/setproperty?dacp.userrating=40&song-spec='dmap.itemid:504'&session-id=100

Notice the song-spec parameter instead of item-spec as expected. Would be feasible to allow the song-spec parameter as well?

The rating works fine with iTunes. I'm using iTunes 12.0.1.26 on OS X 10.10.1.

[1] https://play.google.com/store/apps/details?id=com.squallydoc.retune

**Comment by ejurgensen** [comment]
I've made a fix for this, it's in the branch referenced above. If you could test if it works it would be great.

**Comment by m42i** [comment]
Thanks for the quick fix. It works great for me. The ratings get written to the database and are send correctly back. Only iTunes is a bit slow picking up the changes, but after a iTunes restart they're there.

I also tested with two clients simultaneously. But the rating doesn't get propagated like the play status, e.g. skipping to the end of a track, in the now playing display. I see a "select * from files..." in the logs, so I guess that's a client issue. Am I right?

**Comment by ejurgensen** [comment]
Ok, good it is working.

I think iTunes loads the entire library on startup, so that's why you would see that behavior. Most of the clients communication with the server is request/response, but there is some support for pushing updates, as you have seen with the play status. I don't know if that can be extended to rating updates.
