### ISSUE TITLE
Airply not working after iOS13.3.1

### ISSUE THREAD

**Issue by sebasjunca** [ejurgensen/forked-daapd#902]
Hi all,

I've been using forked-daapd without any issue for the past couple of months, but since a few weeks ago I can't select any airplay speaker (Homepod or AppleTV) form the web interface. They appear on the output speakers, but when I select any of them the box just unchecks.

After checking the log, this is what it shows:

[2020-02-15 18:58:05] [  LOG]     raop: ANNOUNCE request failed in session startup: 400 Bad Request
[2020-02-15 18:58:09] [  LOG]     raop: ANNOUNCE request failed in session startup: 400 Bad Request
[2020-02-15 18:58:10] [  LOG]     raop: ANNOUNCE request failed in session startup: 400 Bad Request
[2020-02-15 18:58:13] [  LOG]     raop: ANNOUNCE request failed in session startup: 400 Bad Request
[2020-02-15 18:58:14] [  LOG]     raop: ANNOUNCE request failed in session startup: 400 Bad Request
[2020-02-15 18:58:15] [  LOG]     raop: ANNOUNCE request failed in session startup: 400 Bad Request
[2020-02-15 18:58:17] [  LOG]     raop: ANNOUNCE request failed in session startup: 400 Bad Request
[2020-02-15 18:58:19] [  LOG]     raop: ANNOUNCE request failed in session startup: 400 Bad Request
[2020-02-15 18:58:20] [  LOG]     raop: ANNOUNCE request failed in session startup: 400 Bad Request
[2020-02-15 18:58:21] [  LOG]     raop: ANNOUNCE request failed in session startup: 400 Bad Request

Aparently it is looking for a homepod with a different IP address, but after updating forked-daapd, deleting the .db and restarting the service it still don't work. 

I don't know if it's because of the iOS update or something else.

Thanks in advance for your help, this is an excellent plug in and I use it to stream my vinyl record player to a Homepod mainly.

**Comment by ejurgensen** [comment]
My Apple TV is also 13.3.1, so I tried to see if it also had issues. It is quite possible that an Apple update could cause the above. However, mine still works, so not sure why you are getting the above. If others get the same it would be good if they could share here.

A few questions for clarification:
1. For the Apple TV I suppose you mean tvOS 13.3.1? Which Apple TV is it?
2. What do you mean with "Aparently it is looking for a homepod with a different IP address"? The log message shows that the device replies, so the IP address is probably ok.
3. Which version of forked-daapd are you using?

**Comment by sebasjunca** [comment]
Hi @ejurgensen thanks for your quick reply. 

Hope this answers will help:
1. Is an AppleTV 4K with tvOS 13.3.1 and a Homepod also on 13.3.1
2. Checking the log it showed a line a few days ago with a homepod connection with a different IP address than the one it has now (although they are not configured with a static IP)
3. The version of Forked-daapd is 27.1

Thanks again!

**Comment by ejurgensen** [comment]
Ok, not sure what I can do to fix this then. If you have ipv6 enabled, you could try disabling it to see if it makes a difference. Though it really shouldn't, since forked-daapd should retry by itself with ipv4 if ipv6 fails.

**Comment by ejurgensen** [comment]
I looked more into this, and the issue seems to have some similarities to issue #557. In that issue the devices responded with 403 Forbidden to the announce, and here you are getting 400 Bad request. Those devices were Airplay 2 capable, just like yours.

So I would like to look more into that. Can you set the log level to debug, restart and then try do select the device? Then check the log if it has a line that says something like "Sending auth-setup to xxxx". It should come shortly before the above error message.

Another thing I would like to understand is why there are so many of the above errors, with only a few seconds in between. Are you perhaps trying to select the device many times?

**Comment by ejurgensen** [comment]
And one more request: From the command line, try running "avahi-browse -r -k _raop._tcp", and then post the output for the devices here.

**Comment by ejurgensen** [comment]
Closing, no feedback

**Comment by sebasjunca** [comment]
Sorry for the delay, It seems the problem is with homepod setup, it should be configured inside the home app > allow Speakers & TV Access > Anyone On the Same Network (or Everyone).

Hope this helps anyone experiencing the same problem.
