### ISSUE TITLE
[web] add "mark all as played" on podcasts page

### ISSUE THREAD

**Issue by whatdoineed2do** [ejurgensen/forked-daapd#911]
cc @chme 

Podcasts tracks can be individually `marked as played`.  It would be nice to have a `mark all as played`.

This could be implemented a couple ways:

* web - the page has a list of new episodes (and their file ids) and thus we could use the same mechanism (`/api/library/tracks/` with `id` and `play_count = increment").
* new explicit REST end point that for that action, sommething like ` /api/library/playlists/markplayed`

**Comment by chme** [comment]
Probably using the existing `PUT /api/library/tracks/{id}` might result in a lot of requests.
I prefer something like `PUT /api/library/playlists/{id}/tracks?play_count=increment` (could then also be extended for albums).

**Comment by whatdoineed2do** [comment]
I was thinking that unless there was a lot of new podcasts using multiple calls to `/api/library/tracks/{id}` would be the same as if the user manually clicked on the "mark as played" button on each podcast entry/modal dialogue.

Also I was intending this to clear out the "new episodes" and not impact the play count on the other tracks of the playlist.

**Comment by whatdoineed2do** [comment]
One thing we may think about is how/where we let people "mass" mark as played.

Ideally it'd be on the `PagePodcasts` - it has the `new episodes` and should be relatively few - so calling `/api/library/tracks/{id}?play_count=increment` on those few episodes shouldn't cause too many calls to the back end.  

Doing this one the `PagePodcast` page we can use the `api/library/playlists/{id}/tracks?play_count=increment` but this is cumbersome if we are trying to mark a load of things as played.

**Comment by chme** [comment]
Closing, the JSON API change is already merged and the web interface changes are part of #917
