### ISSUE TITLE
[web] Volume only view request

### ISSUE THREAD

**Issue by jiserra** [ejurgensen/forked-daapd#919]
Is it possible to have a route to view the _Volume view_ only? With the _Volume view_ I'm referring to the overlay that comes up when you hover on the volume icon (or the hamburger icon in the mobile view).

The reason for it is that I would love to wrap that view in an electron app or similar to control the volume of my Airplay speakers directly through there without the need to open the address in a browser window and clicking the correspondent thing for that overlay to appear.

Thanks!

**Comment by chme** [comment]
It could be done, but if you want to create an electron app, imo it would be better to directly call the JSON API and connect to the websocket.

You can find the docs for the JSON API here: https://github.com/ejurgensen/forked-daapd/blob/master/README_JSON_API.md

**Comment by chme** [comment]
If you need help with the JSON API and the WS let me know.

**Comment by ejurgensen** [comment]
That's pretty neat! It would be great if you would add a page to the [wiki](https://github.com/ejurgensen/forked-daapd/wiki) describing how you did it.
