### ISSUE TITLE
Not exactly an issue: please file this away.

### ISSUE THREAD

**Issue by jimmiedave** [ejurgensen/forked-daapd#920]
After switching to Apple's "Music" app in Catalina, I was worried forked-daapd wouldn't load. it does work properly, but it seemed to be unable to load - only sometimes.

I spent tens of hours trying to diagnose why the forked-daapd library wouldn't load - and then it finally started working correctly, and I had no idea why.

Solved this tonight, and I thought it might prevent all you good contributors from chasing your tail trying to solve this sometime. It is NOT a forked-daapd problem:

IF the name of the music library is long enough that the "Library" menu extends past the left edge of the playlist panel in the "Music" app - that is, if the popup menu to select the forked-daapd library is partly floating over the desktop, instead of completely within the "Music" application window, the library name appears, and can be selected and loaded UNLESS the "Music" application is at the left edge of the desktop or of a screen boundary. IN THAT CASE the music library menu does not appear, and forked-daapd libraries cannot be selected to load. Clicks alternately highlight, or don't highlight the <name of library> menu name. (if you've already loaded a forked-daapd library, you can't select away from it either).

![Screen Shot 2020-03-18 at 9 48 30 PM](https://user-images.githubusercontent.com/35353530/77023313-47c49b00-6962-11ea-9b78-fc8503ecc911.png)

_so_ many hours on this ridiculous business. Remember to ask bug reporters about this...

**Comment by ejurgensen** [comment]
Thanks for sharing. Not sure if I should keep the issue open or not? I suppose Google will find it either way, so maybe it is ok to close?

**Comment by jimmiedave** [comment]
Yeah, let's close, as you've been informed...

Thanks for continuing to maintain forked-daapd!
