### ISSUE TITLE
deleted radiostations in queue

### ISSUE THREAD

**Issue by Ulrichgau** [ejurgensen/forked-daapd#921]
I'm using a freshly installed raspbian buster and FORKED-DAAPD - VERSION 27.1. mainly as an internetradio. From time to time a radiostation in the queue is deleted, (maybe after receiving problems). I had receiving problems also in a former mpd version (0.19) but this version jumped simply to the next station, forked-daapd jumps to the next station and deletes the failed entry in the playlist. So I have to reload the playlist from time to time which is inconvenient and reduces the "womens acceptance factor" significantly ;-)

**Comment by ejurgensen** [comment]
Yes, forked-daapd will remove items from the queue if the item cannot be opened. This was done to avoid a situation where forked-daapd infinitely would try to open a source very rapidly, which could if happen if the queue only had failing items + the user has set repeat mode.

I always care about the WAF, but I'm not sure what a better solution would be. I would say having multiple radio stations in a queue is a bit unusual, but I guess you are just using forked-daapd in another way than me.
