### ISSUE TITLE
Playlists: old deleted playlist show and some playlists are duplicated.

### ISSUE THREAD

**Issue by chesterdkat** [ejurgensen/forked-daapd#924]
In my forked-daapd 27.1 library on a Raspberry Pi 3 running Buster most playlists are duplicated. Playlists that were deleted in iTunes also continue to show up in forked-daapd. I have a nightly sync via rsync copying and syncing my iTunes library from my Mac with the following commands:

/usr/bin/rsync -avzh --delete -e ssh /Volumes/Data/iTunes/ myacc@192.168.0.2:/media/iTunes/

How can I flush and reset the playlists in forked-daapd? Is there something that I am doing incorrectly that is obvious?

Thanks,

**Comment by ejurgensen** [comment]
Sounds like a bug in forked-daapd, but I am not sure what might be triggering it. Can you do the following to help locate the issue?

1. Run `sqlite3 /var/cache/forked-daapd/songs3.db`
2. Run `select * from playlists where title like "%titlename%";` - where titlename is part of the title of a duplicated playlist.
3. Quit with ctrl+d
4. Paste the output here

There are various ways you can get forked-daapd to rescan, you can for instance try the init-rescan method described here http://ejurgensen.github.io/forked-daapd/#library, see "Libraries on network mounts". But before you do that please do the above.

**Comment by chesterdkat** [comment]
sqlite> select * from playlists where title like "%Stars%";
40|Stars|3||1585421085|0|/media/iTunes/iTunes Music Library.xml|0|0|/file:/media/iTunes/iTunes Music Library.xml/Stars|0|6||0|1
41|3 or more Stars|3||1585421085|0|/media/iTunes/iTunes Music Library.xml|0|0|/file:/media/iTunes/iTunes Music Library.xml/3 or more Stars|0|6||0|1
42|3+ Stars added last 90 days|3||1585421107|0|/media/iTunes/iTunes Music Library.xml|0|0|/file:/media/iTunes/iTunes Music Library.xml/3+ Stars added last 90 days|0|6||0|1
43|4 & 5 Stars|3||1585421107|0|/media/iTunes/iTunes Music Library.xml|0|0|/file:/media/iTunes/iTunes Music Library.xml/4 & 5 Stars|0|6||0|1
44|4 Stars + Holiday|3||1585421120|0|/media/iTunes/iTunes Music Library.xml|0|0|/file:/media/iTunes/iTunes Music Library.xml/4 Stars + Holiday|0|6||0|1
48|5 Stars|3||1585421148|0|/media/iTunes/iTunes Music Library.xml|0|0|/file:/media/iTunes/iTunes Music Library.xml/5 Stars|0|6||0|1
50|Blues 3+Stars|3||1585421149|0|/media/iTunes/iTunes Music Library.xml|0|0|/file:/media/iTunes/iTunes Music Library.xml/Blues 3+Stars|0|6||0|1
51|Caribbean 4+ Stars|3||1585421149|0|/media/iTunes/iTunes Music Library.xml|0|0|/file:/media/iTunes/iTunes Music Library.xml/Caribbean 4+ Stars|0|6||0|1
53|Holiday 4+ Stars|3||1585421151|0|/media/iTunes/iTunes Music Library.xml|0|0|/file:/media/iTunes/iTunes Music Library.xml/Holiday 4+ Stars|0|6||0|1
55|Jazz 3+ Stars|3||1585421151|0|/media/iTunes/iTunes Music Library.xml|0|0|/file:/media/iTunes/iTunes Music Library.xml/Jazz 3+ Stars|0|6||0|1
56|Latin 3+ Stars|3||1585421152|0|/media/iTunes/iTunes Music Library.xml|0|0|/file:/media/iTunes/iTunes Music Library.xml/Latin 3+ Stars|0|6||0|1
62|World 3+ Stars|3||1585421175|0|/media/iTunes/iTunes Music Library.xml|0|0|/file:/media/iTunes/iTunes Music Library.xml/World 3+ Stars|0|6||0|1
125|Stars|3||1585421633|0|/media/iTunes/iTunes Library.xml|0|0|/file:/media/iTunes/iTunes Library.xml/Stars|0|6||0|1
126|3 or more Stars|3||1585421633|0|/media/iTunes/iTunes Library.xml|0|0|/file:/media/iTunes/iTunes Library.xml/3 or more Stars|0|6||0|1
127|3+ Stars added last 90 days|3||1585421658|0|/media/iTunes/iTunes Library.xml|0|0|/file:/media/iTunes/iTunes Library.xml/3+ Stars added last 90 days|0|6||0|1
128|4 & 5 Stars|3||1585421658|0|/media/iTunes/iTunes Library.xml|0|0|/file:/media/iTunes/iTunes Library.xml/4 & 5 Stars|0|6||0|1
129|4 Stars + Holiday|3||1585421672|0|/media/iTunes/iTunes Library.xml|0|0|/file:/media/iTunes/iTunes Library.xml/4 Stars + Holiday|0|6||0|1
133|5 Stars|3||1585421703|0|/media/iTunes/iTunes Library.xml|0|0|/file:/media/iTunes/iTunes Library.xml/5 Stars|0|6||0|1
135|Blues 3+Stars|3||1585421705|0|/media/iTunes/iTunes Library.xml|0|0|/file:/media/iTunes/iTunes Library.xml/Blues 3+Stars|0|6||0|1
136|Caribbean 4+ Stars|3||1585421705|0|/media/iTunes/iTunes Library.xml|0|0|/file:/media/iTunes/iTunes Library.xml/Caribbean 4+ Stars|0|6||0|1
138|Holiday 4+ Stars|3||1585421706|0|/media/iTunes/iTunes Library.xml|0|0|/file:/media/iTunes/iTunes Library.xml/Holiday 4+ Stars|0|6||0|1
140|Jazz 3+ Stars|3||1585421707|0|/media/iTunes/iTunes Library.xml|0|0|/file:/media/iTunes/iTunes Library.xml/Jazz 3+ Stars|0|6||0|1
141|Latin 3+ Stars|3||1585421708|0|/media/iTunes/iTunes Library.xml|0|0|/file:/media/iTunes/iTunes Library.xml/Latin 3+ Stars|0|6||0|1
147|World 3+ Stars|3||1585421736|0|/media/iTunes/iTunes Library.xml|0|0|/file:/media/iTunes/iTunes Library.xml/World 3+ Stars|0|6||0|1
sqlite>

**Comment by ejurgensen** [comment]
It looks like you have two similar iTunes library files:
/media/iTunes/iTunes Music Library.xml
/media/iTunes/iTunes Library.xml

So that is why the playlists are duplicated. It's been some time since I used iTunes, perhaps it has changed so it makes two of these files? Or maybe one of these files is just an old leftover that you can delete?

**Comment by chesterdkat** [comment]
I just deleted "iTunes Library" and left "iTunes Library.xml" and did "touch test.full-rescan". I'll let you know what happens. I Rsync my library nightly. If this does the trick I'll set the parameter to not sync "iTunes Library" going forward. If not then I'll reverse the choice and see how that goes.
Thank you!
