### ISSUE TITLE
Feature: Smart Playlists: additional data: bitrate, codectype, bits_per_sample

### ISSUE THREAD

**Issue by bakestile** [ejurgensen/forked-daapd#928]
It would be nice to be able to have Smart Playlist rules that incorporate the following data currently present in the database:

- bitrate
- codectype
- bits_per_sample

The use case is the ability to select 24-bit audio separately from 16-bit audio. iTunes provides the ability to use bitrate & codectype, but not bits per sample, so my current approach would map to `codectype is "alac" and bitrate > 1150 kbps`. It's not perfect, but it catches most content in my library for making HD-only playlists.

Looking at bits_per_sample in the forked-daapd database, it appears that m4a ALAC files w/ 24-bit audio show up as '32' (16-bit audio comes back with a correct '16'), so it would work for my purpose. *I'm not sure if the fact that it says 32, rather than 24, there is a bug or not.* Either way, with the 3 data requested I could work something out equivalent to my current iTunes smart playlists. I'm not aware of a way to view bits_per_sample in the forked-daapd interface, but the iTunes song info (as well as mediainfo) both confirm the 24-bit sample size/bit depth on said files.

The equivalent of codectype in iTunes would be going through some kind of enumeration (maybe only in the interface?). In iTunes, 'alac' would be 'Apple Lossless' in the rules. Personal preference would be that it remain as-is from the database, so `codectype is "alac"`.

Statements regarding 24-bit audio in m4a ALAC files are made via inspection of sqlite database from forked-daapd 27.1 on RPi, library on SMB NAS, clean/new library import.

**Comment by whatdoineed2do** [comment]
This is simple to support:
```
diff --git a/src/SMARTPL.g b/src/SMARTPL.g
index 887293fd..851c7a58 100644
--- a/src/SMARTPL.g
+++ b/src/SMARTPL.g
@@ -87,6 +87,7 @@ STRTAG                :       'artist'
                        |       'album_id'
                        |       'songartistid'
                        |       'songalbumid'
+                       |       'codectype'
                        ;
 
 INTTAG         :       'play_count'
@@ -96,6 +97,8 @@ INTTAG                :       'play_count'
                        |       'compilation'
                        |       'track'
                        |       'disc'
+                       |       'bitrate'
+                       |       'bits_per_sample'
                        ;
 
 DATETAG                :       'time_added'
```

And tested with a `.smartpl` like this:
```
"issue928" {
  bitrate > 800 AND
  codectype is "flac"
}
```
