### ISSUE TITLE
forked-daapd refuses to stop when changing the amplifier input

### ISSUE THREAD

**Issue by beaudett** [ejurgensen/forked-daapd#934]
Hello, 

I am very pleased with forked-daapd and in this period, it is being used a lot at home. 
I however noticed a recent change of behavior, which I find a bit annoying, which probably appeared with the last update I did on my raspberry pi (raspbian stretch)  from forked-daapd:armhf (27.1.102.gite642147-2, 27.1.103.git51b7a88-2). 

My main audio device is a Marantz AV receiver with AirPlay that is also connected to the TV. In previous versions, when forked-daapd was playing music and I was switching on the TV, forked-daapd automatically stopped playing and the sound was that of the TV. In the current version, forked-daapd doesn't stop and after a few seconds it takes over the TV sound (and the artwork of the title played appears on the screen). I have to explicitly pause forked-daapd to be able to watch TV.
From the log (*) , I see that forked-daapd detects that I switched the source but decides to re-enable it.

If this change of behavior was intended, would it be possible to make it configurable ?

Thanks a lot !

(*)
https://gist.github.com/beaudett/6dda29debc5e704152564adc530c35f7

**Comment by ejurgensen** [comment]
Thanks for a good account of the issue. This behavior is not intentional, it is a result of version 27.1 supporting the "dmcp.device-prevent-playback"-command that you see in your log. Previous versions just ignored that, but as you can see from the log your Marantz makes a "dmcp.device-prevent-playback=0" request, which normally means to resume playback on that device, so that is what forked-daapd does.

However, your device also makes a "dmcp.device-busy=1", which I suppose means "don't start playback even though I send a dmcp.device-prevent-playback=0". I don't understand the logic of that command sequence, the device could just not send the resume command. Anyway, "dcmp.device-busy" is not supported by forked-daapd, so that is why you get an unwanted restart. Actually, I have never seen a request "dcmp.device-busy" before. 

I think the way to fix the issue would be to add this support. The question is exactly how... especially how long forked-daapd should consider a device being busy, since there is no guarantee the device will send a "dmcp.device-busy=0".

**Comment by beaudett** [comment]
Hello, 

thanks for the prompt feedback ! One small addition wrt. my previous message: the behavior I described as occurring when I was switching on the TV is exactly the same when I change the amplifier input. 
Indeed, I did exactly the same test switching from forked-daapd airplay to tuner audio. I get the audio for about 1s and forked-daapd takes over and I see the same sequence of
(1) dmcp.device-prevent-playback=1
followed about 1s later by
(2) dmcp.device-busy=1
(3) dmcp.device-prevent-playback=0
in the logfile

I would interpret this sequence as follows:
(1) When I change the source, the player sends the "dmcp.device-prevent-playback=1" to notify that it will be busy switching audio (and possibly also video) source(s). Presumably, the device cannot do anything else while working on it.
(2) When the player has switched the source, it notifies possible clients that it is busy playing something else
(3) Simultaneously, it notifies clients that, even though it plays something else, it is ready to accept playback requests if the user wants to. 
and that's basically when I was finding convenient with the previous version: the audio output is driven by the device that I activate: when I switch on TV, it changes automatically the sound to TV (and forked-daapd silently stops unless another client is listening); if I start forked-daapd playback, it changes the input to airplay; and so on and so forth.
At least, that seems to be the design of the Marantz: there is no button to activate or stop the airplay, the switch to airplay is triggered by forked-daaapd and the stop used to be when switching source. 
As a result, there is no "dmcp.device-busy=0" that is sent out, at least not on that occasion. 

As a matter of fact, I have done a grep before and after "dmcp.device-busy=0"  in the logfile that can be found here:
https://gist.github.com/beaudett/768cd14c98629150f96ac9cc40ff9e41
and the pattern seems quite different. 

The behavior that would fit with this Marantz  device is that when "dmcp.device-prevent-playback=1" is sent out, forked-daapd checks whether an other client is listening, and if there isn't any, it stops.

Let me know if there is something else I can do to diagnose the problem. Thanks again !

**Comment by ejurgensen** [comment]
Yes, I think you are right about the use of prevent-playback. It is also interesting that device-busy=0 is not really used - as your log shows the device makes this request after being enabled, which seems kind of pointless (it also makes an odd volume request after being enabled, btw).

I have tested with iTunes to see how it reacts to various combinations of device-prevent-playback and device-busy, here you can see the results:

Test | Action | Playing to 1 device | Playing to 2 devices
-- | -- | -- | --
1 | device-prevent-playback=1 | Playback stops on device. Device selected + grayed out. | Playback stops on device. Playback continues on second device. Device selected + grayed out.
1 | device-prevent-playback=0 | Playback does not resume. Device selected + no longer grayed. | Playback resumes on device. Device selected + no longer grayed.
2 | device-prevent-playback=1 | (as test 1) |  
2 | Try to start playback | Waits for device |  
2 | device-prevent-playback=0 | Playback resumes. Device selected + no longer grayed. |  
3 | device-prevent-playback=1 | Playback stops on device. Device selected + grayed out. | Playback stops on device. Playback continues on second device. Device selected + grayed out.
3 | device-busy=1 | Device selected + grayed out | Device selected + grayed out.
3 | device-prevent-playback=0 | Playback does not resume. Device selected + grayed out | Playback does not resume on device. Device selected + no longer grayed.
3 | device-busy=0 | Playback does not resume. Device selected + no longer grayed | Playback resumes on device. Device selected + no longer grayed.
4 | device-busy=1 | Playback stops on device. Device selected + grayed out | Playback stops on device. Playback continues on second device. Device selected + grayed out.
4 | device-busy=0 | Playback does not resume. Device selected + no longer grayed. | Playback resumes on deviceDevice selected + no longer grayed.
5 | device-busy=1 | (as test 4) |
5 | Try to start playback | Waits for device |  
5 | device-busy=0 | Playback resumes. Device selected + no longer grayed. |  

In all cases, unselecting a device resets device-prevent-playback and device-busy.

What is strange is that while prevent-playback and busy are clearly registered separately by iTunes, they seem to work exactly the same.

I think forked-daapd should behave like iTunes, so I will work on that. In practice there are some difficulties in this. One is that many clients only understand speakers being disabled/enabled - not this special state where a speaker is enabled but grayed out and not playing.

**Comment by ejurgensen** [comment]
I've added a change so that forked-daapd now matches iTunes better. It should also fix the issue you have. I see you use my RPi build, so the fix will be included in the next release of that. It should only be a few days away. It would be great if you can report back if it works.

**Comment by beaudett** [comment]
Thank you so much !  I will certainly report on the next build.

**Comment by beaudett** [comment]
I have just upgraded to 27.1.104.git805cd16-2 and I confirm that your fix is working as expected. 
Thank you for the prompt feedback and the great piece of software !

**Comment by beaudett** [comment]
Hello,
I am currently running the version 27.1.106.gite3f8c5b-3 and I am observing the same behavior as the one initially reported.
I have copied the log (debug mode) here:
https://gist.github.com/beaudett/0d06b46f6a328d8858ea81e23fba2c6e
Before the log, forked-daapd was playing a podcast (a great new feature) and at the time of the first line, I switched the amplified to the radio, which used to stop forked-daapd. With this version, a few seconds later, forked-daapd takes control of the amplifier and resumes playing the podcast. 
Thanks in advance for your help.

**Comment by ejurgensen** [comment]
Yes, this is due to a workaround added for issue #734. I have now added a commit that limits the workaround, so that you shouldn't be affected by it any more. And just in case you still are, I also added a config option to disable this resumption of playback on a device level. The change will be included in the next RPi version.
