### ISSUE TITLE
alsamixer configuration

### ISSUE THREAD

**Issue by tropas2001** [ejurgensen/forked-daapd#935]
Hi,

Great document describing how to setup alsa, however would it be possible to expand it to cover how to use alsamixer?

I've got a hifiberry amp2 and the suggestion from the vendor [is](https://www.hifiberry.com/docs/software/guide-adding-equalization-using-alsaeq/  that a asound.conf file should contain:

`pcm.!default {
  type plug
  slave.pcm plugequal;
}
ctl.!default {
  type hw card 0
}
ctl.equal {
  type equal;
}
pcm.plugequal {
  type equal;
  slave.pcm "plughw:0,0";
}
pcm.equal {
  type plug;
  slave.pcm plugequal;
}`

but I'm not sure what I would then use to configure in forked-daapd.conf

**Comment by ejurgensen** [comment]
I don't know enough about this to do it, but perhaps @whatdoineed2do can make a PR on this?

**Comment by whatdoineed2do** [comment]
I gave this a go on this Fedora dev box and I've got it working with NO `dmix` device.

@tropas2001 - it's difficult to do this wihout knowing what alsa thinks your devices are.   However you can apply the following by changing `plughw:0` to your amp device as seen under `aplay -l`.  This assumes you have also installed the right packages for the `alsaeq` and `ladsap` plugins on your RPI.

In `/etc/asound.conf` add this:
```
ctl.equal {
  type equal;
  #library /usr/lib64/ladspa/caps.so
}
pcm.plugequal {
  type equal;
  slave.pcm "plughw:0,0";
  #library /usr/lib64/ladspa/caps.so
}
pcm.equal {
  type plug;
  slave.pcm plugequal;
  hint.description "equalised device"
}
```
In `/etc/forked-daapd.conf` add this:
```
alsa "equal" {
    nickname = "Equalised Output"
    mixer = "PCM"
    mixer_device = "hw:0"
}
```
Goto the web ui and on the outputs (the speaker button in top right) you should see an output called `Equalised Output" which you should select and set the volume.

Now start playback for any of your tracks and you should hopefully hear the output.  In a terminal, `alsamixer -Dequal` and you'll see the eqaliser - to test that this is all working, go and drop the upper frequencies and boosting the bass frequencies and give it a second - if this changes the sound profile from your speakers, well done, its done.

What I havent quite figured out is how to plug this into `dmix` but this may not affect you.

**Comment by tropas2001** [comment]
Thanks, but unfortunately I get the following errors;
[2020-04-13 12:22:00] [  LOG]   laudio: Failed to open configured mixer element 'PCM'
[2020-04-13 12:22:00] [  LOG]   laudio: Could not open mixer 'hw:0' ('PCM')
[2020-04-13 12:22:00] [  LOG]   player: Could not start ALSA device 'Equalised Output'
[2020-04-13 12:22:00] [  LOG]   player: Could not activate ALSA device 'Equalised Output'
[2020-04-13 12:22:00] [  LOG]     dacp: Speakers de/activation failed!

this is the output from aplay- l
**** List of PLAYBACK Hardware Devices ****
card 0: sndrpihifiberry [snd_rpi_hifiberry_dacplus], device 0: HiFiBerry DAC+ HiFi pcm512x-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0


Any ideas?

**Comment by whatdoineed2do** [comment]
The `mixer` name needs to change from `PCM`.  The `README_ALSA.md` mentions this under the `Mixer name` section.  Try this:
```
$ amixer -c 0
...
## look for "pvolume" in the capabilities list for each "Simple mixer control", something like this:
Simple mixer control 'USE_THE_VALUE_HERE_FOR_MIXER',0
  Capabilities: pvolume
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 1
  Mono:
  Front Left: Playback 1 [100%] [0.00dB]
  Front Right: Playback 1 [100%] [0.00dB]
...
```
Use the name of the `Simple mixer control` that has a `pvolume` as the `mixer = ` value and restart.
