### ISSUE TITLE
Issues installing on FreeBSD 10.1

### ISSUE THREAD

**Issue by thorsteneckel** [ejurgensen/forked-daapd#94]
Hi there,

as mentioned in [the last issue](https://github.com/ejurgensen/forked-daapd/issues/93) I opened I'm trying to install your fork of the fork-daapd on my FreeBSD 10.1. I'm currently at the point where I have to run ```gmake``` in the ```fork-daapd``` folder, which gives me the following error:

```
mv -f .deps/forked_daapd-DAAP2SQL.Tpo .deps/forked_daapd-DAAP2SQL.Po
/bin/sh ../libtool  --tag=CC   --mode=link cc -I/usr/include -I/usr/local/lib -D_REENTRANT -D_THREAD_SAFE -pthread -I/usr/local/include   -I/usr/local/include   -I/usr/local/src/forked-daapd/avl-0.3.5  -I/usr/local/include -I/usr/local/include    -I/usr/local/include -D_THREAD_SAFE -D_REENTRANT   -I/usr/local/include -I/usr/local/include/libxml2 -I/usr/local/include -I/usr/local/include  -march=native -g -Ofast -pipe -I/usr/local/include -L/usr/local/include -I/usr/include -I/usr/local/src/forked-daapd/avl-0.3.5 -L/usr/local/src/forked-daapd/avl-0.3.5 -Wall -D_LARGEFILE_SOURCE  -L/usr/local/lib -L/usr/lib -o forked-daapd forked_daapd-main.o forked_daapd-db.o forked_daapd-logger.o forked_daapd-conffile.o forked_daapd-cache.o forked_daapd-filescanner.o forked_daapd-filescanner_ffmpeg.o forked_daapd-filescanner_playlist.o forked_daapd-filescanner_icy.o forked_daapd-filescanner_itunes.o forked_daapd-mdns_avahi.o forked_daapd-remote_pairing.o  forked_daapd-ffmpeg_url_evbuffer.o  forked_daapd-httpd.o forked_daapd-httpd_rsp.o forked_daapd-httpd_daap.o forked_daapd-httpd_dacp.o forked_daapd-dmap_common.o forked_daapd-transcode.o forked_daapd-pipe.o forked_daapd-artwork.o forked_daapd-misc.o forked_daapd-rng.o forked_daapd-rsp_query.o forked_daapd-daap_query.o forked_daapd-player.o  forked_daapd-laudio_oss4.o forked_daapd-raop.o evrtsp/forked_daapd-rtsp-libevent20.o forked_daapd-scan-wma.o     forked_daapd-RSPLexer.o forked_daapd-RSPParser.o forked_daapd-RSP2SQL.o forked_daapd-DAAPLexer.o forked_daapd-DAAPParser.o forked_daapd-DAAP2SQL.o -lrt -L/usr/lib -L/usr/local/lib -L/usr/local/lib -lavahi-common -lavahi-client   -L/usr/local/lib -lsqlite3   -L/usr/local/src/forked-daapd/avl-0.3.5 -L/usr/local/include -L/usr/local/lib -lconfuse     -L/usr/local/lib -levent -lavl -L/usr/local/lib -lmxml -lpthread   -lantlr3c -L/usr/local/lib -lplist -L/usr/local/lib -lgcrypt -lgpg-error -L/usr/local/lib -lgpg-error  -lunistring
libtool: link: cc -I/usr/include -I/usr/local/lib -D_REENTRANT -D_THREAD_SAFE -pthread -I/usr/local/include -I/usr/local/include -I/usr/local/src/forked-daapd/avl-0.3.5 -I/usr/local/include -I/usr/local/include -I/usr/local/include -D_THREAD_SAFE -D_REENTRANT -I/usr/local/include -I/usr/local/include/libxml2 -I/usr/local/include -I/usr/local/include -march=native -g -Ofast -pipe -I/usr/local/include -I/usr/include -I/usr/local/src/forked-daapd/avl-0.3.5 -Wall -D_LARGEFILE_SOURCE -o forked-daapd forked_daapd-main.o forked_daapd-db.o forked_daapd-logger.o forked_daapd-conffile.o forked_daapd-cache.o forked_daapd-filescanner.o forked_daapd-filescanner_ffmpeg.o forked_daapd-filescanner_playlist.o forked_daapd-filescanner_icy.o forked_daapd-filescanner_itunes.o forked_daapd-mdns_avahi.o forked_daapd-remote_pairing.o forked_daapd-ffmpeg_url_evbuffer.o forked_daapd-httpd.o forked_daapd-httpd_rsp.o forked_daapd-httpd_daap.o forked_daapd-httpd_dacp.o forked_daapd-dmap_common.o forked_daapd-transcode.o forked_daapd-pipe.o forked_daapd-artwork.o forked_daapd-misc.o forked_daapd-rng.o forked_daapd-rsp_query.o forked_daapd-daap_query.o forked_daapd-player.o forked_daapd-laudio_oss4.o forked_daapd-raop.o evrtsp/forked_daapd-rtsp-libevent20.o forked_daapd-scan-wma.o forked_daapd-RSPLexer.o forked_daapd-RSPParser.o forked_daapd-RSP2SQL.o forked_daapd-DAAPLexer.o forked_daapd-DAAPParser.o forked_daapd-DAAP2SQL.o  -L/usr/local/include -L/usr/local/src/forked-daapd/avl-0.3.5 -L/usr/local/lib -L/usr/lib -lrt /usr/local/lib/libavahi-common.so /usr/local/lib/libavahi-client.so -lsqlite3 -lconfuse -levent -lavl -lmxml -lpthread /usr/local/lib/libantlr3c.a -lplist -lgcrypt -lgpg-error -lunistring -pthread -Wl,-rpath -Wl,/usr/local/lib -Wl,-rpath -Wl,/usr/local/lib
/usr/bin/ld: //lib/libz.so.6: invalid DSO for symbol `deflate@@ZLIB_1.2.4.0' definition
//lib/libz.so.6: could not read symbols: Bad value
cc: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:612: recipe for target 'forked-daapd' failed
gmake[3]: *** [forked-daapd] Error 1
gmake[3]: Leaving directory '/usr/local/src/forked-daapd/forked-daapd/src'
Makefile:505: recipe for target 'all' failed
gmake[2]: *** [all] Error 2
gmake[2]: Leaving directory '/usr/local/src/forked-daapd/forked-daapd/src'
Makefile:532: recipe for target 'all-recursive' failed
gmake[1]: *** [all-recursive] Error 1
gmake[1]: Leaving directory '/usr/local/src/forked-daapd/forked-daapd'
Makefile:399: recipe for target 'all' failed
gmake: *** [all] Error 2
```

What I have done so far (step by step):

1.1. create working folder
```
export WORKDIR=/usr/local/src/forked-daapd
mkdir -p $WORKDIR
cd $WORKDIR
```

1.2. install packages
```
pkg install gcc48 gmake libantlr3c autoconf automake libtool gettext gperf glib libconfuse libevent2 mxml libgcrypt taglib libunistring libplist openjdk8-jre oss libiconv avahi-app avahi sqlite3 yasm pkgconf
```

1.3. install libavl_0.3.5
```
cd $WORKDIR
curl -O http://www.debian.co.il/debian/pool/main/liba/libavl/libavl_0.3.5.orig.tar.gz
tar xzvf libavl_0.3.5.orig.tar.gz
cd avl-0.3.5
gcc48 -O2 -fomit-frame-pointer -pipe -w -fPIC -o avl.o -c avl.c && ar -rc libavl.a avl.o
```

1.4. install antlr3
```
cd $WORKDIR
mkdir antlr3 && cd antlr3
curl -O https://raw.githubusercontent.com/antlr/website-antlr3/gh-pages/download/antlr-3.3-complete.jar
echo '#!/bin/sh' > antlr3
echo exec /usr/local/bin/java -cp $WORKDIR/antlr3/antlr-3.3-complete.jar org.antlr.Tool \"\$@\" >> antlr3
chmod u+x antlr3
export PATH="$PATH:$WORKDIR/antlr3"
```

1.5. install libantlr3c
```
cd $WORKDIR
curl -O http://www.antlr3.org/download/C/libantlr3c-3.2.tar.gz
tar xzvf libantlr3c-3.2.tar.gz
cd libantlr3c-3.2
./configure --disable-antlrdebug --disable-abiflags --disable-dependency-tracking --enable-shared=no
gmake install
```

1.6. install zlib-1.2.8
```
cd $WORKDIR
curl -O http://zlib.net/zlib-1.2.8.tar.gz
tar xzvf zlib-1.2.8.tar.gz
cd zlib-1.2.8
./configure
gmake install
```

1.7. "fixing" forked-daapd configure.ac
( otherwise error message "libav (ffmpeg) >= 0.5.1 required" is thrown no matter what )
```
# search for:
AC_CHECK_LIB([avcodec], [av_lockmgr_register], , AC_MSG_ERROR([libav (ffmpeg) >= 0.5.1 required]))
# replace with:
AC_CHECK_LIB([avcodec], [av_lockmgr_register], AC_MSG_ERROR([libav (ffmpeg) >= 0.5.1 required]))
```

1.8. install forked-daapd
```
cd $WORKDIR
cd forked-daapd
autoreconf -iv -Wno-portability
CC=cc CFLAGS="-march=native -g -Ofast -pipe -I/usr/local/include -L/usr/local/include -I/usr/include -I$WORKDIR/avl-0.3.5 -L$WORKDIR/avl-0.3.5" LDFLAGS="-L/usr/local/lib -L/usr/lib" LIBUNISTRING_CFLAGS="-I/usr/include -I/usr/local/lib" LIBUNISTRING_LIBS="-L/usr/lib -L/usr/local/lib" ZLIB_CFLAGS="-I/usr/include -I/usr/local/lib" ZLIB_LIBS="-L/usr/lib -L/usr/local/lib" LIBAV_LIBS="-L$WORKDIR/avl-0.3.5 -L/usr/local/include" LIBAV_CFLAGS="-I$WORKDIR/avl-0.3.5  -I/usr/local/include" ./configure  --enable-itunes --with-oss4=/usr/local/lib/oss/include/sys
gmake
```

After fireing gmake the error shown above is thrown and gcc stops.

I'm using information gathered from here:
https://github.com/ejurgensen/forked-daapd/blob/master/INSTALL
https://github.com/ejurgensen/forked-daapd/issues/56#issuecomment-59578947
https://github.com/jasonmc/forked-daapd/issues/6#issuecomment-826578

Any feedback is appriciated.

Greetings,
 Thorsten

**Comment by thorsteneckel** [comment]
Side question:
Is "7.1 "fixing" forked-daapd configure.ac" a general issue? I've just looked up 'AC_CHECK_LIB' in the docs and guessed that the error message should be the second parameter:
```
AC_CHECK_LIB (library, function, [action-if-found], [action-if-not-found], [other-libraries])
```
https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Libraries.html

**Comment by freultwah** [comment]
I am one of the guys who has worked on making the thing compile on FreeBSD since the days of yore when Julien Blache was in the mix. I think you are doing too much. This is what I have been doing.

1.2 - gcc48 is completely unnecessary. In fact, even oss4 is unnecessary.

I myself have been avoiding installing OSS4, electing to use the soundcard.h that is part of the base system. Since the configure script breaks when told to look for the file in /usr/include, I've just linked it to where the script expects the OSS4 header file:

mkdir -p /usr/local/lib/oss/include/sys/
ln -sf /usr/include/sys/soundcard.h /usr/local/lib/oss/include/sys/

Just a thought. If you don't actually need OSS4, you can just as well throw it out and use what's already installed.

1.3 - In the avl-0.3.5 directory, just edit the Makefile to include the line CC=clang. Then, just make && make install

1.4 - antlr 3.4 is OK. Just copy antlr-3.4-complete.jar to /usr/local/share/java/. My antlr3 file (which I installed in /usr/local/bin) looks like this:

#!/bin/sh
export CLASSPATH
CLASSPATH=$CLASSPATH:/usr/local/share/java/antlr-3.4-complete.jar:/usr/share/java
/usr/local/openjdk8/bin/java org.antlr.Tool $*

1.5 - libantlr3c-3.4 is also OK. My config.log indicates that I ran ./configure --enable-64bit. gmake && gmake install is all that is needed after that.

1.6 - zlib is already installed as part of the base system in /lib/libz.so.6, no reason to install it again.

1.7 - just remove the offending line from configure.ac.

1.8 - my configure script:

#!/usr/local/bin/bash
CFLAGS="-march=native -O2 -pipe" LDFLAGS=-L/usr/local/lib CPPFLAGS=-I/usr/local/include ./configure --localstatedir=/var --with-oss4=/usr/local/lib/oss/include/sys --enable-itunes --enable-lastfm

Caveat: I do admit that I have been building ffmpeg by hand and avoiding the version in ports, because it adds too much version information to the binaries (ffmpeg becomes ffmpeg25 and the libraries get stuck in subfolders that the configure script is unable to see - or I am too stupid to figure out how to make it) so I just, well, roll my own.

**Comment by thorsteneckel** [comment]
Hi @freultwah - thanks a lot for your reply and the work for making it compile on FreeBSD. I'm a bit of a FreeBSD noob and as you've seen compiling, too. So, thanks for your support! I will use the numbers again for my reply, too.

1.2
gcc => please take a look at the "new"/updated point 1.6 below
OSS4 => I don't actualy need it - thanks for the insight!

1.3 - 1.5 + 1.7 + 1.8
Thanks a lot, I will give that a try! 

1.6
Oh yes, stupid me. In my later approaches I didn't compile zlib by myself anymore. I had read that it's part of FreeBSD (now) and skipped it, as you noticed. Instead 1.6 is the compiling of libav:

1.6 install libav 0.7.7
```
cd $WORKDIR
curl -O https://libav.org/releases/libav-0.7.7.tar.gz
tar xzvf libav-0.7.7.tar.gz
cd libav-0.7.7
ln -s /usr/local/bin/gcc48 /usr/local/bin/gcc
./configure
gmake install
```
You've said that you have used ffmpeg instead. Which version are you using / Is there a version you can propose? That was my latest try since the line in configure.ac was blocking every version before (tried it with 6 different versions of libav and ffmpeg).
As you can see I had to use (and soft link (sorry)) gcc here. So I guess when installing ffmpeg I won't need it anyway?

I appreciate your feedback - thanks again!

**Comment by freultwah** [comment]
Why do you actually need gcc? Building the whole thing with clang works well. Just add CC=cc to the ./configure environment.

libav 11.2 is in ports, 0.7.7 is a bit old. 'pkg install libav' would probably pull in a lot of dependencies you don't want (in my case it demanded to install a few php55 modules for some reason), so maybe just head over to /usr/ports/multimedia/libav, make config and disable everything you don't want. And then make install clean.

I myself have been using ffmpeg, currently at 2.5.3. The way libav is built by the ports is better (no version info on the binaries), but it does not support libfdk-aac, so I've stuck with ffmpeg. Your kilometrage may vary.

**Comment by ejurgensen** [comment]
About 1.7: The order of the arguments in configure.ac is correct, as it is. It is checking for av_lockmgr_register(), which is used by forked-daapd. It was not in older version sof ffmpeg. If it is found, nothing should be done, and if it is not, it should throw an error.

I can’t explain why you get an error even though you are using recent versions of ffmpeg. You can disable the line in configure.ac, it will either solve the problem or mean that you just get another error later (when building, during the linking). Like freultwah, I too recommend using a newer of version of ffmpeg than 0.7.7.

**Comment by freultwah** [comment]
I got that av_lockmgr_register() error a couple of times, too, even though the function was present (I grepped the binaries). After I removed the line, configure worked well and no errors ensued afterwards, either, stuff built and linked fine and ran without problems.

**Comment by ejurgensen** [comment]
I have removed the check for av_lockmgr_register() now

**Comment by thorsteneckel** [comment]
I managed to get it running on my FreeBSD 10.1. I created a gist: https://gist.github.com/thorsteneckel/c0610fb415c8d0486bce

Thanks to you guys!

Sadly I have some issues with my Speakers: https://github.com/ejurgensen/forked-daapd/issues/98#issuecomment-73386293

**Comment by ejurgensen** [comment]
Thanks for this how-to! I decided to update the FreeBSD install info with some of the info, but then one thing led to another, and I ended up writing a FreeBSD install script which should take care of all the steps involved. You can find it in /scripts. I also put your start-up script there.

While working on it, I also found out that some of the old OSS4 configure scripts were jumping through some hoops which at least with FreeBSD 10 are more harmful than beneficial. So I removed some of that, which makes the build process a bit easier.

You can see the entire change referenced above.

@freultwah, you have been through a lot of forked-daapd builds on FreeBSD, I especially hope you find the changes useful.

**Comment by thorsteneckel** [comment]
You sir, are a genius! Not only me but a lot of fellow FreeBSD 10 users will appreciate this, too.
:+1:

**Comment by andrei-trifan** [comment]
forked-daapd is running on my freebsd 10.1 without any major issues. I need to investigate some codec translations problems and I will make a freebsd-port maybe next week.

Andrei T

**Comment by freultwah** [comment]
Magic! No more messing around with soundcard.h location etc. Stuff works. (Did not try the script, though, but it looks sane.)

Perhaps the OSS4 requirement should be removed from the INSTALL file as well? The sound subsystem is installed as part of the base system, and it is not really OSS4, even though they are ioctl compatible by design.
