### ISSUE TITLE
RSS - When adding a new RSS, it would be nice to be able to set how many items to parse/add

### ISSUE THREAD

**Issue by davidlb** [ejurgensen/forked-daapd#951]
I really love the new RSS feature but it would be even better to be able to set the limit when adding a new RSS feed (or even to remove the limit to get all items).

https://github.com/ejurgensen/forked-daapd/blob/95bc6e3e709511a0048697b3ce862a37a3ba3320/src/library/rssscanner.c#L56

Thanks guys for the really good job

**Comment by whatdoineed2do** [comment]
There's 2 ways to address this:

* REST end point (and then the web ui) accepts a `limit`, defaulting to something sensible like 10 - allows per RSS feed configuration:  `/api/library/add?url=http://.......rss&limit=xxxx`
* server level config value - would apply to all RSS feeds (as current)

Technically, neither are technically challenging  - I've got variations of both in my dev branches...

Perhaps this is something ejurgensen would consider

**Comment by ejurgensen** [comment]
I've added a commit so you can adjust the limit, see instructions here https://github.com/ejurgensen/forked-daapd/blob/master/README_JSON_API.md#update-a-playlist.

Note that currently you need to update the library for the change to take effect. Or you can add the RSS again.
