### ISSUE TITLE
RSS: updating query_limit after initial subscription - display order `incorrect`

### ISSUE THREAD

**Issue by whatdoineed2do** [ejurgensen/forked-daapd#956]
The web interface for `podcast` displays episodes ordered by `time_added` (generated by a _smart query_ `)expression': 'media_kind is podcast and songalbumid is "' + albumId + '" ORDER BY time_added DESC'`) which gives us some undesirable ordering in the following situation.

* add a podcast ( default limit for RSS subscription is 10
* at some point update the limit (say 30) via (`/api/library/playlists/<playlist id>?query_limit=30`)
* update the library to bring in the older 20 episodes

This would mean that _older_ episodes - the ones just added in the library after the `query_limit` update - are listed at the top of the individual `podcast` due to `time_added`.  I would expect podcasts to be listed in date of release.

If this is a reasonable expectation then what is the best way to solve?

I recall a discussion that not all (non-RSS) podcasts would populate `date_released` field - if we can guarantee this field is populated for podcasts we could change the web ui to ask for order by `date_released`.

The places that podcasts are added seem limited (rss + the 2 below) a _fixup_ to be applied (`filescanner.c:process_regular_file` and `filescanner_itunes.c:process_track_file` which knows when its scanning for podcasts and force assigns `MEDIA_KIND_PODCAST`).

Is this something that would be accepted?

**Comment by ejurgensen** [comment]
Seems reasonable to sort by date_released. If the field is sometimes zero then I think it just a matter of using ORDER BY date_released DESC, time_added DESC, or perhaps by date_released and title, like S_DATE_RELEASED. I don't think date_released should be filled with incorrect data.

**Comment by whatdoineed2do** [comment]
The main blocker for this would be the web page initiated rest request to find all the episodes for a podcast/playlist. Right now it’s a smart query using `order by time_added` but i couldn’t find a way to make smart query do mutilple `order by` and implementing this looks non trivial.

The next approach would be a new rest end point and corresponding dB query behind it but that’ll be something I think you guys would have better thoughts on how best to do this.

**Comment by chme** [comment]
I don't think `ORDER BY date_released DESC, time_added DESC` gives the desired ordering. It will give you first all podcasts with a `date_released` field set and then the remaining podcasts.

I prefer to simply order by `date_released`. If turns out that this is not enough, we can change the filescanner to set `date_released` for podcasts to `time_added`to ensure all podcasts have a valid value.

**Comment by whatdoineed2do** [comment]
Ordering by `date_released` _should be_ fine with the RSS scanner since every RSS entry _should_ have a publish date (although I've seen RSS entry with no `url` so who knows if we can really rely on this) but I didnt default a value in case of junk in the implementation.

So changing the `podcast` page order to be `date_released` will satisfy my needs since I only have podcasts via RSS.

However the server can source podcasts from the `/Podcast` directory - these would be standard audio files where its not guaranteed if these audio files would have such rich meta, but perhaps we say let these slide since these would end up with `release_date = 0` and i suspect the order by `time_added` was to deal with this.

I'll leave it to @chme to decide on best course.

**Comment by chme** [comment]
Ordering by `date_released` in the podcasts page is fine by me. I've changed it for the new web interface version.
