### ISSUE TITLE
Improvement: Keep setttings for Random play and Consume during restart

### ISSUE THREAD

**Issue by LordMyschkin** [ejurgensen/forked-daapd#963]
I notized that, while my playlist is kept during a restart, settings for "consume" and "random play" get set to "no". Although this is only a minor annoyance, it is somewhat unexpected - so I'd recommend either a setting in config to keep those or to couple persistence of these settings with persistence of the playlist - wich in my opinion would be the expected behavior.

**Comment by ejurgensen** [comment]
Sure, @chme has added a settings module, so I think it could be done via that

**Comment by ejurgensen** [comment]
I've added this now, hope it works!
