### ISSUE TITLE
API call for "now_playing"

### ISSUE THREAD

**Issue by opustecnica** [ejurgensen/forked-daapd#965]
Good afternoon,

Advanced apologies if this is already documented or it has been discussed and I failed to properly research. 

On a Raspberry PI w/ light Raspbian if the info is needed.

I am in the process of adding a 4x20 LCD display to a media server.  2 lines will display various info, while 2 lines will either display bar VU-Meters or a Spectrum Analyzer via CAVA.

I can easily retrieve the current track info via MPC.  I am wondering if I can retrieve the same information via API.  I can pull the current queue, but not the currently playing item.

Also, Ideally, I would like to pipe a connection to the web socket and be notified of a "change event" .  I have attempted to use the curl connection in the examples/documentation, but while I could see the events, I could not see the details of the event.  Likely an error on my part.

Any help and/or suggestion is greatly appreciated.

**Comment by whatdoineed2do** [comment]
The `/api/player` endpoint tells you want is currently playing - you want `item_id` that is the `id` of entry in `queue`.

```
ITEM_ID=$(curl -X GET http://localhost:3689/api/player | jq .item_id)
curl -X GET http://localhost:3689/api/queue | jq ".items[] | select(.id == ${ITEM_ID})"
```
The second output is probably what you want to pull apart.  There also exists `track_id` on that output whcih you can use in `/api/library/track/<trackidhere>` to get simliar data for the given track pulled from the `queue`

**Comment by opustecnica** [comment]
First off thank you.  That approach indeed got me what I needed.

Thank you again.

**Comment by ejurgensen** [comment]
I will close the issue then. Here is also a link to the docs:
https://github.com/ejurgensen/forked-daapd/blob/master/README_JSON_API.md
