### ISSUE TITLE
[web] "now playing" artwork scaling wrong on IOS 13/iphone

### ISSUE THREAD

**Issue by whatdoineed2do** [ejurgensen/forked-daapd#967]
@chme - I think this has been a problem before but was of lesser concern previously as  i have maybe 2-3 artwork peices across my library.  However its a problem now with the most recent 0.7 web interface's `now playing` page and the _always display artwork_ change.

On a computer, the artwork is scaled correctly on the `now playing` page - however on IOS this isn't the case and it chops off bottom of the image (also the case with the autogen'd image when no artwork is available on the media); i've seen this with square artwork and tall artwork too.  Below is the same `forked-daapd` process running and serving web to (L) desktop firefox with window narrowed and (R) IOS 13/iphone

![nowplaying](https://user-images.githubusercontent.com/18466811/80392678-5f6b3980-88a7-11ea-9946-aecdbf3ca347.png)
Whats the best way to help diagnose the issue?

On the desktop, if I shrink the height of the window, I see the artwork get smaller and smaller so I suspect its something on the IOS/safari browser.

**Comment by whatdoineed2do** [comment]
After [a little digging around, this would look like the IOS `vh` bug/feature](https://stackoverflow.com/questions/37112218/css3-100vh-not-constant-in-mobile-browser) - `vh` is used in `.fd-is-fullheight` CSS.

Will dig further and see if there's something that will work on IOS.

**Comment by cdlenfert** [comment]
Thanks for beating me to the punch! Also seeing this on iOS 13.3 (iPhone 8). In this case using Safari in full screen mode from a homescreen shortcut.
![image](https://user-images.githubusercontent.com/17277745/80423625-93d9f800-889d-11ea-8134-d59e4c762b66.png)

**Comment by whatdoineed2do** [comment]
I'm not a web dev so it might be something very stupid of me.  However, some digging suggests that we can use `-webkit-fill-available` instead of the `vh` but whatever i do I can't get it to display properly.  Using below this is a little better but the bottom of image is still chopped so it looks like the height is wrong.

```
/* Now playing page */
.fd-is-fullheight {
  /* height: calc(100vh - 3.25rem - 3.25rem); */
  height: -webkit-calc(-webkit-fill-available - 6.5rem);
  display: flex;
  flex-direction: column;
  justify-content: center;
}

.fd-is-fullheight .fd-is-expanded {
  /* max-height: calc(100vh - 25rem); /*
  max-height: -webkit-fill-available;
  padding: 1.5rem;
  overflow: hidden;
  flex-grow: 1;
  flex-shrink: 1;
}
```

What I was expecting to be able to do was this and let the `-webkit` directive overwite the previous value but it looks like `npm` just uses the first one it finds
```
height: calc(...);
height: -webkit-calc(-webkit-fill-available - 6.5rem);
```
The other thing I've seen is that performing `calc` / `webkit-calc` on `-webkit-fill-available` does nothing;
```
.fd-is-fullheight .fd-is-expanded {                                                                                                                          
  max-height: calc(-webkit-fill-available, - 90%);
```

So we have 2 problems:
* how to make the IOS play nice with `max-height` and `height`
* how to make this a generic solution

Pointers on how to move this along welcome

**Comment by LordMyschkin** [comment]
This seems also a Problem with other Browser; on my  Opera on MacOS Catalina, this pseudo-artwork scales wrong; and on Safari on the same PC, it seems to scale differently wrong to. I post two screenshots of  first Opera, than Safari
![Bildschirmfoto 2020-04-28 um 13 57 52](https://user-images.githubusercontent.com/11705882/80484830-a7966480-8958-11ea-88a5-046844a9543e.png)
![Bildschirmfoto 2020-04-28 um 13 58 53](https://user-images.githubusercontent.com/11705882/80484844-aebd7280-8958-11ea-9ec0-776ca154337a.png)

**Comment by whatdoineed2do** [comment]
Firefox on linux and win7 is fine with scaling so its definitely browser compliance mess.  Maybe we have an experienced web dev that can advise best way forward.

**Comment by cdlenfert** [comment]
@whatdoineed2do I found that adding `max-height: calc(100vh - 28rem);` to the inner image styles resolves the issue in the Safari browser. I'm not able to test on my iPhone because I can't inspect/tweak the styles via the desktop Safari "Develop" menu. But the issue does present itself in Desktop safari and this solution works there at least. I'm optimistic it would also work on iOS, and I see no ill effect in Chrome.

It'd look like this:
```
.fd-cover-image img {
    width: 100%;
    height: 100%;
    object-fit: contain;
    max-height: calc(100vh - 28rem);
    object-position: bottom;
    -webkit-filter: drop-shadow(0 0 1px rgba(0,0,0,.3)) drop-shadow(0 0 10px rgba(0,0,0,.3));
    filter: drop-shadow(0 0 1px rgba(0,0,0,.3)) drop-shadow(0 0 10px rgba(0,0,0,.3));
}
```
![image](https://user-images.githubusercontent.com/17277745/80651379-13e59680-8a33-11ea-9831-97376af64f00.png)

**Comment by cdlenfert** [comment]
@whatdoineed2do @chme **Update:** I'm not sure how to build the /src assets into a final app.css file, but I updated the minified app.css file directly and confirm this works well on iOS.

**Comment by cdlenfert** [comment]
Another issue with this is that the clickable zone for the album extends horizontally almost to the edges of the browser vs. remaining solely on the artwork image itself.

**Comment by whatdoineed2do** [comment]
@cdlenfert This is magic!  Fixes the IOS13/iphone and no impact to Firefox on linux - I've run this building from source.

Shall I leave you to put in the PR?

**Comment by whatdoineed2do** [comment]
@cdlenfert - I've built this using `npm` and tested this on Firefox/linux and has no ill-effect and works with IOS/iphone.  I've put in a PR for this so hopefully it'll not have any issues for merge.

**Comment by cdlenfert** [comment]
@whatdoineed2do Thanks for testing and submitting the PR. I'm new/slow on that type of stuff. I've also found there to be a bit of an over abundance of whitespace above and below the artwork/metadata sections. If you play with the rem values more it's pretty easy to get larger artwork on mobile. I'm also curious if there's any effort underway to support a horizontal layout with artwork on the left, and metadata on the right. If I could build and test changes easier I'd be inclined to play around with it more. I run my server on such a low powered box that it takes a really long time to MAKE, and even when I do that by editing the /src/ styles in the repo, it doesn't include my changes in the minified app.css file. I just don't know the right build processes for doing development on FD.

**Comment by whatdoineed2do** [comment]
@cdlenfert -  np and thanks for the easy fix - I was driving myself crazy with trying the `-webkit-fill-available` mess.  Note the current PR doesn't include the minified javascript but I'll drop them here for you if you want it (just move your old `/usr/share/forked-daapd/htdocs` out of the way and untar this in its place to test)

[fd-htdocs-0.7fix.tar.gz](https://github.com/ejurgensen/forked-daapd/files/4559680/fd-htdocs-0.7fix.tar.gz)


The web interface is owned by @chme and he'll be the person to request big web changes (horizontal mode etc).

To play around with the web interface look at the [web interface readme](https://github.com/ejurgensen/forked-daapd/blob/master/README_PLAYER_WEBINTERFACE.md).  You don't need to build the main server src to make this work, just run the server and build the web stuff and experiment.  The readme tells you how to point this dev web version at a forked daapd server that isnt on the localhost (ie its on a raspberry pi elsewhere on your network)
```
cd <your cloned forked daapd src root>/web-src/src
npm install
npm run dev  ## leave this running in a seperate window
```
Make `.vue` and `web` based changes and the `npm run dev` in the other terminal will make new changes available on http://localhost:8080 - this will connect to the forked daapd server as per your dev config.

Once you're happy with the web changes, `npm run build` will generate the minified js files in `htdocs` that you can install to your production server.  I have local enhancements that never made it into the main branch that I rebase/rebuild after big web release.

One note from my experience on IOS13 devices - i found that if i make a full screen mode/homescreen shortcut pointing at  http://yourdevhost.ip.address:8080 , the iphone wil cache the javascript stuff and doesnt reload after you make dev changes - you need to reset your phone to force it to reload again.  To test on iphone, you need to use safari that you can close the tab.

**Comment by chme** [comment]
Thanks a lot for the report and for digging into this issue! And sorry it took me so long to respond.
@cdlenfert @whatdoineed2do @LordMyschkin could you please give #980 a try. I tried to tackle the issue by consistently using flex layout for the "now playing" page. Before it was a mix of flex and block layout. The current browser support for flex should be good. Same should be the case for the `object-fit` css property for sizing images. I would prefer this solution over @cdlenfert solution, as i can better follow how the different elements should be sized and positioned. If it turns out to not fix the issue, i will merge @cdlenfert solution.

**Comment by whatdoineed2do** [comment]
@chme - your fix seems to be good for my iphone 8/IOS13.  No issues on Firefox neither.

**Comment by cdlenfert** [comment]
@chme I don't know how to get this locally for testing.

**Comment by cdlenfert** [comment]
@chme @whatdoineed2do I think I understand the helpful directions from @whatdoineed2do [above](https://github.com/ejurgensen/forked-daapd/issues/967#issuecomment-621964852) for doing local dev on the web interface. However, after reading the [readme](https://github.com/ejurgensen/forked-daapd/blob/master/README_PLAYER_WEBINTERFACE.md) when looking for the `proxyTable` setting to point at my local server, I didn't find a `config/index.js` file to modify. I did find a `devServer` option in vue.config.js. Is the the new equivalent? And if so, any idea why putting my server's IP in place of localhost isn't connecting the web interface to my server. My local web interface is running at :8080, it just doesn't appear to be connecting my server.

```  devServer: {
    // Proxy forked-daapd JSON API calls to the forked-daapd server running on
    // localhost:3689
    proxy: {
      '/api': {
        target: 'http://192.168.0.8:3689'
      },
      '/artwork': {
        target: 'http://192.168.0.8:3689'
      },
      '/stream.mp3': {
        target: 'http://192.168.0.8:3689'
      }
    }
  }
```

**Comment by cdlenfert** [comment]
@chme also want to add that #980 works for me in terms of scaling the artwork. I'm still seeing an issue where the clickable area (assuming for the image) is 100% of the viewport width.
![image](https://user-images.githubusercontent.com/17277745/80834711-7a42f400-8bae-11ea-812a-13673d043bae.png)

**Comment by whatdoineed2do** [comment]
@cdlenfert - it looks like with recent changes that README is out of date but the file `web-src/vue.config.js` is the one you want to edit and the `devServer` section's IP addresses.

These IPs point to where you have `forked-daapd` running - so I assume `http://192.168.0.8:3689` is your server with the real db etc.

On your dev machine where you are running `npm run dev` you can just use `http://localhost:8080` in your browser and that will give you the dev web sources you can experiment with.

**Comment by cdlenfert** [comment]
@whatdoineed2do I've done all that you say and even though the web interface is running on my local dev machine, and seems at least partially connected with my FD server, I can't see "now playing" info or artwork at the `localhost:8080` address. Is that normal? If so it would make experimenting with artwork scaling very challenging. I'm guessing I've just got something wrong in my setup.
![image](https://user-images.githubusercontent.com/17277745/80839139-dd855400-8bb7-11ea-9830-b9345af907fc.png)

**Comment by whatdoineed2do** [comment]
Yes, what you've done it should work.  Your screenshots do show it losing connection to the bakcend forked daapd server so I wonder if something is happening at the server side as you navigate to `now playing`.

Unfortunately this probably exhausts my knowledge gained from try/error on this one - maybe chme can advise though.

**Comment by cdlenfert** [comment]
Thanks anyway @whatdoineed2do. It loses the connection everywhere and not just upon navigation to `now playing`. But I can still load all my playlists and library directories. However if I try to use any of the playback controls they fail. My speakers also don't show up when viewing in localhost:8080.

**Comment by chme** [comment]
The problem is the connection to forked-daapd's websocket. It does not work, if the web interface dev server is not running on the same machine as forked-daapd. All JSON API calls get proxied correctly, but the websocket connection does not go through the proxy (opens on a different port) and therefor fails. i'll look into this, would be really nice to be able to develop against a forked-daapd server running on a different machine ...

To test the changes, you can copy the web interface files to your forked-daapd server. I've attached the files as a tar.gz file to https://github.com/ejurgensen/forked-daapd/pull/980#issuecomment-622672190

**Comment by chme** [comment]
@cdlenfert oh, just read your post, that you already tested the changes. 

Thanks to all of you for testing this so quickly!

**Comment by chme** [comment]
I've added a change to #980 to allow to develop the web interface against a remote forked-daapd server. There is a new properties file `.env.development` where the forked-daapd JSON API url and the websocket url can be changed to point to the remote server.

**Comment by cdlenfert** [comment]
@chme SWEET! the local dev environment is connecting to my server now. Very nice and thanks for the update!

**Comment by LordMyschkin** [comment]
Confirming works in Opera and Safari on Catalina - and i love the remotely fetched Covers from Discogs and Coverartarchive.
