### ISSUE TITLE
Default trusted_networks does not allow connection from IPv6 hosts.

### ISSUE THREAD

**Issue by mill1000** [ejurgensen/forked-daapd#969]
The default `trusted_networks` configuration does not allow connection for IPv6 hosts.

**Comment by ejurgensen** [comment]
The default should allow for it, ref. [the "fd" part](https://github.com/ejurgensen/forked-daapd/blob/master/forked-daapd.conf.in#L36). Please elaborate on the issue.

**Comment by mill1000** [comment]
Ah. I had assumed `fd` was some short hand for "file descriptor" (made sense at the time, now it feels silly).

Looks like my network is using link-local addresses as I haven't enabled IPv6 on my router. Perhaps the link-local prefix `fe80` should be included as well.
