### ISSUE TITLE
When trying to go to previous Track when already on the first one, Error message is a "internal Server Error" and Playing stops

### ISSUE THREAD

**Issue by LordMyschkin** [ejurgensen/forked-daapd#970]
Exactly the message is Request failed (status: 500 Internal Server Error, url: http://rpi3:3689/api/player/previous)
A distinct Error "Already on first track" would be nice (took me a few attempts to find what went wrong...).

**Comment by whatdoineed2do** [comment]
The player doesn't treat the queue as circular so it errors in these situations.  There's a PR #699 that would address this though

**Comment by LordMyschkin** [comment]
which is one of the possible solutions, surly better than an unconclusive error.

**Comment by ejurgensen** [comment]
A think making the previous command (and the next command) a no-op in this situation would only take a few lines of code. Or it could perhaps be solved in the frontend. @chme what do you prefer?

**Comment by whatdoineed2do** [comment]
IMO, this type of handling must be in the backend in `httpd_jsonapi.c` - stopping such errors at the web ui ignores that people can issue the same REST from a terminal/scripts and getting the same error response.  Furthermore this situation doesn't warrant a `500 internal error` its really a `501 not implemented`.

Personally (and admittedly biased) I'd feel this condition is best handled by PR #699 _CD-like behaviour for skip next/prev_

**Comment by chme** [comment]
@ejurgensen I don't have a strong opinion on this matter ... i tend to prefer how mpd/mpc handles it. If it is the first song, prev command will always start the song from the beginning, and if it is the last song, next command stops playback (without reporting an error). This branch should implement it: https://github.com/chme/forked-daapd/tree/player-prev-next

**Comment by ejurgensen** [comment]
@chme sounds good to me, and changes in the branch also look fine. You are welcome to merge them.

**Comment by ejurgensen** [comment]
Fixed by PR #1042
