### ISSUE TITLE
Some albums are combining in the library

### ISSUE THREAD

**Issue by poot17** [ejurgensen/forked-daapd#972]
Current set up:

CPUinfo: Raspberry Pi 3 Model B Rev 1.2.
OS: PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
forked-daapd -version: forked-daapd 27.1

With a clean install and only changing the "directories" parameter in the conf file, I added one album to the library, restarted forked-daapd and paired my iPhone to forked-daapd via the web interface. I could see the album in the Remote App and Web Client and it looked/played fine. I added a few more albums, a mixture of Compilations (in a Compilations folder) and single artists, restarted the service, and then noticed in the Remote app and Web Client that some of the albums that I added ended up combined into existing albums, and you can mainly tell by the increase count of tracks associated with those albums. Interestingly, if you click on the album, you see only the songs that belong to that album (which is normal), but if you click Play on that album, that album and the ones that were combined with it get added to the queue (not normal).

This is a repeatable observation, but doesn't happen with all albums. For the life of me, I can't find anything in the metadata that is causing the library to combine some albums together. I've used the same hard drive and music data structure that has been fine in the past, however since I did an update on the Pi in January, I've had this problem. When I plug the same hard drive into iTunes, I don't observe this effect, all albums appear independent to each other.

I'd really appreciate a way of understanding what is going on, can you help please? Perhaps this has been observed already but I've missed the post, but if not, I can provide an example and logs of it since it is a peculiar problem.

Thank you in advance,
-Matthew

**Comment by ejurgensen** [comment]
forked-daapd creates songalbumid's that are used to identify albums. It looks like some of your albums have the same id, which they shouldn't:

```
sqlite> select songalbumid,album from files group by songalbumid,album;
(...)
4666373878098654374|A Nod to Bob 2: An Artists' Tribute to Bob Dylan
4666373878098654374|Dark Was The Night: A Red Hot Compilation
4666373878098654374|I'm Not There [Disc 1]
```

To figure out how that happens I would ask you to run ffprobe on a few of the files to get their metadata, so try:
```
ffprobe "/home/pi/Music/Compilations/Dark Was The Night_ A Red Hot Compilatio/2-01 Well Alright.mp3"
ffprobe "/home/pi/Music/Compilations/I'm Not There [Disc 1]/1-01 All Along The Watchtower.mp3"
```

**Comment by poot17** [comment]
I see the same as you, this is the other set
3870692539860529506 No No No
3870692539860529506 Toward The Low Sun

Here are the ffprobe responses (without the ffprobe configuration)

[mp3 @ 0x101ca00] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from '/home/pi/Music/Compilations/Dark Was The Night_ A Red
Hot Compilatio/2-01 Well Alright.mp3':
  Metadata:
    title           : Well Alright
    artist          : Spoon
    TCM             : Britt Daniel
    track           : 1/16
    TPA             : 2/2
    album           : Dark Was The Night: A Red Hot Compilation
    genre           : Indie Rock
    compilation     : 1
    iTunPGAP        : 0
    encoded_by      : iTunes 10.5.2.11
    iTunNORM        :  00000F19 00000EC8 00006C0A 00007742 0000784E
0000784E 00008504 0000874A 0001A37D 0001A37D
    iTunSMPB        :  00000000 00000210 00000ABC 00000000006FAD34 00000000
00329B1A 00000000 00000000 00000000 00000000 00000000 00000000
    iTunes_CDDB_IDs : 16++
    date            : 2009
  Duration: 00:02:46.03, start: 0.000000, bitrate: 160 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 160 kb/s


[mp3 @ 0x904a00] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from '/home/pi/Music/Compilations/I'm Not There [Disc
1]/1-01 All Along The Watchtower.mp3':
  Metadata:
    title           : All Along The Watchtower
    artist          : Eddie Vedder & The Million Dollar Bashers
    TCM             : Bob Dylan
    album           : I'm Not There [Disc 1]
    track           : 1/16
    TPA             : 1/2
    iTunes_CDDB_IDs : 16++
    genre           : Soundtrack
    compilation     : 1
    iTunPGAP        : 0
    encoded_by      : iTunes 11.0.4.4
    iTunNORM        :  00002845 000022E3 00009FE7 000090D9 00018429
0002E482 00008581 0000857F 0000A5EB 00034405
    iTunSMPB        :  00000000 00000210 00000A44 0000000000B588AC 00000000
0052494E 00000000 00000000 00000000 00000000 00000000 00000000
    date            : 2007
  Duration: 00:04:29.84, start: 0.000000, bitrate: 160 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 160 kb/s

**Comment by ejurgensen** [comment]
The cause is this line: `iTunes_CDDB_IDs : 16++`. forked-daapd uses this as ID if present, but as you can see these are for some reason not proper IDs. So the short term solution is that you remove these tags with a tag editor.

I'll add something to future versions so it either doesn't use this field, or checks it.

**Comment by nonyhaha** [comment]
Hello, 
I just found out this, when organizing my library. I have one of the albums with about 210 tracks in it. 
I will try looking for some way to batch remove this kind of tags, as I have a lot of files. 
Any idea if this can be sorted out on the server side?

**Comment by ejurgensen** [comment]
Yes, it's this one: `CATALOGNUMBER : none`

Removing that should fix the issue.
