### ISSUE TITLE
[web] skip forward / back not available for all media

### ISSUE THREAD

**Issue by whatdoineed2do** [ejurgensen/forked-daapd#974]
cc: @chme 

`now playing` has a skip `forward` and `backward` buttons but these are only available for `podcasts` and `audiobooks`.

`components/PlayerButtonSeek*.vue`
```
    visible () {
      return ['podcast', 'audiobook'].includes(this.now_playing.media_kind)
    }
```
This should be available for more items - probably everything except `pipe` and live http streams ~~(I forget if its easy to determine the latter)~~ where I think the stream has 0 play length

**Comment by chme** [comment]
That was intentional. I do not see the benefit of showing skip buttons for music ... (most music apps - at least on android - do not offer this button as well). I'll leave the issue open, to see if there is more interest in this functionality.
