### ISSUE TITLE
Increase buffer size for metadata

### ISSUE THREAD

**Issue by uvjustin** [ejurgensen/forked-daapd#976]
The current value for both PIPE_METADATA_BUFLEN_MAX and PIPE_PICTURE_SIZE_MAX is 262144 (256kb). In my use, some image metadata bumps up against this buffer and then the pipe read is aborted.
Can we increase this buffer to say 512kb? Also, to recover from an overflow in the case that the pipe evbuffer is too large, maybe the pending data can be dumped and subsequent metadata can still be read instead of calling pipe_metadata_watch_del.

**Comment by ejurgensen** [comment]
Ok, should be done now. Let me know if it works.

**Comment by uvjustin** [comment]
Works on my end, thanks.
Since the buffer is much larger now I haven't tested the drain functionality yet.
