### ISSUE TITLE
[web] Times/dates are displayed in US format

### ISSUE THREAD

**Issue by ejurgensen** [ejurgensen/forked-daapd#981]
Is it possible to show them localised?

**Comment by whatdoineed2do** [comment]
I had this in one of my dev trees a while back:
```
diff --git a/web-src/src/filter/index.js b/web-src/src/filter/index.js
index 24e875ce..5741890e 100644
--- a/web-src/src/filter/index.js
+++ b/web-src/src/filter/index.js
@@ -11,6 +11,7 @@ Vue.filter('duration', function (value, format) {
 })
 
 Vue.filter('time', function (value, format) {
+  moment.locale(navigator.language)
   if (format) {
     return moment(value).format(format)
   }
```
It wasn't working trying to set this at a _global_ level and I had to call `.locale(..)` in the `time` filter each time.  `moment` defaults to `en-US` if the `navigator.language` is not valid.

Works on chrome,firefox/linux and IOS13
