### ISSUE TITLE
Playing Music to Amazon Devices (e.g. Echo)

### ISSUE THREAD

**Issue by charlesomer** [ejurgensen/forked-daapd#985]
Hi,

Firstly, apologies if this has already been answered. I am trying to find out if it's possible to stream content to multiple Amazon Devices as well as Airplay devices?
Ideally this would be from any music source but alternatively/additionally, would it be possible to create a group that Spotify recognises which contains Amazon Devices as well as Airplay devices etc.

Thank you
Charles

**Comment by ejurgensen** [comment]
No, forked-daapd doesn't have support for Amazon devices

**Comment by charlesomer** [comment]
I thought that might be the case. I’m guessing it’s a limitation with Alexa/Amazon?

I thought I might be able to pipe the mp3 stream to TuneIn since the app accepts a custom stream but that feature doesn’t exist in the Alexa Skill/Player. Currently trying to find a way to pipe audio to the echo, whether that’s via a skill or other.

**Comment by charlesomer** [comment]
Alternatively, is it possible to play to a Spotify group as well as Airplay/Chromecast? Or create a group that Spotify recognises which contains normal Spotify devices and forked-daapd devices (Airplay/Chromecast)?
