### ISSUE TITLE
Chromcast problems

### ISSUE THREAD

**Issue by ski522** [ejurgensen/forked-daapd#989]
Chromecast was working for me, but I haven't used forked-daapd in a few months and after upgrading I'm now I'm having trouble with not seeing any Chromecast devices. 

I've tried to re-compile with various options but no luck and I keep seeing the following below (note last line). 

Not sure what else to do. 

> [  LOG]     main: Forked Media Server Version 27.1 taking off
> [  LOG]     main: Built with:
> [  LOG]     main: - ffmpeg
> [  LOG]     main: - Chromecast
> [  LOG]     main: - MPD
> [  LOG]     main: - Device verification
> [  LOG]     main: - Websockets
> [  LOG]     main: - ALSA
> [  LOG]     main: - Webinterface
> [  LOG]     main: mDNS init
> [  LOG]     mdns: Avahi state change: Client running
> [  LOG]       db: Configured to use database file '/usr/local/var/cache/forked-daapd/songs3.db'
> [  LOG]       db: Now vacuuming database, this may take some time...
> [  LOG]       db: Database OK with 517 active files and 51 active playlists
> [  LOG]    xcode: Cannot open encoder (opus): Experimental feature
> [  LOG]     cast: Will not be able to stream Chromecast, libav does not support Opus encoding

**Comment by ejurgensen** [comment]
The reason is ffmpeg for some reason has disabled the Opus encoder, see:
https://superuser.com/questions/1315996/ffmpeg-4-0-opus-codec-not-enabled

So you need somehow get an ffmpeg build that can Opus encode. What platform is this on?

**Comment by ski522** [comment]
I'm using Ubuntu 18.04.4 LTS, but even though I had the libeopus-dev libraries installed it appears ffmpeg won't use them with out doing "configure --enable-libopus" before compiling ffmpeg. 

So have recompiled everything and now I'm seeing chromecast devices again, thanks for getting me on the right track!

**Comment by ejurgensen** [comment]
I'm also using Ubuntu 18.04 and it comes with ffmpeg 3.4, which works fine out of the box. So not sure why you were seeing this problem unless you weren't using Ubuntu's ffmpeg.

**Comment by ski522** [comment]
Goes back to this link https://github.com/ejurgensen/forked-daapd/issues/533#issuecomment-557736550 where I tried compiling the latest version of ffmpeg to see if I could play the link in that post, so I wasn't using the distro version off ffmpeg...didn't even think about trying the distro version of ffmpeg.

Of course I still can't play that link for some reason, but not a big deal for me, it was only during xmas I was interested in the link.
