### ISSUE TITLE
[question] Is a Smart Playlist of X number of random tracks possible

### ISSUE THREAD

**Issue by cdlenfert** [ejurgensen/forked-daapd#992]
I'd like to have a smart playlist that when played generates a list of 100 random tracks and starts playing them. I realize this could be multiple requests.

1. the smart playlist that pics 100 random songs
2. the command to start the playlist
3. the ability for the 100 random songs to be generated each time the playlist is played

Is this sort of thing doable? I didn't see any randomization referenced in [the Smart Playlist readme](https://github.com/ejurgensen/forked-daapd/blob/master/README_SMARTPL.md).

**Comment by ejurgensen** [comment]
I'm not sure about the 100 limit, but other than that this seems a lot like just starting random playback of a playlist? But since you ask I assume the limit is important?

**Comment by LordMyschkin** [comment]
no, it's an entire different thing related to #979: Selection of random tracks out of a large library. 
I got this sort of working via a python script (although the "randomness" of the SQLITE-Query seems to be defective), the solution via the "ashuffle -o 100" command made for mpd does not work  for forked-daapd.

**Comment by whatdoineed2do** [comment]
Currently the `SMART.pl` doesn't support this but it's 5lines to support:
```
diff --git a/src/SMARTPL.g b/src/SMARTPL.g
index 533ad5c2..9a671536 100644
--- a/src/SMARTPL.g
+++ b/src/SMARTPL.g
@@ -37,6 +37,7 @@ ordertag      :       STRTAG
                        |       INTTAG
                        |       DATETAG
                        |       ENUMTAG
+                        |       RANDOMTAG
                        |       (XXX)? NeverUsedRule
                        ;
 
@@ -118,6 +119,9 @@ GROUPTAG    :       'track_count'
                        |       'album_count'
                        ;
 
+RANDOMTAG       :       'random'
+                        ;
+
 INCLUDES       :       'includes'
                        ;
 
diff --git a/src/SMARTPL2SQL.g b/src/SMARTPL2SQL.g
index c7382338..3b90b080 100644
--- a/src/SMARTPL2SQL.g
+++ b/src/SMARTPL2SQL.g
@@ -373,6 +373,11 @@ ordertag   returns [ pANTLR3_STRING result ]
                        $result->append8($result, "f.");
                        $result->appendS($result, $ENUMTAG.text->toUTF8($ENUMTAG.text));
                }
+       |       RANDOMTAG
+               {
+                       $result = $RANDOMTAG.text->factory->newRaw($RANDOMTAG.text->factory);
+                       $result->append8($result, "random()");
+               }
        ;

```
And works with a playlist like this:
```
"random 3 pop songs" {
  genre is "Pop" and
  media_kind is music
  order by random desc
  limit 3
}
```
Notice the new `random` keyword.  Everything you ask the server for the playlist it'll select a random number of rows from the result set.  I'll package this up into a PR.

```
# look  for `id` of element that matches "random 3 pop songs", lets say it id: 29
$ curl -X GET http://localhost:3689/api/library/playlists | jq
curl -X GET http://localhost:3689/api/library/playlists/29/tracks  | jq .items[].id 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2412  100  2412    0     0   138k      0 --:--:-- --:--:-- --:--:--  138k
102
99
125
$ curl -X GET http://localhost:3689/api/library/playlists/29/tracks  | jq .items[].id 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2490  100  2490    0     0   202k      0 --:--:-- --:--:-- --:--:--  221k
115
123
84
```

**Comment by whatdoineed2do** [comment]
@cdlenfert - to do what you want - _queue X random tracks and play_ via REST - is not achievable right now as it looks like the `items/add` endpoint doesnt honor `limit` or can you specify a playlist for it to add.


Ideally you'd do the following (but it doesn't work right now - this will just add your Pop tracks in a random order to the queue as `limit` does NOT work but should be fixable)
```
curl -X POST "http://localhost:3689/api/queue/items/add?limit=3&clear=true&expression=genre+is+%22Pop%22+order+by+random+desc&playback=start"

curl -X POST "http://localhost:3689/api/queue/items/add?clear=true&expression=genre+is+%22Pop%22+order+by+random+desc+limit+3&playback=start"
```

**Comment by cdlenfert** [comment]
Just WOW! you all are fast and this is working perfectly for me! Play the smart playlist and I get 100 new random tracks each time! And it's way faster than shuffling my entire library! So cool!!
