### ISSUE TITLE
no sound on homepod (airplay)

### ISSUE THREAD

**Issue by pabuta88** [ejurgensen/forked-daapd#993]
Hi, first of all thanks a lot for your amazing work! I installed the media server on my raspberry pi 4 following the instructions linked in the install-file. When starting forked-daapd, my homepod is shown in outputs and I can select it. The connection also seems to work since ongoing music on the homepod (streamed by my iPhone via airplay) is interrupted. However, there is no sound. Changing the volumes doesn't help either. The forked-daapd’s log file unfortunately doesn't show anything. I'm desperate and would love to make this work 😔

**Comment by ejurgensen** [comment]
Try disabling ipv6 in forked-daapd's config. If it still doesn't work then also set the log level to debug, and attach a log file here (please attach, don't paste).

**Comment by pabuta88** [comment]
Perfect - that was it! Thank you so much for your quick response and for solving my problem! ☺️
