### ISSUE TITLE
BUG: SEGV forked-daapd with smart random playlist

### ISSUE THREAD

**Issue by LordMyschkin** [ejurgensen/forked-daapd#999]
I tried the random playlist feature (after a recompile of course) and it instantly crashes:
 
The Playlist in question is:
"random 100" {
    media_kind IS music
    oder by random desc
    limit 100
}

**Comment by whatdoineed2do** [comment]
This is something screwy with parser - this works:

```
"random2 100" {
  media_kind is music
  order by random desc
  limit 100
}
```

**Comment by whatdoineed2do** [comment]
To clarify - as its caught me out before - this is the lex/parser not recognising a token (in this case the token`IS`) and then getting itself into a recursive call until it eats all the memory.

If you look at `SMARTPL.g` you can see that some of the tokens accept upper case version (`order by` and `ORDER BY`, `limit` and `LIMIT`,..).  Not sure if there was a reason for this.

The easiest thing is to update the definitions to accept lower and upper case but you may want to run this past @chme or @ejurgensen about this.

**Comment by LordMyschkin** [comment]
works great now - though in webinterface, those smart playlists are not listed unter playlists; but they are selectable as files.
Love this new feature - sorry for letting you wait so long for feedback, but I had a typo in the playlist and was quite confused by them not showing up under "playlists"
